### ISSUE TITLE
How to read a file in android internal storage?

### ISSUE THREAD

**Issue by yms2772** [fyne-io/fyne#1047]
I am making android app using fyne-io.

My app should read json file in /sdcard, but using ``ioutil.ReadFile``, `os.Stat` cannot read my json file.
However, when I build it for windows it works fine.

And I also read its logcat, it shows nothing.

Unlike reading , it can write on sdcard.

Reading sdcard: X
Writing sdcard: O

AndroidManifest.xml File
```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="1" android:versionName="1.0" package="com.eclass.todo" platformBuildVersionCode="17" platformBuildVersionName="4.0.4-1406430">
    <application android:label="E-Class TODO" android:debuggable="true">
        <activity android:label="E-Class TODO" android:name="org.golang.app.GoNativeActivity" android:configChanges="keyboardHidden|orientation">
            <meta-data android:name="android.app.lib_name" android:value="TODO"/>
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
    </application>
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.INTERNET"/>
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
</manifest>
```

**Comment by andydotxyz** [comment]
Can you provide the error you get when trying to read?

**Comment by yms2772** [comment]
> Can you provide the error you get when trying to read?

Um.. there is no error.
When I use ``panic(err)``, It shows nothing.
I think ``err`` is ``nil``.

**Comment by andydotxyz** [comment]
Can you please share the code that is failing an how you are asserting that it cannot read?

It would also be a good idea to confirm the path that is being read and verify it's existence on the device.

**Comment by yms2772** [comment]
It is part of the problem in the whole code.

```go
loginInfo := "/sdcard/login.json"

loginContent.OnSubmit = func() {
		loginProg := dialog.NewProgressInfinite("Login", "Logging in...", loginW)
		loginProg.Show()

		if CheckLogin(username.Text, password.Text) {
			myID = username.Text
			myPW = password.Text

			loginJSON := LoginInfo{
				ID: myID,
				PW: myPW,
			}

			file, _ := json.MarshalIndent(loginJSON, "", " ")

			ioutil.WriteFile(loginInfo, file, 0777)

			fmt.Println(string(file))

			dialog.ShowConfirm("E-Class TODO", "Login Complete", func(b bool) {
				if b {
					os.Exit(1)
				}
			}, loginW)
		} else {
			loginProg.Hide()

			dialog.ShowError(fmt.Errorf("Account is not correct"), loginW)
		}
	}

	loginContent.OnCancel = func() {
		os.Exit(1)
	}

	loginW.SetContent(widget.NewVBox(
		layout.NewSpacer(),
		widget.NewGroup("E-Class Login",
			loginContent,
		),
		layout.NewSpacer(),
	))

	_, err := os.Stat(loginInfo)
	if err == nil {
		loginJSON, err := ioutil.ReadFile(loginInfo)
		if err != nil {
			os.Remove(loginInfo)
			os.Exit(1)
		}

		_, isJSON := gjson.Parse(string(loginJSON)).Value().(map[string]interface{})
		if !isJSON {
			os.Remove(loginInfo)
			os.Exit(1)
		}

		myID = gjson.Get(string(loginJSON), "id").String()
		myPW = gjson.Get(string(loginJSON), "pw").String()
	} else {
		panic(err)

		loginW.ShowAndRun()
	}
```

**Comment by yms2772** [comment]
> Can you please share the code that is failing an how you are asserting that it cannot read?
> 
> It would also be a good idea to confirm the path that is being read and verify it's existence on the device.

It is part of the problem in the whole code.

```go
loginInfo := "/sdcard/login.json"

loginContent.OnSubmit = func() {
		loginProg := dialog.NewProgressInfinite("Login", "Logging in...", loginW)
		loginProg.Show()

		if CheckLogin(username.Text, password.Text) {
			myID = username.Text
			myPW = password.Text

			loginJSON := LoginInfo{
				ID: myID,
				PW: myPW,
			}

			file, _ := json.MarshalIndent(loginJSON, "", " ")

			ioutil.WriteFile(loginInfo, file, 0777)

			fmt.Println(string(file))

			dialog.ShowConfirm("E-Class TODO", "Login Complete", func(b bool) {
				if b {
					os.Exit(1)
				}
			}, loginW)
		} else {
			loginProg.Hide()

			dialog.ShowError(fmt.Errorf("Account is not correct"), loginW)
		}
	}

	loginContent.OnCancel = func() {
		os.Exit(1)
	}

	loginW.SetContent(widget.NewVBox(
		layout.NewSpacer(),
		widget.NewGroup("E-Class Login",
			loginContent,
		),
		layout.NewSpacer(),
	))

	_, err := os.Stat(loginInfo)
	if err == nil {
		loginJSON, err := ioutil.ReadFile(loginInfo)
		if err != nil {
			os.Remove(loginInfo)
			os.Exit(1)
		}

		_, isJSON := gjson.Parse(string(loginJSON)).Value().(map[string]interface{})
		if !isJSON {
			os.Remove(loginInfo)
			os.Exit(1)
		}

		myID = gjson.Get(string(loginJSON), "id").String()
		myPW = gjson.Get(string(loginJSON), "pw").String()
	} else {
		panic(err)

		loginW.ShowAndRun()
	}
```

**Comment by yms2772** [comment]
> Well, when you get `loginJSON, err` you are not printing the error anywhere - it would be helpful if you added `log.Println("Read error", err)` or `dialog.ShowError(err, loginW)` if you want it in the UI.

``loginJSON, err := ioutil.ReadFile(loginInfo)`` this code is played when ``/sdcard/login.json`` is exist.
If it is not exist, ``loginW.ShowAndRun()`` will be played.

When I run my app, there is a file which is login.json in /sdcard, but ``loginW.ShowAndRun()`` is played.

My app cannot reach ``loginJSON, err := ioutil.ReadFile(loginInfo)`` point. It just go through ``loginW.ShowAndRun()`` point.

**Comment by yms2772** [comment]
This logcat is ``panic`` of ``os.Stat``
``todo.go:205`` is ``os.Stat(loginInfo)``
```go
05-29 23:57:37.355 24232     0 E Go      : panic: nil
05-29 23:57:37.355 24232     0 E Go      : 
05-29 23:57:37.355 24232     0 E Go      : goroutine 35 [running]:
05-29 23:57:37.355 24232 24262 E GoLog   : panic: nil
05-29 23:57:37.355 24232     0 E Go      : main.main()
05-29 23:57:37.355 24232 24262 E GoLog   : 
05-29 23:57:37.355 24232     0 E Go      : 	/mnt/e/Workspace/Go/source/e-class_todo_android/todo.go:205 +0x720
05-29 23:57:37.355 24232     0 E Go      : github.com/fyne-io/mobile/app/internal/callfn.CallFn(0x771416a380)
05-29 23:57:37.355 24232     0 E Go      : 	/mnt/e/Workspace/Go_linux/pkg/mod/github.com/fyne-io/mobile@v0.0.2-0.20200511203347-825e44fe5a95/app/internal/callfn/callfn_arm64.s:10 +0x1c
05-29 23:57:37.355 24232     0 E Go      : created by github.com/fyne-io/mobile/app.callMain
05-29 23:57:37.355 24232     0 E Go      : 	/mnt/e/Workspace/Go_linux/pkg/mod/github.com/fyne-io/mobile@v0.0.2-0.20200511203347-825e44fe5a95/app/android.go:107 +0x2bc
```

**Comment by andydotxyz** [comment]
Are you sure that is the only panic? The one above is inside a err != nil guard but printing a nil error...

**Comment by yms2772** [comment]
> P.S. it looks like you are using the JSON to manage your own config storage. Did you consider using `App.Preferences()` instead?

Oh this is what I want. Thank you.
Now I use `App.Preferences()` instead json.
