### ISSUE TITLE
Creating a windows inside onClose handler causes Fyne to panic.

### ISSUE THREAD

**Issue by ababo** [fyne-io/fyne#1106]
Indeed I have encountered that while trying to workaround a missing `WillClose()` handler (needed to prevent closing the window, so I tried to reopen it again). So when I try to create a window within the handler I get:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x45b73d2]

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.(*Window).Focus.func1(0x0)
	/Users/ababo/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200222043503-6f7a984d4dc4/window.go:607 +0x22
github.com/go-gl/glfw/v3.3/glfw.(*Window).Focus(0x0)
	/Users/ababo/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200222043503-6f7a984d4dc4/window.go:607 +0x2b
fyne.io/fyne/internal/driver/glfw.(*window).create.func3()
	/Users/ababo/go/pkg/mod/fyne.io/fyne@v1.3.0/internal/driver/glfw/window.go:1172 +0x3f5
fyne.io/fyne/internal/driver/glfw.(*gLDriver).runGL(0xc000031b80)
	/Users/ababo/go/pkg/mod/fyne.io/fyne@v1.3.0/internal/driver/glfw/loop.go:96 +0x59b
fyne.io/fyne/internal/driver/glfw.(*gLDriver).Run(0xc000031b80)
	/Users/ababo/go/pkg/mod/fyne.io/fyne@v1.3.0/internal/driver/glfw/driver.go:70 +0x37
fyne.io/fyne/app.(*fyneApp).Run(0xc0000723c0)
	/Users/ababo/go/pkg/mod/fyne.io/fyne@v1.3.0/app/app.go:57 +0x93
main.main()
```
Reproduced on OSX 10.15.5 with Go 1.14.1.

**Comment by andydotxyz** [comment]
Can you please share the code that you are using to cause this panic?

**Comment by ababo** [comment]
Fairly simple: `win.SetOnClosed(func() { app.NewWindow("title").Show() })`

**Comment by andydotxyz** [comment]
Thanks. I guess that this is the only window visible at the time?
I can replicate it under those circumstances as the creation of a new window is happening after the app realises it should quit.

I can fix the crash, but I will have to think about how this could be supported. It's a bit troublesome and #467 is probably tracking the right way to do this.

In the meantime you can add `time.Sleep(time.Second)` after `Window.Show()` - it will not delay your application but it will stop the shutdown of the app long enough to realise that there is now another window...

**Comment by andydotxyz** [comment]
This patch fixes the panic, though it does not change the overall behaviour - for that we need #467 .
Feel free to test the patch :)

**Comment by andydotxyz** [comment]
The patch is landed on develop for testing, will be in 1.3.1 at some point.
The bigger picture issue is tracked in #467 but with the timer workaround you should be OK.

**Comment by ababo** [comment]
The issue still persists on `v1.3.1-0.20200622224053-33c346cb13d6`.

**Comment by andydotxyz** [comment]
Can you please post the revised panic stack trace? I can no longer replicate it here...

**Comment by ababo** [comment]
```
	/usr/local/Cellar/go/1.14.1/libexec/src/runtime/panic.go:967 +0x166
github.com/go-gl/glfw/v3.3/glfw.(*Window).Focus.func1(0x0)
	/Users/ababo/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200222043503-6f7a984d4dc4/window.go:607 +0x22
github.com/go-gl/glfw/v3.3/glfw.(*Window).Focus(0x0)
	/Users/ababo/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200222043503-6f7a984d4dc4/window.go:607 +0x2b
fyne.io/fyne/internal/driver/glfw.(*window).create.func3()
	/Users/ababo/go/pkg/mod/fyne.io/fyne@v1.3.0/internal/driver/glfw/window.go:1172 +0x3f5
fyne.io/fyne/internal/driver/glfw.(*gLDriver).runGL(0xc00002f540)
	/Users/ababo/go/pkg/mod/fyne.io/fyne@v1.3.0/internal/driver/glfw/loop.go:96 +0x59b
fyne.io/fyne/internal/driver/glfw.(*gLDriver).Run(0xc00002f540)
	/Users/ababo/go/pkg/mod/fyne.io/fyne@v1.3.0/internal/driver/glfw/driver.go:70 +0x37
fyne.io/fyne/app.(*fyneApp).Run(0xc000078240)
```

**Comment by andydotxyz** [comment]
That is still using the v1.3.0 release

**Comment by ababo** [comment]
oh, sorry, will redo

**Comment by ababo** [comment]
```
/usr/local/Cellar/go/1.14.1/libexec/src/runtime/panic.go:967 +0x166
github.com/go-gl/glfw/v3.3/glfw.(*Window).Focus.func1(0x0)
	/Users/ababo/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200222043503-6f7a984d4dc4/window.go:607 +0x22
github.com/go-gl/glfw/v3.3/glfw.(*Window).Focus(0x0)
	/Users/ababo/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200222043503-6f7a984d4dc4/window.go:607 +0x2b
fyne.io/fyne/internal/driver/glfw.(*window).create.func3()
	/Users/ababo/go/pkg/mod/fyne.io/fyne@v1.3.1-0.20200622224053-33c346cb13d6/internal/driver/glfw/window.go:1177 +0x3f5
fyne.io/fyne/internal/driver/glfw.(*gLDriver).runGL(0xc00002f500)
	/Users/ababo/go/pkg/mod/fyne.io/fyne@v1.3.1-0.20200622224053-33c346cb13d6/internal/driver/glfw/loop.go:96 +0x5b8
fyne.io/fyne/internal/driver/glfw.(*gLDriver).Run(0xc00002f500)
	/Users/ababo/go/pkg/mod/fyne.io/fyne@v1.3.1-0.20200622224053-33c346cb13d6/internal/driver/glfw/driver.go:70 +0x37
fyne.io/fyne/app.(*fyneApp).Run(0xc000070240)
	/Users/ababo/go/pkg/mod/fyne.io/fyne@v1.3.1-0.20200622224053-33c346cb13d6/app/app.go:57 +0x93
```

**Comment by andydotxyz** [comment]
Ah yes, it turns out I missed a fine in my commit sorry - there is a more complete solution in PR #1133
