### ISSUE TITLE
Crash "WGL: Failed to make context current" in demo

### ISSUE THREAD

**Issue by windexlight** [fyne-io/fyne#1461]
### Describe the bug:
Fyne demo crashes when resizing the window.

### To Reproduce:
Steps to reproduce the behaviour:
1. Build fyne_demo.exe under Windows at the Go and Fyne versions listed below. I built without the GUI flags to get a command line output, probably will crash with them also.
2. Go to Graphics tab, and select QuestionIcon (others probably work too, but this is the one I used to reproduce).
3. Grab the lower right corner of the window and rapidly drag the mouse back and forth to continuously resize the window. Keep doing this for possibly several minutes. Maybe also try restarting the app a few times if not reproducing.
4. App crashes with something like the below error dump.

### Error dump:
```
2020/10/24 17:17:00 PlatformError: WGL: Failed to make context current: The handle is invalid.
2020/10/24 17:17:00 Error 502 in GL Renderer
2020/10/24 17:17:00   At: C:/Users/[redacted]/go/src/fyne.io/fyne/internal/painter/gl/gl_core.go:84
2020/10/24 17:17:00 Error 502 in GL Renderer
2020/10/24 17:17:00   At: C:/Users/[redacted]/go/src/fyne.io/fyne/internal/painter/gl/gl_core.go:183
2020/10/24 17:17:00 Error 502 in GL Renderer
2020/10/24 17:17:00   At: C:/Users/[redacted]/go/src/fyne.io/fyne/internal/painter/gl/gl_core.go:189
2020/10/24 17:17:00 Error 502 in GL Renderer
2020/10/24 17:17:00   At: C:/Users/[redacted]/go/src/fyne.io/fyne/internal/painter/gl/gl_core.go:206
2020/10/24 17:17:00 Error 502 in GL Renderer
2020/10/24 17:17:00   At: C:/Users/[redacted]/go/src/fyne.io/fyne/internal/painter/gl/gl_core.go:208
2020/10/24 17:17:00 Error 502 in GL Renderer
2020/10/24 17:17:00   At: C:/Users/[redacted]/go/src/fyne.io/fyne/internal/painter/gl/gl_core.go:210
2020/10/24 17:17:00 Error 502 in GL Renderer
2020/10/24 17:17:00   At: C:/Users/[redacted]/go/src/fyne.io/fyne/internal/painter/gl/gl_core.go:215
2020/10/24 17:17:00 Error 502 in GL Renderer
2020/10/24 17:17:00   At: C:/Users/[redacted]/go/src/fyne.io/fyne/internal/painter/gl/gl_core.go:220
2020/10/24 17:17:00 Error 502 in GL Renderer
2020/10/24 17:17:00   At: C:/Users/[redacted]/go/src/fyne.io/fyne/internal/painter/gl/gl_core.go:242
2020/10/24 17:17:00 Error 502 in GL Renderer
2020/10/24 17:17:00   At: C:/Users/[redacted]/go/src/fyne.io/fyne/internal/painter/gl/gl_core.go:246
Exception 0xc0000005 0x0 0xc 0x52f74360
PC=0x52f74360
signal arrived during external code execution

fyne.io/fyne/vendor/github.com/go-gl/gl/v3.2-core/gl._Cfunc_glowDrawArrays(0x52ec7100, 0x5, 0x4)
        _cgo_gotypes.go:6242 +0x4c
fyne.io/fyne/vendor/github.com/go-gl/gl/v3.2-core/gl.DrawArrays(...)
        C:/Users/[redacted]/go/src/fyne.io/fyne/vendor/github.com/go-gl/gl/v3.2-core/gl/package.go:9268
fyne.io/fyne/internal/painter/gl.(*glPainter).glDrawTexture(0xc000150510, 0x3f80000000000001)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/painter/gl/gl_core.go:248 +0xf3
fyne.io/fyne/internal/painter/gl.(*glPainter).drawTextureWithDetails(0xc000150510, 0xc540c0, 0xc000318200, 0xc0000939d0, 0x4, 0x21, 0x2fb, 0x254, 0x303, 0x279, ...)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/painter/gl/draw.go:69 +0x154
fyne.io/fyne/internal/painter/gl.(*glPainter).drawWidget(0xc000150510, 0xc558e0, 0xc000318200, 0x4, 0x21, 0x303, 0x279)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/painter/gl/draw.go:78 +0x1b0
fyne.io/fyne/internal/painter/gl.(*glPainter).drawObject(0xc000150510, 0xc540c0, 0xc000318200, 0x4, 0x21, 0x303, 0x279)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/painter/gl/draw.go:155 +0x13d
fyne.io/fyne/internal/painter/gl.(*glPainter).Paint(0xc000150510, 0xc540c0, 0xc000318200, 0x4, 0x21, 0x303, 0x279)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/painter/gl/painter.go:68 +0x93
fyne.io/fyne/internal/driver/glfw.(*glCanvas).paint.func1(0xc0000a27d0, 0x4, 0x21)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/canvas.go:407 +0x16a
fyne.io/fyne/internal/driver/glfw.(*glCanvas).walkTree.func1(0xc540c0, 0xc000318200, 0x4, 0x21, 0x0, 0x0, 0x7fffffff, 0x7fffffff, 0xc000093c58)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/canvas.go:463 +0x13e
fyne.io/fyne/internal/driver.walkObjectTree(0xc540c0, 0xc000318200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fffffff, 0x7fffffff, ...)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/util.go:74 +0x2d8
fyne.io/fyne/internal/driver.WalkVisibleObjectTree(0xc540c0, 0xc000318200, 0xc000093d10, 0xc000093ce8, 0x2)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/util.go:25 +0x8c
fyne.io/fyne/internal/driver/glfw.(*glCanvas).walkTree(0xc000172000, 0xc000567920, 0xc000093db8, 0xc000093da8)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/canvas.go:484 +0x161
fyne.io/fyne/internal/driver/glfw.(*glCanvas).walkTrees(0xc000172000, 0xc000093db8, 0xc000093da8)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/canvas.go:422 +0x56
fyne.io/fyne/internal/driver/glfw.(*glCanvas).paint(0xc000172000, 0x303, 0x279)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/canvas.go:415 +0xdc
fyne.io/fyne/internal/driver/glfw.(*gLDriver).repaintWindow.func1()
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/loop.go:164 +0x8a
fyne.io/fyne/internal/driver/glfw.(*window).RunWithContext(0xc00016e000, 0xc000093e60)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/window.go:1043 +0x3f
fyne.io/fyne/internal/driver/glfw.(*gLDriver).repaintWindow(0xc0000a20f0, 0xc00016e000)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/loop.go:155 +0x67
fyne.io/fyne/internal/driver/glfw.(*gLDriver).startDrawThread.func1(0xc0000a20f0, 0xc00016a000, 0xc00016c000)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/loop.go:208 +0x238
created by fyne.io/fyne/internal/driver/glfw.(*gLDriver).startDrawThread
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/loop.go:182 +0xc4

goroutine 1 [chan send, locked to thread]:
fyne.io/fyne/internal/driver/glfw.runOnDraw(...)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/loop.go:64
fyne.io/fyne/internal/driver/glfw.(*window).platformResize(0xc00016e000, 0x340, 0x1ef)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/window_other.go:14 +0x12f
fyne.io/fyne/internal/driver/glfw.(*window).resized(0xc00016e000, 0xc000598000, 0x340, 0x1ef)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/window.go:517 +0xbb
fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/glfw.goWindowSizeCB(0x3b3ea30, 0x1ef00000340)
        C:/Users/[redacted]/go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/glfw/window.go:213 +0x68
fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/glfw._cgoexpwrap_b933ac915954_goWindowSizeCB(0x3b3ea30, 0x1ef00000340)
        _cgo_gotypes.go:2690 +0x42
fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/glfw._Cfunc_glfwPollEvents()
        _cgo_gotypes.go:1511 +0x48
fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/glfw.PollEvents()
        C:/Users/[redacted]/go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/glfw/window.go:949 +0x29
fyne.io/fyne/internal/driver/glfw.(*gLDriver).tryPollEvents(0xc0000a20f0)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/loop.go:222 +0x45
fyne.io/fyne/internal/driver/glfw.(*gLDriver).runGL(0xc0000a20f0)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/loop.go:102 +0x1d1
fyne.io/fyne/internal/driver/glfw.(*gLDriver).Run(0xc0000a20f0)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/driver.go:71 +0x3e
fyne.io/fyne/internal/driver/glfw.(*window).ShowAndRun(0xc00016e000)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/window.go:412 +0x5e
main.main()
        C:/Users/[redacted]/go/src/fyne.io/fyne/cmd/fyne_demo/main.go:131 +0xe32

goroutine 19 [sleep, 2 minutes]:
runtime.goparkunlock(...)
        c:/go/src/runtime/proc.go:307
time.Sleep(0x22ecb25c00)
        c:/go/src/runtime/time.go:105 +0x16e
fyne.io/fyne/internal/painter.svgCacheJanitor.func1()
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/painter/svg_cache.go:51 +0x11d
sync.(*Once).Do(0xf545f8, 0xc0000721d0)
        c:/go/src/sync/once.go:44 +0xba
created by fyne.io/fyne/internal/painter.svgCacheJanitor
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/painter/svg_cache.go:49 +0xa2

goroutine 20 [chan receive, 2 minutes]:
fyne.io/fyne/app.newAppWithDriver.func1(0xc00005c300, 0xc0000e8240)
        C:/Users/[redacted]/go/src/fyne.io/fyne/app/app.go:113 +0x44
created by fyne.io/fyne/app.newAppWithDriver
        C:/Users/[redacted]/go/src/fyne.io/fyne/app/app.go:111 +0x18b

goroutine 21 [syscall, 2 minutes, locked to thread]:
syscall.Syscall6(0x7ffba2f15dd0, 0x5, 0x1f0, 0xc000149d10, 0xc000149d14, 0xc000149d78, 0xffffffff, 0x0, 0x0, 0x0, ...)
        c:/go/src/runtime/syscall_windows.go:197 +0xed
syscall.GetQueuedCompletionStatus(0x1f0, 0xc000149d10, 0xc000149d14, 0xc000149d78, 0xffffffff, 0x0, 0x0)
        c:/go/src/syscall/zsyscall_windows.go:556 +0xb6
fyne.io/fyne/vendor/github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc00006e380)
        C:/Users/[redacted]/go/src/fyne.io/fyne/vendor/github.com/fsnotify/fsnotify/windows.go:381 +0x98
created by fyne.io/fyne/vendor/github.com/fsnotify/fsnotify.NewWatcher
        C:/Users/[redacted]/go/src/fyne.io/fyne/vendor/github.com/fsnotify/fsnotify/windows.go:46 +0x21c

goroutine 22 [chan receive, 2 minutes]:
fyne.io/fyne/app.watchFile.func1(0xc00006e380, 0xc00009c2d0, 0x2f, 0xc00005f1f0, 0xc00005f200)
        C:/Users/[redacted]/go/src/fyne.io/fyne/app/settings_desktop.go:42 +0x5f
created by fyne.io/fyne/app.watchFile
        C:/Users/[redacted]/go/src/fyne.io/fyne/app/settings_desktop.go:41 +0xee

goroutine 6 [chan receive, 1 minutes]:
fyne.io/fyne/internal/driver/glfw.(*window).runEventQueue(0xc00016e000)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/window.go:1103 +0xb8
created by fyne.io/fyne/internal/driver/glfw.(*gLDriver).createWindow.func1
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/window.go:1128 +0x10a

goroutine 7 [chan receive, 2 minutes]:
fyne.io/fyne/internal/driver/glfw.(*glCanvas).setupThemeListener.func1(0xc00016a060, 0xc000172000)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/canvas.go:506 +0x4e
created by fyne.io/fyne/internal/driver/glfw.(*glCanvas).setupThemeListener
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/canvas.go:504 +0xad

goroutine 8 [sleep]:
runtime.goparkunlock(...)
        c:/go/src/runtime/proc.go:307
time.Sleep(0x3b9aca00)
        c:/go/src/runtime/time.go:105 +0x16e
fyne.io/fyne/cmd/fyne_demo/screens.GraphicsScreen.func1(0xc000175080)
        C:/Users/[redacted]/go/src/fyne.io/fyne/cmd/fyne_demo/screens/graphics.go:25 +0x48
created by fyne.io/fyne/cmd/fyne_demo/screens.GraphicsScreen
        C:/Users/[redacted]/go/src/fyne.io/fyne/cmd/fyne_demo/screens/graphics.go:23 +0x147

goroutine 9 [chan receive]:
fyne.io/fyne/widget.(*infProgressRenderer).infiniteProgressLoop(0xc000026400)
        C:/Users/[redacted]/go/src/fyne.io/fyne/widget/progressbarinfinite.go:134 +0x3c
created by fyne.io/fyne/widget.(*infProgressRenderer).start
        C:/Users/[redacted]/go/src/fyne.io/fyne/widget/progressbarinfinite.go:113 +0xda

goroutine 66 [sleep]:
runtime.goparkunlock(...)
        c:/go/src/runtime/proc.go:307
time.Sleep(0x3b9aca00)
        c:/go/src/runtime/time.go:105 +0x16e
fyne.io/fyne/cmd/fyne_demo/screens.setScaleText(0xc000318280, 0xc57aa0, 0xc00016e000)
        C:/Users/[redacted]/go/src/fyne.io/fyne/cmd/fyne_demo/screens/advanced.go:25 +0x37
created by fyne.io/fyne/cmd/fyne_demo/screens.AdvancedScreen
        C:/Users/[redacted]/go/src/fyne.io/fyne/cmd/fyne_demo/screens/advanced.go:38 +0x1ea

goroutine 69 [chan receive, 2 minutes]:
fyne.io/fyne/internal/painter.SvgCacheMonitorTheme.func1(0xc00056e120)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/painter/svg_cache.go:103 +0x3b
created by fyne.io/fyne/internal/painter.SvgCacheMonitorTheme
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/painter/svg_cache.go:101 +0xa3
rax     0x6
rbx     0xc4b3a90
rcx     0xa06880c
rdi     0xa06880c
rsi     0x4
rbp     0x1
rsp     0x4b3fd90
r8      0x2
r9      0xfffffffff5f97800
r10     0xc
r11     0x4
r12     0x0
r13     0x52460000
r14     0x0
r15     0xc4b3810
rip     0x52f74360
rflags  0x10287
cs      0x33
fs      0x53
gs      0x2b
```

### Device (please complete the following information):
 - OS: Windows 10 2004 (build 19041.572)
 - Go version: 1.12.7
 - Fyne version: 86d26ebe4d97a525aa5cf1b6720186fc76d3b669

**Comment by andydotxyz** [comment]
If possible could you test the `develop` branch? That code has been updated and we should be releasing the new version in a few days.

**Comment by windexlight** [comment]
I did reproduce a crash in the demo using the latest develop (e28ed2c7d4d3681cfc9072e004cea3d5c55ea3a6).

```
2020/10/26 12:14:58 PlatformError: WGL: Failed to make context current: The requested transformation operation is not supported.
Exception 0xc0000005 0x0 0xc 0x53044360
PC=0x53044360
signal arrived during external code execution

fyne.io/fyne/vendor/github.com/go-gl/gl/v3.2-core/gl._Cfunc_glowDrawArrays(0x52f97100, 0x5, 0x4)
        _cgo_gotypes.go:6242 +0x4c
fyne.io/fyne/vendor/github.com/go-gl/gl/v3.2-core/gl.DrawArrays(...)
        C:/Users/[redacted]/go/src/fyne.io/fyne/vendor/github.com/go-gl/gl/v3.2-core/gl/package.go:9268
fyne.io/fyne/internal/painter/gl.(*glPainter).glDrawTexture(0xc00016a570, 0x3f80000000000001)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/painter/gl/gl_core.go:248 +0xf3
fyne.io/fyne/internal/painter/gl.(*glPainter).drawTextureWithDetails(0xc00016a570, 0xd06b20, 0xc00011ba00, 0xc00008f9d0, 0x4, 0x21, 0x2cc, 0x218, 0x2d4, 0x23d, ...)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/painter/gl/draw.go:76 +0x1e9
fyne.io/fyne/internal/painter/gl.(*glPainter).drawWidget(0xc00016a570, 0xd08ae0, 0xc00011ba00, 0x4, 0x21, 0x2d4, 0x23d)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/painter/gl/draw.go:85 +0x1a7
fyne.io/fyne/internal/painter/gl.(*glPainter).drawObject(0xc00016a570, 0xd06b20, 0xc00011ba00, 0x4, 0x21, 0x2d4, 0x23d)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/painter/gl/draw.go:158 +0x13d
fyne.io/fyne/internal/painter/gl.(*glPainter).Paint(0xc00016a570, 0xd06b20, 0xc00011ba00, 0x4, 0x21, 0x2d4, 0x23d)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/painter/gl/painter.go:68 +0x93
fyne.io/fyne/internal/driver/glfw.(*glCanvas).paint.func1(0xc0000a2190, 0x4, 0x21)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/canvas.go:423 +0x16a
fyne.io/fyne/internal/driver/glfw.(*glCanvas).walkTree.func1(0xd06b20, 0xc00011ba00, 0x4, 0x21, 0x0, 0x0, 0x7fffffff, 0x7fffffff, 0x12f)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/canvas.go:498 +0x13e
fyne.io/fyne/internal/driver.walkObjectTree(0xd06b20, 0xc00011ba00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fffffff, 0x7fffffff, ...)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/util.go:74 +0x2d8
fyne.io/fyne/internal/driver.WalkVisibleObjectTree(0xd06b20, 0xc00011ba00, 0xc00008fd10, 0xc00008fce8, 0x42ecf6)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/util.go:25 +0x8c
fyne.io/fyne/internal/driver/glfw.(*glCanvas).walkTree(0xc00019c000, 0xc00016c4a0, 0xc00008fdb8, 0xc00008fda8)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/canvas.go:519 +0x161
fyne.io/fyne/internal/driver/glfw.(*glCanvas).walkTrees(0xc00019c000, 0xc00008fdb8, 0xc00008fda8)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/canvas.go:526 +0x56
fyne.io/fyne/internal/driver/glfw.(*glCanvas).paint(0xc00019c000, 0x2d4, 0x23d)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/canvas.go:431 +0xdc
fyne.io/fyne/internal/driver/glfw.(*gLDriver).repaintWindow.func1()
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/loop.go:164 +0x8a
fyne.io/fyne/internal/driver/glfw.(*window).RunWithContext(0xc000198000, 0xc00008fe60)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/window.go:1091 +0x3f
fyne.io/fyne/internal/driver/glfw.(*gLDriver).repaintWindow(0xc0000a24b0, 0xc000198000)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/loop.go:155 +0x67
fyne.io/fyne/internal/driver/glfw.(*gLDriver).startDrawThread.func1(0xc0000a24b0, 0xc000188000, 0xc00018c000)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/loop.go:208 +0x238
created by fyne.io/fyne/internal/driver/glfw.(*gLDriver).startDrawThread
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/loop.go:182 +0xc4

goroutine 1 [chan send, locked to thread]:
fyne.io/fyne/internal/driver/glfw.runOnDraw(...)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/loop.go:64
fyne.io/fyne/internal/driver/glfw.(*window).platformResize(0xc000198000, 0x31c, 0x1c9)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/window_other.go:14 +0x12f
fyne.io/fyne/internal/driver/glfw.(*window).resized(0xc000198000, 0xc000149c20, 0x31c, 0x1c9)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/window.go:536 +0xbb
fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/glfw.goWindowSizeCB(0x1f3ea30, 0x1c90000031c)
        C:/Users/[redacted]/go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/glfw/window.go:213 +0x68
fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/glfw._cgoexpwrap_b933ac915954_goWindowSizeCB(0x1f3ea30, 0x1c90000031c)
        _cgo_gotypes.go:2690 +0x42
fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/glfw._Cfunc_glfwPollEvents()
        _cgo_gotypes.go:1511 +0x48
fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/glfw.PollEvents()
        C:/Users/[redacted]/go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/glfw/window.go:949 +0x29
fyne.io/fyne/internal/driver/glfw.(*gLDriver).tryPollEvents(0xc0000a24b0)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/loop.go:222 +0x45
fyne.io/fyne/internal/driver/glfw.(*gLDriver).runGL(0xc0000a24b0)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/loop.go:102 +0x1d1
fyne.io/fyne/internal/driver/glfw.(*gLDriver).Run(0xc0000a24b0)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/driver.go:71 +0x3e
fyne.io/fyne/internal/driver/glfw.(*window).ShowAndRun(0xc000198000)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/window.go:436 +0x5e
main.main()
        C:/Users/[redacted]/go/src/fyne.io/fyne/cmd/fyne_demo/main.go:110 +0xeb0

goroutine 19 [sleep, 3 minutes]:
runtime.goparkunlock(...)
        c:/go/src/runtime/proc.go:307
time.Sleep(0x22ecb25c00)
        c:/go/src/runtime/time.go:105 +0x16e
fyne.io/fyne/internal/painter.svgCacheJanitor.func1()
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/painter/svg_cache.go:51 +0x11d
sync.(*Once).Do(0x106f3a0, 0xc0000721f0)
        c:/go/src/sync/once.go:44 +0xba
created by fyne.io/fyne/internal/painter.svgCacheJanitor
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/painter/svg_cache.go:49 +0xa2

goroutine 20 [chan receive, 4 minutes]:
fyne.io/fyne/test.NewApp.func1(0xc00005c360, 0xc00014be30)
        C:/Users/[redacted]/go/src/fyne.io/fyne/test/testapp.go:103 +0x4f
created by fyne.io/fyne/test.NewApp
        C:/Users/[redacted]/go/src/fyne.io/fyne/test/testapp.go:101 +0x1e0

goroutine 21 [chan receive, 4 minutes]:
fyne.io/fyne/app.newAppWithDriver.func1(0xc00005c4e0, 0xc00014bea0)
        C:/Users/[redacted]/go/src/fyne.io/fyne/app/app.go:126 +0x44
created by fyne.io/fyne/app.newAppWithDriver
        C:/Users/[redacted]/go/src/fyne.io/fyne/app/app.go:124 +0x1f1

goroutine 22 [syscall, 4 minutes, locked to thread]:
syscall.Syscall6(0x7ffba2f15dd0, 0x5, 0x1e0, 0xc000165d10, 0xc000165d14, 0xc000165d78, 0xffffffff, 0x0, 0x0, 0x0, ...)
        c:/go/src/runtime/syscall_windows.go:197 +0xed
syscall.GetQueuedCompletionStatus(0x1e0, 0xc000165d10, 0xc000165d14, 0xc000165d78, 0xffffffff, 0x0, 0x0)
        c:/go/src/syscall/zsyscall_windows.go:556 +0xb6
fyne.io/fyne/vendor/github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc00006eac0)
        C:/Users/[redacted]/go/src/fyne.io/fyne/vendor/github.com/fsnotify/fsnotify/windows.go:381 +0x98
created by fyne.io/fyne/vendor/github.com/fsnotify/fsnotify.NewWatcher
        C:/Users/[redacted]/go/src/fyne.io/fyne/vendor/github.com/fsnotify/fsnotify/windows.go:46 +0x21c

goroutine 23 [chan receive, 4 minutes]:
fyne.io/fyne/app.watchFile.func1(0xc00006eac0, 0xc00009c360, 0x2f, 0xc00005f520, 0xc00005f530)
        C:/Users/[redacted]/go/src/fyne.io/fyne/app/settings_desktop.go:42 +0x5f
created by fyne.io/fyne/app.watchFile
        C:/Users/[redacted]/go/src/fyne.io/fyne/app/settings_desktop.go:41 +0xee

goroutine 36 [chan receive, 3 minutes]:
fyne.io/fyne/internal/driver/glfw.(*window).runEventQueue(0xc000198000)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/window.go:1151 +0xb8
created by fyne.io/fyne/internal/driver/glfw.(*gLDriver).createWindow.func1
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/window.go:1176 +0x10a

goroutine 37 [chan receive, 4 minutes]:
fyne.io/fyne/internal/driver/glfw.(*glCanvas).setupThemeListener.func1(0xc000188060, 0xc00019c000)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/canvas.go:458 +0x4e
created by fyne.io/fyne/internal/driver/glfw.(*glCanvas).setupThemeListener
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/driver/glfw/canvas.go:456 +0xad

goroutine 9 [chan receive, 4 minutes]:
fyne.io/fyne/internal/painter.SvgCacheMonitorTheme.func1(0xc0004b2060)
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/painter/svg_cache.go:103 +0x3b
created by fyne.io/fyne/internal/painter.SvgCacheMonitorTheme
        C:/Users/[redacted]/go/src/fyne.io/fyne/internal/painter/svg_cache.go:101 +0xa3
rax     0x6
rbx     0xcb5ca90
rcx     0xd5210b0
rdi     0xd5210b0
rsi     0x4
rbp     0x1
rsp     0x541fd90
r8      0x2
r9      0xfffffffff2adef5c
r10     0xc
r11     0x4
r12     0x0
r13     0x52530000
r14     0x0
r15     0xcb5c810
rip     0x53044360
rflags  0x10287
cs      0x33
fs      0x53
gs      0x2b
```

**Comment by windexlight** [comment]
For what it's worth, I tried to reproduce on a different Windows 10 PC (both develop and master branches), this one with newer and higher spec hardware. On this other PC, my Go and GCC installations are brand new (Go 1.15.3). Windows version is 1909 (build 18363.1139). I could not manage to get a crash after much trying, but I do get errors on the console at seemingly random intervals:

```
2020/10/26 13:11:41 PlatformError: WGL: Failed to make context current: The requested transformation operation is not supported.
2020/10/26 13:13:49 PlatformError: WGL: Failed to make context current: The requested transformation operation is not supported.
2020/10/26 13:14:43 PlatformError: WGL: Failed to make context current: The requested transformation operation is not supported.
2020/10/26 13:15:02 PlatformError: WGL: Failed to make context current: The handle is invalid.
2020/10/26 13:34:31 PlatformError: WGL: Failed to make context current: The handle is invalid.
2020/10/26 13:35:48 PlatformError: WGL: Failed to make context current: The requested transformation operation is not supported.
2020/10/26 13:39:01 PlatformError: WGL: Failed to make context current: The handle is invalid.
2020/10/26 13:42:46 PlatformError: WGL: Failed to make context current: The handle is invalid.
2020/10/26 13:43:46 PlatformError: WGL: Failed to make context current: The handle is invalid.
```

This is on develop. On the master branch, I get the same errors, but they are also followed by a litany of these (on various lines in gl_core.go):

```
2020/10/26 11:31:57 Error 502 in GL Renderer
2020/10/26 11:31:57   At: C:/Users/[redacted]/go/src/fyne.io/fyne/internal/painter/gl/gl_core.go:84
```

**Comment by Jacalz** [comment]
Hi @windexlight. I know a few have been running Fyne applications though WSL2 recently. Can you please check if this is still and issue on the latest Fyne version?

**Comment by andydotxyz** [comment]
Closing due to lack of activity
