### ISSUE TITLE
Error when running fyne app as systemd service

### ISSUE THREAD

**Issue by Cookie04DE** [fyne-io/fyne#1463]
### Describe the bug:
Running a fyne application as a service on linux fails.

### To Reproduce:
Steps to reproduce the behaviour:
1. Compile main.go
2. Create service file
3. Start service
4. Run systemctl status

### Files:
main.go:
```
package main

import (
	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Test")
	w.SetContent(widget.NewButton("Exit", func() {
		w.Close()
	}))
	w.ShowAndRun()
}
```
huetest.service:
```
[Unit]
Description=Hue Test App

[Service]
Type=simple
ExecStart=/usr/bin/HueTest
[Install]
WantedBy=graphical.target
```
### Systemctl status error:
```
Okt 26 12:51:30 conrad-debian systemd[1]: Started Hue Test App.
Okt 26 12:51:30 conrad-debian HueTest[3391]: 2020/10/26 12:51:30 Fyne error:  Unable to create settings storage:
Okt 26 12:51:30 conrad-debian HueTest[3391]: 2020/10/26 12:51:30   Cause: mkdir .config/fyne: no such file or directory
Okt 26 12:51:30 conrad-debian HueTest[3391]: 2020/10/26 12:51:30   At: /media/conrad/Seagate/Programmieren Server/Go/src/fyne.io/fyne/app/settings_deskt
Okt 26 12:51:30 conrad-debian HueTest[3391]: 2020/10/26 12:51:30 Fyne error:  Settings watch error:
Okt 26 12:51:30 conrad-debian HueTest[3391]: 2020/10/26 12:51:30   Cause: no such file or directory
Okt 26 12:51:30 conrad-debian HueTest[3391]: 2020/10/26 12:51:30   At: /media/conrad/Seagate/Programmieren Server/Go/src/fyne.io/fyne/app/settings_deskt
Okt 26 12:51:30 conrad-debian HueTest[3391]: 2020/10/26 12:51:30 PlatformError: X11: The DISPLAY environment variable is missing
Okt 26 12:51:30 conrad-debian HueTest[3391]: panic: NotInitialized: The GLFW library is not initialized
Okt 26 12:51:30 conrad-debian HueTest[3391]: goroutine 1 [running, locked to thread]:
Okt 26 12:51:30 conrad-debian HueTest[3391]: fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/glfw.acceptError(0x0, 0x0, 0x0, 0x434b4d, 0x77e740)
Okt 26 12:51:30 conrad-debian HueTest[3391]:         /media/conrad/Seagate/Programmieren Server/Go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/gl
Okt 26 12:51:30 conrad-debian HueTest[3391]: fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/glfw.panicError(...)
Okt 26 12:51:30 conrad-debian HueTest[3391]:         /media/conrad/Seagate/Programmieren Server/Go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/gl
Okt 26 12:51:30 conrad-debian HueTest[3391]: fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/glfw.CreateStandardCursor(0x36001, 0x1)
Okt 26 12:51:30 conrad-debian HueTest[3391]:         /media/conrad/Seagate/Programmieren Server/Go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/gl
Okt 26 12:51:30 conrad-debian HueTest[3391]: fyne.io/fyne/internal/driver/glfw.initCursors()
Okt 26 12:51:30 conrad-debian HueTest[3391]:         /media/conrad/Seagate/Programmieren Server/Go/src/fyne.io/fyne/internal/driver/glfw/window.go:34 +0
Okt 26 12:51:30 conrad-debian HueTest[3391]: fyne.io/fyne/internal/driver/glfw.(*gLDriver).initGLFW.func1()
Okt 26 12:51:30 conrad-debian HueTest[3391]:         /media/conrad/Seagate/Programmieren Server/Go/src/fyne.io/fyne/internal/driver/glfw/loop.go:76 +0x6
Okt 26 12:51:30 conrad-debian HueTest[3391]: sync.(*Once).doSlow(0xd15790, 0xc000195de0)
Okt 26 12:51:30 conrad-debian HueTest[3391]:         /media/conrad/Seagate/Installationen/Linux/go/src/sync/once.go:66 +0xec
Okt 26 12:51:30 conrad-debian HueTest[3391]: sync.(*Once).Do(...)
Okt 26 12:51:30 conrad-debian HueTest[3391]:         /media/conrad/Seagate/Installationen/Linux/go/src/sync/once.go:57
Okt 26 12:51:30 conrad-debian HueTest[3391]: fyne.io/fyne/internal/driver/glfw.(*gLDriver).initGLFW(0xc000068140)
Okt 26 12:51:30 conrad-debian HueTest[3391]:         /media/conrad/Seagate/Programmieren Server/Go/src/fyne.io/fyne/internal/driver/glfw/loop.go:69 +0x6
Okt 26 12:51:30 conrad-debian HueTest[3391]: fyne.io/fyne/internal/driver/glfw.(*gLDriver).createWindow.func1()
Okt 26 12:51:30 conrad-debian HueTest[3391]:         /media/conrad/Seagate/Programmieren Server/Go/src/fyne.io/fyne/internal/driver/glfw/window.go:1136 
Okt 26 12:51:30 conrad-debian HueTest[3391]: fyne.io/fyne/internal/driver/glfw.runOnMain(0xc0000754a0)
Okt 26 12:51:30 conrad-debian HueTest[3391]:         /media/conrad/Seagate/Programmieren Server/Go/src/fyne.io/fyne/internal/driver/glfw/loop.go:51 +0xb
Okt 26 12:51:30 conrad-debian HueTest[3391]: fyne.io/fyne/internal/driver/glfw.(*gLDriver).createWindow(0xc000068140, 0x7955ef, 0x4, 0xc00018c001, 0xc00
Okt 26 12:51:30 conrad-debian HueTest[3391]:         /media/conrad/Seagate/Programmieren Server/Go/src/fyne.io/fyne/internal/driver/glfw/window.go:1135 
Okt 26 12:51:30 conrad-debian HueTest[3391]: fyne.io/fyne/internal/driver/glfw.(*gLDriver).CreateWindow(0xc000068140, 0x7955ef, 0x4, 0xc00018c000, 0xc00
Okt 26 12:51:30 conrad-debian HueTest[3391]:         /media/conrad/Seagate/Programmieren Server/Go/src/fyne.io/fyne/internal/driver/glfw/window.go:1127 
Okt 26 12:51:30 conrad-debian HueTest[3391]: fyne.io/fyne/app.(*fyneApp).NewWindow(0xc00018c000, 0x7955ef, 0x4, 0xc00018c000, 0x0)
Okt 26 12:51:30 conrad-debian HueTest[3391]:         /media/conrad/Seagate/Programmieren Server/Go/src/fyne.io/fyne/app/app.go:44 +0x47
Okt 26 12:51:30 conrad-debian HueTest[3391]: main.main()
Okt 26 12:51:30 conrad-debian HueTest[3391]:         /media/conrad/Seagate/Programmieren Server/Go/src/github.com/Cookie04DE/HueTest/main.go:10 +0x56
Okt 26 12:51:30 conrad-debian systemd[1]: huetest.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Okt 26 12:51:30 conrad-debian systemd[1]: huetest.service: Failed with result 'exit-code'.
```

### Device (please complete the following information):
 - OS: Linux Debian
 - Version: 4.19.0-12-amd64
 - Go version: go1.15.3 linux/amd64
 - Fyne version: latest (develop branch)

**Comment by andydotxyz** [comment]
I don't think that systemd services have access to your graphics environment do they?
The error pasted looks like it might not be the whole stack so the cause is not included, but my guess would be it's failing to connect to your X session.

**Comment by Cookie04DE** [comment]
I edited my post to include the whole log. Is there any way to let a fyne app run as a systemd service? I just want this app to launch on startup, so perhaps a systemd service is overkill. If it is not possible for a fyne app to run as a service, is there any other way to launch it at startup?

**Comment by andydotxyz** [comment]
I don't think this is specific to Fyne apps, but likely the same for any graphical app.
You should use your .Xinitrc or your desktop environment's "startup items".
Various options are availalbe but these will ensure that the graphics system is running and available before starting the app.

**Comment by andydotxyz** [comment]
You can see from your log that the problem is indeed a missing X environment:

> PlatformError: X11: The DISPLAY environment variable is missing
