### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by DeadNumbers** [fyne-io/fyne#148]
Code from demo:
```Go
package main

import (
	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
)

func main() {
	app := app.New()

	w := app.NewWindow("Hello")
	w.SetContent(widget.NewVBox(
		widget.NewLabel("Hello Fyne!"),
		widget.NewButton("Quit", func() {
			app.Quit()
		}),
	))

	w.ShowAndRun()
}
```
```
go run demo.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x51bb82]

goroutine 1 [running, locked to thread]:
fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw.(*Window).MakeContextCurrent.func1(0x0)
        /home/user/Go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/context.go:16 +0x22
fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw.(*Window).MakeContextCurrent(0x0)
        /home/user/Go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/context.go:16 +0x2b
fyne.io/fyne/driver/gl.(*gLDriver).CreateWindow.func1()
        /home/user/Go/src/fyne.io/fyne/driver/gl/window.go:779 +0x11c
fyne.io/fyne/driver/gl.runOnMain(0xc0000866c0)
        /home/user/Go/src/fyne.io/fyne/driver/gl/loop.go:39 +0xab
fyne.io/fyne/driver/gl.(*gLDriver).CreateWindow(0xc00009a700, 0x6599a6, 0x5, 0xc0000920c0, 0x7f8900)
        /home/user/Go/src/fyne.io/fyne/driver/gl/window.go:763 +0x99
fyne.io/fyne/app.(*fyneApp).NewWindow(0xc0000920c0, 0x6599a6, 0x5, 0xc0000920c0, 0xc0000a9f88)
        /home/user/Go/src/fyne.io/fyne/app/app.go:33 +0x47
main.main()
        /tmp/demo.go:11 +0xb9
exit status 2
```

**Comment by DeadNumbers** [comment]
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/user/Go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build181348020=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by andydotxyz** [comment]
There was an unreported error here so it's not clear what went wrong.
I have updated the code so that it logs the cause - can you please update and post the new log output?

**Comment by DeadNumbers** [comment]
@andydotxyz 
```
2019/03/13 21:16:13 Window creation error VersionUnavailable: GLX: Failed to create context: GLXBadFBConfig
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x59c226]

goroutine 1 [running, locked to thread]:
fyne.io/fyne/driver/gl.(*window).SetContent(0x0, 0x6a2f00, 0xc00005e420)
        /home/user/Go/src/fyne.io/fyne/driver/gl/window.go:312 +0x26
main.main()
        /tmp/app.go:12 +0x21e
exit status 2
```

**Comment by andydotxyz** [comment]
It looks like a version issue in OpenGL. Can you please provide the result for this command:

glxinfo | grep version

Is there anything unusual about your graphics card or the computer itself?

**Comment by DeadNumbers** [comment]
```
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 0.0
    Max compat profile version: 2.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 2.0
OpenGL version string: 2.1 Mesa 18.3.4
OpenGL shading language version string: 1.20
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 18.3.4
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
```
>Is there anything unusual about your graphics card or the computer itself?
I think, no.

**Comment by andydotxyz** [comment]
It looks like your graphics processor does not support the OpenGL version we require. I had not imagined this would occur on a modern computer. Can you confirm if your CPU is one of the following Fifth generation or earlier? https://en.wikipedia.org/wiki/List_of_Intel_graphics_processing_units#Fifth_generation

We currently require SandyBridge if it's an Intel processor - which started in 2011...

**Comment by andydotxyz** [comment]
I made a working branch that uses an older OpenGL version. If you were able to it would be great for you to try it out. If you can go to the $GOPATH/src/fyne.io/fyne and `git checkout downgrage_opengl` (yes, apologies about the spelling mistake).

Running any fyne example after that may work for you :)

**Comment by ajstarks** [comment]
Here is the similar behavior on Mac (macOS 10.14.3, Go 1.12.1)

```
$ go run hf.go
# fyne.io/fyne/driver/gl
gowork/src/fyne.io/fyne/driver/gl/gl_darwinfix.go:10:5: warning: 'NSOpenGLContext' is deprecated: first deprecated in macOS 10.14 - Please use Metal or MetalKit. [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSOpenGL.h:202:12: note: 'NSOpenGLContext' has been explicitly marked deprecated here
panic: close of closed channel

goroutine 1 [running, locked to thread]:
fyne.io/fyne/driver/gl.(*gLDriver).runGL(0xc0000b66e0)
	/Users/nm55336/gowork/src/fyne.io/fyne/driver/gl/loop.go:90 +0x3b5
fyne.io/fyne/driver/gl.(*gLDriver).Run(0xc0000b66e0)
	/Users/nm55336/gowork/src/fyne.io/fyne/driver/gl/driver.go:55 +0x43
fyne.io/fyne/driver/gl.(*window).ShowAndRun(0xc00010c180)
	/Users/nm55336/gowork/src/fyne.io/fyne/driver/gl/window.go:288 +0x58
main.main()
	/Users/nm55336/work/hf.go:19 +0x235
exit status 2
```

**Comment by andydotxyz** [comment]
This looks like a completely different issue.
I don’t know what exactly to suggest without knowing what your code is doing but a quick guess would be to ask if you are calling ShowAndRun() from a goroutine?

**Comment by ajstarks** [comment]
This is using the hello program:

```
package main

import (
	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
)

func main() {
	a := app.New()

	w := a.NewWindow("Hello")
	w.SetContent(widget.NewVBox(
		widget.NewLabel("Hello Fyne!"),
		widget.NewButton("Quit", func() {
			a.Quit()
		}),
	))

	w.ShowAndRun()
}
```

**Comment by andydotxyz** [comment]
Oh, strange. I have the same machine and the running the same code works fine. It looks like the window is closing as soon as it’s opened - no idea why that could be. 

Is there anything unusual about the terminal or system configuration?

**Comment by ajstarks** [comment]
you see it when you hit the Quit button.  Nothing strange about the system.

**Comment by andydotxyz** [comment]
Ah, that makes sense thanks.
So the application works correctly until you click the Quit button @ajstarks?

I think we can track that down.

**Comment by andydotxyz** [comment]
@ajstarks I think this is exactly what was just reported in #175 - do you agree?

**Comment by ajstarks** [comment]
yes -- the same
