### ISSUE TITLE
Multiple calls to `Quit` panics `NotInitialized: The GLFW library is not initialized`

### ISSUE THREAD

**Issue by AlbinoGeek** [fyne-io/fyne#1731]
### Describe the bug:
If multiple calls to `Quit` occur (due to, for example, windows `SetOnClose` also calling this function) will lead to the following panic being thrown:

```
panic: NotInitialized: The GLFW library is not initialized

goroutine 25 [running]:
github.com/go-gl/glfw/v3.3/glfw.acceptError(0x0, 0x0, 0x0, 0xc00008e4e0, 0xc00008e301)
        /home/damon/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200625191551-73d3c3675aa3/error.go:174 +0x225
github.com/go-gl/glfw/v3.3/glfw.panicError(...)
        /home/damon/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200625191551-73d3c3675aa3/error.go:185
github.com/go-gl/glfw/v3.3/glfw.(*Window).SetShouldClose(0xc0001603f0, 0xc00016c701)
        /home/damon/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200625191551-73d3c3675aa3/window.go:384 +0x4a
fyne.io/fyne/internal/driver/glfw.(*window).Close(0xc00009eea0)
        /home/damon/go/src/fyne@develop/internal/driver/glfw/window.go:425 +0x3c
fyne.io/fyne/app.(*fyneApp).Quit(0xc0001467e0)
        /home/damon/go/src/fyne@develop/app/app.go:71 +0x79
main.main.func3()
        /home/damon/go/src/liquid-sim/main.go:91 +0x2f
fyne.io/fyne/internal/driver/glfw.(*window).runEventQueue(0xc00009eea0)
        /home/damon/go/src/fyne@develop/internal/driver/glfw/window.go:1182 +0x7a
created by fyne.io/fyne/internal/driver/glfw.(*gLDriver).createWindow.func1
        /home/damon/go/src/fyne@develop/internal/driver/glfw/window.go:1206 +0x10d
exit status 2
```

### To Reproduce:
Steps to reproduce the behaviour:
1. Register `SetOnClosed(...)` to quit the app
2. Call the function to quit the app

### Device (please complete the following information):
 - OS: Fedora Linux
 - Version: Workstation 33
 - Go version: 1.15.6 linux/amd64
 - Fyne version: ab0568914435

**Comment by AlbinoGeek** [comment]
This is reproducible in 2.0.0-rc5

**Comment by andydotxyz** [comment]
I cannot replicate this sorry. Perhaps you can test this patch to see if it helps:

```diff
--- a/internal/driver/glfw/window.go
+++ b/internal/driver/glfw/window.go
@@ -428,6 +428,7 @@ func (w *window) Close() {
        }
 
        w.viewport.SetShouldClose(true)
+       w.viewport = nil
 
        w.canvas.walkTrees(nil, func(node *renderCacheNode) {
                switch co := node.obj.(type) {
```

**Comment by AlbinoGeek** [comment]
I cannot replicate this in `2.0.0` with or without the change (refreshed my mod cache, removed rc5 and got the plain version.)
