### ISSUE TITLE
Change Scroll.Direction

### ISSUE THREAD

**Issue by stuartmscott** [fyne-io/fyne#1751]
### Describe the bug:
`ScrollContainer.Direction` is a public API however changing it from one restriction (eg. `ScrollHorizontalOnly`) to another (eg. `ScrollVerticalOnly`) will crash as the ScrollBarAreas are only created once in `ScrollContainer.CreateRenderer`

### Stack:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x42c5f89]

goroutine 13 [running]:
fyne.io/fyne/widget.(*scrollContainerRenderer).layoutBars(0xc0002042a0, 0x4200000043d18000)
	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/widget/scroller.go:252 +0x1a9
fyne.io/fyne/widget.(*scrollContainerRenderer).Layout(0xc0002042a0, 0x4200000043d18000)
	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/widget/scroller.go:274 +0x117
fyne.io/fyne/widget.(*scrollContainerRenderer).Refresh(0xc0002042a0)
	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/widget/scroller.go:293 +0xea
fyne.io/fyne/widget.(*BaseWidget).Refresh(0xc0002444d0)
	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/widget/widget.go:137 +0x5c
fyne.io/fyne/widget.(*ScrollContainer).refreshWithoutOffsetUpdate(...)
	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/widget/scroller.go:432
fyne.io/fyne/widget.(*ScrollContainer).Refresh(0xc0002444d0)
	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/widget/scroller.go:428 +0x4a
```

**Comment by andydotxyz** [comment]
Fixed on `develop`
