### ISSUE TITLE
Error about the new version 2.0.0

### ISSUE THREAD

**Issue by cplasfwst** [fyne-io/fyne#1852]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xba74c7]

goroutine 50 [running, locked to thread]:
fyne.io/fyne/v2/widget.(*tableRenderer).moveIndicators(0xc00013ae00)
        C:/Users/Administrator/go/pkg/mod/fyne.io/fyne/v2@v2.0.0/widget/table.go:316 +0x1c7
fyne.io/fyne/v2/widget.(*tableRenderer).Layout(0xc00013ae00, 0x4402000044460000)
        C:/Users/Administrator/go/pkg/mod/fyne.io/fyne/v2@v2.0.0/widget/table.go:240 +0x36
fyne.io/fyne/v2/internal/driver/glfw.updateLayout(0x105d100, 0xc00005f360)
        C:/Users/Administrator/go/pkg/mod/fyne.io/fyne/v2@v2.0.0/internal/driver/glfw/canvas.go:638 +0x123
fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).ensureMinSize.func1(0xc004d37180)
        C:/Users/Administrator/go/pkg/mod/fyne.io/fyne/v2@v2.0.0/internal/driver/glfw/canvas.go:349 +0x19e
fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).walkTree.func2(0x105c980, 0xc000322540, 0x105d0a0, 0xc000338150)
        C:/Users/Administrator/go/pkg/mod/fyne.io/fyne/v2@v2.0.0/internal/driver/glfw/canvas.go:531 +0xe3
fyne.io/fyne/v2/internal/driver.walkObjectTree(0x105c980, 0xc000322540, 0x436a000041000000, 0x105d0a0, 0xc000338150, 0x436a000041000000, 0x0, 0x4f0000004f000000, 0xc00035bcd8, 0xc00035bcb0, ...)
        C:/Users/Administrator/go/pkg/mod/fyne.io/fyne/v2@v2.0.0/internal/driver/util.go:197 +0x32a
fyne.io/fyne/v2/internal/driver.walkObjectTree.func1(...)
        C:/Users/Administrator/go/pkg/mod/fyne.io/fyne/v2@v2.0.0/internal/driver/util.go:176
fyne.io/fyne/v2/internal/driver.walkObjectTree(0x105d0a0, 0xc000338150, 0x4210000040800000, 0x105d100, 0xc00005f360, 0x4210000040800000, 0x0, 0x4f0000004f000000, 0xc00035bcd8, 0xc00035bcb0, ...)
        C:/Users/Administrator/go/pkg/mod/fyne.io/fyne/v2@v2.0.0/internal/driver/util.go:190 +0x40f
fyne.io/fyne/v2/internal/driver.walkObjectTree.func1(...)
        C:/Users/Administrator/go/pkg/mod/fyne.io/fyne/v2@v2.0.0/internal/driver/util.go:176
fyne.io/fyne/v2/internal/driver.walkObjectTree(0x105d100, 0xc00005f360, 0x4080000040800000, 0x105c6e0, 0xc0000a6540, 0x4080000040800000, 0x0, 0x4f0000004f000000, 0xc00035bcd8, 0xc00035bcb0, ...)
        C:/Users/Administrator/go/pkg/mod/fyne.io/fyne/v2@v2.0.0/internal/driver/util.go:190 +0x40f
fyne.io/fyne/v2/internal/driver.walkObjectTree.func1(...)
        C:/Users/Administrator/go/pkg/mod/fyne.io/fyne/v2@v2.0.0/internal/driver/util.go:176
fyne.io/fyne/v2/internal/driver.walkObjectTree(0x105c6e0, 0xc0000a6540, 0xed806700, 0x0, 0x0, 0x0, 0x0, 0x4f0000004f000000, 0xc00035bcd8, 0xc00035bcb0, ...)
        C:/Users/Administrator/go/pkg/mod/fyne.io/fyne/v2@v2.0.0/internal/driver/util.go:190 +0x40f
fyne.io/fyne/v2/internal/driver.WalkVisibleObjectTree(0x105c6e0, 0xc0000a6540, 0xc00035bcd8, 0xc00035bcb0, 0xc00035bcc8)
        C:/Users/Administrator/go/pkg/mod/fyne.io/fyne/v2@v2.0.0/internal/driver/util.go:134 +0x9b
fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).walkTree(0xc0000a4100, 0xc000004860, 0x0, 0xc00035bdb0)
        C:/Users/Administrator/go/pkg/mod/fyne.io/fyne/v2@v2.0.0/internal/driver/glfw/canvas.go:537 +0x165
fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).walkTrees(0xc0000a4100, 0x0, 0xc00035bdb0)
        C:/Users/Administrator/go/pkg/mod/fyne.io/fyne/v2@v2.0.0/internal/driver/glfw/canvas.go:544 +0x56
fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).ensureMinSize(0xc0000a4100, 0xc00035be20)
        C:/Users/Administrator/go/pkg/mod/fyne.io/fyne/v2@v2.0.0/internal/driver/glfw/canvas.go:354 +0xa5
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow.func1()
        C:/Users/Administrator/go/pkg/mod/fyne.io/fyne/v2@v2.0.0/internal/driver/glfw/loop.go:156 +0x47
fyne.io/fyne/v2/internal/driver/glfw.(*window).RunWithContext(0xc0001421c0, 0xc00035be58)
        C:/Users/Administrator/go/pkg/mod/fyne.io/fyne/v2@v2.0.0/internal/driver/glfw/window.go:1181 +0x3f
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow(0xc00004c3c0, 0xc0001421c0)
        C:/Users/Administrator/go/pkg/mod/fyne.io/fyne/v2@v2.0.0/internal/driver/glfw/loop.go:155 +0x67
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread.func1(0xc00004c3c0, 0xc00008e0c0, 0xc000086050)
        C:/Users/Administrator/go/pkg/mod/fyne.io/fyne/v2@v2.0.0/internal/driver/glfw/loop.go:211 +0x245
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread
        C:/Users/Administrator/go/pkg/mod/fyne.io/fyne/v2@v2.0.0/internal/driver/glfw/loop.go:182 +0xc8
exit status 2

```

**Comment by Jacalz** [comment]
Can you please fill out the issue template? The issue templates are there to help us more easily reproduce issues. Not having that information makes it harder for use to be able to help.

**Comment by andydotxyz** [comment]
At lest we need replication steps - there is no information about what application was being run, or how the error occurred.

**Comment by andydotxyz** [comment]
Closing due to no activity, many issues in this area were solved in following patch releases
