### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by yale8848** [fyne-io/fyne#189]
i test fyne_demo/input.go ,when i press some characters random, it will be panic.

Env:
fyne.io/fyne v0.0.0-20190323142420-7491e6591c72
window10 64 
go 1.12

```
panic: runtime error: index out of range

goroutine 1 [running, locked to thread]:
fyne.io/fyne/widget.(*textRenderer).MinSize(0xc0003be200, 0xc00015a090, 0x953d40)
	C:/YaleSoftFiles/WorkSpace/Go/pkg/mod/fyne.io/fyne@v0.0.0-20190323142420-7491e6591c72/widget/text.go:206 +0x113
fyne.io/fyne/widget.(*baseWidget).minSize(0xc00015a090, 0x954e20, 0xc00015a090, 0x954700, 0xc00015a090)
	C:/YaleSoftFiles/WorkSpace/Go/pkg/mod/fyne.io/fyne@v0.0.0-20190323142420-7491e6591c72/widget/widget.go:48 +0x74
fyne.io/fyne/widget.(*Label).MinSize(...)
	C:/YaleSoftFiles/WorkSpace/Go/pkg/mod/fyne.io/fyne@v0.0.0-20190323142420-7491e6591c72/widget/label.go:85
fyne.io/fyne/widget.(*groupRenderer).Layout(0xc0003be1c0, 0x90, 0x103)
	C:/YaleSoftFiles/WorkSpace/Go/pkg/mod/fyne.io/fyne@v0.0.0-20190323142420-7491e6591c72/widget/group.go:116 +0x1d0
fyne.io/fyne/widget.(*groupRenderer).Refresh(0xc0003be1c0)
	C:/YaleSoftFiles/WorkSpace/Go/pkg/mod/fyne.io/fyne@v0.0.0-20190323142420-7491e6591c72/widget/group.go:138 +0x85
fyne.io/fyne/widget.Refresh(0x954d00, 0xc0003ec0f0)
	C:/YaleSoftFiles/WorkSpace/Go/pkg/mod/fyne.io/fyne@v0.0.0-20190323142420-7491e6591c72/widget/widget.go:99 +0x5f
fyne.io/fyne/widget.(*Group).Prepend(0xc0003ec0f0, 0x954700, 0xc00010a630)
	C:/YaleSoftFiles/WorkSpace/Go/pkg/mod/fyne.io/fyne@v0.0.0-20190323142420-7491e6591c72/widget/group.go:51 +0x14b
git.daoxuehao.com/YaleRen/fyne-hello/demo.prependTo(0xc0003ec0f0, 0xc000442690, 0x7)
	C:/YaleSoftFiles/WorkSpace/Go/src/git.daoxuehao.com/YaleRen/fyne-hello/demo/input.go:42 +0x91
git.daoxuehao.com/YaleRen/fyne-hello/demo.Input.func1(0xc000000073)
	C:/YaleSoftFiles/WorkSpace/Go/src/git.daoxuehao.com/YaleRen/fyne-hello/demo/input.go:26 +0xa3
fyne.io/fyne/driver/gl.(*window).charModInput(0xc0003e2100, 0xc0003e2080, 0x73, 0x0)
	C:/YaleSoftFiles/WorkSpace/Go/pkg/mod/fyne.io/fyne@v0.0.0-20190323142420-7491e6591c72/driver/gl/window.go:796 +0x71
github.com/go-gl/glfw/v3.2/glfw.goCharModsCB(0x326e830, 0x73)
	C:/YaleSoftFiles/WorkSpace/Go/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190217072633-93b30450e032/v3.2/glfw/input.go:300 +0x64
github.com/go-gl/glfw/v3.2/glfw._cgoexpwrap_23342e142132_goCharModsCB(0x326e830, 0x73)
	_cgo_gotypes.go:2135 +0x42
github.com/go-gl/glfw/v3.2/glfw._Cfunc_glfwPollEvents()
	_cgo_gotypes.go:1171 +0x48
github.com/go-gl/glfw/v3.2/glfw.PollEvents()
	C:/YaleSoftFiles/WorkSpace/Go/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190217072633-93b30450e032/v3.2/glfw/window.go:777 +0x29
fyne.io/fyne/driver/gl.(*gLDriver).runGL(0xc000050b20)
	C:/YaleSoftFiles/WorkSpace/Go/pkg/mod/fyne.io/fyne@v0.0.0-20190323142420-7491e6591c72/driver/gl/loop.go:77 +0x1dc
fyne.io/fyne/driver/gl.(*gLDriver).Run(0xc000050b20)
	C:/YaleSoftFiles/WorkSpace/Go/pkg/mod/fyne.io/fyne@v0.0.0-20190323142420-7491e6591c72/driver/gl/driver.go:58 +0x4a
fyne.io/fyne/driver/gl.(*window).ShowAndRun(0xc0000d6100)
	C:/YaleSoftFiles/WorkSpace/Go/pkg/mod/fyne.io/fyne@v0.0.0-20190323142420-7491e6591c72/driver/gl/window.go:288 +0x5f
main.main()
	C:/YaleSoftFiles/WorkSpace/Go/src/git.daoxuehao.com/YaleRen/fyne-hello/main/main.go:102 +0xe4c

```

some times panic like this:

```
panic: runtime error: index out of range

goroutine 570 [running]:
github.com/goki/freetype/truetype.(*GlyphBuf).loadSimple(0xc000062300, 0x7281b4, 0x58, 0x5cac8, 0x1, 0x7281c2, 0x20, 0x5caba)
	C:/YaleSoftFiles/WorkSpace/Go/pkg/mod/github.com/goki/freetype@v0.0.0-20181231101311-fa8a33aabaff/truetype/glyph.go:338 +0x8b7
github.com/goki/freetype/truetype.(*GlyphBuf).load(0xc000062300, 0x9501002e00000000, 0x0, 0x0)
	C:/YaleSoftFiles/WorkSpace/Go/pkg/mod/github.com/goki/freetype@v0.0.0-20181231101311-fa8a33aabaff/truetype/glyph.go:234 +0x9e2
github.com/goki/freetype/truetype.(*GlyphBuf).Load(0xc000062300, 0xc000096780, 0x2e00000340, 0x0, 0x0, 0x0)
	C:/YaleSoftFiles/WorkSpace/Go/pkg/mod/github.com/goki/freetype@v0.0.0-20181231101311-fa8a33aabaff/truetype/glyph.go:104 +0x222
github.com/goki/freetype/truetype.(*face).GlyphAdvance(0xc00005f800, 0xc00000004b, 0x0)
	C:/YaleSoftFiles/WorkSpace/Go/pkg/mod/github.com/goki/freetype@v0.0.0-20181231101311-fa8a33aabaff/truetype/face.go:371 +0x18c
fyne.io/fyne/driver/gl.(*compositeFace).GlyphAdvance(0xc00042e240, 0xc00000004b, 0x0)
	C:/YaleSoftFiles/WorkSpace/Go/pkg/mod/fyne.io/fyne@v0.0.0-20190323142420-7491e6591c72/driver/gl/font.go:48 +0x91
golang.org/x/image/font.MeasureString(0x9d8d60, 0xc00042e240, 0xc000058730, 0xa, 0x0)
	C:/YaleSoftFiles/WorkSpace/Go/pkg/mod/golang.org/x/image@v0.0.0-20190227222117-0694c2d4d067/font/font.go:299 +0x115
fyne.io/fyne/driver/gl.(*gLDriver).RenderedTextSize(0xc00004eb20, 0xc000058730, 0xa, 0xc, 0x0, 0x0, 0x0)
	C:/YaleSoftFiles/WorkSpace/Go/pkg/mod/fyne.io/fyne@v0.0.0-20190323142420-7491e6591c72/driver/gl/driver.go:44 +0x104
fyne.io/fyne/canvas.(*Text).MinSize(0xc0000353b0, 0x0, 0x0)
	C:/YaleSoftFiles/WorkSpace/Go/pkg/mod/fyne.io/fyne@v0.0.0-20190323142420-7491e6591c72/canvas/text.go:26 +0x10b
fyne.io/fyne/widget.(*textRenderer).MinSize(0xc0002be9c0, 0x0, 0x0)
	C:/YaleSoftFiles/WorkSpace/Go/pkg/mod/fyne.io/fyne@v0.0.0-20190323142420-7491e6591c72/widget/text.go:205 +0xb0
fyne.io/fyne/widget.(*baseWidget).minSize(0xc00010d710, 0x9da7a0, 0xc00010d710, 0x0, 0x0)
	C:/YaleSoftFiles/WorkSpace/Go/pkg/mod/fyne.io/fyne@v0.0.0-20190323142420-7491e6591c72/widget/widget.go:48 +0x9d
fyne.io/fyne/widget.(*Label).MinSize(0xc00010d710, 0x0, 0x0)
	C:/YaleSoftFiles/WorkSpace/Go/pkg/mod/fyne.io/fyne@v0.0.0-20190323142420-7491e6591c72/widget/label.go:85 +0x61
fyne.io/fyne/layout.(*boxLayout).Layout(0xc0000584ec, 0xc000144000, 0x2f, 0x30, 0xa5, 0x920)
	C:/YaleSoftFiles/WorkSpace/Go/pkg/mod/fyne.io/fyne@v0.0.0-20190323142420-7491e6591c72/layout/boxlayout.go:55 +0x746
fyne.io/fyne/widget.(*boxRenderer).Layout(0xc00006a9f0, 0xa5, 0x920)
	C:/YaleSoftFiles/WorkSpace/Go/pkg/mod/fyne.io/fyne@v0.0.0-20190323142420-7491e6591c72/widget/box.go:112 +0x83
fyne.io/fyne/widget.(*boxRenderer).Refresh(0xc00006a9f0)
	C:/YaleSoftFiles/WorkSpace/Go/pkg/mod/fyne.io/fyne@v0.0.0-20190323142420-7491e6591c72/widget/box.go:132 +0xaf
fyne.io/fyne/widget.Refresh(0x9da4a0, 0xc000088fc0)
	C:/YaleSoftFiles/WorkSpace/Go/pkg/mod/fyne.io/fyne@v0.0.0-20190323142420-7491e6591c72/widget/widget.go:99 +0x63
fyne.io/fyne/widget.(*Box).Prepend(0xc000088fc0, 0x9da0e0, 0xc00010d710)
	C:/YaleSoftFiles/WorkSpace/Go/pkg/mod/fyne.io/fyne@v0.0.0-20190323142420-7491e6591c72/widget/box.go:58 +0x289
fyne.io/fyne/widget.(*Group).Prepend(0xc0000864b0, 0x9da0e0, 0xc00010d710)
	C:/YaleSoftFiles/WorkSpace/Go/pkg/mod/fyne.io/fyne@v0.0.0-20190323142420-7491e6591c72/widget/group.go:49 +0x51
git.daoxuehao.com/YaleRen/fyne-hello/demo.prependTo(0xc0000864b0, 0xc000058700, 0xa)
	C:/YaleSoftFiles/WorkSpace/Go/src/git.daoxuehao.com/YaleRen/fyne-hello/demo/input.go:42 +0x65
git.daoxuehao.com/YaleRen/fyne-hello/demo.Input.func3(0xc0000443f0)
	C:/YaleSoftFiles/WorkSpace/Go/src/git.daoxuehao.com/YaleRen/fyne-hello/demo/input.go:32 +0xa6
created by fyne.io/fyne/driver/gl.(*window).keyPressed
	C:/YaleSoftFiles/WorkSpace/Go/pkg/mod/fyne.io/fyne@v0.0.0-20190323142420-7491e6591c72/driver/gl/window.go:699 +0x84f

```
![image](https://user-images.githubusercontent.com/2555005/55046084-3dd3c900-507b-11e9-8ab8-751fb6dbf4bf.png)

**Comment by steveoc64** [comment]
Thanks for posting (with stack trace !!)

The second crash is happening deep inside a 3rd party TrueType lib - will have a look at that separately and maybe fix it in the upstream `github.com/goki/freetype`.

**Comment by steveoc64** [comment]
1st item is a classic race condition with slices ... should be able to post a fix for that shortly.

(in several places) its iterating over a slice of "texts" in 1 thread, and then re-setting the slice to empty in another thread.

When this happens, the original iterator keeps looping over the old, now-dead data.  (You can dump the asm output to prove that the compiler does this).   So now inside the loop, all references into the slice being iterated over are at risk of exploding, either through index out of range errors, or worse - segfault from memory access to items that have been GC'd since the start of the iteration.

Fix is to use a mutex around any slices where other goroutines can reset the entire slice.

There is a performance hit with the mutex approach - might be a better way to avoid the crash, but at least the mutex will stop it crashing.

Why are we resetting the []texts on each refresh ?  is there a better way around this ?

**Comment by andydotxyz** [comment]
The freetype lib is marked as not thread safe. It's on us to not call it on multiple threads :(

**Comment by andydotxyz** [comment]
This may not be fully resolved, but the alternative crash is tracked under #164
