### ISSUE TITLE
Fyne app crash (SIGSEGV)

### ISSUE THREAD

**Issue by Nelegres** [fyne-io/fyne#2116]
### Describe the bug:
I wanted to have a scrollable window that displays only a limited number of lines (for example 20). To achieve that I used a VBox and add/remove elements when the counter is above 20. If I run the main.go the program crashes immediately but if I put a 50ms delay before the Refresh() it does not.

### Example code:
**main.go:** 

```
package main

import (
	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/canvas"
	"fyne.io/fyne/container"
	"image/color"
	"strconv"
        "time"
)

func main() {
	a := app.New()
	w := a.NewWindow("hello world")
	w.Resize(fyne.NewSize(1000, 600))
	logBox := container.NewVBox()
	scroll := container.NewScroll(logBox)
	queue := make([]*canvas.Text, 0)
	counter := 0
	go func() {
		for {
			if counter >= 20 {
				logBox.Remove(queue[counter-20])
			}
			counterString := canvas.NewText("String: " + strconv.Itoa(counter), color.White)
			queue = append(queue, counterString)
			logBox.Add(counterString)
                        //time.Sleep(50 * time.Millisecond)
			logBox.Refresh()
			counter++
		}
	}()
	w.SetContent(scroll)
	w.ShowAndRun()
}
```

**Stack trace:** 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x5a4687]

goroutine 23 [running, locked to thread]:
fyne.io/fyne/internal/driver.walkObjectTree(0x0, 0x0, 0x7eab58, 0xc00012c230, 0x0, 0x0, 0x0, 0x0, 0x7fffffff, 0x7fffffff, ...)
        /home/justin/go/pkg/mod/fyne.io/fyne@v1.4.3/internal/driver/util.go:58 +0x47
fyne.io/fyne/internal/driver.walkObjectTree(0x7eab58, 0xc00012c230, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fffffff, 0x7fffffff, ...)
        /home/justin/go/pkg/mod/fyne.io/fyne@v1.4.3/internal/driver/util.go:81 +0x1ef
fyne.io/fyne/internal/driver.WalkCompleteObjectTree(0x7eab58, 0xc00012c230, 0xc000105e00, 0x0, 0xc00012c200)
        /home/justin/go/pkg/mod/fyne.io/fyne@v1.4.3/internal/driver/util.go:43 +0x85
fyne.io/fyne/internal/driver/glfw.freeDirtyTextures(0xc0001c2000)
        /home/justin/go/pkg/mod/fyne.io/fyne@v1.4.3/internal/driver/glfw/loop.go:233 +0x6c
fyne.io/fyne/internal/driver/glfw.(*gLDriver).repaintWindow.func1()
        /home/justin/go/pkg/mod/fyne.io/fyne@v1.4.3/internal/driver/glfw/loop.go:161 +0x5e
fyne.io/fyne/internal/driver/glfw.(*window).RunWithContext(0xc00010eb60, 0xc000105ea8)
        /home/justin/go/pkg/mod/fyne.io/fyne@v1.4.3/internal/driver/glfw/window.go:1095 +0x38
fyne.io/fyne/internal/driver/glfw.(*gLDriver).repaintWindow(0xc00012c0f0, 0xc00010eb60)
        /home/justin/go/pkg/mod/fyne.io/fyne@v1.4.3/internal/driver/glfw/loop.go:155 +0x65
fyne.io/fyne/internal/driver/glfw.(*gLDriver).startDrawThread.func1(0xc00012c0f0, 0xc00012e3c0, 0xc00012c190)
        /home/justin/go/pkg/mod/fyne.io/fyne@v1.4.3/internal/driver/glfw/loop.go:208 +0x269
created by fyne.io/fyne/internal/driver/glfw.(*gLDriver).startDrawThread
        /home/justin/go/pkg/mod/fyne.io/fyne@v1.4.3/internal/driver/glfw/loop.go:182 +0xbd

Process finished with exit code 2
```

### Device (please complete the following information):
 - **OS:** Linux Mint
 - **Version:** 20.1 (Ulyssa)
 - **Go version:** go1.16 linux/amd64
 - **Fyne version:** v.2.0.0

**Comment by andydotxyz** [comment]
Can you try calling `SetContent` before you start the goroutine?
The call to `Refresh()` expects the element to be in a window, so that might be the cause of the nil pointer...

**Comment by Nelegres** [comment]
I moved w.SetContent(scroll) to before the goroutine but I got the same problem.

**Comment by andydotxyz** [comment]
Can you please try with latest fyne API?
Your bug report says you are using `2.0.0` but the code says you are not (as the imports are for <= `1.4.3`).

**Comment by andydotxyz** [comment]
I am not able to replicate the stack trace using >= 2.0.1

**Comment by Nelegres** [comment]
You were right I was using an older version and not 2.0.1. The crash does not happen anymore thanks!
