### ISSUE TITLE
Fyne apps do not scale properly in mobile Linux

### ISSUE THREAD

**Issue by Arsen6331** [fyne-io/fyne#2280]
### Describe the bug:
When using a Fyne app on a mobile Linux device (PinePhone specifically), it does not scale properly.

### To Reproduce:
Steps to reproduce the behaviour:
1. Install Manjaro with Plasma Mobile on PinePhone
2. Install `base-devel`
3. Use git to clone repo: `git clone https://aur.archlinux.org/permafrost-git.git`
4. Run `makepkg -si` in repo
5. Open permafrost from menu

### Screenshots:
Portrait:
![Screenshot_20210609_010850](https://user-images.githubusercontent.com/41810442/121317924-9c359c80-c8bf-11eb-9f43-68bd0a22327d.png)
Landscape:
![Screenshot_20210609_010944](https://user-images.githubusercontent.com/41810442/121317942-9fc92380-c8bf-11eb-8d30-3f8b0ecfef7b.png)

### Device:
 - **OS:** Linux
 - **Version:** 5.12.9
 - **Go version:** 1.16.5
 - **Fyne version:** 2.0.3

**Comment by Jacalz** [comment]
The mobile support requires building using the mobile driver. Are you compiling with `go build -tags mobile`?

**Comment by Arsen6331** [comment]
I did not think to do so as the docs say that the mobile tag is for a simulator. Anyway, trying that, I received the following panic:

```go
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x103 pc=0xffff856abfe0]

runtime stack:
runtime.throw(0x845bd0, 0x2a)
	/usr/lib/go/src/runtime/panic.go:1117 +0x54
runtime.sigpanic()
	/usr/lib/go/src/runtime/signal_unix.go:718 +0x29c

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x753830, 0x40005b3c78, 0x4000094550)
	/usr/lib/go/src/runtime/cgocall.go:154 +0x50 fp=0x40005b3c40 sp=0x40005b3c00 pc=0x409390
github.com/fyne-io/mobile/app._Cfunc_createWindow()
	_cgo_gotypes.go:58 +0x40 fp=0x40005b3c70 sp=0x40005b3c40 pc=0x715c10
github.com/fyne-io/mobile/app.main(0x40000a1fc0)
	/home/arsen/go/pkg/mod/github.com/fyne-io/mobile@v0.1.3-0.20210412090810-650a3139866a/app/x11.go:44 +0x78 fp=0x40005b3db0 sp=0x40005b3c70 pc=0x716448
github.com/fyne-io/mobile/app.Main(...)
	/home/arsen/go/pkg/mod/github.com/fyne-io/mobile@v0.1.3-0.20210412090810-650a3139866a/app/app.go:21
fyne.io/fyne/v2/internal/driver/gomobile.(*mobileDriver).Run(0x40000943c0)
	/home/arsen/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/driver/gomobile/driver.go:114 +0x5c fp=0x40005b3de0 sp=0x40005b3db0 pc=0x71c8ec
fyne.io/fyne/v2/internal/driver/gomobile.(*window).ShowAndRun(0x40000929c0)
	/home/arsen/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/driver/gomobile/window.go:172 +0x54 fp=0x40005b3e10 sp=0x40005b3de0 pc=0x71f294
main.initGUI()
	/home/arsen/permafrost/main.go:93 +0x1d0 fp=0x40005b3e80 sp=0x40005b3e10 pc=0x750f50
main.main()
	/home/arsen/permafrost/main.go:45 +0x5f0 fp=0x40005b3f70 sp=0x40005b3e80 pc=0x750d40
runtime.main()
	/usr/lib/go/src/runtime/proc.go:225 +0x274 fp=0x40005b3fd0 sp=0x40005b3f70 pc=0x43afe4
runtime.goexit()
	/usr/lib/go/src/runtime/asm_arm64.s:1130 +0x4 fp=0x40005b3fd0 sp=0x40005b3fd0 pc=0x46bb04

goroutine 21 [select]:
fyne.io/fyne/v2/data/binding.makeInfiniteQueue.func1(0x4000096120, 0x40000bc0b0)
	/home/arsen/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/data/binding/queue.go:36 +0xf8
created by fyne.io/fyne/v2/data/binding.makeInfiniteQueue
	/home/arsen/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/data/binding/queue.go:21 +0xa0

goroutine 22 [chan receive]:
fyne.io/fyne/v2/data/binding.processItems()
	/home/arsen/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/data/binding/queue.go:54 +0x3c
created by fyne.io/fyne/v2/data/binding.init.0
	/home/arsen/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/data/binding/queue.go:15 +0x30

goroutine 23 [sleep]:
time.Sleep(0x22ecb25c00)
	/usr/lib/go/src/runtime/time.go:193 +0xcc
fyne.io/fyne/v2/internal/painter.svgCacheJanitor.func1()
	/home/arsen/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/painter/svg_cache.go:57 +0xe0
sync.(*Once).doSlow(0xe17bb8, 0x40000bace0)
	/usr/lib/go/src/sync/once.go:68 +0x11c
sync.(*Once).Do(0xe17bb8, 0x40000bace0)
	/usr/lib/go/src/sync/once.go:59 +0x44
created by fyne.io/fyne/v2/internal/painter.svgCacheJanitor
	/home/arsen/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/painter/svg_cache.go:55 +0x9c

goroutine 24 [select]:
github.com/fyne-io/mobile/app.pump.func1(0x4000096180, 0x40000bc0b8)
	/home/arsen/go/pkg/mod/github.com/fyne-io/mobile@v0.1.3-0.20210412090810-650a3139866a/app/app.go:189 +0x124
created by github.com/fyne-io/mobile/app.pump
	/home/arsen/go/pkg/mod/github.com/fyne-io/mobile@v0.1.3-0.20210412090810-650a3139866a/app/app.go:172 +0x88

goroutine 25 [chan receive]:
fyne.io/fyne/v2/app.newAppWithDriver.func1(0x40000963c0, 0x400026a230)
	/home/arsen/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/app/app.go:120 +0x34
created by fyne.io/fyne/v2/app.newAppWithDriver
	/home/arsen/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/app/app.go:118 +0x1c4

goroutine 26 [chan receive]:
fyne.io/fyne/v2/internal/driver/gomobile.(*mobileCanvas).setupThemeListener.func1(0x4000096420, 0x40000d0c60)
	/home/arsen/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/driver/gomobile/canvas.go:326 +0x2c
created by fyne.io/fyne/v2/internal/driver/gomobile.(*mobileCanvas).setupThemeListener
	/home/arsen/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/driver/gomobile/canvas.go:324 +0x94

goroutine 3 [chan receive]:
fyne.io/fyne/v2/internal/painter.SvgCacheMonitorTheme.func1(0x40000260c0)
	/home/arsen/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/painter/svg_cache.go:109 +0x2c
created by fyne.io/fyne/v2/internal/painter.SvgCacheMonitorTheme
	/home/arsen/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/painter/svg_cache.go:107 +0x8c
```

**Comment by andydotxyz** [comment]
PinePhone support is somewhat early as it uses wayland (at least mine does). I guess you have an X compatibility layer added?

Does it work better/worse if you do `fyne build -tags wayland`?

**Comment by andydotxyz** [comment]
I just tested this today and it should be working now. I have opened a new issue for tracking completion of PinePhone support (#2721)

Compile command: `CGO_ENABLED=1 GOARCH=arm64 CC=/usr/bin/aarch64-linux-gnu-gcc  go build -tags mobile,wayland .`

**Comment by Arsen6331** [comment]
It does mostly work, but the screen is blurry. Also, text overlaps other elements, but it's much better than before.

**Comment by Arsen6331** [comment]
![Screenshot of pinephone](https://user-images.githubusercontent.com/41810442/151678549-d84636f5-870f-4906-8fe6-1c3bb0e34cea.png)

**Comment by andydotxyz** [comment]
The overlap is not a driver issue - your app is requesting to put more content in than the screen allows. You might need to consider updating your UI. Standard Grid can be a drawback here, consider AdaptiveGrid instead.

**Comment by andydotxyz** [comment]
Text blurring might be a <1 scale that we maybe should not support… can you install the fyne_demo app and see what “Advanced” reports for scale please?

**Comment by Arsen6331** [comment]
Here is the advanced section:

![Fyne demo advanced section screenshot](https://user-images.githubusercontent.com/41810442/151719002-6b116865-bd34-4adf-8a2f-64c83429f532.png)

**Comment by Arsen6331** [comment]
I ran it using `go run fyne.io/fyne/v2/cmd/fyne_demo@develop -tags wayland,mobile` if that's relevant.

**Comment by andydotxyz** [comment]
Thanks. Texture scale of 0.91 could be causing the blur and looks erroneous. It will require a little exploration of the code to see why this could be happening.

**Comment by andydotxyz** [comment]
Is this still an issue @Elara6331 ? There have been a lot of changes to text handling in the last year!

**Comment by andydotxyz** [comment]
This should now be resolved along with #4390 and others
