### ISSUE TITLE
app can't lunch on android 4.1.2 jelly bean (api 16)

### ISSUE THREAD

**Issue by madaxemad** [fyne-io/fyne#2327]
### Describe the bug:
app can't lunch on android 4.1.2 jelly bean (api 16)
any code even simple test

### To Reproduce:
on new fyne golang i compiled all ways were possible fyne fyne-cross but it don't lunch

last versions were ok! had no problem with api16 (fyne2.0.0,fyne-cross 1.0.0)

if jelly bean is out for fyne it must not install on api 16 and don't run ,
must installed and run or don't parse on api 16 at all

### Example code:
any simple code

### Device (please complete the following information):
 - **OS:** android api16 jellybean 4.1.2
 - **Version:** 2.0.3
 - **Go version:** 16.6.6
 - **Fyne version:** 2.0.3

**Comment by andydotxyz** [comment]
Can you share any errors you see? It should work down to Android 4.1.
Can you please add information on what device you are using?

**Comment by madaxemad** [comment]
> Can you share any errors you see?
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] pkg=com.temp.pkg }
Error: Activity not started, unable to resolve Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.temp.pkg }


> Can you please add information on what device you are using?

galaxy star

**Comment by madaxemad** [comment]
:Monkey: seed=0 count=500
:AllowPackage: com.temp.pkg
:IncludeCategory: android.intent.category.LAUNCHER
:IncludeCategory: android.intent.category.MONKEY
// Event percentages:
//   0: 15.0%
//   1: 10.0%
//   2: 2.0%
//   3: 15.0%
//   4: -0.0%
//   5: 25.0%
//   6: 15.0%
//   7: 2.0%
//   8: 2.0%
//   9: 1.0%
//   10: 13.0%
// Monkey Start Time : 1555722019
:Switch: #Intent;action=android.intent.action.MAIN;category=android.intent.category.LAUNCHER;launchFlags=0x10200000;component=com.temp.pkg/org.golang.app.GoNativeActivity;end
    // Allowing start of Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.temp.pkg/org.golang.app.GoNativeActivity } in package com.temp.pkg
:Sending Flip keyboardOpen=false
:Sending Touch (ACTION_DOWN): 0:(73.0,47.0)
:Sending Touch (ACTION_UP): 0:(73.19875,47.495113)
    // Rejecting start of Intent { cmp=com.sec.android.app.popupuireceiver/.popupNetworkError } in package com.sec.android.app.popupuireceiver
// First JavaCrash Time : 1555724461
// CRASH: com.temp.pkg (pid 32759)
// Short Msg: java.lang.IllegalArgumentException
// Long Msg: java.lang.IllegalArgumentException: Unable to load native library: /data/data/com.temp.pkg/lib/libm.so
// Build Label: samsung/mintxx/mint:4.1.2/JZO54K/S5282XXAMI5:user/release-keys
// Build Changelist: S5282XXAMI5
// Build Time: 1380506980000
// java.lang.RuntimeException: Unable to start activity ComponentInfo{com.temp.pkg/org.golang.app.GoNativeActivity}: java.lang.IllegalArgumentException: Unable to load native library: /data/data/com.temp.pkg/lib/libm.so
//      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2121)
//      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2146)
//      at android.app.ActivityThread.access$700(ActivityThread.java:140)
//      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238)
//      at android.os.Handler.dispatchMessage(Handler.java:99)
//      at android.os.Looper.loop(Looper.java:137)
//      at android.app.ActivityThread.main(ActivityThread.java:4944)
//      at java.lang.reflect.Method.invokeNative(Native Method)
//      at java.lang.reflect.Method.invoke(Method.java:511)
//      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
//      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
//      at dalvik.system.NativeStart.main(Native Method)
// Caused by: java.lang.IllegalArgumentException: Unable to load native library: /data/data/com.temp.pkg/lib/libm.so
//      at android.app.NativeActivity.onCreate(NativeActivity.java:199)
//      at org.golang.app.GoNativeActivity.onCreate(GoNativeActivity.java:209)
//      at android.app.Activity.performCreate(Activity.java:5188)
//      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
//      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2085)
//      ... 11 more
//
** Monkey aborted due to error.
Events injected: 12
:Sending rotation degree=0, persist=false
:Dropped: keys=0 pointers=0 trackballs=0 flips=0 rotations=0
## Network stats: elapsed time=9509ms (0ms mobile, 0ms wifi, 9509ms not connected)
** System appears to have crashed at event 12 of 500 using seed 0

**Comment by andydotxyz** [comment]
Is there nothing more to that error? The "Caused by" lines don't seem to conclude down to the underlying cause. (The last exception in the stack is likely the most important).
