### ISSUE TITLE
panic: FormatUnavailable: NSGL: Failed to find a suitable pixel format

### ISSUE THREAD

**Issue by Antonboom** [fyne-io/fyne#2373]
No idea how to repoduce :(

```
GLFW: An invalid error was not accepted by the caller: FormatUnavailable: NSGL: Failed to find a suitable pixel format
GLFW: Please report this bug in the Go package immediately.
panic: FormatUnavailable: NSGL: Failed to find a suitable pixel format

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.acceptError(0xc001c53cc0, 0x2, 0x2, 0x0, 0x0)
        /Users/a.telyshev/xxx/vendor/github.com/go-gl/glfw/v3.3/glfw/error.go:178 +0x20c
github.com/go-gl/glfw/v3.3/glfw.CreateWindow(0x4b7, 0x664, 0xc0017441e0, 0x19, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/a.telyshev/xxx/vendor/github.com/go-gl/glfw/v3.3/glfw/window.go:350 +0x197
fyne.io/fyne/v2/internal/driver/glfw.(*window).create.func1()
        /Users/a.telyshev/xxx/vendor/fyne.io/fyne/v2/internal/driver/glfw/window.go:1327 +0x14b
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).runGL(0xc0003ae780)
        /Users/a.telyshev/xxx/vendor/fyne.io/fyne/v2/internal/driver/glfw/loop.go:97 +0x16c
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).Run(0xc0003ae780)
        /Users/a.telyshev/xxx/vendor/fyne.io/fyne/v2/internal/driver/glfw/driver.go:80 +0x3a
fyne.io/fyne/v2/internal/driver/glfw.(*window).ShowAndRun(0xc000986000)
        /Users/a.telyshev/xxx/vendor/fyne.io/fyne/v2/internal/driver/glfw/window.go:450 +0x3d
main.(*Casino).Run(0xc00067ba40)
        /Users/a.telyshev/xxx/cmd/casino-mini/casino.go:98 +0x45
main.main()
        /Users/a.telyshev/xxx/cmd/casino-mini/main.go:64 +0x25
```

```
$ go version
go1.16.5 darwin/amd64
```

```
$ uname -a
Darwin telyshev.local 19.6.0 Darwin Kernel Version 19.6.0: Thu May  6 00:48:39 PDT 2021; root:xnu-6153.141.33~1/RELEASE_X86_64 x86_64
```

**Comment by Jacalz** [comment]
I appreciate that you have added pretty much most of the information from it, but please use the issue templates when opening new issues. The templates are designed to help us save time and give us all the necessary information related to the issue. Thanks for understanding. There is no need to open a new issue for this, but I am saying it just to make sure that everyone gets the message :)

**Comment by Antonboom** [comment]
@Jacalz, I'm sorry

I ignored the template because I don't have most of the information for it ((

**Comment by Jacalz** [comment]
No worries. As I mentioned in the message above, I just wanted to inform for the next time you open an issue :)

**Comment by andydotxyz** [comment]
Please fill out information for the graphics hardware and driver loaded.
Also are you running this on a desktop computer or remote server?

**Comment by Antonboom** [comment]
- Desktop macOS Catalina 10.15.7 (19H1217) (**M1**), Graphics: Intel UHD Graphics 630 1536 MB
- Fyne version: `fyne.io/fyne/v2 v2.0.3`

**Comment by andydotxyz** [comment]
Hmm, are you running inside a virtual machine, container or under some other intermediate graphics driver? 
It seems similar to #2177

**Comment by andydotxyz** [comment]
As was highlighted in this newer issue the issue arises with virtual machines. Were you in a VM @Antonboom?

> * Graphics: Intel UHD Graphics 630 1536 MB

This is more than capable of running our needed OpenGL support, so my guess is that it was not being used - which leads to the virtualisation question above.

**Comment by Antonboom** [comment]
No, I don't use virtual machines :(

**Comment by Lewiscowles1986** [comment]
This specifically mentions inability to find suitable pixel format, and I think should be reported to go-gl/glfw repo.

`go-gl/glfw/v3.3`

I've done this as you can see above. On the glfw repo; also linking to other consumers hitting the same issues with go flutter.
