### ISSUE TITLE
Fyne application freeze when widget.NewSelectEntry() is combined with image saving

### ISSUE THREAD

**Issue by FredSoftwares** [fyne-io/fyne#2397]
Hi,

I have a strange bug in my application that fortunately I managed to reproduce with this toy program.

my code create a small toolbox window with a select entry and a button. 

The button save a picture displayed in a fyne window using the code :
```
c := w.Content().(*container.Scroll).Content
img := software.Render(c, theme.DarkTheme())
```

The button work perfectly if nothing is selected in the select entry list.
If an item is selected in the select entry list, the application freeze...

it seems that something in the `widget.NewSelectEntry()` code interfere with 
```
c := w.Content().(*container.Scroll).Content
img := software.Render(c, theme.DarkTheme())
```

I spent a lot of time trying for example to put the result of the select entry list in a binding.String variable, but nothing works.

Thanks for your comments !

To reproduce the bug

https://user-images.githubusercontent.com/26299514/130618588-4c1c02b3-6dc5-4d2b-b450-db8d69b963ac.mp4

, run this code in a folder with a "image.png" picture. Click on the "open tool box" button. Try to press the "screenshot" button, it will work until nothing is selected in the select entry list. 

```
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/driver/software"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"
	"image/color"
	"image/png"
	"log"
	"os"
)

// main create 2 windows :
// w = a window "Picture" display a picture
// w2 = a window with a button "Open Tool Box"
func main() {
	a := app.New()
	w := a.NewWindow("Picture")
	wContent := container.NewScroll(makePicture())
	w.SetContent(wContent)
	w.Resize(fyne.NewSize(120, 120))
	w.Show()

	// app window
	w2 := a.NewWindow("My App")
	but := widget.NewButton("Open Tool Box", func() {
		createToolBox(a, w)
	})
	w2.SetContent(but)
	w2.ShowAndRun()
	w.ShowAndRun()
}

// the button "Open Tool Box" create a new window whith the screenshot button
func createToolBox(a fyne.App, w fyne.Window) {
	w3 := a.NewWindow("Tool Box")
	list := []string{"A", "B", "C"}
	userChoice := widget.NewSelectEntry(list)
	but := widget.NewButton("screenshot", func() {
		go saveimage(w) // saveimage works only if nothing is selected in userChoice := widget.NewSelectEntry(list) !
	})

	content := container.NewVBox(
		userChoice,
		but,
	)
	w3.SetContent(content)
	w3.Show()
}

// save the scroll containt to file
func saveimage(w fyne.Window) {
	c := w.Content().(*container.Scroll).Content
	img := software.Render(c, theme.DarkTheme())
	path := "test.png"
	log.Println("Saving image to ", path)
	outputFile, err := os.Create(path)
	if err != nil {
		log.Println("The image cannot be saved to the file")
	}
	png.Encode(outputFile, img)

	outputFile.Close()
	log.Println("image saved !")
}

// makePicture return a container with a picture and a circle
func makePicture() fyne.CanvasObject {
	image := canvas.NewImageFromFile("image.png")
	image.FillMode = canvas.ImageFillOriginal // this line is responsible for the bug
	bg := canvas.NewCircle(color.NRGBA{255, 0, 0, 150})
	bg.StrokeColor = color.White
	bg.StrokeWidth = 5

	bg.Resize(fyne.NewSize(100, 100))
	bg.Move(fyne.NewPos(10, 10))
	c := container.NewMax(image, bg)

	return c
}

```

**Comment by andydotxyz** [comment]
Running the same scenario on develop branch gets a crash instead:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x44d7d97]

goroutine 40 [running]:
fyne.io/fyne/v2/internal/painter/software.drawPixels(0x0, 0x0, 0x20, 0x20, 0x0, 0xc0004ccf40, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/andy/Fyne/fyne/internal/painter/software/draw.go:84 +0x37
fyne.io/fyne/v2/internal/painter/software.drawImage(0x46c1890, 0xc0000c30e0, 0xc0001a2a80, 0x0, 0xc0004ccf40, 0x0, 0x0, 0x1, 0x1)
        /Users/andy/Fyne/fyne/internal/painter/software/draw.go:80 +0x227
fyne.io/fyne/v2/internal/painter/software.(*Painter).Paint.func1(0x46beed8, 0xc0001a2a80, 0x0, 0x0, 0x4f0000004f000000, 0x405a500)
        /Users/andy/Fyne/fyne/internal/painter/software/painter.go:39 +0x29e
fyne.io/fyne/v2/internal/driver.walkObjectTree(0x46beed8, 0xc0001a2a80, 0x0, 0x46bee18, 0xc0003d6000, 0x0, 0x0, 0x4f0000004f000000, 0xc0000a9df0, 0x0, ...)
        /Users/andy/Fyne/fyne/internal/driver/util.go:169 +0x482
fyne.io/fyne/v2/internal/driver.walkObjectTree.func1(...)
        /Users/andy/Fyne/fyne/internal/driver/util.go:176
fyne.io/fyne/v2/internal/driver.walkObjectTree(0x46bee18, 0xc0003d6000, 0x458f200, 0x0, 0x0, 0x0, 0x0, 0x4f0000004f000000, 0xc0000a9df0, 0x0, ...)
        /Users/andy/Fyne/fyne/internal/driver/util.go:190 +0x3ff
fyne.io/fyne/v2/internal/driver.WalkVisibleObjectTree(0x46bee18, 0xc0003d6000, 0xc00049e5f0, 0x0, 0xc0004ccf40)
        /Users/andy/Fyne/fyne/internal/driver/util.go:134 +0x94
fyne.io/fyne/v2/internal/painter/software.(*Painter).Paint(0x4c6e9c8, 0x46c1890, 0xc0000c30e0, 0x0, 0x1)
        /Users/andy/Fyne/fyne/internal/painter/software/painter.go:57 +0x17d
fyne.io/fyne/v2/test.(*testCanvas).Capture(0xc0000c30e0, 0xc0003d6000, 0x46c1890)
        /Users/andy/Fyne/fyne/test/testcanvas.go:83 +0x26f
fyne.io/fyne/v2/driver/software.Render(0x46bee18, 0xc0003d6000, 0x46bbe70, 0xc0000befc0, 0xc00049e768, 0x406cd8b)
        /Users/andy/Fyne/fyne/driver/software/render.go:29 +0x1ca
main.saveimage(0x46c1d80, 0xc00033e1e0)
        /Users/andy/Fyne/fyne/cmd/hello/main.go:58 +0xcc
created by main.createToolBox.func1
        /Users/andy/Fyne/fyne/cmd/hello/main.go:44 +0x47
exit status 2
```
