### ISSUE TITLE
Data race in texture cache

### ISSUE THREAD

**Issue by changkun** [fyne-io/fyne#2414]
### Describe the bug:

Install the `fyne_demo` on iOS, click a menu item, then tap the close button, continue to click another menu item. Loop this process, and the app will crash with a `concurrent map iteration and map write` runtime panic.

### To Reproduce:

1. Run fyne_demo on iOS
2. Tap around, click the close button several times
3. If lucky, crash as follows

### Screenshots:

```go
fatal error: concurrent map iteration and map write

goroutine 26 [running]:
runtime.throw({0x1051808ab, 0x105110418})
	/Users/changkun/dev/godev/go-gerrit/src/runtime/panic.go:965 +0x50 fp=0x13005ad70 sp=0x13005ad40 pc=0x104e4a370
runtime.mapiternext(0x13005ae18)
	/Users/changkun/dev/godev/go-gerrit/src/runtime/map.go:859 +0x534 fp=0x13005ade0 sp=0x13005ad70 pc=0x104e278b4
fyne.io/fyne/v2/internal/cache.RangeTexturesFor({0x1053280b0, 0x130548840}, 0x13005aee8)
	/Users/changkun/dev/changkun.de/fyne/internal/cache/texture_common.go:45 +0x6c fp=0x13005ae80 sp=0x13005ade0 pc=0x10501a95c
fyne.io/fyne/v2/internal/driver/gomobile.(*window).Close(0x1305467e0)
	/Users/changkun/dev/changkun.de/fyne/internal/driver/gomobile/window.go:160 +0x19c fp=0x13005af00 sp=0x13005ae80 pc=0x10511019c
fyne.io/fyne/v2/internal/driver/gomobile.(*window).tryClose(0x13026c880)
	/Users/changkun/dev/changkun.de/fyne/internal/driver/gomobile/window.go:145 +0x38 fp=0x13005af20 sp=0x13005af00 pc=0x10510ff78
fyne.io/fyne/v2/internal/driver/gomobile.(*window).Show.func1()
	/Users/changkun/dev/changkun.de/fyne/internal/driver/gomobile/window.go:113 +0x24 fp=0x13005af40 sp=0x13005af20 pc=0x10510fec4
fyne.io/fyne/v2/widget.(*Button).Tapped(0x130596000, 0x0)
	/Users/changkun/dev/changkun.de/fyne/widget/button.go:192 +0x50 fp=0x13005af60 sp=0x13005af40 pc=0x1050bab20
fyne.io/fyne/v2/internal/driver/gomobile.(*mobileDriver).tapUpCanvas.func1.1()
	/Users/changkun/dev/changkun.de/fyne/internal/driver/gomobile/driver.go:355 +0x30 fp=0x13005af80 sp=0x13005af60 pc=0x10510ce50
fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue(0x1305467e0)
	/Users/changkun/dev/changkun.de/fyne/internal/driver/common/window.go:58 +0x50 fp=0x13005afb0 sp=0x13005af80 pc=0x1050afae0
fyne.io/fyne/v2/internal/driver/gomobile.(*mobileDriver).CreateWindow.func1()
	/Users/changkun/dev/changkun.de/fyne/internal/driver/gomobile/driver.go:73 +0x2c fp=0x13005afd0 sp=0x13005afb0 pc=0x10510b10c
runtime.goexit()
	/Users/changkun/dev/godev/go-gerrit/src/runtime/asm_arm64.s:1259 +0x4 fp=0x13005afd0 sp=0x13005afd0 pc=0x104e787c4
created by fyne.io/fyne/v2/internal/driver/gomobile.(*mobileDriver).CreateWindow
	/Users/changkun/dev/changkun.de/fyne/internal/driver/gomobile/driver.go:73 +0x138

goroutine 1 [runnable, locked to thread]:
github.com/fyne-io/mobile/gl._Cfunc_process(0x1300ee708, 0x0, 0x0, 0x0, 0x3)
	_cgo_gotypes.go:109 +0x3c
github.com/fyne-io/mobile/gl.(*context).DoWork(0x1300ee6e0)
	/Users/changkun/go/pkg/mod/github.com/fyne-io/mobile@v0.1.3-0.20210811181917-d62fb16c28ec/gl/work.go:147 +0x1c8
github.com/fyne-io/mobile/app.drawloop()
	/Users/changkun/go/pkg/mod/github.com/fyne-io/mobile@v0.1.3-0.20210811181917-d62fb16c28ec/app/darwin_ios.go:219 +0x80
github.com/fyne-io/mobile/app._Cfunc_runApp()
	_cgo_gotypes.go:201 +0x38
github.com/fyne-io/mobile/app.main(0x1300211c0)
	/Users/changkun/go/pkg/mod/github.com/fyne-io/mobile@v0.1.3-0.20210811181917-d62fb16c28ec/app/darwin_ios.go:75 +0x58
github.com/fyne-io/mobile/app.Main(...)
	/Users/changkun/go/pkg/mod/github.com/fyne-io/mobile@v0.1.3-0.20210811181917-d62fb16c28ec/app/app.go:21
fyne.io/fyne/v2/internal/driver/gomobile.(*mobileDriver).Run(0x13009d6c0)
	/Users/changkun/dev/changkun.de/fyne/internal/driver/gomobile/driver.go:138 +0x64
fyne.io/fyne/v2/internal/driver/gomobile.(*window).ShowAndRun(0x13006e1c0)
	/Users/changkun/dev/changkun.de/fyne/internal/driver/gomobile/window.go:187 +0x3c
main.main()
	/Users/changkun/dev/changkun.de/fyne/cmd/fyne_demo/main.go:66 +0x440

goroutine 19 [select]:
github.com/fyne-io/mobile/app.pump.func1()
	/Users/changkun/go/pkg/mod/github.com/fyne-io/mobile@v0.1.3-0.20210811181917-d62fb16c28ec/app/app.go:189 +0x120
created by github.com/fyne-io/mobile/app.pump
	/Users/changkun/go/pkg/mod/github.com/fyne-io/mobile@v0.1.3-0.20210811181917-d62fb16c28ec/app/app.go:172 +0xc0

goroutine 20 [chan receive]:
fyne.io/fyne/v2/test.NewApp.func1()
	/Users/changkun/dev/changkun.de/fyne/test/testapp.go:113 +0x44
created by fyne.io/fyne/v2/test.NewApp
	/Users/changkun/dev/changkun.de/fyne/test/testapp.go:111 +0x310

goroutine 6 [chan receive]:
fyne.io/fyne/v2/internal/driver/common.newUnboundedChan.func1()
	/Users/changkun/dev/changkun.de/fyne/internal/driver/common/canvas.go:538 +0x88
created by fyne.io/fyne/v2/internal/driver/common.newUnboundedChan
	/Users/changkun/dev/changkun.de/fyne/internal/driver/common/canvas.go:535 +0xd8

goroutine 7 [chan receive]:
fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue(0x13007a1b0)
	/Users/changkun/dev/changkun.de/fyne/internal/driver/common/window.go:57 +0x70
created by fyne.io/fyne/v2/internal/driver/gomobile.(*mobileDriver).CreateWindow
	/Users/changkun/dev/changkun.de/fyne/internal/driver/gomobile/driver.go:73 +0x138

goroutine 10 [runnable]:
github.com/fyne-io/mobile/gl.(*context).enqueue(0x1300ee6e0, {{0x23, 0x7a, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...})
	/Users/changkun/go/pkg/mod/github.com/fyne-io/mobile@v0.1.3-0.20210811181917-d62fb16c28ec/gl/work.go:106 +0x80
github.com/fyne-io/mobile/gl.(*context).DeleteTexture(0x1053219c8, {0x3058ee40})
	/Users/changkun/go/pkg/mod/github.com/fyne-io/mobile@v0.1.3-0.20210811181917-d62fb16c28ec/gl/gl.go:456 +0x78
fyne.io/fyne/v2/internal/painter/gl.(*glPainter).freeTexture(0x13006e140, {0x1053219c8, 0x13058ee40})
	/Users/changkun/dev/changkun.de/fyne/internal/painter/gl/gl_gomobile.go:107 +0x7c
fyne.io/fyne/v2/internal/painter/gl.(*glPainter).Free(0x1052967a0, {0x1053219c8, 0x13058ee40})
	/Users/changkun/dev/changkun.de/fyne/internal/painter/gl/painter.go:74 +0x28
fyne.io/fyne/v2/internal/driver/common.(*Canvas).FreeDirtyTextures.func1({0x1053219c8, 0x13058ee40}, {0x3058ee40, 0x1}, {0x5322ec8, 0x1}, {0x30592090, 0x1})
	/Users/changkun/dev/changkun.de/fyne/internal/driver/common/canvas.go:202 +0x44
fyne.io/fyne/v2/internal/driver.walkObjectTree({0x1053219c8, 0x13058ee40}, 0x0, {0x0, 0x0}, {0x3, 0x0}, {0x301a1d98, 0x1}, {0x50ade48, ...}, ...)
	/Users/changkun/dev/changkun.de/fyne/internal/driver/util.go:169 +0x1f8
fyne.io/fyne/v2/internal/driver.WalkCompleteObjectTree({0x1053219c8, 0x13058ee40}, 0xffffffffffffffff, 0x0)
	/Users/changkun/dev/changkun.de/fyne/internal/driver/util.go:116 +0x60
fyne.io/fyne/v2/internal/driver/common.(*Canvas).FreeDirtyTextures(0x13007e000)
	/Users/changkun/dev/changkun.de/fyne/internal/driver/common/canvas.go:205 +0x54
fyne.io/fyne/v2/internal/driver/gomobile.(*mobileDriver).handlePaint(0x13009d6c0, {0x80}, {0x1053289c0, 0x13007a1b0})
	/Users/changkun/dev/changkun.de/fyne/internal/driver/gomobile/driver.go:253 +0x90
fyne.io/fyne/v2/internal/driver/gomobile.(*mobileDriver).Run.func1({0x1053236a8, 0x1058bac40})
	/Users/changkun/dev/changkun.de/fyne/internal/driver/gomobile/driver.go:188 +0x2b4
github.com/fyne-io/mobile/app.main.func1()
	/Users/changkun/go/pkg/mod/github.com/fyne-io/mobile@v0.1.3-0.20210811181917-d62fb16c28ec/app/darwin_ios.go:72 +0x3c
created by github.com/fyne-io/mobile/app.main
	/Users/changkun/go/pkg/mod/github.com/fyne-io/mobile@v0.1.3-0.20210811181917-d62fb16c28ec/app/darwin_ios.go:71 +0x54

goroutine 25 [chan receive]:
fyne.io/fyne/v2/internal/driver/common.newUnboundedChan.func1()
	/Users/changkun/dev/changkun.de/fyne/internal/driver/common/canvas.go:538 +0x88
created by fyne.io/fyne/v2/internal/driver/common.newUnboundedChan
	/Users/changkun/dev/changkun.de/fyne/internal/driver/common/canvas.go:535 +0xd8

goroutine 27 [sleep]:
time.Sleep(0x3b9aca00)
	/Users/changkun/dev/godev/go-gerrit/src/runtime/time.go:194 +0x11c
fyne.io/fyne/v2/cmd/fyne_demo/tutorials.setScaleText(0x1300c3220, 0x1300c3540, {0x1053289c0, 0x1305467e0})
	/Users/changkun/dev/changkun.de/fyne/cmd/fyne_demo/tutorials/advanced.go:33 +0x3c
created by fyne.io/fyne/v2/cmd/fyne_demo/tutorials.advancedScreen
	/Users/changkun/dev/changkun.de/fyne/cmd/fyne_demo/tutorials/advanced.go:48 +0x288

goroutine 52 [chan receive]:
fyne.io/fyne/v2/internal/animation.(*Runner).runAnimations.func1()
	/Users/changkun/dev/changkun.de/fyne/internal/animation/runner.go:69 +0x40
created by fyne.io/fyne/v2/internal/animation.(*Runner).runAnimations
	/Users/changkun/dev/changkun.de/fyne/internal/animation/runner.go:67 +0x88
```

### Example code:

see #2406

### Device (please complete the following information):
 - **OS:** iOS
 - **Version:** iOS 15 beta 7
 - **Go version:** 1.18
 - **Fyne version:** 0bbf592f8f95b4baf9121a0c5813f8017cdc2189

**Comment by changkun** [comment]
Close as the corresponding PR is merged.
