### ISSUE TITLE
table widget occasionally panics

### ISSUE THREAD

**Issue by cmitsakis** [fyne-io/fyne#2422]
### Describe the bug:
I noticed the table widget occasionally panics.

fyne 2.0.4
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x61540d]

goroutine 12 [running, locked to thread]:
fyne.io/fyne/v2/widget.(*tableRenderer).moveIndicators(0xc0003240e0)
	fyne.io/fyne/v2@v2.0.4/widget/table.go:316 +0x18d
fyne.io/fyne/v2/widget.(*tableRenderer).Layout(0xc0003240e0, {0x3180a0, 0xc0})
	fyne.io/fyne/v2@v2.0.4/widget/table.go:240 +0x2e
fyne.io/fyne/v2/internal/driver/glfw.updateLayout({0x75d520, 0xc0003180a0})
	fyne.io/fyne/v2@v2.0.4/internal/driver/glfw/canvas.go:657 +0xc3
fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).ensureMinSize.func1(0xc0003bb800)
	fyne.io/fyne/v2@v2.0.4/internal/driver/glfw/canvas.go:353 +0x25a
fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).walkTree.func2({0x75cfe0, 0xc0003044e0}, {0xc0003044e0, 0xc000304180})
	fyne.io/fyne/v2@v2.0.4/internal/driver/glfw/canvas.go:550 +0xae
fyne.io/fyne/v2/internal/driver.walkObjectTree({0x75cfe0, 0xc0003044e0}, 0x0, {0x75d4c0, 0xc0003200c0}, {0x63db10, 0xc0}, {0x4308a5, 0x0}, {0x6b7a40, ...}, ...)
	fyne.io/fyne/v2@v2.0.4/internal/driver/util.go:197 +0x370
fyne.io/fyne/v2/internal/driver.walkObjectTree.func1(...)
	fyne.io/fyne/v2@v2.0.4/internal/driver/util.go:176
fyne.io/fyne/v2/internal/driver.walkObjectTree({0x75d4c0, 0xc0003200c0}, 0x0, {0x75d520, 0xc0003180a0}, {0x320480, 0xc0}, {0x63dd20, 0xc0}, {0x63dcf8, ...}, ...)
	fyne.io/fyne/v2@v2.0.4/internal/driver/util.go:190 +0x41d
fyne.io/fyne/v2/internal/driver.walkObjectTree.func1(...)
	fyne.io/fyne/v2@v2.0.4/internal/driver/util.go:176
fyne.io/fyne/v2/internal/driver.walkObjectTree({0x75d520, 0xc0003180a0}, 0x0, {0x0, 0x0}, {0x15275040, 0x31aa}, {0x63dc98, 0xc0}, {0x628466, ...}, ...)
	fyne.io/fyne/v2@v2.0.4/internal/driver/util.go:190 +0x41d
fyne.io/fyne/v2/internal/driver.WalkVisibleObjectTree({0x75d520, 0xc0003180a0}, 0x300000002, 0xc00031c000)
	fyne.io/fyne/v2@v2.0.4/internal/driver/util.go:134 +0x4c
fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).walkTree(0xc000105860, 0xc00031a040, 0x0, 0xc00063de08)
	fyne.io/fyne/v2@v2.0.4/internal/driver/glfw/canvas.go:556 +0x173
fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).walkTrees(0xc0002fc000, 0xc00063de50, 0x61fbad)
	fyne.io/fyne/v2@v2.0.4/internal/driver/glfw/canvas.go:563 +0x3c
fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).ensureMinSize(0xc0002fc000)
	fyne.io/fyne/v2@v2.0.4/internal/driver/glfw/canvas.go:358 +0x7b
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow.func1()
	fyne.io/fyne/v2@v2.0.4/internal/driver/glfw/loop.go:156 +0x33
fyne.io/fyne/v2/internal/driver/glfw.(*window).RunWithContext(0x100c00006a3c0, 0xc00063deb0)
	fyne.io/fyne/v2@v2.0.4/internal/driver/glfw/window.go:1207 +0x43
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow(0xc00063df90, 0xc00063df20)
	fyne.io/fyne/v2@v2.0.4/internal/driver/glfw/loop.go:155 +0x4a
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread.func1()
	fyne.io/fyne/v2@v2.0.4/internal/driver/glfw/loop.go:211 +0x2f7
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread
	fyne.io/fyne/v2@v2.0.4/internal/driver/glfw/loop.go:182 +0xcf
```

fyne develop 08dae6d
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6db08d]

goroutine 34 [running, locked to thread]:
fyne.io/fyne/v2/widget.(*tableRenderer).moveIndicators(0xc00013c070)
	fyne.io/fyne/v2@v2.0.5-0.20210831124636-08dae6d2454e/widget/table.go:425 +0x18d
fyne.io/fyne/v2/widget.(*tableRenderer).Layout(0xc00013c070, {0x3fcbe0, 0xc0})
	fyne.io/fyne/v2@v2.0.5-0.20210831124636-08dae6d2454e/widget/table.go:349 +0x2e
fyne.io/fyne/v2/internal/driver/common.updateLayout({0x87c3a0, 0xc0003fcbe0})
	fyne.io/fyne/v2@v2.0.5-0.20210831124636-08dae6d2454e/internal/driver/common/canvas.go:515 +0xc3
fyne.io/fyne/v2/internal/driver/common.(*Canvas).EnsureMinSize.func1(0xc0003f3040)
	fyne.io/fyne/v2@v2.0.5-0.20210831124636-08dae6d2454e/internal/driver/common/canvas.go:97 +0x225
fyne.io/fyne/v2/internal/driver/common.(*Canvas).walkTree.func2({0x87bd40, 0xc000060300}, {0xc000060300, 0xfeb7986c6})
	fyne.io/fyne/v2@v2.0.5-0.20210831124636-08dae6d2454e/internal/driver/common/canvas.go:433 +0xae
fyne.io/fyne/v2/internal/driver.walkObjectTree({0x87bd40, 0xc000060300}, 0x0, {0x87c340, 0xc0001384c0}, {0xd492e0, 0x0}, {0x74fb58, 0xc0}, {0x57a4ca, ...}, ...)
	fyne.io/fyne/v2@v2.0.5-0.20210831124636-08dae6d2454e/internal/driver/util.go:197 +0x370
fyne.io/fyne/v2/internal/driver.walkObjectTree.func1(...)
	fyne.io/fyne/v2@v2.0.5-0.20210831124636-08dae6d2454e/internal/driver/util.go:176
fyne.io/fyne/v2/internal/driver.walkObjectTree({0x87c340, 0xc0001384c0}, 0x0, {0x87c3a0, 0xc0003fcbe0}, {0x0, 0x0}, {0x622eb9, 0x0}, {0x429409, ...}, ...)
	fyne.io/fyne/v2@v2.0.5-0.20210831124636-08dae6d2454e/internal/driver/util.go:190 +0x41d
fyne.io/fyne/v2/internal/driver.walkObjectTree.func1(...)
	fyne.io/fyne/v2@v2.0.5-0.20210831124636-08dae6d2454e/internal/driver/util.go:176
fyne.io/fyne/v2/internal/driver.walkObjectTree({0x87c3a0, 0xc0003fcbe0}, 0x0, {0x0, 0x0}, {0x74fc70, 0xc0}, {0x74fc78, 0xc0}, {0x718726, ...}, ...)
	fyne.io/fyne/v2@v2.0.5-0.20210831124636-08dae6d2454e/internal/driver/util.go:190 +0x41d
fyne.io/fyne/v2/internal/driver.WalkVisibleObjectTree({0x87c3a0, 0xc0003fcbe0}, 0x878880, 0xc0000b0d20)
	fyne.io/fyne/v2@v2.0.5-0.20210831124636-08dae6d2454e/internal/driver/util.go:134 +0x4c
fyne.io/fyne/v2/internal/driver/common.(*Canvas).walkTree(0x6ea0c4, 0xc0000c6be0, 0x0, 0xc00074fdf0)
	fyne.io/fyne/v2@v2.0.5-0.20210831124636-08dae6d2454e/internal/driver/common/canvas.go:439 +0x173
fyne.io/fyne/v2/internal/driver/common.(*Canvas).WalkTrees(0xc0000cdc20, 0x42a0d1, 0x0)
	fyne.io/fyne/v2@v2.0.5-0.20210831124636-08dae6d2454e/internal/driver/common/canvas.go:351 +0x3c
fyne.io/fyne/v2/internal/driver/common.(*Canvas).EnsureMinSize(0xc0000cdc20)
	fyne.io/fyne/v2@v2.0.5-0.20210831124636-08dae6d2454e/internal/driver/common/canvas.go:102 +0xfa
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow.func1()
	fyne.io/fyne/v2@v2.0.5-0.20210831124636-08dae6d2454e/internal/driver/glfw/loop.go:163 +0x35
fyne.io/fyne/v2/internal/driver/glfw.(*window).RunWithContext(0xc000112000, 0xc00074fea0)
	fyne.io/fyne/v2@v2.0.5-0.20210831124636-08dae6d2454e/internal/driver/glfw/window.go:1317 +0x4f
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow(0xc00074ff90, 0xc00074ff18)
	fyne.io/fyne/v2@v2.0.5-0.20210831124636-08dae6d2454e/internal/driver/glfw/loop.go:162 +0x4a
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread.func1()
	fyne.io/fyne/v2@v2.0.5-0.20210831124636-08dae6d2454e/internal/driver/glfw/loop.go:225 +0x33a
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread
	fyne.io/fyne/v2@v2.0.5-0.20210831124636-08dae6d2454e/internal/driver/glfw/loop.go:189 +0xcf
```

Rarely I also get this panic
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x61540d]

goroutine 20 [running]:
fyne.io/fyne/v2/widget.(*tableRenderer).moveIndicators(0xc0000cc0e0)
	fyne.io/fyne/v2@v2.0.4/widget/table.go:316 +0x18d
fyne.io/fyne/v2/widget.(*tableRenderer).Refresh(0xc0000cc0e0)
	fyne.io/fyne/v2@v2.0.4/widget/table.go:252 +0x8d
fyne.io/fyne/v2/widget.(*BaseWidget).Refresh(0xc0000c00a0)
	fyne.io/fyne/v2@v2.0.4/widget/widget.go:139 +0x2e
main.createTable.func4()
	private/tablePanic2/main.go:55 +0x271
created by main.createTable
	private/tablePanic2/main.go:33 +0x27b
```

### To Reproduce:
Run the code in the next section.

I managed to reproduce it by making a table and a goroutine that modifies the data and refreshes the table while a script clicks at random locations.

Every 1/20 of a second the goroutine changes the data of the table between `dataVariations[0]` and `dataVariations[1]`. `dataVariations[0]` has length of 1 so the table has 1 row, and `dataVariations[1]` has length of 10. It's important that the length changes. It's also important that the cells have *short* strings (4 characters).

I noticed the it doesn't panic if:

- the number of rows doesn't change (`len(dataVariations[0]) == len(dataVariations[1])`)
- cells have longer strings (`r0c0 11111` instead of `r0c0`)

### Example code:
```go
package main

import (
	"fmt"
	"os"
	"time"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("table")
	w.SetContent(createTable())
	w.Resize(fyne.NewSize(1280, 720))
	//w.SetFullScreen(true)
	w.ShowAndRun()
}

func createTable() *widget.Table {
	data0 := [][]string{{"c1", "c2", "c3", "c4", "c5", "c6", "c7", "c8", "c9", "c10"}}
	t := widget.NewTable(
		func() (int, int) {
			return len(data0), len(data0[0])
		},
		func() fyne.CanvasObject {
			return widget.NewLabel("asdfghjkl")
		},
		func(cellID widget.TableCellID, obj fyne.CanvasObject) {
			obj.(*widget.Label).SetText(data0[cellID.Row][cellID.Col])
		})
	go func() {
		const iterations = 10000
		dataVariations := make([][][]string, 2)
		dataVariations[0] = make([][]string, 10)
		dataVariations[1] = make([][]string, 10)
		for r:=0; r<10; r++ {
			rowDataA := make([]string, 10)
			rowDataB := make([]string, 10)
			for c:=0; c<10; c++ {
				rowDataA[c] = fmt.Sprintf("r%dc%d", r, c)
				// if you enable the following line, and line 54, it doesn't panic
				//rowDataA[c] = fmt.Sprintf("r%dc%d 11111", r, c)
				rowDataB[c] = ""
			}
			dataVariations[0][r] = rowDataA
			dataVariations[1][r] = rowDataB
		}
		// if you remove the following line, it doesn't panic
		dataVariations[1] = [][]string{{"r0c0", "r0c1", "r0c2", "r0c3", "r0c4", "r0c5", "r0c6", "r0c7", "r0c8", "r0c9"}}
		// if you enable the following line, and line 45, it doesn't panic
		//dataVariations[1] = [][]string{{"r0c0 11111", "r0c1 11111", "r0c2 11111", "r0c3 11111", "r0c4 11111", "r0c5 11111", "r0c6 11111", "r0c7 11111", "r0c8 11111", "r0c9 11111"}}
		for i:=0; i<iterations; i++ {
			time.Sleep(time.Second/20)
			func(data [][]string) {
				t.Length = func() (int, int) {
					return len(data), len(data[0])
				}
				t.UpdateCell = func(cellID widget.TableCellID, obj fyne.CanvasObject) {
					obj.(*widget.Label).SetText(data[cellID.Row][cellID.Col])
				}
			}(dataVariations[i%2])
			t.Refresh()
		}
		os.Exit(1)
	}()
	return t
}
```

The following script clicks at random coordinates at the top left part of the screen.
This can be dangerous so make sure there is nothing else there.
Make sure the window is maximized or placed at the top left corner.
It works on linux only and requires `xdotool`.
```sh
#!/bin/bash
./executable & # replace this with the name of the executable
process_id=$!
while [ -e /proc/$process_id ]; do
  x=$(( RANDOM % 700 + 70 )) # random value from 70 to 700
  y=$(( RANDOM % 400 + 70 )) # random value from 70 to 400
  xdotool mousemove $x $y click 1 &
  sleep 0.05
done
```

### Device (please complete the following information):
 - **OS:** Linux
 - **Version:** 5.13.10
 - **Go version:** 1.17
 - **Fyne version:** 2.0.4 and 08dae6d

**Comment by andydotxyz** [comment]
Changes to the table code 2 days after this was reported may have resolved this.
I cannot replicate it any more. Can you test on latest develop @cmitsakis ?

**Comment by cmitsakis** [comment]
This panic has been resolved on latest develop. Thanks.

Now I get a different panic. Although much less frequently. It panics 50% of the time, so you have to run the script a couple of times.

```
panic: runtime error: index out of range [1] with length 1

goroutine 6 [running]:
main.createTable.func4.1.2({0xc0013b3a40, 0xc00104e7b0}, {0x87c240, 0xc0013b3a40})
	tablePanic/main.go:62 +0x11c
fyne.io/fyne/v2/widget.(*tableCellsRenderer).Refresh(0xc00005e780)
	fyne.io/fyne/v2@v2.0.5-0.20210911121929-b8bab111114f/widget/table.go:661 +0x691
fyne.io/fyne/v2/widget.(*BaseWidget).Refresh(0xc00065e000)
	fyne.io/fyne/v2@v2.0.5-0.20210911121929-b8bab111114f/widget/widget.go:138 +0x2e
fyne.io/fyne/v2/widget.(*Table).finishScroll(0xc0003eee60)
	fyne.io/fyne/v2@v2.0.5-0.20210911121929-b8bab111114f/widget/table.go:280 +0x4e
fyne.io/fyne/v2/widget.(*Table).ScrollTo(0xc0003eee60, {0x6, 0x7cdcda})
	fyne.io/fyne/v2@v2.0.5-0.20210911121929-b8bab111114f/widget/table.go:189 +0x1d0
fyne.io/fyne/v2/widget.(*Table).Select(0xc0003eee60, {0x8, 0x6})
	fyne.io/fyne/v2@v2.0.5-0.20210911121929-b8bab111114f/widget/table.go:92 +0xbd
fyne.io/fyne/v2/widget.(*tableCells).Tapped(0xc00006c050, 0xc000e00560)
	fyne.io/fyne/v2@v2.0.5-0.20210911121929-b8bab111114f/widget/table.go:518 +0x105
fyne.io/fyne/v2/internal/driver/glfw.(*window).mouseClickedHandleTapDoubleTap.func1()
	fyne.io/fyne/v2@v2.0.5-0.20210911121929-b8bab111114f/internal/driver/glfw/window.go:885 +0x26
fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue(0xc000070000)
	fyne.io/fyne/v2@v2.0.5-0.20210911121929-b8bab111114f/internal/driver/common/window.go:58 +0x56
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1
	fyne.io/fyne/v2@v2.0.5-0.20210911121929-b8bab111114f/internal/driver/glfw/window.go:1388 +0x15b
```

It is caused by the `UpdateCell` function at line 62 in my code:
```go
t.UpdateCell = func(cellID widget.TableCellID, obj fyne.CanvasObject) {
	obj.(*widget.Label).SetText(data[cellID.Row][cellID.Col])
}
```

Although `data` has length 1, `updateCell` is called with `cellID.Row = 1`.

Maybe it's a race condition when a click happens between updates to `t.Length`, `t.UpdateCell`, and `t.Refresh()`?

**Comment by andydotxyz** [comment]
I can't seem to replicate the latest problem on my Linux install sorry.
It may not be possible to guard against the race you describe however as GUI events are inherently async, so if your data has shrunk during the tap callback processing this could happen.
In the future we could investigate whether user events could be processed on the same background as the graphical processing - but that could lead to UI freezes, so I don't think it's desirable.
I reckon all that makes sense is to add bounds checks if you know the data could shrink at runtime.

**Comment by cmitsakis** [comment]
Ok I understand. This panic rarely happens and there is a workaround, so I consider the issue resolved. Thank you.
