### ISSUE TITLE
Crash when resizing window on M1 Macbook w/ GOARCH=arm64

### ISSUE THREAD

**Issue by meagar** [fyne-io/fyne#2430]
### Describe the bug:

All of the code samples from [the tour](https://developer.fyne.io/tour/introduction/) crash after a second or so of window resizing, when building with `GOARCH=arm64`. Unsetting `GOARCH` resolves the issue for some examples, but not all.

### To Reproduce:
Steps to reproduce the behaviour:

1. Use any of the trivial samples from the tour
2. Run the example (ie `go run main.go`)
3. Resize the window until it crashes, typically several seconds

Note there are deprecation warnings on startup, I'm not sure if they're related.

### Screenshots:

https://www.youtube.com/watch?v=yfnjc1CLrLo

### Example code:

```
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	app := app.New()

	w := app.NewWindow("Hello")
	w.SetContent(widget.NewLabel("Hello Fyne!"))

	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:** MacOS
 - **Version:** 11.5.2 (20G95)
 - **Go version:** go1.17 darwin/amd64
 - **Fyne version:** v2.0.4

### Crash output:

```
~/fyne-test (master) $ go run ./main.go
# fyne.io/fyne/v2/app
app_darwin.m:10:33: warning: 'NSUserNotificationCenter' is deprecated: first deprecated in macOS 11.0 - All NSUserNotifications API should be replaced with UserNotifications.frameworks API [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h:118:12: note: 'NSUserNotificationCenter' has been explicitly marked deprecated here
app_darwin.m:11:32: warning: 'NSUserNotification' is deprecated: first deprecated in macOS 11.0 - All NSUserNotifications API should be replaced with UserNotifications.frameworks API [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h:24:12: note: 'NSUserNotification' has been explicitly marked deprecated here
app_darwin.m:17:33: warning: 'NSUserNotificationCenter' is deprecated: first deprecated in macOS 11.0 - All NSUserNotifications API should be replaced with UserNotifications.frameworks API [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h:118:12: note: 'NSUserNotificationCenter' has been explicitly marked deprecated here
app_darwin.m:18:32: warning: 'NSUserNotification' is deprecated: first deprecated in macOS 11.0 - All NSUserNotifications API should be replaced with UserNotifications.frameworks API [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h:24:12: note: 'NSUserNotification' has been explicitly marked deprecated here
app_darwin.m:37:5: warning: 'NSUserNotificationCenter' is deprecated: first deprecated in macOS 11.0 - All NSUserNotifications API should be replaced with UserNotifications.frameworks API [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h:118:12: note: 'NSUserNotificationCenter' has been explicitly marked deprecated here
app_darwin.m:37:66: warning: 'NSUserNotificationCenter' is deprecated: first deprecated in macOS 11.0 - All NSUserNotifications API should be replaced with UserNotifications.frameworks API [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h:118:12: note: 'NSUserNotificationCenter' has been explicitly marked deprecated here
app_darwin.m:43:5: warning: 'NSUserNotification' is deprecated: first deprecated in macOS 11.0 - All NSUserNotifications API should be replaced with UserNotifications.frameworks API [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h:24:12: note: 'NSUserNotification' has been explicitly marked deprecated here
app_darwin.m:43:61: warning: 'NSUserNotification' is deprecated: first deprecated in macOS 11.0 - All NSUserNotifications API should be replaced with UserNotifications.frameworks API [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h:24:12: note: 'NSUserNotification' has been explicitly marked deprecated here
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x2 addr=0x11123e90 pc=0x1900db240]

runtime stack:
runtime.throw({0x100e64e01, 0x2a})
	/usr/local/go/src/runtime/panic.go:1198 +0x54
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:719 +0x230

goroutine 25 [syscall, locked to thread]:
runtime.cgocall(0x100e40910, 0x14000129d38)
	/usr/local/go/src/runtime/cgocall.go:156 +0x50 fp=0x14000129d00 sp=0x14000129cc0 pc=0x100c0d890
github.com/go-gl/gl/v3.2-core/gl._Cfunc_glowClear(0x1d24fe5f4, 0x4100)
	_cgo_gotypes.go:3663 +0x40 fp=0x14000129d30 sp=0x14000129d00 pc=0x100dcc630
github.com/go-gl/gl/v3.2-core/gl.Clear(...)
	/Users/matthew.eager/.go/pkg/mod/github.com/go-gl/gl@v0.0.0-20190320180904-bf2b1f2f34d7/v3.2-core/gl/package.go:8667
fyne.io/fyne/v2/internal/painter/gl.(*glPainter).glClearBuffer(0x14000070000)
	/Users/matthew.eager/.go/pkg/mod/fyne.io/fyne/v2@v2.0.4/internal/painter/gl/gl_core.go:188 +0xd8 fp=0x14000129d60 sp=0x14000129d30 pc=0x100df0788
fyne.io/fyne/v2/internal/painter/gl.(*glPainter).Clear(0x14000070000)
	/Users/matthew.eager/.go/pkg/mod/fyne.io/fyne/v2@v2.0.4/internal/painter/gl/painter.go:53 +0x28 fp=0x14000129d80 sp=0x14000129d60 pc=0x100df0ec8
fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).paint(0x14000346000, {0x432e0000, 0x437a0000})
	/Users/matthew.eager/.go/pkg/mod/fyne.io/fyne/v2@v2.0.4/internal/driver/glfw/canvas.go:431 +0x68 fp=0x14000129e00 sp=0x14000129d80 pc=0x100e04128
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow.func1()
	/Users/matthew.eager/.go/pkg/mod/fyne.io/fyne/v2@v2.0.4/internal/driver/glfw/loop.go:164 +0x9c fp=0x14000129e60 sp=0x14000129e00 pc=0x100e067cc
fyne.io/fyne/v2/internal/driver/glfw.(*window).RunWithContext(0x140001921c0, 0x14000129ea0)
	/Users/matthew.eager/.go/pkg/mod/fyne.io/fyne/v2@v2.0.4/internal/driver/glfw/window.go:1207 +0x50 fp=0x14000129e80 sp=0x14000129e60 pc=0x100e0f130
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow(0x1400010e3c0, 0x140001921c0)
	/Users/matthew.eager/.go/pkg/mod/fyne.io/fyne/v2@v2.0.4/internal/driver/glfw/loop.go:155 +0x50 fp=0x14000129ec0 sp=0x14000129e80 pc=0x100e06710
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread.func1(0x1400010e3c0, 0x14000118480, 0x1400010e460)
	/Users/matthew.eager/.go/pkg/mod/fyne.io/fyne/v2@v2.0.4/internal/driver/glfw/loop.go:211 +0x300 fp=0x14000129fc0 sp=0x14000129ec0 pc=0x100e06c90
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1133 +0x4 fp=0x14000129fc0 sp=0x14000129fc0 pc=0x100c70664
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread
	/Users/matthew.eager/.go/pkg/mod/fyne.io/fyne/v2@v2.0.4/internal/driver/glfw/loop.go:182 +0xac

goroutine 1 [chan send, locked to thread]:
fyne.io/fyne/v2/internal/driver/glfw.runOnDraw(...)
	/Users/matthew.eager/.go/pkg/mod/fyne.io/fyne/v2@v2.0.4/internal/driver/glfw/loop.go:64
fyne.io/fyne/v2/internal/driver/glfw.(*window).platformResize(0x140001921c0, {0x432e0000, 0x43790000})
	/Users/matthew.eager/.go/pkg/mod/fyne.io/fyne/v2@v2.0.4/internal/driver/glfw/window_notlinux.go:14 +0x124
fyne.io/fyne/v2/internal/driver/glfw.(*window).resized(0x140001921c0, 0x1400015e480, 0xae, 0xf9)
	/Users/matthew.eager/.go/pkg/mod/fyne.io/fyne/v2@v2.0.4/internal/driver/glfw/window.go:553 +0x104
github.com/go-gl/glfw/v3.3/glfw.goWindowSizeCB(0x115609790, 0xae, 0xf9)
	/Users/matthew.eager/.go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20210410170116-ea3d685f79fb/window.go:213 +0x58
github.com/go-gl/glfw/v3.3/glfw._Cfunc_glfwPollEvents()
	_cgo_gotypes.go:1474 +0x40
github.com/go-gl/glfw/v3.3/glfw.PollEvents()
	/Users/matthew.eager/.go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20210410170116-ea3d685f79fb/window.go:949 +0x20
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).tryPollEvents(0x1400010e3c0)
	/Users/matthew.eager/.go/pkg/mod/fyne.io/fyne/v2@v2.0.4/internal/driver/glfw/loop.go:225 +0x3c
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).runGL(0x1400010e3c0)
	/Users/matthew.eager/.go/pkg/mod/fyne.io/fyne/v2@v2.0.4/internal/driver/glfw/loop.go:102 +0x1d8
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).Run(0x1400010e3c0)
	/Users/matthew.eager/.go/pkg/mod/fyne.io/fyne/v2@v2.0.4/internal/driver/glfw/driver.go:80 +0x38
fyne.io/fyne/v2/internal/driver/glfw.(*window).ShowAndRun(0x140001921c0)
	/Users/matthew.eager/.go/pkg/mod/fyne.io/fyne/v2@v2.0.4/internal/driver/glfw/window.go:449 +0x38
main.main()
	/Users/matthew.eager/fyne-test/main.go:14 +0xcc

goroutine 19 [sleep]:
time.Sleep(0x22ecb25c00)
	/usr/local/go/src/runtime/time.go:193 +0x138
fyne.io/fyne/v2/internal/painter.svgCacheJanitor.func1()
	/Users/matthew.eager/.go/pkg/mod/fyne.io/fyne/v2@v2.0.4/internal/painter/svg_cache.go:57 +0x44
sync.(*Once).doSlow(0x1013df910, 0x14000144cb0)
	/usr/local/go/src/sync/once.go:68 +0x10c
sync.(*Once).Do(0x1013df910, 0x14000144cb0)
	/usr/local/go/src/sync/once.go:59 +0x38
created by fyne.io/fyne/v2/internal/painter.svgCacheJanitor
	/Users/matthew.eager/.go/pkg/mod/fyne.io/fyne/v2@v2.0.4/internal/painter/svg_cache.go:55 +0x9c

goroutine 20 [select]:
fyne.io/fyne/v2/data/binding.makeInfiniteQueue.func1(0x14000118120, 0x140001400b8)
	/Users/matthew.eager/.go/pkg/mod/fyne.io/fyne/v2@v2.0.4/data/binding/queue.go:36 +0x100
created by fyne.io/fyne/v2/data/binding.makeInfiniteQueue
	/Users/matthew.eager/.go/pkg/mod/fyne.io/fyne/v2@v2.0.4/data/binding/queue.go:21 +0xac

goroutine 21 [chan receive]:
fyne.io/fyne/v2/data/binding.processItems()
	/Users/matthew.eager/.go/pkg/mod/fyne.io/fyne/v2@v2.0.4/data/binding/queue.go:54 +0x3c
created by fyne.io/fyne/v2/data/binding.init.0
	/Users/matthew.eager/.go/pkg/mod/fyne.io/fyne/v2@v2.0.4/data/binding/queue.go:15 +0x30

goroutine 22 [chan receive]:
fyne.io/fyne/v2/app.newAppWithDriver.func1(0x14000118300, 0x140002f6230)
	/Users/matthew.eager/.go/pkg/mod/fyne.io/fyne/v2@v2.0.4/app/app.go:120 +0x34
created by fyne.io/fyne/v2/app.newAppWithDriver
	/Users/matthew.eager/.go/pkg/mod/fyne.io/fyne/v2@v2.0.4/app/app.go:118 +0x234

goroutine 23 [syscall]:
syscall.syscall6(0x100e272c0, 0x6, 0x0, 0x0, 0x14000040e88, 0xa, 0x1013df9f0)
	/usr/local/go/src/runtime/sys_darwin.go:44 +0x1c
golang.org/x/sys/unix.kevent(0x6, 0x0, 0x0, 0x14000040e88, 0xa, 0x1013df9f0)
	/Users/matthew.eager/.go/pkg/mod/golang.org/x/sys@v0.0.0-20200720211630-cb9d2d5c5666/unix/zsyscall_darwin_arm64.go:292 +0x80
golang.org/x/sys/unix.Kevent(0x6, {0x0, 0x0, 0x0}, {0x14000040e88, 0xa, 0xa}, 0x1013df9f0)
	/Users/matthew.eager/.go/pkg/mod/golang.org/x/sys@v0.0.0-20200720211630-cb9d2d5c5666/unix/syscall_bsd.go:413 +0x70
github.com/fsnotify/fsnotify.read(0x6, {0x14000040e88, 0xa, 0xa}, 0x1013df9f0)
	/Users/matthew.eager/.go/pkg/mod/github.com/fsnotify/fsnotify@v1.4.9/kqueue.go:511 +0x50
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0x14000142780)
	/Users/matthew.eager/.go/pkg/mod/github.com/fsnotify/fsnotify@v1.4.9/kqueue.go:274 +0x88
created by github.com/fsnotify/fsnotify.NewWatcher
	/Users/matthew.eager/.go/pkg/mod/github.com/fsnotify/fsnotify@v1.4.9/kqueue.go:62 +0x1c4

goroutine 24 [chan receive]:
fyne.io/fyne/v2/app.watchFile.func1(0x14000142780, {0x14000161400, 0x3b}, 0x14000123cb0, 0x14000123cc0)
	/Users/matthew.eager/.go/pkg/mod/fyne.io/fyne/v2@v2.0.4/app/settings_desktop.go:42 +0x48
created by fyne.io/fyne/v2/app.watchFile
	/Users/matthew.eager/.go/pkg/mod/fyne.io/fyne/v2@v2.0.4/app/settings_desktop.go:41 +0xec

goroutine 26 [chan receive]:
fyne.io/fyne/v2/internal/driver/glfw.(*window).runEventQueue(0x140001921c0)
	/Users/matthew.eager/.go/pkg/mod/fyne.io/fyne/v2@v2.0.4/internal/driver/glfw/window.go:1267 +0x90
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1
	/Users/matthew.eager/.go/pkg/mod/fyne.io/fyne/v2@v2.0.4/internal/driver/glfw/window.go:1292 +0x138

goroutine 27 [chan receive]:
fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).setupThemeListener.func1(0x140001184e0, 0x14000346000)
	/Users/matthew.eager/.go/pkg/mod/fyne.io/fyne/v2@v2.0.4/internal/driver/glfw/canvas.go:495 +0x40
created by fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).setupThemeListener
	/Users/matthew.eager/.go/pkg/mod/fyne.io/fyne/v2@v2.0.4/internal/driver/glfw/canvas.go:493 +0x94

goroutine 29 [chan receive]:
fyne.io/fyne/v2/internal/painter.SvgCacheMonitorTheme.func1(0x14000118600)
	/Users/matthew.eager/.go/pkg/mod/fyne.io/fyne/v2@v2.0.4/internal/painter/svg_cache.go:109 +0x2c
created by fyne.io/fyne/v2/internal/painter.SvgCacheMonitorTheme
	/Users/matthew.eager/.go/pkg/mod/fyne.io/fyne/v2@v2.0.4/internal/painter/svg_cache.go:107 +0x8c
exit status 2
```

**Comment by Bluebugs** [comment]
I wonder if my branch for handling resize asynchronously would actually solve your problem, would you mind testing : https://github.com/fyne-io/fyne/pull/960 .

**Comment by changkun** [comment]
This is duplicated with #2188, it should be fixed in #2429

**Comment by Jacalz** [comment]
Closing as duplicate per the comment above.

**Comment by meagar** [comment]
Thanks all, sorry, I did try to find existing issues but didn't manage to find that one.

**Comment by Jacalz** [comment]
No worries. It happens to all of us :)
