### ISSUE TITLE
Window double close cause panic

### ISSUE THREAD

**Issue by changkun** [fyne-io/fyne#2472]
### Describe the bug:

An observed panic on iOS:

```
panic: close of nil channel

goroutine 114 [running]:
fyne.io/fyne/v2/internal/driver/common.(*Window).DestroyEventQueue(0x1301ce2d0)
	/Users/changkun/dev/changkun.de/fyne/internal/driver/common/window.go:27 +0x104
created by fyne.io/fyne/v2/internal/driver/mobile.(*window).Close
	/Users/changkun/dev/changkun.de/fyne/internal/driver/mobile/window.go:178 +0x248
```

### To Reproduce:

Steps to reproduce the behaviour:

1. In fyne_demo
2. Click a tab, close it
3. It lucky, the panic happens

### Device (please complete the following information):
 - **OS:**  iOS
 - **Version:**  iOS15
 - **Go version:**  Go 1.18
 - **Fyne version:**  Fyne v2.1

**Comment by andydotxyz** [comment]
Ah thanks for tracking down the cause on this one - I had started noticing it but had thought it was a random crash.
