### ISSUE TITLE
Scrolling list bound to data programmatically causes nil pointer dereference

### ISSUE THREAD

**Issue by thenick775** [fyne-io/fyne#2549]
### Describe the bug:

When scrolling a list bound to data using the keyboard programmatically, this results in a nil pointer dereference. This is after the list has been bound to an existing slice of string.

Sometimes this works, but more often than not I run into this issue, since keyboard scrolling using the arrow keys did not seem to be supported.

I have seen this behavior in the middle of list navigation in this manner, as well as at the end and near the beginning. I also see this when using the mouse wheel to scroll.

### To Reproduce:
Steps to reproduce the behaviour:

declare a list and populate it with data (50-100 elements)

use a function like the one included below to map the keydowns to a scroll, where the keyup function will just disable the bool used to keep the scroll going, this function is called from a goroutine.

### Example code:
```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/data/binding"
	"fyne.io/fyne/v2/driver/desktop"
	"fyne.io/fyne/v2/widget"
	"time"
)

var list *widget.List
var ScrollStop bool
var slice []string
var count int

func Scroll(key fyne.KeyEvent, loc int) {
	time.Sleep(200 * time.Millisecond)
	for ScrollStop {
		time.Sleep(50 * time.Millisecond)
		switch key.Name {
		case fyne.KeyDown:
			loc += 1
			if loc > len(slice)-1 {
				ScrollStop = false
				break
			}
			list.Select(loc)
		case fyne.KeyUp:
			loc -= 1
			if loc < 0 {
				ScrollStop = false
				break
			}
			list.Select(loc)
		}
	}
}

func up(key *fyne.KeyEvent) {
	switch key.Name {
	case fyne.KeyDown:
		fallthrough
	case fyne.KeyUp:
		ScrollStop = false
	}
}

func down(key *fyne.KeyEvent) {
	switch key.Name {
	case fyne.KeyDown:
		list.Select(count + 1)
		ScrollStop = true
		go Scroll(*key, count+1)
	case fyne.KeyUp:
		list.Select(count - 1)
		ScrollStop = true
		go Scroll(*key, count-1)
	}
}

func selected(index int) {
	if index < 0 {
		index = 0
	} else if index > list.Length()-1 {
		index = list.Length() - 1
	}
	count = index
}

func main() {
	ScrollStop, count = false, 0

	slice = []string{}
	var data binding.ExternalStringList

	for i := 0; i < 100; i++ {
		slice = append(slice, "word")
	}

	a := app.NewWithID("com.vancise.listtest")
	w := a.NewWindow("List Test")

	data = binding.BindStringList(
		&slice,
	)

	list = widget.NewListWithData(data,
		func() fyne.CanvasObject {
			return widget.NewLabel("template")
		},
		func(i binding.DataItem, o fyne.CanvasObject) {
			o.(*widget.Label).Wrapping = fyne.TextTruncate
			o.(*widget.Label).Bind(i.(binding.String))
		})
	list.OnSelected = selected

	view := container.NewBorder(
		container.NewVBox(
			widget.NewLabel("List Test"),
			widget.NewSeparator()),
		nil,
		nil,
		nil,
		list)

	list.Select(0)

	if deskCanvas, ok := w.Canvas().(desktop.Canvas); ok {
		deskCanvas.SetOnKeyDown(down) //for monitoring navigation of the list in inquire mode
		deskCanvas.SetOnKeyUp(up)
	} else {
		panic("not desktop canvas")
	}

	w.Resize(fyne.NewSize(940, 660))
	w.SetContent(view)
	w.ShowAndRun()
}
```

### Error Report
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x415fce2]

goroutine 15 [running]:
fyne.io/fyne/v2/data/binding.(*boundExternalStringListItem).Get(0x0)
	<autogenerated>:1 +0x22
fyne.io/fyne/v2/widget.(*Label).createListener.func1()
	/Users/nickvancise/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/widget/label.go:148 +0x37
fyne.io/fyne/v2/data/binding.(*listener).DataChanged(0x1)
	/Users/nickvancise/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/data/binding/binding.go:55 +0x1a
fyne.io/fyne/v2/data/binding.queueItem.func1.1()
	/Users/nickvancise/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/data/binding/queue.go:19 +0x42
created by fyne.io/fyne/v2/data/binding.queueItem.func1
	/Users/nickvancise/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/data/binding/queue.go:17 +0x45
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

### Device (please complete the following information):
 - OS: MacOS BigSur 11.6
 - go version go1.17 darwin/amd64
 - required fyne.io/fyne/v2 v2.1.0 in go mod file

Any help on debugging this problem is appreciated!

**Comment by Jacalz** [comment]
Please provide a fully working code example instead of a short code snippet. We prefer to have minimal code examples that provide nothing more than a base of reproducing the issues but can be built and tested without having to guess how pieces should be put together.

**Comment by thenick775** [comment]
Updated code section with full example

**Comment by andydotxyz** [comment]
What happens if you move the wrapping code line into the template function?
As it never changes it would be better to set that once.

**Comment by thenick775** [comment]
@andydotxyz I was able to replicate the issue with the wrapping line moved to the label creation as well:
```go
list = widget.NewListWithData(data,
		func() fyne.CanvasObject {
			tmp :=  widget.NewLabel("template")
			tmp.Wrapping = fyne.TextTruncate
			return tmp
		},
		func(i binding.DataItem, o fyne.CanvasObject) {
			//o.(*widget.Label).Wrapping = fyne.TextTruncate
			o.(*widget.Label).Bind(i.(binding.String))
		})
```
