### ISSUE TITLE
panic on move from external screen to internal MBP display

### ISSUE THREAD

**Issue by toaster** [fyne-io/fyne#263]
I just got this one when moving my Fyne app from my external display to the internal MBP screen:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x42d80e2]

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.2/glfw.(*Monitor).GetPhysicalSize.func1(0x0, 0xc003252b78, 0xc003252b7c)
        /Users/tilo/go/pkg/mod/github.com/go-gl/glfw@v0.0.0-20181213070059-819e8ce5125f/v3.2/glfw/monitor.go:100 +0x22
github.com/go-gl/glfw/v3.2/glfw.(*Monitor).GetPhysicalSize(0x0, 0x0, 0x0)
        /Users/tilo/go/pkg/mod/github.com/go-gl/glfw@v0.0.0-20181213070059-819e8ce5125f/v3.2/glfw/monitor.go:100 +0x72
fyne.io/fyne/driver/gl.(*window).detectScale(0xc0000dc180, 0xc0032c7ab0)
        /Users/tilo/work/private/fyne/driver/gl/window.go:303 +0x6e
fyne.io/fyne/driver/gl.(*window).moved(0xc0000dc180, 0xc000154300, 0x333, 0x54)
        /Users/tilo/work/private/fyne/driver/gl/window.go:427 +0x5f
github.com/go-gl/glfw/v3.2/glfw.goWindowPosCB(0x4f33400, 0x5400000333)
        /Users/tilo/go/pkg/mod/github.com/go-gl/glfw@v0.0.0-20181213070059-819e8ce5125f/v3.2/glfw/window.go:179 +0x61
github.com/go-gl/glfw/v3.2/glfw._cgoexpwrap_98eab2324846_goWindowPosCB(0x4f33400, 0x5400000333)
        _cgo_gotypes.go:2146 +0x3b
github.com/go-gl/glfw/v3.2/glfw._Cfunc_glfwPollEvents()
        _cgo_gotypes.go:1117 +0x41
github.com/go-gl/glfw/v3.2/glfw.PollEvents()
        /Users/tilo/go/pkg/mod/github.com/go-gl/glfw@v0.0.0-20181213070059-819e8ce5125f/v3.2/glfw/window.go:777 +0x22
fyne.io/fyne/driver/gl.(*gLDriver).runGL(0xc0000a64e0)
        /Users/tilo/work/private/fyne/driver/gl/loop.go:77 +0x1d5
fyne.io/fyne/driver/gl.(*gLDriver).Run(0xc0000a64e0)
        /Users/tilo/work/private/fyne/driver/gl/driver.go:71 +0x43
fyne.io/fyne/driver/gl.(*window).ShowAndRun(0xc0000dc180)
        /Users/tilo/work/private/fyne/driver/gl/window.go:346 +0x58
main.(*tmpc).Run(...)
        /Users/tilo/work/private/go_gui_test/cmd/fyne/main.go:90
main.main()
        /Users/tilo/work/private/go_gui_test/cmd/fyne/main.go:230 +0x11e
```

Most of the time this works fine.

**Comment by andydotxyz** [comment]
It looks like there is a nil pointer in there somewhere... possibly a race condition in the window move code... Was it flickering from one screen to another? Did you notice anything strange before it crashed?

**Comment by toaster** [comment]
Flickering? I don't remember.
Strange behaviour? No.

But I move windows so fast and absent-minded that this does not mean that there was no strange behaviour or flickering.

**Comment by andydotxyz** [comment]
can you replicate it when moving slowly or does this not happen reliably?

**Comment by toaster** [comment]
It does not happen reliably. Most of the time moving windows back and forth between screens works fine.
Probably we should just let this issue stay open until me or some other has new insights.

**Comment by andydotxyz** [comment]
Has anyone got thoughts on this? :)
Not sure if / how we can get this resolved for the 1.1.1 bugfix release

**Comment by andydotxyz** [comment]
As suggested by @toaster let's leave this for a while, off this milestone.

**Comment by andydotxyz** [comment]
Pretty sure this is no longer an issue, as we don't auto-scale on macOS anymore.
Please re-open if it ever happens again.
