### ISSUE TITLE
macOS 12.2.1 window reopen bug

### ISSUE THREAD

**Issue by Urethramancer** [fyne-io/fyne#2770]
I just updated my primary Mac to the security patch released in the past day, and Fyne programs started behaving very differently.

The program:
Creates a main window and a prefs window, the latter starting off hidden with an override  to make the close button hide it. Shortcut key and menu option opens it.

Symptoms:
- Opening preferences works once, clicking again while it's open does nothing bad.
- Closing prefs and opening the window again crashes the program.
- Running the same binary a second time does not cause a crash, but the prefs window won't open either.
- Making a small change and rebuilding the binary makes it crash that one time again.

Extra weirdness: The way it crashes differs for some runs. See log output below.

This worked perfectly well on macOS 12.1.0, which I was running a couple of hours ago. I had copied this barest skeleton of a program from another project, which I happened to have an already compiled binary of, from before the OS update. This also showed the same behaviour with a single crash.

Here's the first crash output type I see:

```log
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x2 addr=0x3000000012a76176 pc=0x1a3688308]

runtime stack:
runtime.throw({0x102634086?, 0x10228514c?})
	/usr/local/go/src/runtime/panic.go:992 +0x50
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:786 +0x1e8

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x102608648, 0x1400029fcf8)
	/usr/local/go/src/runtime/cgocall.go:157 +0x54 fp=0x1400029fcc0 sp=0x1400029fc80 pc=0x102253e54
github.com/go-gl/glfw/v3.3/glfw._Cfunc_glfwSetWindowPos(0x12a75e710, 0x2e8, 0x111)
	_cgo_gotypes.go:2184 +0x38 fp=0x1400029fcf0 sp=0x1400029fcc0 pc=0x1025d7478
github.com/go-gl/glfw/v3.3/glfw.(*Window).SetPos.func1(0x140000b6000?, 0x2e8, 0x111)
	/Users/orb/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20211213063430-748e38ca8aec/window.go:472 +0x6c fp=0x1400029fd30 sp=0x1400029fcf0 pc=0x1025dc09c
github.com/go-gl/glfw/v3.3/glfw.(*Window).SetPos(0x1400013b1a0?, 0x3?, 0x3?)
	/Users/orb/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20211213063430-748e38ca8aec/window.go:472 +0x20 fp=0x1400029fd60 sp=0x1400029fd30 pc=0x1025dbfd0
fyne.io/fyne/v2/internal/driver/glfw.(*window).doShowAgain.func1()
	/Users/orb/go/pkg/mod/fyne.io/fyne/v2@v2.1.2-rc2.0.20220205172416-4889de4c5c09/internal/driver/glfw/window.go:963 +0x68 fp=0x1400029fda0 sp=0x1400029fd60 pc=0x1025e9528
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).runGL(0x1400013ad20)
	/Users/orb/go/pkg/mod/fyne.io/fyne/v2@v2.1.2-rc2.0.20220205172416-4889de4c5c09/internal/driver/glfw/loop.go:125 +0x1d0 fp=0x1400029ff00 sp=0x1400029fda0 pc=0x1025e1160
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).Run(0x1400037e1e0?)
	/Users/orb/go/pkg/mod/fyne.io/fyne/v2@v2.1.2-rc2.0.20220205172416-4889de4c5c09/internal/driver/glfw/driver.go:85 +0x34 fp=0x1400029ff30 sp=0x1400029ff00 pc=0x1025dfdb4
fyne.io/fyne/v2/internal/driver/glfw.(*window).ShowAndRun(0x1400037e1e0)
	/Users/orb/go/pkg/mod/fyne.io/fyne/v2@v2.1.2-rc2.0.20220205172416-4889de4c5c09/internal/driver/glfw/window.go:231 +0x30 fp=0x1400029ff50 sp=0x1400029ff30 pc=0x1025e4450
main.(*App).Run(...)
	/Users/orb/go/src/github.com/grimdork/clannnish/app.go:55
main.main()
	/Users/orb/go/src/github.com/grimdork/clannnish/main.go:9 +0x38 fp=0x1400029ff70 sp=0x1400029ff50 pc=0x1025f4bf8
runtime.main()
	/usr/local/go/src/runtime/proc.go:255 +0x270 fp=0x1400029ffd0 sp=0x1400029ff70 pc=0x102284c80
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1259 +0x4 fp=0x1400029ffd0 sp=0x1400029ffd0 pc=0x1022b1574

goroutine 19 [syscall]:
syscall.syscall6(0x1025ee9e0, 0x3, 0x0, 0x0, 0x14000050e68, 0xa, 0x102cf0e40)
	/usr/local/go/src/runtime/sys_darwin.go:44 +0x1c
golang.org/x/sys/unix.kevent(0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/Users/orb/go/pkg/mod/golang.org/x/sys@v0.0.0-20220209214540-3681064d5158/unix/zsyscall_darwin_arm64.go:276 +0x5c
golang.org/x/sys/unix.Kevent(0x0?, {0x0?, 0x0?, 0x0?}, {0x14000050e68?, 0x1025f0280?, 0x0?}, 0x0?)
	/Users/orb/go/pkg/mod/golang.org/x/sys@v0.0.0-20220209214540-3681064d5158/unix/syscall_bsd.go:417 +0x44
github.com/fsnotify/fsnotify.read(0x0?, {0x14000050e68?, 0x0?, 0xa}, 0x0?)
	/Users/orb/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.1/kqueue.go:512 +0x48
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0x1400013ad80)
	/Users/orb/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.1/kqueue.go:275 +0x78
created by github.com/fsnotify/fsnotify.NewWatcher
	/Users/orb/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.1/kqueue.go:63 +0x1ac

goroutine 20 [chan receive]:
fyne.io/fyne/v2/app.watchFile.func1()
	/Users/orb/go/pkg/mod/fyne.io/fyne/v2@v2.1.2-rc2.0.20220205172416-4889de4c5c09/app/settings_desktop.go:43 +0x64
created by fyne.io/fyne/v2/app.watchFile
	/Users/orb/go/pkg/mod/fyne.io/fyne/v2@v2.1.2-rc2.0.20220205172416-4889de4c5c09/app/settings_desktop.go:42 +0x120

goroutine 21 [syscall]:
syscall.syscall6(0x1025ee9e0, 0x5, 0x0, 0x0, 0x14000051e68, 0xa, 0x102cf0e40)
	/usr/local/go/src/runtime/sys_darwin.go:44 +0x1c
golang.org/x/sys/unix.kevent(0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/Users/orb/go/pkg/mod/golang.org/x/sys@v0.0.0-20220209214540-3681064d5158/unix/zsyscall_darwin_arm64.go:276 +0x5c
golang.org/x/sys/unix.Kevent(0x0?, {0x0?, 0x0?, 0x0?}, {0x14000051e68?, 0x1025f0280?, 0x0?}, 0x0?)
	/Users/orb/go/pkg/mod/golang.org/x/sys@v0.0.0-20220209214540-3681064d5158/unix/syscall_bsd.go:417 +0x44
github.com/fsnotify/fsnotify.read(0x5?, {0x14000051e68?, 0xa?, 0xa}, 0x102cf0e40?)
	/Users/orb/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.1/kqueue.go:512 +0x48
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0x1400013af00)
	/Users/orb/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.1/kqueue.go:275 +0x78
created by github.com/fsnotify/fsnotify.NewWatcher
	/Users/orb/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.1/kqueue.go:63 +0x1ac

goroutine 22 [chan receive]:
fyne.io/fyne/v2/app.watchFile.func1()
	/Users/orb/go/pkg/mod/fyne.io/fyne/v2@v2.1.2-rc2.0.20220205172416-4889de4c5c09/app/settings_desktop.go:43 +0x64
created by fyne.io/fyne/v2/app.watchFile
	/Users/orb/go/pkg/mod/fyne.io/fyne/v2@v2.1.2-rc2.0.20220205172416-4889de4c5c09/app/settings_desktop.go:42 +0x120

goroutine 34 [select, locked to thread]:
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread.func1()
	/Users/orb/go/pkg/mod/fyne.io/fyne/v2@v2.1.2-rc2.0.20220205172416-4889de4c5c09/internal/driver/glfw/loop.go:226 +0xac
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread
	/Users/orb/go/pkg/mod/fyne.io/fyne/v2@v2.1.2-rc2.0.20220205172416-4889de4c5c09/internal/driver/glfw/loop.go:222 +0xf4

goroutine 23 [select]:
fyne.io/fyne/v2/internal/async.(*UnboundedFuncChan).processing(0x140003f4ab0)
	/Users/orb/go/pkg/mod/fyne.io/fyne/v2@v2.1.2-rc2.0.20220205172416-4889de4c5c09/internal/async/chan_func.go:45 +0xbc
created by fyne.io/fyne/v2/internal/async.NewUnboundedFuncChan
	/Users/orb/go/pkg/mod/fyne.io/fyne/v2@v2.1.2-rc2.0.20220205172416-4889de4c5c09/internal/async/chan_func.go:22 +0x100

goroutine 24 [chan receive]:
fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue(0x0?)
	/Users/orb/go/pkg/mod/fyne.io/fyne/v2@v2.1.2-rc2.0.20220205172416-4889de4c5c09/internal/driver/common/window.go:34 +0x4c
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1
	/Users/orb/go/pkg/mod/fyne.io/fyne/v2@v2.1.2-rc2.0.20220205172416-4889de4c5c09/internal/driver/glfw/window.go:942 +0x148

goroutine 7 [chan receive]:
fyne.io/fyne/v2/internal/driver/glfw.runOnMain(0x14000498cb0)
	/Users/orb/go/pkg/mod/fyne.io/fyne/v2@v2.1.2-rc2.0.20220205172416-4889de4c5c09/internal/driver/glfw/loop.go:70 +0x188
fyne.io/fyne/v2/internal/driver/glfw.(*window).doShowAgain(0x1400037e3c0)
	/Users/orb/go/pkg/mod/fyne.io/fyne/v2@v2.1.2-rc2.0.20220205172416-4889de4c5c09/internal/driver/glfw/window.go:957 +0x6c
fyne.io/fyne/v2/internal/driver/glfw.(*window).doShow(0x1400037e3c0)
	/Users/orb/go/pkg/mod/fyne.io/fyne/v2@v2.1.2-rc2.0.20220205172416-4889de4c5c09/internal/driver/glfw/window.go:137 +0xac
created by fyne.io/fyne/v2/internal/driver/glfw.(*window).Show
	/Users/orb/go/pkg/mod/fyne.io/fyne/v2@v2.1.2-rc2.0.20220205172416-4889de4c5c09/internal/driver/glfw/window.go:132 +0x64
```

And this is the output I got on the most recent run:
```log
2022-02-12 03:51:16.012 clannnish[28169:114399] -[NSKeyValueUndefinedSetter frameRectForContentRect:]: unrecognized selector sent to instance 0x6000025e7390
2022-02-12 03:51:16.013 clannnish[28169:114399] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSKeyValueUndefinedSetter frameRectForContentRect:]: unrecognized selector sent to instance 0x6000025e7390'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001a39481cc __exceptionPreprocess + 240
	1   libobjc.A.dylib                     0x00000001a36997b8 objc_exception_throw + 60
	2   CoreFoundation                      0x00000001a39db1a0 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00000001a38a8360 ___forwarding___ + 1728
	4   CoreFoundation                      0x00000001a38a7be0 _CF_forwarding_prep_0 + 96
	5   clannnish                           0x00000001006848c0 _glfwPlatformSetWindowPos + 140
	6   clannnish                           0x00000001003313dc runtime.asmcgocall.abi0 + 124
)
libc++abi: terminating with uncaught exception of type NSException
SIGABRT: abort
PC=0x1a37c99b8 m=0 sigcode=0
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x100688668, 0x1400029fcf8)
	/usr/local/go/src/runtime/cgocall.go:157 +0x54 fp=0x1400029fcc0 sp=0x1400029fc80 pc=0x1002d3e94
github.com/go-gl/glfw/v3.3/glfw._Cfunc_glfwSetWindowPos(0x13d644780, 0x2e8, 0x111)
	_cgo_gotypes.go:2184 +0x38 fp=0x1400029fcf0 sp=0x1400029fcc0 pc=0x1006574b8
github.com/go-gl/glfw/v3.3/glfw.(*Window).SetPos.func1(0x14000488000?, 0x2e8, 0x111)
	/Users/orb/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20211213063430-748e38ca8aec/window.go:472 +0x6c fp=0x1400029fd30 sp=0x1400029fcf0 pc=0x10065c0dc
github.com/go-gl/glfw/v3.3/glfw.(*Window).SetPos(0x1400040a240?, 0x3?, 0x3?)
	/Users/orb/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20211213063430-748e38ca8aec/window.go:472 +0x20 fp=0x1400029fd60 sp=0x1400029fd30 pc=0x10065c010
fyne.io/fyne/v2/internal/driver/glfw.(*window).doShowAgain.func1()
	/Users/orb/go/pkg/mod/fyne.io/fyne/v2@v2.1.2-rc2.0.20220205172416-4889de4c5c09/internal/driver/glfw/window.go:963 +0x68 fp=0x1400029fda0 sp=0x1400029fd60 pc=0x100669568
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).runGL(0x140000b8d20)
	/Users/orb/go/pkg/mod/fyne.io/fyne/v2@v2.1.2-rc2.0.20220205172416-4889de4c5c09/internal/driver/glfw/loop.go:125 +0x1d0 fp=0x1400029ff00 sp=0x1400029fda0 pc=0x1006611a0
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).Run(0x1400041e000?)
	/Users/orb/go/pkg/mod/fyne.io/fyne/v2@v2.1.2-rc2.0.20220205172416-4889de4c5c09/internal/driver/glfw/driver.go:85 +0x34 fp=0x1400029ff30 sp=0x1400029ff00 pc=0x10065fdf4
fyne.io/fyne/v2/internal/driver/glfw.(*window).ShowAndRun(0x1400041e000)
	/Users/orb/go/pkg/mod/fyne.io/fyne/v2@v2.1.2-rc2.0.20220205172416-4889de4c5c09/internal/driver/glfw/window.go:231 +0x30 fp=0x1400029ff50 sp=0x1400029ff30 pc=0x100664490
main.(*App).Run(...)
	/Users/orb/go/src/github.com/grimdork/clannnish/app.go:54
main.main()
	/Users/orb/go/src/github.com/grimdork/clannnish/main.go:9 +0x38 fp=0x1400029ff70 sp=0x1400029ff50 pc=0x100674c18
runtime.main()
	/usr/local/go/src/runtime/proc.go:255 +0x270 fp=0x1400029ffd0 sp=0x1400029ff70 pc=0x100304cc0
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1259 +0x4 fp=0x1400029ffd0 sp=0x1400029ffd0 pc=0x1003315b4

goroutine 19 [syscall]:
syscall.syscall6(0x10066ea20, 0x3, 0x0, 0x0, 0x14000050e68, 0xa, 0x100d70e40)
	/usr/local/go/src/runtime/sys_darwin.go:44 +0x1c
golang.org/x/sys/unix.kevent(0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/Users/orb/go/pkg/mod/golang.org/x/sys@v0.0.0-20220209214540-3681064d5158/unix/zsyscall_darwin_arm64.go:276 +0x5c
golang.org/x/sys/unix.Kevent(0x0?, {0x0?, 0x0?, 0x0?}, {0x14000050e68?, 0x1006702c0?, 0x0?}, 0x0?)
	/Users/orb/go/pkg/mod/golang.org/x/sys@v0.0.0-20220209214540-3681064d5158/unix/syscall_bsd.go:417 +0x44
github.com/fsnotify/fsnotify.read(0x0?, {0x14000050e68?, 0x0?, 0xa}, 0x0?)
	/Users/orb/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.1/kqueue.go:512 +0x48
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0x140000b8d80)
	/Users/orb/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.1/kqueue.go:275 +0x78
created by github.com/fsnotify/fsnotify.NewWatcher
	/Users/orb/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.1/kqueue.go:63 +0x1ac

goroutine 20 [chan receive]:
fyne.io/fyne/v2/app.watchFile.func1()
	/Users/orb/go/pkg/mod/fyne.io/fyne/v2@v2.1.2-rc2.0.20220205172416-4889de4c5c09/app/settings_desktop.go:43 +0x64
created by fyne.io/fyne/v2/app.watchFile
	/Users/orb/go/pkg/mod/fyne.io/fyne/v2@v2.1.2-rc2.0.20220205172416-4889de4c5c09/app/settings_desktop.go:42 +0x120

goroutine 21 [syscall]:
syscall.syscall6(0x10066ea20, 0x5, 0x0, 0x0, 0x14000051e68, 0xa, 0x100d70e40)
	/usr/local/go/src/runtime/sys_darwin.go:44 +0x1c
golang.org/x/sys/unix.kevent(0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/Users/orb/go/pkg/mod/golang.org/x/sys@v0.0.0-20220209214540-3681064d5158/unix/zsyscall_darwin_arm64.go:276 +0x5c
golang.org/x/sys/unix.Kevent(0x0?, {0x0?, 0x0?, 0x0?}, {0x14000051e68?, 0x1006702c0?, 0x0?}, 0x0?)
	/Users/orb/go/pkg/mod/golang.org/x/sys@v0.0.0-20220209214540-3681064d5158/unix/syscall_bsd.go:417 +0x44
github.com/fsnotify/fsnotify.read(0x0?, {0x14000051e68?, 0x0?, 0xa}, 0x0?)
	/Users/orb/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.1/kqueue.go:512 +0x48
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0x140000b8f00)
	/Users/orb/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.1/kqueue.go:275 +0x78
created by github.com/fsnotify/fsnotify.NewWatcher
	/Users/orb/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.1/kqueue.go:63 +0x1ac

goroutine 22 [chan receive]:
fyne.io/fyne/v2/app.watchFile.func1()
	/Users/orb/go/pkg/mod/fyne.io/fyne/v2@v2.1.2-rc2.0.20220205172416-4889de4c5c09/app/settings_desktop.go:43 +0x64
created by fyne.io/fyne/v2/app.watchFile
	/Users/orb/go/pkg/mod/fyne.io/fyne/v2@v2.1.2-rc2.0.20220205172416-4889de4c5c09/app/settings_desktop.go:42 +0x120

goroutine 34 [select, locked to thread]:
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread.func1()
	/Users/orb/go/pkg/mod/fyne.io/fyne/v2@v2.1.2-rc2.0.20220205172416-4889de4c5c09/internal/driver/glfw/loop.go:226 +0xac
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread
	/Users/orb/go/pkg/mod/fyne.io/fyne/v2@v2.1.2-rc2.0.20220205172416-4889de4c5c09/internal/driver/glfw/loop.go:222 +0xf4

goroutine 35 [select]:
fyne.io/fyne/v2/internal/async.(*UnboundedFuncChan).processing(0x1400040c0c0)
	/Users/orb/go/pkg/mod/fyne.io/fyne/v2@v2.1.2-rc2.0.20220205172416-4889de4c5c09/internal/async/chan_func.go:45 +0xbc
created by fyne.io/fyne/v2/internal/async.NewUnboundedFuncChan
	/Users/orb/go/pkg/mod/fyne.io/fyne/v2@v2.1.2-rc2.0.20220205172416-4889de4c5c09/internal/async/chan_func.go:22 +0x100

goroutine 36 [chan receive]:
fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue(0x0?)
	/Users/orb/go/pkg/mod/fyne.io/fyne/v2@v2.1.2-rc2.0.20220205172416-4889de4c5c09/internal/driver/common/window.go:34 +0x4c
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1
	/Users/orb/go/pkg/mod/fyne.io/fyne/v2@v2.1.2-rc2.0.20220205172416-4889de4c5c09/internal/driver/glfw/window.go:942 +0x148

goroutine 5 [chan receive]:
fyne.io/fyne/v2/internal/driver/glfw.runOnMain(0x140000206c0)
	/Users/orb/go/pkg/mod/fyne.io/fyne/v2@v2.1.2-rc2.0.20220205172416-4889de4c5c09/internal/driver/glfw/loop.go:70 +0x188
fyne.io/fyne/v2/internal/driver/glfw.(*window).doShowAgain(0x1400041e1e0)
	/Users/orb/go/pkg/mod/fyne.io/fyne/v2@v2.1.2-rc2.0.20220205172416-4889de4c5c09/internal/driver/glfw/window.go:957 +0x6c
fyne.io/fyne/v2/internal/driver/glfw.(*window).doShow(0x1400041e1e0)
	/Users/orb/go/pkg/mod/fyne.io/fyne/v2@v2.1.2-rc2.0.20220205172416-4889de4c5c09/internal/driver/glfw/window.go:137 +0xac
created by fyne.io/fyne/v2/internal/driver/glfw.(*window).Show
	/Users/orb/go/pkg/mod/fyne.io/fyne/v2@v2.1.2-rc2.0.20220205172416-4889de4c5c09/internal/driver/glfw/window.go:132 +0x64

r0      0x0
r1      0x0
r2      0x0
r3      0x0
r4      0x1a37bd0ad
r5      0x16fb2dc30
r6      0x6e
r7      0x600
r8      0x6ebd0b84f81d3da4
r9      0x6ebd0b85f937b824
r10     0x2
r11     0xb
r12     0xcda0381a
r13     0x4da03800
r14     0x10
r15     0x2
r16     0x148
r17     0x1fe033530
r18     0x1400eb940
r19     0x6
r20     0x1012a8580
r21     0x103
r22     0x6000004e49c0
r23     0x12d604080
r24     0x1edd730fd
r25     0x0
r26     0x1edd7312c
r27     0x850
r28     0x100d409c0
r29     0x16fb2dba0
lr      0x1a37fceb0
sp      0x16fb2db80
pc      0x1a37c99b8
fault   0x1a37c99b8
```

main.go:
```go
package main

func main() {
	app, err := NewApp()
	if err != nil {
		panic(err)
	}

	app.Run()
}
```

app.go:
```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/driver/desktop"
)

// App holds a Fyne app and its windows.
type App struct {
	fyne.App
	main  fyne.Window
	prefs fyne.Window
}

// APPNAME is used in a few different places.
const APPNAME = "Clannish"

// NewApp creates a new App.
func NewApp() (*App, error) {
	a := &App{
		App: app.NewWithID(APPNAME),
	}

	a.main = a.NewWindow(APPNAME)
	a.main.SetMaster()
	a.main.Resize(fyne.Size{Width: 600, Height: 400})

	prefs := fyne.NewMenuItem("Preferences…", func() {
		a.prefs.Show()
	})

	prefs.Shortcut = &desktop.CustomShortcut{
		KeyName:  fyne.KeyComma,
		Modifier: desktop.SuperModifier,
	}
	menu := fyne.NewMainMenu(
		fyne.NewMenu("Tools", prefs),
		fyne.NewMenu("Window"),
	)
	a.main.SetMainMenu(menu)

	a.prefs = a.NewWindow("Preferences")
	a.prefs.Resize(fyne.Size{Width: 500, Height: 150})
	a.prefs.SetCloseIntercept(func() {
		a.prefs.Hide()
	})

	return a, nil
}

// Run the app.
func (a *App) Run() {
	a.main.ShowAndRun()
}
```

OS: macOS 12.2.1
Go version go1.18beta2 darwin/arm64
Fyne is the latest on the develop branch

**Comment by andydotxyz** [comment]
Can you please test with a released Fyne (v2.1.2) and Go? (1.17.x).
There are too many unreleased versions in this issue to know where to start...

**Comment by Jacalz** [comment]
Thanks for opening this issue and thanks for providing all of the important information. However, I just want to say that we strongly prefer (want) the use of the issue templates instead of removing them. Please consider this when opening your next issue.

If this indeed is an issue in Go 1.18 and not earlier versions, a an issue should probably be opened upstream with the Go compiler.

**Comment by Urethramancer** [comment]
I managed to reproduce it with the combination of Go 1.17.x and Fyne's develop branch, but not with Fyne stable.

**Comment by andydotxyz** [comment]
Thanks for the info, good to know it's not in production. Marking as blocker for before develop goes for release.

**Comment by changkun** [comment]
I can't reproduce this issue on develop branch. Environment: macOS 12.3.1 + Go 1.18.2 + fyne's develop branch c92f334f933729eeff58f02783ba613fe28e6541

I would suggest that this is unlikely an issue on the fyne side, and we could probably remove the blocker and close this case directly. It may belong to the underlying driver compatibility issue with the specific macOS version.

**Comment by andydotxyz** [comment]
Hmm, This is strange indeed. The fact that it was previously happening on develop but not master makes me nervous.
The backlog mentions `-[NSKeyValueUndefinedSetter frameRectForContentRect:]` which is itself clearly wrong so somehow we get the wrong type of object when looking to get window bounds - which does not seem like the sort of thing a driver issue would cause.

@Urethramancer can you please check latest develop and see if you can replicate?
I cannot replicate it either so we may find it was a passing issue, but right now it is hard to say...

**Comment by Urethramancer** [comment]
I'm having trouble compiling anything using CGo now for some reason, and after wiping everything and updating to latest stable Go, Xcode, Xcode CLI tools and checking that no stray GNU binutils are in the way, I still can't combine Fyne or anything else CGo-based. I'll have to check with the regular Go channels when I have the time and energy.

**Comment by andydotxyz** [comment]
May relate to #3197 either way as it's been a while without replication going to close.
Please re-open if it is possible to see it happening with newer Fyne releases.
