### ISSUE TITLE
scrolling widget.NewListWithData while its data is being updated crashes the app 

### ISSUE THREAD

**Issue by vboehr** [fyne-io/fyne#2839]
### Is your feature request related to a problem? Please describe:

While using **widget.NewListWithData** when the code try to update the binding while the user scroll the list the program crashes.

### Is it possible to construct a solution with the existing API?

I can try to add a refresh button but you know automatic update of list's data is better for the user.
 
### Describe the solution you'd like to see:

to expose somthing like **IsScrolling()** so that the program checks before updating databinding using **Set**

**Comment by Jacalz** [comment]
I must have misunderstood your last comment. Sorry about that. I thought you were just suggesting a new feature and not necessarily experiencing the same crash.

Would you mind sharing a small code example, so that we can replicate what you are seeing? Thanks.

**Comment by andydotxyz** [comment]
> to expose somthing like **IsScrolling()** so that the program checks before updating databinding using **Set**

I don't think that we should add APIs to work around this. We should fix the crash.
There is not supposed to be any limitation on when data can be changed.

**Comment by vboehr** [comment]
With a simple code that can reproduce the crash:
`package main

import (

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"

	"fyne.io/fyne/v2/data/binding"
	"fyne.io/fyne/v2/widget"
)

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("List Data")

	data := binding.BindStringList(
		&[]string{"Item 1", "Item 2", "Item 3"},
	)

	list := widget.NewListWithData(data,
		func() fyne.CanvasObject {
			return widget.NewLabel("template")
		},
		func(i binding.DataItem, o fyne.CanvasObject) {
			o.(*widget.Label).Bind(i.(binding.String))
		})


	go func (){
		for {

			tmpdata:=GetData()

			data.Set(tmpdata)


		}

	}()

	myWindow.SetContent(list)
	myWindow.Resize(fyne.NewSize(400, 400))
	myWindow.ShowAndRun()
}

func GetData()[]string{
tmp:=[]string{"1", "2", "3","1", "2", "3","1", "2", "3","1", "2", "3"}

return tmp
}`

**Comment by vboehr** [comment]
As I run the code and while scrolling I get this error:
go run main.gopanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x68e9e5]

goroutine 8 [running]:
fyne.io/fyne/v2/data/binding.(*boundExternalStringListItem).Get(0x0, 0xc0002c2508, 0xc0003b0470, 0xc0002c25b8, 0xc000736400)
	<autogenerated>:1 +0x5
fyne.io/fyne/v2/widget.(*Label).createListener.func1()
	/home/gutenberg/go/src/fyne.io/fyne/v2/widget/label.go:120 +0x45
fyne.io/fyne/v2/data/binding.(*listener).DataChanged(0xc000010140)
	/home/gutenberg/go/src/fyne.io/fyne/v2/data/binding/binding.go:55 +0x28
fyne.io/fyne/v2/data/binding.processItems()
	/home/gutenberg/go/src/fyne.io/fyne/v2/data/binding/queue.go:56 +0x94
created by fyne.io/fyne/v2/data/binding.init.0
	/home/gutenberg/go/src/fyne.io/fyne/v2/data/binding/queue.go:15 +0x35
exit status 2

**Comment by andreapenname** [comment]
I think this is due to how the garbage collector operates. This bug is not related to how fyne works.

**Comment by andydotxyz** [comment]
> As I run the code and while scrolling I get this error:

thanks @vboehr can you please confirm which version of Fyne you are using?

> I think this is due to how the garbage collector operates. This bug is not related to how fyne works.

Even if this is true we have made an error somewhere. The fyne library should never panic (unless fatal error during setup).

**Comment by vboehr** [comment]
I am sorry I am responding a little bit late.
I am using fyne v2 v2.1.1

**Comment by Jacalz** [comment]
Thanks. Could you please test on the latest release (v2.1.4 as it currently stands)?

**Comment by vboehr** [comment]
I upgraded as follows: 
go get fyne.io/fyne/v2@v2.1.4

And bug did not occur again!
