### ISSUE TITLE
Setting TextWrapWord crashes the application 

### ISSUE THREAD

**Issue by wolfderechter** [fyne-io/fyne#2961]
### Describe the bug:
When I set the label wrapping to TextWrapWord my application crashes on startup

### To Reproduce:
Steps to reproduce the behaviour:
1. Run the application
2. See error

### Example code:
```go
package main

import (
	"encoding/json"
	"fmt"
	"io/ioutil"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	movieResults, err := LoadMovies()
	if err != nil {
		fmt.Println("Hi")
		panic(err)
	}

	a := app.New()
	w := a.NewWindow("Movie View")
	w.Resize(fyne.NewSize(700, 600))

	listView := widget.NewList(func() int {
		return len(movieResults.Results)
	}, func() fyne.CanvasObject {
		return widget.NewLabel("template")
	}, func(id widget.ListItemID, object fyne.CanvasObject) {
		object.(*widget.Label).SetText(movieResults.Results[id].Title)
	})

	contentText := widget.NewLabel("Please select a movie ")
	contentText.Wrapping = fyne.TextWrapWord

	listView.OnSelected = func(id widget.ListItemID) {
		contentText.SetText(movieResults.Results[id].Overview)
	}

	split := container.NewHSplit(
		listView,
		container.NewMax(contentText),
	)
	split.Offset = 0.2

	w.SetContent(split)

	w.ShowAndRun()
}
```

### Error Message
```console
PS C:\Users\wolfd\Documents\School\Go\FyneGUI> go run main.go
panic: runtime error: index out of range [-1]

goroutine 1 [running, locked to thread]:
fyne.io/fyne/v2/widget.(*RichText).updateRowBounds.func1({0xc000458000, 0x1, 0xc00045c000})
        C:/Users/wolfd/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/widget/richtext.go:381 +0xc2b
fyne.io/fyne/v2/widget.(*RichText).updateRowBounds(0xc0000c4000)
        C:/Users/wolfd/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/widget/richtext.go:411 +0x106
fyne.io/fyne/v2/widget.(*RichText).Resize(0xc0000c4000, {0x0, 0x0})
        C:/Users/wolfd/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/widget/richtext.go:109 +0x105
fyne.io/fyne/v2/widget.(*Label).Resize(0xc0000c2000, {0x2a2000, 0xc0})
        C:/Users/wolfd/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/widget/label.go:108 +0x4b
fyne.io/fyne/v2/layout.(*maxLayout).Layout(0xc00052f840, {0xc0000b8040, 0x1, 0xc0000c0001}, {0x464000, 0xc0})
        C:/Users/wolfd/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/layout/maxlayout.go:22 +0x82
fyne.io/fyne/v2.(*Container).layout(...)
        C:/Users/wolfd/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/container.go:171
fyne.io/fyne/v2.(*Container).Resize(0xc0000c0000, {0x42d3b13c, 0x42a01800})
        C:/Users/wolfd/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/container.go:99 +0x62
fyne.io/fyne/v2/container.(*splitContainerRenderer).Layout(0xc0004041b0, {0x462000, 0xc0})
        C:/Users/wolfd/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/container/split.go:126 +0x237
fyne.io/fyne/v2/widget.(*BaseWidget).Resize(0xc000462000, {0x52f8e8, 0x42e3b13c})
        C:/Users/wolfd/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/widget/widget.go:61 +0x13e
fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).Resize(0xc0000ba000, {0xba000, 0xc0})
        C:/Users/wolfd/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/internal/driver/glfw/canvas.go:123 +0xcc
fyne.io/fyne/v2/internal/driver/glfw.(*window).resized(0xc0000b4000, 0x7ff77db42500, 0x7ff77e1a67a0, 0xc00052f9a8)
        C:/Users/wolfd/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/internal/driver/glfw/window.go:565 +0xd8
github.com/go-gl/glfw/v3.3/glfw.goWindowSizeCB(0x7ff77d874cc6, 0x94, 0x3a)
        C:/Users/wolfd/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20211024062804-40e447a793be/window.go:213 +0x4b
github.com/go-gl/glfw/v3.3/glfw._Cfunc_glfwSetWindowSizeLimits(0x2767f92aa80, 0x92, 0x3a, 0xffffffff, 0xffffffff)
        _cgo_gotypes.go:2349 +0x52
github.com/go-gl/glfw/v3.3/glfw.(*Window).SetSizeLimits.func1(0x92, 0x92, 0x3a, 0xffffffffffffffff, 0xffffffffffffffff)
        C:/Users/wolfd/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20211024062804-40e447a793be/window.go:505 +0x7e
github.com/go-gl/glfw/v3.3/glfw.(*Window).SetSizeLimits(0xc0000b4038, 0xc00009e118, 0xc000468090, 0xc00009e168, 0xc00009e16c)
        C:/Users/wolfd/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20211024062804-40e447a793be/window.go:505 +0x19
fyne.io/fyne/v2/internal/driver/glfw.(*window).fitContent(0xc0000b4000)
        C:/Users/wolfd/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/internal/driver/glfw/window.go:325 +0x1e6
fyne.io/fyne/v2/internal/driver/glfw.(*window).create.func3()
        C:/Users/wolfd/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/internal/driver/glfw/window.go:1492 +0x38a
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).runGL(0xc00005e3c0)
        C:/Users/wolfd/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/internal/driver/glfw/loop.go:127 +0x197
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).Run(0xc0000b4000)
        C:/Users/wolfd/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/internal/driver/glfw/driver.go:85 +0x30
fyne.io/fyne/v2/internal/driver/glfw.(*window).ShowAndRun(0xc0000b4000)
        C:/Users/wolfd/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/internal/driver/glfw/window.go:479 +0x2f
main.main()
        C:/Users/wolfd/Documents/School/Go/FyneGUI/main.go:64 +0x2ed
exit status 2
```

### Device (please complete the following information):
 - **OS:** Windows 10
 - **Version:** 10.0.19043 Build 19043
 - **Go version:** 1.17.8
 - **Fyne version:** 2.1.4

**Comment by andydotxyz** [comment]
Thanks, will look into this. 
Just so you know `container.NewMax(` adds nothing in your code, as a single item will always fill the space that it is given.

**Comment by wolfderechter** [comment]
Oh I might add that I was following along the following tutorial as an intro to Fyne: https://youtu.be/m_ZyPDARmsI

**Comment by andydotxyz** [comment]
I cannot replicate this with fyne on `develop` branch - perhaps it has been fixed by other text work.
Can you please confirm @wolfderechter ?

**Comment by wolfderechter** [comment]
I replicated the issue on my desktop with fyne version 2.2.0. I haven't done anything else since I put the project aside.

Full code example which gives the error:

`package main

import (
	"encoding/json"
	"io/ioutil"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

type MovieResults struct {
	Results []Movie `json:"results"`
}

type Movie struct {
	Title    string `json:"title"`
	Overview string `json:"overview"`
}

func main() {
	movieResults, err := LoadMovies()
	if err != nil {
		panic(err)
	}

	a := app.New()
	w := a.NewWindow("Movie View")
	// w.Resize(fyne.NewSize(700, 600))
	w.Resize(fyne.NewSize(500, 500))

	//takes in 3 functions
	//1 needs to return length of the list
	//2 is like a template, which item the list is gonna render
	//3 is gonna pass in the object and give the id so we can update the obj

	listView := widget.NewList(func() int {
		return len(movieResults.Results)
	}, func() fyne.CanvasObject {
		return widget.NewLabel("template")
	}, func(id widget.ListItemID, object fyne.CanvasObject) {
		object.(*widget.Label).SetText(movieResults.Results[id].Title)
	})

	// contentText := widget.NewLabel("Please select a movie ")
	contentText := widget.NewLabel("Please select a movie ")
	contentText.Wrapping = fyne.TextWrapWord

	listView.OnSelected = func(id widget.ListItemID) {
		contentText.SetText(movieResults.Results[id].Overview)
	}

	split := container.NewHSplit(
		listView,
		contentText,
		//this will fill in the blank
		// container.NewMax(contentText),
	)
	split.Offset = 0.2

	w.SetContent(split)

	w.ShowAndRun()
}

func LoadMovies() (MovieResults, error) {
	data, err := ioutil.ReadFile("./data.json")
	if err != nil {
		return MovieResults{}, err
	}

	var movieResults MovieResults
	err = json.Unmarshal(data, &movieResults)
	if err != nil {
		return MovieResults{}, err
	}
	return movieResults, nil
}
`

**Comment by andydotxyz** [comment]
This won't load data without `data.json` file present - can you either make a sample that does not need that or provide the file?

**Comment by andydotxyz** [comment]
Thanks. It looks like this and #3003 are the same issue
