### ISSUE TITLE
Segmentation violation during boxLayout layout pass when widgets are constructed concurrently 

### ISSUE THREAD

**Issue by AkiSakurai** [fyne-io/fyne#2968]
``` go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/canvas"
	"math/rand"
	"image/color"
	"strings"
	"time"
)



func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("List Data")
	myWindow.Resize(fyne.NewSize(200, 300)) 

	colors  := []color.Color{color.White, color.Black}

	text := canvas.NewText("Starting....", color.White)
	myWindow.SetContent(text)

	go func(){
		time.Sleep(time.Millisecond * 1000)
		for {
			vbox := container.NewVBox()
			time.Sleep(time.Millisecond * 100)
			for i:= 0; i< 50; i++ {
				go func(){
					hbox := container.NewHBox()
					vbox.Add(hbox)
					for j := 0; j < 50; j++ {
						go func() {
							mycolor  := colors[rand.Intn(len(colors))]
							text := canvas.NewText(strings.Repeat("1", rand.Intn(5)), mycolor)
							hbox.Add(text)
						}()
					}
				}()
			}
			myWindow.SetContent(vbox)
		}
	}()

	myWindow.ShowAndRun()
}
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x422650e]

goroutine 43515 [running]:
fyne.io/fyne/v2/layout.(*boxLayout).MinSize(0xc00078e9b0, {0xc00199a200?, 0x1e, 0x4225ea6?})
	/Users/a/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/layout/boxlayout.go:125 +0x8e
fyne.io/fyne/v2.(*Container).MinSize(0xc000880a60?)
	/Users/a/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/container.go:71 +0x72
fyne.io/fyne/v2/layout.(*boxLayout).Layout(0xc000880a60, {0xc000446200, 0x18, 0x0?}, {0x0?, 0x0?})
	/Users/a/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/layout/boxlayout.go:74 +0x4c7
fyne.io/fyne/v2.(*Container).layout(...)
	/Users/a/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/container.go:171
fyne.io/fyne/v2.(*Container).Add(0x4460910?, {0x4462dd0?, 0xc000f64040?})
	/Users/a/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/container.go:57 +0xe5
main.main.func1.1()
	/Users/a/Desktop/Study/fyne-race/main.go:34 +0x7e
created by main.main.func1
	/Users/a/Desktop/Study/fyne-race/main.go:32 +0xae
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x4226299]

goroutine 43669 [running]:
fyne.io/fyne/v2/layout.(*boxLayout).Layout(0xc00078e9b0, {0xc00199a200, 0x1f, 0x4184729?}, {0x1?, 0x7ffffffc?})
	/Users/a/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/layout/boxlayout.go:63 +0x399
fyne.io/fyne/v2.(*Container).layout(...)
	/Users/a/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/container.go:171
fyne.io/fyne/v2.(*Container).Add(0x0?, {0x44630d0?, 0xc001e2c880?})
	/Users/a/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/container.go:57 +0xe5
main.main.func1.1.1()
	/Users/a/Desktop/Study/fyne-race/main.go:39 +0xad
created by main.main.func1.1
	/Users/a/Desktop/Study/fyne-race/main.go:36 +0x87
exit status 2

```
 - **OS:**  MacOS 
 - **Version:** 12.3.1
 - **Go version:** 1.18.1
 - **Fyne version:** 2.1.4

**Comment by andydotxyz** [comment]
Can you please test using the `develop` branch as there have been other fixes to the container concurrency support.

**Comment by AkiSakurai** [comment]
I have tested on develop branch, the issue is still exists.

**Comment by changkun** [comment]
I can reproduce the problem on dev branch

**Comment by changkun** [comment]
OK, I can see why this will crash. The program largely violates data races and confuses fyne's internal renderer. The Vbox and Hbox are concurrently created without any protection.

A lock guaranteed program won't crash, specifically:

```diff
package main

import (
	"image/color"
	"math/rand"
	"strings"
	"sync"
	"time"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/container"
)

func main() {
	w := app.New().NewWindow("List Data")
	w.Resize(fyne.NewSize(200, 300))

	colors := []color.Color{color.White, color.Black}

	text := canvas.NewText("Starting....", color.White)
	w.SetContent(text)

	go func() {
		time.Sleep(time.Millisecond * 1000)
		for {
+			vmu := sync.Mutex{}
			vbox := container.NewVBox()
+			wg := sync.WaitGroup{}
			for i := 0; i < 50; i++ {
+				wg.Add(1)
				go func() {
+					defer wg.Done()
+					hmu := sync.Mutex{}
					hbox := container.NewHBox()

+					vmu.Lock()
					vbox.Add(hbox)
+					vmu.Unlock()
+					wgg := sync.WaitGroup{}
					for j := 0; j < 50; j++ {
+						wgg.Add(1)
						go func() {
+							defer wgg.Done()
							mycolor := colors[rand.Intn(len(colors))]
							text := canvas.NewText(strings.Repeat("1", rand.Intn(5)), mycolor)
+							hmu.Lock()
							hbox.Add(text)
+							hmu.Unlock()
						}()
					}
+					wgg.Wait()
				}()
			}
+			wg.Wait()
			w.SetContent(vbox)
		}
	}()
	w.ShowAndRun()
}
```

With this observation, I'd consider this is not a valid problem, and we don't need solve anything for now.

Perhaps this could give us a sampled evidence where we might want to make the APIs more concurrently safe, such as (*Container).Add() need to guarantee its atomicity, to protect against misuses like this. What do you think? @andydotxyz

**Comment by AkiSakurai** [comment]
This is of course a invalid program in other GUI framework. 

https://fyne.io/blog/2018/06/26/fun-with-fractals.html#about
But from this blog post, it give me false impression that it is okay do that. The parse function mutate the buttonList without any _synchronization._

**Comment by changkun** [comment]
Interesting. I didn’t know this was somewhat encouraged (perhaps not on purpose.)

**Comment by changkun** [comment]
Also, back in 2018, the internal renderer works a bit different from today, which I guess we could either solve by:

1. explicit documentation on what is an expected behavior; or
2. making the call concurrent safe

**Comment by AkiSakurai** [comment]
I can reproduce the problem with just one goroutine.



``` golang
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/canvas"
	"math/rand"
	"image/color"
	"strings"
	"time"
)

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("List Data")
	myWindow.Resize(fyne.NewSize(200, 300)) 
	colors  := []color.Color{color.White, color.Black}
	vbox := container.NewVBox()
	go func(){
		size := 50
		for i:= 0; i < size; i++ {
			hbox := container.NewHBox()
			vbox.Add(hbox)
		}
		for{
			for i:= 0; i < size; i++ {
				hbox := vbox.Objects[i].(*fyne.Container)
				hbox.Objects = nil
					for j := 0; j < rand.Intn(50); j++ {
						mycolor  := colors[rand.Intn(len(colors))]
						text := canvas.NewText(strings.Repeat("1", rand.Intn(5)), mycolor)
						hbox.Add(text)
					}
			} 
			time.Sleep(1)
			vbox.Refresh()
		}
	}()
	myWindow.SetContent(vbox)
	myWindow.ShowAndRun()
}
```
```

2022/05/15 10:32:56   At: /Users/a/go/pkg/mod/github.com/fyne-io/fyne/v2@v2.1.4-0.20220514124826-61b61b441312/internal/driver/glfw/window_desktop.go:198
unexpected fault address 0xb01dfacedebac1e
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x4315592]

goroutine 18 [running, locked to thread]:
runtime.throw({0x44ba74b?, 0xc001433e18?})
	/usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc000373688 sp=0xc000373658 pc=0x4036f11
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:825 +0x305 fp=0xc0003736d8 sp=0xc000373688 pc=0x404c4a5
fyne.io/fyne/v2/layout.(*boxLayout).MinSize(0xc00049202a, {0xc002150a70?, 0x2, 0x4314f26?})
	/Users/a/go/pkg/mod/github.com/fyne-io/fyne/v2@v2.1.4-0.20220514124826-61b61b441312/layout/boxlayout.go:125 +0x92 fp=0xc000373738 sp=0xc0003736d8 pc=0x4315592
fyne.io/fyne/v2.(*Container).MinSize(0xc00040003a?)
	/Users/a/go/pkg/mod/github.com/fyne-io/fyne/v2@v2.1.4-0.20220514124826-61b61b441312/container.go:84 +0x72 fp=0xc000373790 sp=0xc000373738 pc=0x42321b2
fyne.io/fyne/v2/layout.(*boxLayout).Layout(0xc00040003a, {0xc0004a0000, 0x32, 0x3?}, {0x3738a0?, 0xc0?})
	/Users/a/go/pkg/mod/github.com/fyne-io/fyne/v2@v2.1.4-0.20220514124826-61b61b441312/layout/boxlayout.go:95 +0x1c4 fp=0xc000373858 sp=0xc000373790 pc=0x4315144
fyne.io/fyne/v2/internal/driver/common.updateLayout({0x45a5f30?, 0xc00041e080?})
	/Users/a/go/pkg/mod/github.com/fyne-io/fyne/v2@v2.1.4-0.20220514124826-61b61b441312/internal/driver/common/canvas.go:532 +0x70 fp=0xc0003738b0 sp=0xc000373858 pc=0x4314ad0
fyne.io/fyne/v2/internal/driver/common.(*Canvas).EnsureMinSize.func1(0xc000f776c0)
	/Users/a/go/pkg/mod/github.com/fyne-io/fyne/v2@v2.1.4-0.20220514124826-61b61b441312/internal/driver/common/canvas.go:97 +0x235 fp=0xc000373938 sp=0xc0003738b0 pc=0x43130f5
fyne.io/fyne/v2/internal/driver/common.(*Canvas).walkTree.func2({0x45a6230?, 0xc0021e5880?}, {0xc0021e5880?, 0x45a5f30?})
	/Users/a/go/pkg/mod/github.com/fyne-io/fyne/v2@v2.1.4-0.20220514124826-61b61b441312/internal/driver/common/canvas.go:453 +0xae fp=0xc000373960 sp=0xc000373938 pc=0x431464e
fyne.io/fyne/v2/internal/driver.walkObjectTree({0x45a6230, 0xc0021e5880}, 0x0, {0x45a5f30, 0xc000494140}, {0x1d06be4?, 0xc0?}, {0x373c98?, 0xc0?}, {0x373ca8?, ...}, ...)
	/Users/a/go/pkg/mod/github.com/fyne-io/fyne/v2@v2.1.4-0.20220514124826-61b61b441312/internal/driver/util.go:197 +0x370 fp=0xc000373a28 sp=0xc000373960 pc=0x4251c50
fyne.io/fyne/v2/internal/driver.walkObjectTree.func1(...)
	/Users/a/go/pkg/mod/github.com/fyne-io/fyne/v2@v2.1.4-0.20220514124826-61b61b441312/internal/driver/util.go:176
fyne.io/fyne/v2/internal/driver.walkObjectTree({0x45a5f30, 0xc000494140}, 0x0, {0x45a5f30, 0xc00041e080}, {0x42b96d0?, 0x0?}, {0x425bcec?, 0x0?}, {0x1d06be4?, ...}, ...)
	/Users/a/go/pkg/mod/github.com/fyne-io/fyne/v2@v2.1.4-0.20220514124826-61b61b441312/internal/driver/util.go:190 +0x41d fp=0xc000373af0 sp=0xc000373a28 pc=0x4251cfd
fyne.io/fyne/v2/internal/driver.walkObjectTree.func1(...)
	/Users/a/go/pkg/mod/github.com/fyne-io/fyne/v2@v2.1.4-0.20220514124826-61b61b441312/internal/driver/util.go:176
fyne.io/fyne/v2/internal/driver.walkObjectTree({0x45a5f30, 0xc00041e080}, 0x0, {0x0, 0x0}, {0x4?, 0x0?}, {0x373c00?, 0xc0?}, {0x43e4326?, ...}, ...)
	/Users/a/go/pkg/mod/github.com/fyne-io/fyne/v2@v2.1.4-0.20220514124826-61b61b441312/internal/driver/util.go:190 +0x41d fp=0xc000373bb8 sp=0xc000373af0 pc=0x4251cfd
fyne.io/fyne/v2/internal/driver.WalkVisibleObjectTree({0x45a5f30?, 0xc00041e080?}, 0x45a4940?, 0xc000096360?)
	/Users/a/go/pkg/mod/github.com/fyne-io/fyne/v2@v2.1.4-0.20220514124826-61b61b441312/internal/driver/util.go:134 +0x4c fp=0xc000373c20 sp=0xc000373bb8 pc=0x425188c
fyne.io/fyne/v2/internal/driver/common.(*Canvas).walkTree(0x43d07a4?, 0xc000412060, 0x0, 0xc000373d78)
	/Users/a/go/pkg/mod/github.com/fyne-io/fyne/v2@v2.1.4-0.20220514124826-61b61b441312/internal/driver/common/canvas.go:459 +0x165 fp=0xc000373cd8 sp=0xc000373c20 pc=0x4314525
fyne.io/fyne/v2/internal/driver/common.(*Canvas).WalkTrees(0xc00041a000, 0x4007791?, 0x0?)
	/Users/a/go/pkg/mod/github.com/fyne-io/fyne/v2@v2.1.4-0.20220514124826-61b61b441312/internal/driver/common/canvas.go:371 +0x3c fp=0xc000373d30 sp=0xc000373cd8 pc=0x431407c
fyne.io/fyne/v2/internal/driver/common.(*Canvas).EnsureMinSize(0xc00041a000)
	/Users/a/go/pkg/mod/github.com/fyne-io/fyne/v2@v2.1.4-0.20220514124826-61b61b441312/internal/driver/common/canvas.go:102 +0xf1 fp=0xc000373db0 sp=0xc000373d30 pc=0x4312d91
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow.func1()
	/Users/a/go/pkg/mod/github.com/fyne-io/fyne/v2@v2.1.4-0.20220514124826-61b61b441312/internal/driver/glfw/loop.go:195 +0x35 fp=0xc000373e00 sp=0xc000373db0 pc=0x43d3695
fyne.io/fyne/v2/internal/driver/glfw.(*window).RunWithContext(0xc0003de620?, 0xc000373e30)
	/Users/a/go/pkg/mod/github.com/fyne-io/fyne/v2@v2.1.4-0.20220514124826-61b61b441312/internal/driver/glfw/window.go:903 +0x4f fp=0xc000373e20 sp=0xc000373e00 pc=0x43db42f
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow(0xc000373eb0?, 0x3?)
	/Users/a/go/pkg/mod/github.com/fyne-io/fyne/v2@v2.1.4-0.20220514124826-61b61b441312/internal/driver/glfw/loop.go:194 +0x4a fp=0xc000373e58 sp=0xc000373e20 pc=0x43d362a
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).drawSingleFrame(0xc000373f90?)
	/Users/a/go/pkg/mod/github.com/fyne-io/fyne/v2@v2.1.4-0.20220514124826-61b61b441312/internal/driver/glfw/loop.go:102 +0x1cb fp=0xc000373ef8 sp=0xc000373e58 pc=0x43d2e0b
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread.func1()
	/Users/a/go/pkg/mod/github.com/fyne-io/fyne/v2@v2.1.4-0.20220514124826-61b61b441312/internal/driver/glfw/loop.go:250 +0x1a6 fp=0xc000373fe0 sp=0xc000373ef8 pc=0x43d3b66
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000373fe8 sp=0xc000373fe0 pc=0x4066481
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread
	/Users/a/go/pkg/mod/github.com/fyne-io/fyne/v2@v2.1.4-0.20220514124826-61b61b441312/internal/driver/glfw/loop.go:226 +0xea

goroutine 1 [select, locked to thread]:
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).runGL(0xc0003de620)
	/Users/a/go/pkg/mod/github.com/fyne-io/fyne/v2@v2.1.4-0.20220514124826-61b61b441312/internal/driver/glfw/loop.go:121 +0x19f
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).Run(0xc000418000?)
	/Users/a/go/pkg/mod/github.com/fyne-io/fyne/v2@v2.1.4-0.20220514124826-61b61b441312/internal/driver/glfw/driver.go:160 +0x33
fyne.io/fyne/v2/internal/driver/glfw.(*window).ShowAndRun(0xc000418000)
	/Users/a/go/pkg/mod/github.com/fyne-io/fyne/v2@v2.1.4-0.20220514124826-61b61b441312/internal/driver/glfw/window.go:230 +0x2c
main.main()
	/Users/a/Desktop/Study/fyne-race/main.go:41 +0x1b7

goroutine 6 [syscall]:
syscall.syscall6(0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/sys_darwin.go:44 +0x6a
golang.org/x/sys/unix.kevent(0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/Users/a/go/pkg/mod/golang.org/x/sys@v0.0.0-20210809222454-d867a43fc93e/unix/zsyscall_darwin_amd64.go:276 +0x52
golang.org/x/sys/unix.Kevent(0x0?, {0x0?, 0x0?, 0x0?}, {0xc000064678?, 0x400acc5?, 0x0?}, 0x0?)
	/Users/a/go/pkg/mod/golang.org/x/sys@v0.0.0-20210809222454-d867a43fc93e/unix/syscall_bsd.go:429 +0x3c
github.com/fsnotify/fsnotify.read(0x3?, {0xc000064678?, 0xa?, 0xa}, 0x4af43a0?)
	/Users/a/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.1/kqueue.go:512 +0x3f
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc0000964e0)
	/Users/a/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.1/kqueue.go:275 +0xa5
created by github.com/fsnotify/fsnotify.NewWatcher
	/Users/a/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.1/kqueue.go:63 +0x1c5

goroutine 7 [chan receive]:
fyne.io/fyne/v2/app.watchFile.func1()
	/Users/a/go/pkg/mod/github.com/fyne-io/fyne/v2@v2.1.4-0.20220514124826-61b61b441312/app/settings_desktop.go:43 +0x6c
created by fyne.io/fyne/v2/app.watchFile
	/Users/a/go/pkg/mod/github.com/fyne-io/fyne/v2@v2.1.4-0.20220514124826-61b61b441312/app/settings_desktop.go:42 +0x10a

goroutine 19 [select]:
fyne.io/fyne/v2/internal/async.(*UnboundedFuncChan).processing(0xc000406030)
	/Users/a/go/pkg/mod/github.com/fyne-io/fyne/v2@v2.1.4-0.20220514124826-61b61b441312/internal/async/chan_func.go:45 +0xda
created by fyne.io/fyne/v2/internal/async.NewUnboundedFuncChan
	/Users/a/go/pkg/mod/github.com/fyne-io/fyne/v2@v2.1.4-0.20220514124826-61b61b441312/internal/async/chan_func.go:22 +0xf8

goroutine 20 [chan receive]:
fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue(0x0?)
	/Users/a/go/pkg/mod/github.com/fyne-io/fyne/v2@v2.1.4-0.20220514124826-61b61b441312/internal/driver/common/window.go:34 +0x4d
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1
	/Users/a/go/pkg/mod/github.com/fyne-io/fyne/v2@v2.1.4-0.20220514124826-61b61b441312/internal/driver/glfw/window.go:942 +0x136

goroutine 21 [runnable]:
fyne.io/fyne/v2/app.(*settings).Theme(0x44b88f5?)
	/Users/a/go/pkg/mod/github.com/fyne-io/fyne/v2@v2.1.4-0.20220514124826-61b61b441312/app/settings.go:63 +0xa2
fyne.io/fyne/v2/canvas.NewText({0xc001433e4c, 0x2}, {0x45a22a0?, 0x47e05e0})
	/Users/a/go/pkg/mod/github.com/fyne-io/fyne/v2@v2.1.4-0.20220514124826-61b61b441312/canvas/text.go:45 +0x5f
main.main.func1()
	/Users/a/Desktop/Study/fyne-race/main.go:32 +0x198
created by main.main
	/Users/a/Desktop/Study/fyne-race/main.go:20 +0x185
exit status 2
```

I am not sure how the problem can be fixed by documentation.

fyne do not expose the main thread like other ui framework, if the ui methods are not concurrent safe, race conditions exist no matter what the user do.

Imho, the simplest solution is to add a non blocking runOnMain function to restrict ui call on main thread.

**Comment by changkun** [comment]
> I am not sure how the problem can be fixed by documentation.

It is a bit difficult to understand when a real code will need to do that much update on the canvas and call Refresh that frequently. This is potentially discouraged: https://staticcheck.io/docs/checks#SA1004 

"Fixed by documentation" means that this is an assumption and potential advice to guide people to avoid writing code like this. 

> fyne do not expose the main thread like other ui framework, if the ui methods are not concurrent safe, race conditions exist no matter what the user do.
> Imho, the simplest solution is to add a non blocking runOnMain function to restrict ui call on main thread.

Expose main thread was previously proposed in https://github.com/fyne-io/fyne/issues/2716. IMHO that exposing the mainthread is not helpful and very difficult to use properly.

I think you may refer to the rendering thread, not the main thread. They are different in fyne in the current implementation.

**Comment by AkiSakurai** [comment]
Alright, lower the update frequency do make the problem disappear. Seems very unlikely that the rendering thread will
access the same variable in user thread at the same time if we update ui at normal refresh rate.

**Comment by andydotxyz** [comment]
There are some issues as discussed above, but also this is not the fastest version of the code you are writing.
When adding a lot of items to a container it is better to make the list of items then set them all in one go - much faster.

The fractals demo does do some async but it is updating images/rasters IIRC which are special cases.
