### ISSUE TITLE
Crash when using Chinese IME

### ISSUE THREAD

**Issue by yeziyezi** [fyne-io/fyne#3213]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Crash when typing more Chinese characters in vbox entry

### How to reproduce

1. run the code
2. typing long chinese character in one time
3. the app crash

### Screenshots

![image](https://user-images.githubusercontent.com/19251487/185798729-b954686b-eede-449e-b1ac-0ac04f6905f0.png)
![image](https://user-images.githubusercontent.com/19251487/185798745-0049d0b1-7a59-4101-9a10-67fa65000637.png)

### Example code

```go
a := app.New()
	w := a.NewWindow("Fyne")

	w1Binding := binding.NewString()
	c := container.NewVBox(widget.NewLabelWithData(w1Binding), widget.NewEntryWithData(w1Binding))
	w.SetContent(c)
	w.Resize(fyne.Size{
		Width:  500,
		Height: 300,
	})
	w.Show()
	a.Run()
```

### Fyne version

2.2.3

### Go compiler version

1.19

### Operating system

Windows

### Operating system version

windows11

### Additional Information

error message:
```
panic: runtime error: slice bounds out of range [7:6]

goroutine 20 [running]:
fyne.io/fyne/v2/widget.(*RichText).insertAt(0xc00048c000, 0x7, {0xc0000f1f30, 0x1})
        C:/Users/10158/go/pkg/mod/fyne.io/fyne/v2@v2.2.3/widget/richtext.go:222 +0x2be
fyne.io/fyne/v2/widget.(*Entry).TypedRune(0xc0000b81e0, 0x73)
        C:/Users/10158/go/pkg/mod/fyne.io/fyne/v2@v2.2.3/widget/entry.go:738 +0x11b
fyne.io/fyne/v2/internal/driver/glfw.(*window).processCharInput.func1()
        C:/Users/10158/go/pkg/mod/fyne.io/fyne/v2@v2.2.3/internal/driver/glfw/window.go:782 +0x25
fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue(0x0?)
        C:/Users/10158/go/pkg/mod/fyne.io/fyne/v2@v2.2.3/internal/driver/common/window.go:35 +0x3e
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1
        C:/Users/10158/go/pkg/mod/fyne.io/fyne/v2@v2.2.3/internal/driver/glfw/window.go:942 +0x136
exit status 2
```

**Comment by QIN2DIM** [comment]
```go
package main

import (
	"fmt"
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/data/binding"
	"fyne.io/fyne/v2/widget"
)

func main() {
	panel := app.New()

	win := panel.NewWindow("Fyne")
	win.Resize(fyne.NewSize(500, 300))

	w1Binding := binding.NewString()

	// CanvasEntry
	entry := widget.NewEntry()
	entry.OnChanged = func(s string) {
		err := w1Binding.Set(s)
		if err != nil {
			fmt.Printf("Failed to set binding string - %s", s)
		}
	}

	// Canvas bind label
	label := widget.NewLabelWithData(w1Binding)

	content := container.NewVBox(label, entry)
	win.SetContent(content)
	
	win.ShowAndRun()
}



```

**Comment by andydotxyz** [comment]
Because the developers don't have the setup for Chinese input can you please provide some code that replicates this?
The step "typing long chinese character in one time" is not something we know how to do without more information.

**Comment by QIN2DIM** [comment]
I have found in some tests that it does crash if I use the above writing style. But I don't think the root problem is "typing too long text at once".

1. √ Copy text from elsewhere and enter Entry.
2. √ Indirectly modify the value displayed in the Entry widget by updating the binding object via goroutine.
3. ... Enter text using Chinese IME.

It only crashes in the third case.

**Comment by yeziyezi** [comment]
> Because the developers don't have the setup for Chinese input can you please provide some code that replicates this? The step "typing long chinese character in one time" is not something we know how to do without more information.

This bug need Chinese input method to replicate.

Under normal circumstances ,change to the Chinese input mode,type some words,the input method will show you  some choice.
![image](https://user-images.githubusercontent.com/19251487/185917056-38c8f910-caf4-4e70-8c04-b8fd88a448dc.png)
then press 1,the words selected will eval to editor(or input box)
![image](https://user-images.githubusercontent.com/19251487/185917116-ec7dfe97-7dbb-4d31-9f05-b692f85cac70.png)

To replicates this bug, the input method need change to Chinese input mode.
Run the code above,fyne will show a input box. 
type some words long enough (for example 'aaaaaaaaaaaaa' ), 
![image](https://user-images.githubusercontent.com/19251487/185918883-ebdf4f0e-3e6e-4a0f-81db-25ed3d11b85f.png)
press 1 , app will crash.

If the Chinese words selected not long enough ,like two or three,app will not crash.

**Comment by QIN2DIM** [comment]
https://user-images.githubusercontent.com/62018067/185923028-74377660-a67e-4125-9a70-5b48fa8cf838.mp4

**Comment by yeziyezi** [comment]
> Because the developers don't have the setup for Chinese input can you please provide some code that replicates this? The step "typing long chinese character in one time" is not something we know how to do without more information.

Here is the code 
```go
import (
	"fyne.io/fyne/v2/data/binding"
	"fyne.io/fyne/v2/test"
	"fyne.io/fyne/v2/widget"
	"testing"
)

func Test(t *testing.T) {
	b := binding.NewString()
	entry := widget.NewEntryWithData(b)
	s := "一二三四五六七八九十"
	test.Type(entry, s)
	bstr, err := b.Get()
	if err != nil {
		t.Fatal(err)
	}
	if s != bstr {
		t.Fatal("string not equals,bstr=", bstr)
	}
}
```

Got error:
```
=== RUN   Test
--- FAIL: Test (0.00s)
panic: runtime error: slice bounds out of range [6:5] [recovered]
	panic: runtime error: slice bounds out of range [6:5]

goroutine 22 [running]:
testing.tRunner.func1.2({0x4445380, 0xc0000ba1f8})
	/Users/lirunze/go/go1.19/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
	/Users/lirunze/go/go1.19/src/testing/testing.go:1399 +0x39f
panic({0x4445380, 0xc0000ba1f8})
	/Users/lirunze/go/go1.19/src/runtime/panic.go:884 +0x212
fyne.io/fyne/v2/widget.(*RichText).insertAt(0xc00007e000, 0x6, {0xc0000e3db0, 0x3})
	/Users/lirunze/GolandProjects/fyne/widget/richtext.go:222 +0x2be
fyne.io/fyne/v2/widget.(*Entry).TypedRune(0xc0003e4000, 0x4e5d)
	/Users/lirunze/GolandProjects/fyne/widget/entry.go:740 +0x11b
fyne.io/fyne/v2/test.typeChars(...)
	/Users/lirunze/GolandProjects/fyne/test/test.go:311
fyne.io/fyne/v2/test.Type({0x454b0a0, 0xc0003e4000}, {0x448af0c, 0x1e})
	/Users/lirunze/GolandProjects/fyne/test/test.go:232 +0xde
fyne.io/fyne/v2/cmd/fyne_demo.Test(0xc0000936c0)
	/Users/lirunze/GolandProjects/fyne/cmd/fyne_demo/main_test.go:14 +0xb6
testing.tRunner(0xc0000936c0, 0x44b1c50)
	/Users/lirunze/go/go1.19/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	/Users/lirunze/go/go1.19/src/testing/testing.go:1493 +0x35f

```

with --race parameter,I go this error:
```
WARNING: DATA RACE
Read at 0x00c00007e0c0 by goroutine 10:
  fyne.io/fyne/v2/widget.(*Entry).Validate()
      /Users/lirunze/GolandProjects/fyne/widget/entry_validation.go:15 +0x44
  fyne.io/fyne/v2/widget.(*Entry).updateFromData()
      /Users/lirunze/GolandProjects/fyne/widget/entry.go:1133 +0xc9
  fyne.io/fyne/v2/widget.(*Entry).updateFromData-fm()
      <autogenerated>:1 +0x4d
  fyne.io/fyne/v2/widget.(*basicBinder).Bind.func1()
      /Users/lirunze/GolandProjects/fyne/widget/bind_helper.go:24 +0x6b
  fyne.io/fyne/v2/data/binding.(*listener).DataChanged()
      /Users/lirunze/GolandProjects/fyne/data/binding/binding.go:56 +0x3d
  fyne.io/fyne/v2/data/binding.DataListener.DataChanged-fm()
      <autogenerated>:1 +0x48
  fyne.io/fyne/v2/data/binding.queueItem.func1.1()
      /Users/lirunze/GolandProjects/fyne/data/binding/queue.go:19 +0x76

Previous write at 0x00c00007e0c0 by goroutine 8:
  fyne.io/fyne/v2/widget.(*Entry).Bind()
      /Users/lirunze/GolandProjects/fyne/widget/entry.go:144 +0x15a
  fyne.io/fyne/v2/widget.NewEntryWithData()
      /Users/lirunze/GolandProjects/fyne/widget/entry.go:106 +0xd0
  fyne.io/fyne/v2/cmd/fyne_demo.Test()
      /Users/lirunze/GolandProjects/fyne/cmd/fyne_demo/main_test.go:12 +0x14d
  testing.tRunner()
      /Users/lirunze/go/go1.19/src/testing/testing.go:1446 +0x216
  testing.(*T).Run.func1()
      /Users/lirunze/go/go1.19/src/testing/testing.go:1493 +0x47
```

I tried to replace string ```s``` to ```1234567899abcabfabdajsbdajbdajsd``` ,I go data race too.
```go
func Test(t *testing.T) {
	b := binding.NewString()
	entry := widget.NewEntryWithData(b)
	s := "1234567899abcabfabdajsbdajbdajsd"
	test.Type(entry, s)
	bstr, err := b.Get()
	if err != nil {
		t.Fatal(err)
	}
	if s != bstr {
		t.Fatal("string not equals,bstr=", bstr)
	}
}
```
```
WARNING: DATA RACE
Read at 0x00c00038a0c0 by goroutine 10:
  fyne.io/fyne/v2/widget.(*Entry).Validate()
      /Users/lirunze/GolandProjects/fyne/widget/entry_validation.go:15 +0x44
  fyne.io/fyne/v2/widget.(*Entry).updateFromData()
      /Users/lirunze/GolandProjects/fyne/widget/entry.go:1133 +0xc9
  fyne.io/fyne/v2/widget.(*Entry).updateFromData-fm()
      <autogenerated>:1 +0x4d
  fyne.io/fyne/v2/widget.(*basicBinder).Bind.func1()
      /Users/lirunze/GolandProjects/fyne/widget/bind_helper.go:24 +0x6b
  fyne.io/fyne/v2/data/binding.(*listener).DataChanged()
      /Users/lirunze/GolandProjects/fyne/data/binding/binding.go:56 +0x3d
  fyne.io/fyne/v2/data/binding.DataListener.DataChanged-fm()
      <autogenerated>:1 +0x48
  fyne.io/fyne/v2/data/binding.queueItem.func1.1()
      /Users/lirunze/GolandProjects/fyne/data/binding/queue.go:19 +0x76

Previous write at 0x00c00038a0c0 by goroutine 8:
  fyne.io/fyne/v2/widget.(*Entry).Bind()
      /Users/lirunze/GolandProjects/fyne/widget/entry.go:144 +0x15a
  fyne.io/fyne/v2/widget.NewEntryWithData()
      /Users/lirunze/GolandProjects/fyne/widget/entry.go:106 +0xd0
  fyne.io/fyne/v2/cmd/fyne_demo.Test()
      /Users/lirunze/GolandProjects/fyne/cmd/fyne_demo/main_test.go:12 +0x14d
  testing.tRunner()
      /Users/lirunze/go/go1.19/src/testing/testing.go:1446 +0x216
  testing.(*T).Run.func1()
      /Users/lirunze/go/go1.19/src/testing/testing.go:1493 +0x47

```

**Comment by andydotxyz** [comment]
> Here is the code

Thanks, that is very helpful.
Unfortunately running the test locally did not crash/fail. Do you have a `FYNE_FONT` variable set that I need to set up as well?

**Comment by QIN2DIM** [comment]
@andydotxyz 

https://github.com/QIN2DIM/fyne-poems/tree/main/theme

**Comment by yeziyezi** [comment]
> > Here is the code
> 
> Thanks, that is very helpful. Unfortunately running the test locally did not crash/fail. Do you have a `FYNE_FONT` variable set that I need to set up as well?

No ```FYNE_FONT``` variable set.

I tried on macos 10.15 with go1.18, got the same error.

**Comment by andydotxyz** [comment]
I believe this was fixed with the new text handling subsystem. Please do re-open if you can replicate the issue with Fyne v2.6.1
