### ISSUE TITLE
Panic when opening and closing windows quickly

### ISSUE THREAD

**Issue by Cookie04DE** [fyne-io/fyne#3280]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

The below code panics.

### How to reproduce

1. Use the following code:
```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.NewWithID("test")
	go main2(a)
	a.Run()
}

func main2(a fyne.App) {
	w := a.NewWindow("Window")
	w.SetContent(widget.NewLabel("Hello"))
	w.Show()
	func() {
		w := a.NewWindow("Window 2")
		w.SetContent(widget.NewLabel("Hello 2"))
		w.Show()
	}()
	time.Sleep(time.Second) // this is a workaround for the first panic
	w.Close()
}
```
with the following `go.mod`:
```
module github.com/Cookie04DE/FyneTest

go 1.18

require fyne.io/fyne/v2 v2.2.3

require (
	fyne.io/systray v1.10.1-0.20220621085403-9a2652634e93 // indirect
	github.com/davecgh/go-spew v1.1.1 // indirect
	github.com/fredbi/uri v0.0.0-20181227131451-3dcfdacbaaf3 // indirect
	github.com/fsnotify/fsnotify v1.5.4 // indirect
	github.com/fyne-io/gl-js v0.0.0-20220119005834-d2da28d9ccfe // indirect
	github.com/fyne-io/glfw-js v0.0.0-20220120001248-ee7290d23504 // indirect
	github.com/fyne-io/image v0.0.0-20220602074514-4956b0afb3d2 // indirect
	github.com/go-gl/gl v0.0.0-20211210172815-726fda9656d6 // indirect
	github.com/go-gl/glfw/v3.3/glfw v0.0.0-20211213063430-748e38ca8aec // indirect
	github.com/godbus/dbus/v5 v5.1.0 // indirect
	github.com/goki/freetype v0.0.0-20181231101311-fa8a33aabaff // indirect
	github.com/gopherjs/gopherjs v1.17.2 // indirect
	github.com/jsummers/gobmp v0.0.0-20151104160322-e2ba15ffa76e // indirect
	github.com/pmezard/go-difflib v1.0.0 // indirect
	github.com/srwiley/oksvg v0.0.0-20200311192757-870daf9aa564 // indirect
	github.com/srwiley/rasterx v0.0.0-20200120212402-85cb7272f5e9 // indirect
	github.com/stretchr/testify v1.8.0 // indirect
	github.com/tevino/abool v1.2.0 // indirect
	github.com/yuin/goldmark v1.4.0 // indirect
	golang.org/x/image v0.0.0-20220601225756-64ec528b34cd // indirect
	golang.org/x/mobile v0.0.0-20211207041440-4e6c2922fdee // indirect
	golang.org/x/net v0.0.0-20211112202133-69e39bad7dc2 // indirect
	golang.org/x/sys v0.0.0-20220722155257-8c9f86f7a55f // indirect
	golang.org/x/text v0.3.7 // indirect
	gopkg.in/yaml.v3 v3.0.1 // indirect
	honnef.co/go/js/dom v0.0.0-20210725211120-f030747120f2 // indirect
)
```
2. Run it with `go run .`
3. See either one of the following panics:
The following panic is way more common than the one after it:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x100a06da8]

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.(*Window).SetCloseCallback(0x14000480600?, 0x14000002228?)
        /Users/cookie/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20211213063430-748e38ca8aec/window.go:799 +0x18
fyne.io/fyne/v2/internal/driver/glfw.(*window).create.func3()
        /Users/cookie/go/pkg/mod/fyne.io/fyne/v2@v2.2.3/internal/driver/glfw/window_desktop.go:690 +0x74
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).runGL(0x14000424620)
        /Users/cookie/go/pkg/mod/fyne.io/fyne/v2@v2.2.3/internal/driver/glfw/loop.go:129 +0x1dc
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).Run(0x140000021a0?)
        /Users/cookie/go/pkg/mod/fyne.io/fyne/v2@v2.2.3/internal/driver/glfw/driver.go:164 +0x3c
fyne.io/fyne/v2/app.(*fyneApp).Run(0x100a45e11?)
        /Users/cookie/go/pkg/mod/fyne.io/fyne/v2@v2.2.3/app/app.go:68 +0x80
main.main()
        /Users/cookie/Documents/Programmieren/Go/FyneTest/main.go:12 +0x90
exit status 2
```
This one is more rare:
```
SIGTRAP: trace trap
PC=0x1a167b5e8 m=0 sigcode=0
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x1012ba598, 0x1400029fd58)
        /usr/local/go/src/runtime/cgocall.go:158 +0x54 fp=0x1400029fd20 sp=0x1400029fce0 pc=0x100eea6a4
github.com/go-gl/glfw/v3.3/glfw._Cfunc_glfwPollEvents()
        _cgo_gotypes.go:1503 +0x34 fp=0x1400029fd50 sp=0x1400029fd20 pc=0x1012847d4
github.com/go-gl/glfw/v3.3/glfw.PollEvents()
        /Users/cookie/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20211213063430-748e38ca8aec/window.go:964 +0x1c fp=0x1400029fd60 sp=0x1400029fd50 pc=0x10128b33c
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).tryPollEvents(0x1400029fea8?)
        /Users/cookie/go/pkg/mod/fyne.io/fyne/v2@v2.2.3/internal/driver/glfw/loop_desktop.go:39 +0x38 fp=0x1400029fd80 sp=0x1400029fd60 pc=0x101295008
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).runGL(0x1400039c620)
        /Users/cookie/go/pkg/mod/fyne.io/fyne/v2@v2.2.3/internal/driver/glfw/loop.go:134 +0x1fc fp=0x1400029fee0 sp=0x1400029fd80 pc=0x10129436c
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).Run(0x140000021a0?)
        /Users/cookie/go/pkg/mod/fyne.io/fyne/v2@v2.2.3/internal/driver/glfw/driver.go:164 +0x3c fp=0x1400029ff10 sp=0x1400029fee0 pc=0x101292fdc
fyne.io/fyne/v2/app.(*fyneApp).Run(0x1012c9e11?)
        /Users/cookie/go/pkg/mod/fyne.io/fyne/v2@v2.2.3/app/app.go:68 +0x80 fp=0x1400029ff30 sp=0x1400029ff10 pc=0x1012a4cd0
main.main()
        /Users/cookie/Documents/Programmieren/Go/FyneTest/main.go:12 +0x90 fp=0x1400029ff70 sp=0x1400029ff30 pc=0x1012a7c00
runtime.main()
        /usr/local/go/src/runtime/proc.go:250 +0x24c fp=0x1400029ffd0 sp=0x1400029ff70 pc=0x100f1da9c
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x1400029ffd0 sp=0x1400029ffd0 pc=0x100f4ac04

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x1400005afa0 sp=0x1400005af80 pc=0x100f1de64
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:369
runtime.forcegchelper()
        /usr/local/go/src/runtime/proc.go:302 +0xac fp=0x1400005afd0 sp=0x1400005afa0 pc=0x100f1dcfc
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x1400005afd0 sp=0x1400005afd0 pc=0x100f4ac04
created by runtime.init.6
        /usr/local/go/src/runtime/proc.go:290 +0x24

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x1400005b770 sp=0x1400005b750 pc=0x100f1de64
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:369
runtime.bgsweep(0x0?)
        /usr/local/go/src/runtime/mgcsweep.go:297 +0x10c fp=0x1400005b7b0 sp=0x1400005b770 pc=0x100f0b13c
runtime.gcenable.func1()
        /usr/local/go/src/runtime/mgc.go:178 +0x28 fp=0x1400005b7d0 sp=0x1400005b7b0 pc=0x100eff918
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x1400005b7d0 sp=0x1400005b7d0 pc=0x100f4ac04
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:178 +0x74

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x140000340e0?, 0x1013b65f0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x1400005bf50 sp=0x1400005bf30 pc=0x100f1de64
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:369
runtime.(*scavengerState).park(0x1019b8060)
        /usr/local/go/src/runtime/mgcscavenge.go:389 +0x5c fp=0x1400005bf80 sp=0x1400005bf50 pc=0x100f0908c
runtime.bgscavenge(0x0?)
        /usr/local/go/src/runtime/mgcscavenge.go:622 +0xac fp=0x1400005bfb0 sp=0x1400005bf80 pc=0x100f0969c
runtime.gcenable.func2()
        /usr/local/go/src/runtime/mgc.go:179 +0x28 fp=0x1400005bfd0 sp=0x1400005bfb0 pc=0x100eff8b8
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x1400005bfd0 sp=0x1400005bfd0 pc=0x100f4ac04
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:179 +0xb8

goroutine 18 [finalizer wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000056580 sp=0x14000056560 pc=0x100f1de64
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:369
runtime.runfinq()
        /usr/local/go/src/runtime/mfinal.go:180 +0x120 fp=0x140000567d0 sp=0x14000056580 pc=0x100efeb40
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140000567d0 sp=0x140000567d0 pc=0x100f4ac04
created by runtime.createfing
        /usr/local/go/src/runtime/mfinal.go:157 +0x84

goroutine 19 [syscall]:
syscall.syscall6(0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/sys_darwin.go:44 +0x64 fp=0x14000056c30 sp=0x14000056b70 pc=0x100f47454
golang.org/x/sys/unix.kevent(0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /Users/cookie/go/pkg/mod/golang.org/x/sys@v0.0.0-20220722155257-8c9f86f7a55f/unix/zsyscall_darwin_arm64.go:276 +0x58 fp=0x14000056ca0 sp=0x14000056c30 pc=0x1012a1838
golang.org/x/sys/unix.Kevent(0x0?, {0x0?, 0x0?, 0x0?}, {0x14000056e68?, 0x1012a36bc?, 0x0?}, 0x0?)
        /Users/cookie/go/pkg/mod/golang.org/x/sys@v0.0.0-20220722155257-8c9f86f7a55f/unix/syscall_bsd.go:399 +0x40 fp=0x14000056ce0 sp=0x14000056ca0 pc=0x1012a1780
github.com/fsnotify/fsnotify.read(0x0?, {0x14000056e68?, 0x0?, 0xa}, 0x0?)
        /Users/cookie/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.4/kqueue.go:525 +0x44 fp=0x14000056d40 sp=0x14000056ce0 pc=0x1012a46f4
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0x1400012c420)
        /Users/cookie/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.4/kqueue.go:288 +0x74 fp=0x14000056fb0 sp=0x14000056d40 pc=0x1012a36e4
github.com/fsnotify/fsnotify.NewWatcher.func1()
        /Users/cookie/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.4/kqueue.go:63 +0x28 fp=0x14000056fd0 sp=0x14000056fb0 pc=0x1012a2328
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000056fd0 sp=0x14000056fd0 pc=0x100f4ac04
created by github.com/fsnotify/fsnotify.NewWatcher
        /Users/cookie/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.4/kqueue.go:63 +0x1a8

goroutine 20 [chan receive]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000057690 sp=0x14000057670 pc=0x100f1de64
runtime.chanrecv(0x14000102240, 0x140000577b0, 0x1)
        /usr/local/go/src/runtime/chan.go:583 +0x454 fp=0x14000057720 sp=0x14000057690 pc=0x100eed434
runtime.chanrecv2(0x0?, 0x0?)
        /usr/local/go/src/runtime/chan.go:447 +0x14 fp=0x14000057750 sp=0x14000057720 pc=0x100eecfc4
fyne.io/fyne/v2/app.watchFile.func1()
        /Users/cookie/go/pkg/mod/fyne.io/fyne/v2@v2.2.3/app/settings_desktop.go:43 +0x60 fp=0x140000577d0 sp=0x14000057750 pc=0x1012a6f40
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140000577d0 sp=0x140000577d0 pc=0x100f4ac04
created by fyne.io/fyne/v2/app.watchFile
        /Users/cookie/go/pkg/mod/fyne.io/fyne/v2@v2.2.3/app/settings_desktop.go:42 +0x11c

goroutine 21 [syscall]:
syscall.syscall6(0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/sys_darwin.go:44 +0x64 fp=0x14000057c30 sp=0x14000057b70 pc=0x100f47454
golang.org/x/sys/unix.kevent(0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /Users/cookie/go/pkg/mod/golang.org/x/sys@v0.0.0-20220722155257-8c9f86f7a55f/unix/zsyscall_darwin_arm64.go:276 +0x58 fp=0x14000057ca0 sp=0x14000057c30 pc=0x1012a1838
golang.org/x/sys/unix.Kevent(0x0?, {0x0?, 0x0?, 0x0?}, {0x14000057e68?, 0x1012a36bc?, 0x0?}, 0x0?)
        /Users/cookie/go/pkg/mod/golang.org/x/sys@v0.0.0-20220722155257-8c9f86f7a55f/unix/syscall_bsd.go:399 +0x40 fp=0x14000057ce0 sp=0x14000057ca0 pc=0x1012a1780
github.com/fsnotify/fsnotify.read(0x0?, {0x14000057e68?, 0x0?, 0xa}, 0x0?)
        /Users/cookie/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.4/kqueue.go:525 +0x44 fp=0x14000057d40 sp=0x14000057ce0 pc=0x1012a46f4
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0x1400012c5a0)
        /Users/cookie/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.4/kqueue.go:288 +0x74 fp=0x14000057fb0 sp=0x14000057d40 pc=0x1012a36e4
github.com/fsnotify/fsnotify.NewWatcher.func1()
        /Users/cookie/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.4/kqueue.go:63 +0x28 fp=0x14000057fd0 sp=0x14000057fb0 pc=0x1012a2328
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000057fd0 sp=0x14000057fd0 pc=0x100f4ac04
created by github.com/fsnotify/fsnotify.NewWatcher
        /Users/cookie/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.4/kqueue.go:63 +0x1a8

goroutine 22 [chan receive]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000058690 sp=0x14000058670 pc=0x100f1de64
runtime.chanrecv(0x14000102360, 0x140000587b0, 0x1)
        /usr/local/go/src/runtime/chan.go:583 +0x454 fp=0x14000058720 sp=0x14000058690 pc=0x100eed434
runtime.chanrecv2(0x0?, 0x0?)
        /usr/local/go/src/runtime/chan.go:447 +0x14 fp=0x14000058750 sp=0x14000058720 pc=0x100eecfc4
fyne.io/fyne/v2/app.watchFile.func1()
        /Users/cookie/go/pkg/mod/fyne.io/fyne/v2@v2.2.3/app/settings_desktop.go:43 +0x60 fp=0x140000587d0 sp=0x14000058750 pc=0x1012a6f40
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140000587d0 sp=0x140000587d0 pc=0x100f4ac04
created by fyne.io/fyne/v2/app.watchFile
        /Users/cookie/go/pkg/mod/fyne.io/fyne/v2@v2.2.3/app/settings_desktop.go:42 +0x11c

goroutine 23 [chan send]:
runtime.gopark(0x140001071e0?, 0x101161d88?, 0x28?, 0xfe?, 0x101293908?)
        /usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x1400011fdd0 sp=0x1400011fdb0 pc=0x100f1de64
runtime.chansend(0x140001020c0, 0x1400011fec0, 0x1, 0x0?)
        /usr/local/go/src/runtime/chan.go:259 +0x43c fp=0x1400011fe60 sp=0x1400011fdd0 pc=0x100eec67c
runtime.chansend1(0x101991340?, 0x10?)
        /usr/local/go/src/runtime/chan.go:145 +0x18 fp=0x1400011fe90 sp=0x1400011fe60 pc=0x100eec228
fyne.io/fyne/v2/internal/driver/glfw.runOnMain(0x14000680000)
        /Users/cookie/go/pkg/mod/fyne.io/fyne/v2@v2.2.3/internal/driver/glfw/loop.go:69 +0x170 fp=0x1400011ff00 sp=0x1400011fe90 pc=0x101293b70
fyne.io/fyne/v2/internal/driver/glfw.(*window).RescaleContext(0x14000426000)
        /Users/cookie/go/pkg/mod/fyne.io/fyne/v2@v2.2.3/internal/driver/glfw/window.go:909 +0x60 fp=0x1400011ff30 sp=0x1400011ff00 pc=0x10129bfc0
fyne.io/fyne/v2/internal/driver/glfw.(*window).SetContent(0x14000426000, {0x10148fd78, 0x1400043a000})
        /Users/cookie/go/pkg/mod/fyne.io/fyne/v2@v2.2.3/internal/driver/glfw/window.go:264 +0x168 fp=0x1400011ff70 sp=0x1400011ff30 pc=0x1012976f8
main.main2({0x101490c48, 0x1400039c690})
        /Users/cookie/Documents/Programmieren/Go/FyneTest/main.go:17 +0x6c fp=0x1400011ffb0 sp=0x1400011ff70 pc=0x1012a7cec
main.main.func1()
        /Users/cookie/Documents/Programmieren/Go/FyneTest/main.go:11 +0x2c fp=0x1400011ffd0 sp=0x1400011ffb0 pc=0x1012a7c4c
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x1400011ffd0 sp=0x1400011ffd0 pc=0x100f4ac04
created by main.main
        /Users/cookie/Documents/Programmieren/Go/FyneTest/main.go:11 +0x80

goroutine 34 [select, locked to thread]:
runtime.gopark(0x14000058f88?, 0x4?, 0x60?, 0x93?, 0x14000058f30?)
        /usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000492dc0 sp=0x14000492da0 pc=0x100f1de64
runtime.selectgo(0x14000492f88, 0x14000058f28, 0x1012cb7a9?, 0x0, 0x14000058f38?, 0x1)
        /usr/local/go/src/runtime/select.go:328 +0x688 fp=0x14000492ee0 sp=0x14000492dc0 pc=0x100f2dc48
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread.func1()
        /Users/cookie/go/pkg/mod/fyne.io/fyne/v2@v2.2.3/internal/driver/glfw/loop.go:230 +0xac fp=0x14000492fd0 sp=0x14000492ee0 pc=0x101294c9c
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000492fd0 sp=0x14000492fd0 pc=0x100f4ac04
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread
        /Users/cookie/go/pkg/mod/fyne.io/fyne/v2@v2.2.3/internal/driver/glfw/loop.go:226 +0xf0

goroutine 35 [select]:
runtime.gopark(0x14000430758?, 0x2?, 0xc8?, 0x5?, 0x140004306f0?)
        /usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x1400048ed70 sp=0x1400048ed50 pc=0x100f1de64
runtime.selectgo(0x1400048ef58, 0x140004306ec, 0x0?, 0x0, 0x0?, 0x1)
        /usr/local/go/src/runtime/select.go:328 +0x688 fp=0x1400048ee90 sp=0x1400048ed70 pc=0x100f2dc48
fyne.io/fyne/v2/internal/async.(*UnboundedFuncChan).processing(0x1400040a090)
        /Users/cookie/go/pkg/mod/fyne.io/fyne/v2@v2.2.3/internal/async/chan_func.go:45 +0xc0 fp=0x1400048efb0 sp=0x1400048ee90 pc=0x1011714c0
fyne.io/fyne/v2/internal/async.NewUnboundedFuncChan.func1()
        /Users/cookie/go/pkg/mod/fyne.io/fyne/v2@v2.2.3/internal/async/chan_func.go:22 +0x28 fp=0x1400048efd0 sp=0x1400048efb0 pc=0x101171378
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x1400048efd0 sp=0x1400048efd0 pc=0x100f4ac04
created by fyne.io/fyne/v2/internal/async.NewUnboundedFuncChan
        /Users/cookie/go/pkg/mod/fyne.io/fyne/v2@v2.2.3/internal/async/chan_func.go:22 +0xfc

goroutine 36 [chan receive]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000430ec0 sp=0x14000430ea0 pc=0x100f1de64
runtime.chanrecv(0x14000428060, 0x14000430fa0, 0x1)
        /usr/local/go/src/runtime/chan.go:583 +0x454 fp=0x14000430f50 sp=0x14000430ec0 pc=0x100eed434
runtime.chanrecv2(0x0?, 0x0?)
        /usr/local/go/src/runtime/chan.go:447 +0x14 fp=0x14000430f80 sp=0x14000430f50 pc=0x100eecfc4
fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue(0x0?)
        /Users/cookie/go/pkg/mod/fyne.io/fyne/v2@v2.2.3/internal/driver/common/window.go:34 +0x48 fp=0x14000430fb0 sp=0x14000430f80 pc=0x1011c07d8
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1.1()
        /Users/cookie/go/pkg/mod/fyne.io/fyne/v2@v2.2.3/internal/driver/glfw/window.go:942 +0x28 fp=0x14000430fd0 sp=0x14000430fb0 pc=0x10129c4d8
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000430fd0 sp=0x14000430fd0 pc=0x100f4ac04
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1
        /Users/cookie/go/pkg/mod/fyne.io/fyne/v2@v2.2.3/internal/driver/glfw/window.go:942 +0x144

goroutine 37 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000431740 sp=0x14000431720 pc=0x100f1de64
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1235 +0xec fp=0x140004317d0 sp=0x14000431740 pc=0x100f01a7c
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140004317d0 sp=0x140004317d0 pc=0x100f4ac04
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1159 +0x28

goroutine 38 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000431f40 sp=0x14000431f20 pc=0x100f1de64
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1235 +0xec fp=0x14000431fd0 sp=0x14000431f40 pc=0x100f01a7c
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000431fd0 sp=0x14000431fd0 pc=0x100f4ac04
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1159 +0x28

goroutine 39 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000432740 sp=0x14000432720 pc=0x100f1de64
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1235 +0xec fp=0x140004327d0 sp=0x14000432740 pc=0x100f01a7c
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140004327d0 sp=0x140004327d0 pc=0x100f4ac04
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1159 +0x28

goroutine 40 [GC worker (idle)]:
runtime.gopark(0x1140c5480d1b6?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000432f40 sp=0x14000432f20 pc=0x100f1de64
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1235 +0xec fp=0x14000432fd0 sp=0x14000432f40 pc=0x100f01a7c
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000432fd0 sp=0x14000432fd0 pc=0x100f4ac04
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1159 +0x28

goroutine 50 [GC worker (idle)]:
runtime.gopark(0x1140c548099e3?, 0x1400039c620?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000058f40 sp=0x14000058f20 pc=0x100f1de64
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1235 +0xec fp=0x14000058fd0 sp=0x14000058f40 pc=0x100f01a7c
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000058fd0 sp=0x14000058fd0 pc=0x100f4ac04
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1159 +0x28

goroutine 41 [GC worker (idle)]:
runtime.gopark(0x1140c54809ab3?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000433740 sp=0x14000433720 pc=0x100f1de64
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1235 +0xec fp=0x140004337d0 sp=0x14000433740 pc=0x100f01a7c
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140004337d0 sp=0x140004337d0 pc=0x100f4ac04
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1159 +0x28

goroutine 51 [GC worker (idle)]:
runtime.gopark(0x1019e9360?, 0x1?, 0xad?, 0xc2?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x1400042c740 sp=0x1400042c720 pc=0x100f1de64
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1235 +0xec fp=0x1400042c7d0 sp=0x1400042c740 pc=0x100f01a7c
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x1400042c7d0 sp=0x1400042c7d0 pc=0x100f4ac04
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1159 +0x28

goroutine 42 [GC worker (idle)]:
runtime.gopark(0x1140c5480cec8?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000433f40 sp=0x14000433f20 pc=0x100f1de64
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1235 +0xec fp=0x14000433fd0 sp=0x14000433f40 pc=0x100f01a7c
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000433fd0 sp=0x14000433fd0 pc=0x100f4ac04
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1159 +0x28

r0      0x0
r1      0x0
r2      0x0
r3      0x0
r4      0x0
r5      0x0
r6      0x0
r7      0x0
r8      0x14d0667227ab0031
r9      0x14d0667227ab0031
r10     0xfffffffe617a9437
r11     0x0
r12     0x0
r13     0x10
r14     0x44f4
r15     0x44f4
r16     0xfffffffffffffff4
r17     0x1f8b6bf10
r18     0x0
r19     0x13ef48720
r20     0x141012c00
r21     0x1e8d87937
r22     0x1f8cda5e8
r23     0x11
r24     0xffffffffffffffff
r25     0x0
r26     0x1f4d27000
r27     0xffffffffffffffff
r28     0x1e8d891d2
r29     0x16ef1abe0
lr      0x8c0e8001a167b5e8
sp      0x16ef1aba0
pc      0x1a167b5e8
fault   0x1a167b5e8
exit status 2
```

### Example code

Please see above.

### Fyne version

2.2.3

### Go compiler version

`go1.19.1 darwin/arm64`

### Operating system

macOS

### Operating system version

macOS Monterey Version 12.6

**Comment by williambrode** [comment]
I'm seeing this on fyne v2.3.5 as well.  Same backtrace:

```
github.com/go-gl/glfw/v3.3/glfw.(*Window).SetCloseCallback(0x14000480600?, 0x14000002228?)
        /Users/cookie/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20211213063430-748e38ca8aec/window.go:799 +0x18
```

Use case is loading an infinite progress bar window during a file delete.  But in this case the delete was so fast (empty folder) I think it caused the crash.

**Comment by andydotxyz** [comment]
Please test against v2.4.0, as that is now the current release

**Comment by andydotxyz** [comment]
Seems to be resolved with fyne on develop
