### ISSUE TITLE
crash in widget.(*RichText).insertAt

### ISSUE THREAD

**Issue by secsys-go** [fyne-io/fyne#3293]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

We used the Fuzz engine to modify some Test(TestEntry_PasteUnicode) data, and then the following crash appeared. Triggered when the value of the exported member (e.CursorColumn) is greater than a certain capacity.

### How to reproduce

The simplified test code is in **Example code**

### Screenshots

CrashLog
```
panic: runtime error: slice bounds out of range [:33] with capacity 32 [recovered]
        panic: runtime error: slice bounds out of range [:33] with capacity 32

goroutine 63 [running]:
testing.tRunner.func1.2({0x87e8c0, 0xc000024120})
        /home/zjx/.local/go/src/testing/testing.go:1211 +0x24e
testing.tRunner.func1()
        /home/zjx/.local/go/src/testing/testing.go:1214 +0x218
panic({0x87e8c0, 0xc000024120})
        /home/zjx/.local/go/src/runtime/panic.go:1038 +0x215
fyne.io/fyne/v2/widget.(*RichText).insertAt(0xc000160580, 0x21, {0x8bfb90, 0x1c})
        /home/zjx/workspace/gowork/src/purelib/crashConfirm/fyne/widget/richtext.go:222 +0x2c6
fyne.io/fyne/v2/widget.(*Entry).pasteFromClipboard(0xc00000c1e0, {0x973e78, 0xc0007b5da0})
        /home/zjx/workspace/gowork/src/purelib/crashConfirm/fyne/widget/entry.go:855 +0x12e
fyne.io/fyne/v2/widget.(*Entry).registerShortcut.func3({0x9701e0, 0xc0007b5db0})
        /home/zjx/workspace/gowork/src/purelib/crashConfirm/fyne/widget/entry.go:891 +0x45
fyne.io/fyne/v2.(*ShortcutHandler).TypedShortcut(0xc00000c228, {0x9701e0, 0xc0007b5db0})
        /home/zjx/workspace/gowork/src/purelib/crashConfirm/fyne/shortcut.go:21 +0x77
fyne.io/fyne/v2/widget.(*Entry).TypedShortcut(...)
        /home/zjx/workspace/gowork/src/purelib/crashConfirm/fyne/widget/entry.go:750
fyne.io/fyne/v2/widget_test.TestEntry_PasteUnicode(0x0)
        /home/zjx/workspace/gowork/src/purelib/crashConfirm/fyne/widget/entry_test.go:892 +0xf9
```

### Example code

```go
//part of the Test Code
	e.SetText("000000n000000n000000n00")
	e.CursorColumn = 33

	clipboard := test.NewClipboard()
	clipboard.SetContent("thing {\n\titem: 'val测试'\n}")
	shortcut := &fyne.ShortcutPaste{Clipboard: clipboard}
	e.TypedShortcut(shortcut)
```

### Fyne version

commit 638ae24e4bebfc0b6dbaabf8db5807eeabfafc61 (HEAD -> master, origin/master, origin/HEAD)

### Go compiler version

1.17.8

### Operating system

Linux

### Operating system version

OS: Linux r920 4.15.0-159-generic #167-Ubuntu

**Comment by ChandanChainani** [comment]
@secsys-go this doesn't seem like an issue since cursor column will not be position beyond input text so if type text is of length 22 than `CursorColumn` would be 22

**Comment by andydotxyz** [comment]
> @secsys-go this doesn't seem like an issue since `CursorColumn` will not be position beyond input text so if type text is of length 21 than `CursorColumn` would be 22
> 
> The above example text is of length 23 then `CursorColumn` would be 24 it should not go beyond which is in the case

This is true, but we we should code carefully so that nothing can crash - any public API we have should handle bounds checks to avoid panic.
