### ISSUE TITLE
crash in widget.createList.func3

### ISSUE THREAD

**Issue by secsys-go** [fyne-io/fyne#3294]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

We used the Fuzz engine to modify some Test(TestList_OffsetChange) data, and then the following crash appeared. Occurs when the incoming float is NaN.

### How to reproduce

The simplified test code is in **Example code**

### Screenshots

CrashLog
```
panic: runtime error: index out of range [-9223372036854775808] [recovered]
        panic: runtime error: index out of range [-9223372036854775808]

goroutine 11 [running]:
testing.tRunner.func1.2({0x87e8c0, 0xc000025980})
        /home/zjx/.local/go/src/testing/testing.go:1211 +0x24e
testing.tRunner.func1()
        /home/zjx/.local/go/src/testing/testing.go:1214 +0x218
panic({0x87e8c0, 0xc000025980})
        /home/zjx/.local/go/src/runtime/panic.go:1038 +0x215
fyne.io/fyne/v2/widget.createList.func3(0x97ecf0, {0x97ba98, 0xc000020d80})
        /home/zjx/workspace/gowork/src/purelib/crashConfirm/fyne/widget/list_test.go:446 +0xa9
fyne.io/fyne/v2/widget.(*listLayout).setupListItem(0xc00012c2d0, 0xc000430e00, 0x8000000000000000)
        /home/zjx/workspace/gowork/src/purelib/crashConfirm/fyne/widget/list.go:412 +0x9b
fyne.io/fyne/v2/widget.(*listLayout).updateList(0xc00012c2d0, 0x0)
        /home/zjx/workspace/gowork/src/purelib/crashConfirm/fyne/widget/list.go:450 +0x3ad
fyne.io/fyne/v2/widget.(*listLayout).offsetUpdated(...)
        /home/zjx/workspace/gowork/src/purelib/crashConfirm/fyne/widget/list.go:396
fyne.io/fyne/v2/internal/widget.(*Scroll).updateOffset(0xc0004309a0, 0x0, 0x7fc00000)
        /home/zjx/workspace/gowork/src/purelib/crashConfirm/fyne/internal/widget/scroller.go:488 +0x1e9
fyne.io/fyne/v2/internal/widget.(*Scroll).scrollBy(0xc0004309a0, 0x0, 0x7fc00000)
        /home/zjx/workspace/gowork/src/purelib/crashConfirm/fyne/internal/widget/scroller.go:469 +0xc8
fyne.io/fyne/v2/internal/widget.(*Scroll).Scrolled(...)
        /home/zjx/workspace/gowork/src/purelib/crashConfirm/fyne/internal/widget/scroller.go:462
fyne.io/fyne/v2/widget.TestList_OffsetChange(0x0)
        /home/zjx/workspace/gowork/src/purelib/crashConfirm/fyne/widget/list_test.go:84 +0x11d
```

### Example code

```go
//part of the Test Code
	test.NewApp()
	defer test.NewApp()

	list := createList(1000)
	w := test.NewWindow(list)
	w.Resize(fyne.NewSize(200, float32(math.NaN())))

	assert.Equal(t, float32(0), list.offsetY)

	scroll := test.WidgetRenderer(list).(*listRenderer).scroller
	scroll.Scrolled(&fyne.ScrollEvent{Scrolled: fyne.NewDelta(0, float32(math.NaN()))})
```

### Fyne version

commit 638ae24e4bebfc0b6dbaabf8db5807eeabfafc61 (HEAD -> master, origin/master, origin/HEAD)

### Go compiler version

1.17.8

### Operating system

Linux

### Operating system version

OS: Linux r920 4.15.0-159-generic #167-Ubuntu

**Comment by andydotxyz** [comment]
This was resolved in the v2.3.0 release earlier this month.
