### ISSUE TITLE
Clipboard from menuItem doesn't work as expected in Plasma Wayland

### ISSUE THREAD

**Issue by IvoryJam** [fyne-io/fyne#3493]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

.Clipboard().Content() doesn't work if ran from MenuItem until the main window is focused. If the main window is closed it crashes.

Works in Gnome Wayland (using Appindicator for the menu)
Does not work in KDE Wayland

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x91e458]

goroutine 22 [running]:
main.main.func2()
        /home/adam/Documents/go/test/main.go:24 +0x78
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).refreshSystray.func1()
        /home/adam/.local/go/pkg/mod/fyne.io/fyne/v2@v2.2.4/internal/driver/glfw/driver_desktop.go:74 +0x35
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).refreshSystray
        /home/adam/.local/go/pkg/mod/fyne.io/fyne/v2@v2.2.4/internal/driver/glfw/driver_desktop.go:72 +0x145
exit status 2
```

### How to reproduce

1. Copy text to clipboard
2. Run button in menu
3. Click main window
4. Run button in menu

For the crashing
1. Close main window
2. Run button in menu

### Example code

```go
package main

import (
	"fmt"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/driver/desktop"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("New Window")
	lbl := widget.NewLabel("")
	btn := widget.NewButton("Clippy", func() {
		lbl.SetText(w.Clipboard().Content())
	})

	m := fyne.NewMenu("Test")
	m.Items = append(m.Items, fyne.NewMenuItem("clipboard", func() {
		fmt.Println(w.Clipboard().Content())
	}))

	if desk, ok := a.(desktop.App); ok {
		desk.SetSystemTrayMenu(m)
	}
	w.SetContent(container.NewVBox(lbl, btn))
	w.ShowAndRun()
}
```

### Fyne version

2.2.4

### Go compiler version

1.19.3

### Operating system

Linux

### Operating system version

Fedora 37 KDE 5.26.4 Wayland

**Comment by Jacalz** [comment]
Most likely fixed by https://github.com/fyne-io/fyne/pull/4417/files.
