### ISSUE TITLE
When the program has an Entry or Label, and the Entry or Label is in a VBox or HBox, the program crashes when minimized.

### ISSUE THREAD

**Issue by wanghonghust** [fyne-io/fyne#3553]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

#### When minimizing the program, the following error occurs and the program crashes and exits

```txt
panic: runtime error: slice bounds out of range [:-416]

goroutine 18 [running, locked to thread]:
golang.org/x/image/vector.(*Rasterizer).setUseFloatingPointMath(0xc00042e000, 0x1?)
        C:/Users/****/go/pkg/mod/golang.org/x/image@v0.0.0-20220601225756-64ec528b34cd/vector/vector.go:143 +0x125
golang.org/x/image/vector.(*Rasterizer).Reset(0x10?, 0xc0005a1580?, 0x7ff75963d090?)
        C:/Users/****/go/pkg/mod/golang.org/x/image@v0.0.0-20220601225756-64ec528b34cd/vector/vector.go:123 +0x65
github.com/srwiley/rasterx.(*ScannerGV).SetBounds(...)
        C:/Users/****/go/pkg/mod/github.com/srwiley/rasterx@v0.0.0-20210519020934-456a8d69b780/scan.go:166
github.com/srwiley/rasterx.NewScannerGV(0xd?, 0xd?, {0x7ff759ea8e00?, 0xc000426140}, {{0xc0005a15f8?, 0x7ff759421751?}, {0x0?, 0xc0005a1610?}})
        C:/Users/****/go/pkg/mod/github.com/srwiley/rasterx@v0.0.0-20210519020934-456a8d69b780/scan.go:173 +0x69
fyne.io/fyne/v2/internal/painter.DrawRectangle(0xc000034780, 0x40400000, 0xc0005a1668)
        C:/Users/****/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/painter/draw.go:90 +0x16c
fyne.io/fyne/v2/internal/painter/gl.(*painter).newGlStrokedRectTexture(0xc0000bc0c0, {0x7ff759eaa920?, 0xc000034780?})
        C:/Users/****/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/painter/gl/texture.go:156 +0xa9
fyne.io/fyne/v2/internal/painter/gl.(*painter).newGlRectTexture(0x7ff759d4ab00?, {0x7ff759eaa920?, 0xc000034780?})
        C:/Users/****/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/painter/gl/texture.go:146 +0x4e
fyne.io/fyne/v2/internal/painter/gl.(*painter).getTexture(0xc0000bc0c0, {0x7ff759eaa920, 0xc000034780}, 0xc0005a1830)
        C:/Users/****/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/painter/gl/texture.go:36 +0x4f
fyne.io/fyne/v2/internal/painter/gl.(*painter).drawTextureWithDetails(0xc0000bc0c0, {0x7ff759eaa920?, 0xc000034780?}, 0x7ff759449e0c?, {0x5a1840?, 0xc0?}, {0x593e3d09?, 0x7ff7?}, {0x5a1840?, 0x41f0c000?}, ...)
        C:/Users/****/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/painter/gl/draw.go:134 +0x8b
fyne.io/fyne/v2/internal/painter/gl.(*painter).drawRectangle(0xc0000bc0c0, 0xc000034780, {0x0?, 0x0?}, {0x5a18c0?, 0x74c0?})
        C:/Users/****/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/painter/gl/draw.go:104 +0x185
fyne.io/fyne/v2/internal/painter/gl.(*painter).drawObject(0xc0000343c0?, {0x7ff759eaa920?, 0xc000034780?}, {0x593ebebd?, 0x7ff7?}, {0x59d02740?, 0x7ff7?})
        C:/Users/****/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/painter/gl/draw.go:86 +0x1c5
fyne.io/fyne/v2/internal/painter/gl.(*painter).Paint(0x7ff7593ee145?, {0x7ff759eaa920, 0xc000034780}, {0x593ebebd?, 0x7ff7?}, {0x59d02740?, 0x7ff7?})
        C:/Users/****/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/painter/gl/painter.go:84 +0x74
fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).paint.func1(0x7ff75963cb51?, {0x5963d1dc?, 0x7ff7?})
        C:/Users/****/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/canvas.go:284 +0xff
fyne.io/fyne/v2/internal/driver/common.(*Canvas).walkTree.func1({0x7ff759eaa920?, 0xc000034780}, {0x34780?, 0xc0?}, {0xb81e0?, 0xc0?}, {0xf3465f1d?, 0xe?})
        C:/Users/****/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/common/canvas.go:438 +0x277
fyne.io/fyne/v2/internal/driver.walkObjectTree({0x7ff759eaa920, 0xc000034780}, 0x0, {0x7ff759eaae00, 0xc0000b81e0}, {0x5a1b18?, 0xc0?}, {0x0?, 0x0?}, {0x40c00000?, ...}, ...)
        C:/Users/****/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/util.go:169 +0x29b
fyne.io/fyne/v2/internal/driver.walkObjectTree.func1(...)
        C:/Users/****/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/util.go:176
fyne.io/fyne/v2/internal/driver.walkObjectTree({0x7ff759eaae00, 0xc0000b81e0}, 0x0, {0x7ff759eaa680, 0xc00028e230}, {0x59d1f360?, 0x7ff7?}, {0x132e9b0?, 0xc0?}, {0xceb3e0?, ...}, ...)
        C:/Users/****/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/util.go:190 +0x41d
fyne.io/fyne/v2/internal/driver.walkObjectTree.func1(...)
        C:/Users/****/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/util.go:176
fyne.io/fyne/v2/internal/driver.walkObjectTree({0x7ff759eaa680, 0xc00028e230}, 0x0, {0x0, 0x0}, {0x0?, 0x0?}, {0x5a1c80?, 0xc0?}, {0x59421751?, ...}, ...)
        C:/Users/****/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/util.go:190 +0x41d
fyne.io/fyne/v2/internal/driver.WalkVisibleObjectTree({0x7ff759eaa680?, 0xc00028e230?}, 0xc0005a1cb0?, 0x7ff75943eca5?)
        C:/Users/****/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/util.go:134 +0x4c
fyne.io/fyne/v2/internal/driver/common.(*Canvas).walkTree(0xc000000000?, 0xc000eaf3c0, 0xc0005a1dd0, 0xc0005a1db8)
        C:/Users/****/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/common/canvas.go:459 +0x165
fyne.io/fyne/v2/internal/driver/common.(*Canvas).WalkTrees(0xc0000ba000, 0xc0005a1da0?, 0x7ff7599231c6?)
        C:/Users/****/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/common/canvas.go:371 +0x3c
fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).paint(0xc0000ba000, {0x0?, 0x0?})
        C:/Users/****/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/canvas.go:296 +0xfe
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow.func1()
        C:/Users/****/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/loop.go:203 +0x8f
fyne.io/fyne/v2/internal/driver/glfw.(*window).RunWithContext(0x7ff759901066?, 0xc0005a1e80)
        C:/Users/****/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/window.go:903 +0x4f
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow(0xc0000ba000?, 0x0?)
        C:/Users/****/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/loop.go:194 +0x4a
fyne.io/fyne/v2/internal/driver/glfw.(*window).platformResize.func1()
        C:/Users/****/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/window_notlinux.go:17 +0x48
fyne.io/fyne/v2/internal/driver/glfw.(*window).RunWithContext(0xc0005a1f90?, 0xc0009152e0)
        C:/Users/****/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/window.go:903 +0x4f
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread.func1()
        C:/Users/****/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/loop.go:234 +0x13b
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread
        C:/Users/****/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/loop.go:226 +0xea
exit status 2
```

### How to reproduce

1. Run the following example code
```Golang
package main

import (
	"log"

	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("Entry Widget")

	input := widget.NewEntry()
	input.SetPlaceHolder("Enter text...")

	content := container.NewVBox(input, widget.NewButton("Save", func() {
		log.Println("Content was:", input.Text)
	}))

	myWindow.SetContent(content)
	myWindow.ShowAndRun()
}

```
2. Minimize program window

#### Sample code, taken from official documentation.
```Golang
package main

import (
	"log"

	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("Entry Widget")

	input := widget.NewEntry()
	input.SetPlaceHolder("Enter text...")

	content := container.NewVBox(input, widget.NewButton("Save", func() {
		log.Println("Content was:", input.Text)
	}))

	myWindow.SetContent(content)
	myWindow.ShowAndRun()
}

```

### Fyne version

v2.3.0

### Go compiler version

1.18.1 

### Operating system

Other (specify below)

### Operating system version

Windows 10

**Comment by andydotxyz** [comment]
I cannot replicate on macOS or Linux, suspect it may be an issue on Windows only for some reason.
Perhaps the same cause as https://github.com/fyne-io/defyne/issues/19

**Comment by andydotxyz** [comment]
I see now this is the same as #3552, closing as a duplicate

**Comment by bobowang2017** [comment]
I have encountered similar problems, how to solve it?

**Comment by andydotxyz** [comment]
This is closed as duplicate, so the conversation is in the linked issue
