### ISSUE TITLE
When the app contains an entry, the app panics when minimizing on Windows

### ISSUE THREAD

**Issue by SKBotNL** [fyne-io/fyne#3569]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When an entry is in the content of a window, minimizing causes the app to panic
```
panic: runtime error: index out of range [0] with length 0

goroutine 20 [running, locked to thread]:
golang.org/x/image/vector.(*Rasterizer).rasterizeDstRGBASrcUniformOpOver(0xc000034dd0, 0xc00033fd80, {{0xc010000000000000?, 0xc010000000000000?}, {0x3ff0000000000000?, 0x0?}}, 0x0, 0x0, 0x0, 0x0)
        C:/Users/Sven/go/pkg/mod/golang.org/x/image@v0.0.0-20220601225756-64ec528b34cd/vector/vector.go:398 +0x305
golang.org/x/image/vector.(*Rasterizer).Draw(0xc000034dd0, {0x7ff79e545e60?, 0xc00033fd80}, {{0x3ff0000000000000?, 0x0?}, {0x0?, 0x3ff0000000000000?}}, {0x7ff79e5451b0?, 0xc00033fdc0?}, {0x0, ...})
        C:/Users/Sven/go/pkg/mod/golang.org/x/image@v0.0.0-20220601225756-64ec528b34cd/vector/vector.go:287 +0x1ab
github.com/srwiley/rasterx.(*ScannerGV).Draw(0xc000034dd0)
        C:/Users/Sven/go/pkg/mod/github.com/srwiley/rasterx@v0.0.0-20210519020934-456a8d69b780/scan.go:141 +0x85
fyne.io/fyne/v2/internal/painter.DrawRectangle(0xc000094960, 0x40400000, 0xc000763730)
        C:/Users/Sven/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/painter/draw.go:102 +0x310
fyne.io/fyne/v2/internal/painter/gl.(*painter).newGlStrokedRectTexture(0xc000092000, {0x7ff79e5487e0?, 0xc000094960?})
        C:/Users/Sven/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/painter/gl/texture.go:156 +0xa5
fyne.io/fyne/v2/internal/painter/gl.(*painter).newGlRectTexture(0x7ff79e3dfd60?, {0x7ff79e5487e0?, 0xc000094960?})
        C:/Users/Sven/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/painter/gl/texture.go:146 +0x4e
fyne.io/fyne/v2/internal/painter/gl.(*painter).getTexture(0xc000092000, {0x7ff79e5487e0, 0xc000094960}, 0xc0007638f8)
        C:/Users/Sven/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/painter/gl/texture.go:36 +0x4f
fyne.io/fyne/v2/internal/painter/gl.(*painter).drawTextureWithDetails(0xc000092000, {0x7ff79e5487e0?, 0xc000094960?}, 0xf79de9e1da?, {0x7638f0?, 0xc0?}, {0x9debec77?, 0x7ff7?}, {0x9e5487e0?, 0x7ff7?}, ...)
        C:/Users/Sven/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/painter/gl/draw.go:134 +0x8b
fyne.io/fyne/v2/internal/painter/gl.(*painter).drawRectangle(0xc000092000, 0xc000094960, {0x9e3dfd60?, 0x7ff7?}, {0x9e5487e0?, 0x7ff7?})
        C:/Users/Sven/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/painter/gl/draw.go:104 +0x17e
fyne.io/fyne/v2/internal/painter/gl.(*painter).drawObject(0x7ff79e843e60?, {0x7ff79e5487e0?, 0xc000094960?}, {0x9da5c0bd?, 0x7ff7?}, {0x9e396700?, 0x7ff7?})
        C:/Users/Sven/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/painter/gl/draw.go:86 +0x16d
fyne.io/fyne/v2/internal/painter/gl.(*painter).Paint(0x7ff79da5e37f?, {0x7ff79e5487e0, 0xc000094960}, {0x9da5c0bd?, 0x7ff7?}, {0x9e396700?, 0x7ff7?})
        C:/Users/Sven/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/painter/gl/painter.go:84 +0x74
fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).paint.func1(0x7ff79dcc82d1?, {0x9dcc895c?, 0x7ff7?})
        C:/Users/Sven/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/canvas.go:284 +0x102
fyne.io/fyne/v2/internal/driver/common.(*Canvas).walkTree.func1({0x7ff79e5487e0?, 0xc000094960}, {0x94960?, 0xc0?}, {0xd01e0?, 0xc0?}, {0xbc6d33a9?, 0xe?})
        C:/Users/Sven/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/common/canvas.go:438 +0x277
fyne.io/fyne/v2/internal/driver.walkObjectTree({0x7ff79e5487e0, 0xc000094960}, 0x0, {0x7ff79e548c60, 0xc0000d01e0}, {0x9e3b4060?, 0x7ff7?}, {0x3ac000?, 0xc0?}, {0x754390?, ...}, ...)
        C:/Users/Sven/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/util.go:169 +0x29b
fyne.io/fyne/v2/internal/driver.walkObjectTree.func1(...)
        C:/Users/Sven/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/util.go:176
fyne.io/fyne/v2/internal/driver.walkObjectTree({0x7ff79e548c60, 0xc0000d01e0}, 0x0, {0x0, 0x0}, {0x9da93651?, 0x7ff7?}, {0x0?, 0x0?}, {0x763c88?, ...}, ...)
        C:/Users/Sven/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/util.go:190 +0x41d
fyne.io/fyne/v2/internal/driver.WalkVisibleObjectTree({0x7ff79e548c60?, 0xc0000d01e0?}, 0xc0000844e0?, 0x200000003?)
        C:/Users/Sven/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/util.go:134 +0x4c
fyne.io/fyne/v2/internal/driver/common.(*Canvas).walkTree(0xc000000000?, 0xc000206dc0, 0xc000763dd0, 0xc000763da0)
        C:/Users/Sven/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/common/canvas.go:459 +0x165
fyne.io/fyne/v2/internal/driver/common.(*Canvas).WalkTrees(0xc0000d2000, 0xc000763da0?, 0x7ff79dfb23e6?)
        C:/Users/Sven/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/common/canvas.go:371 +0x3c
fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).paint(0xc0000d2000, {0x0?, 0x0?})
        C:/Users/Sven/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/canvas.go:296 +0xfe
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow.func1()
        C:/Users/Sven/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/loop.go:203 +0x8f
fyne.io/fyne/v2/internal/driver/glfw.(*window).RunWithContext(0x7ff79df8f8e6?, 0xc000763e80)
        C:/Users/Sven/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/window.go:903 +0x4f
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow(0xc0000d2000?, 0x0?)
        C:/Users/Sven/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/loop.go:194 +0x4a
fyne.io/fyne/v2/internal/driver/glfw.(*window).platformResize.func1()
        C:/Users/Sven/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/window_notlinux.go:17 +0x48
fyne.io/fyne/v2/internal/driver/glfw.(*window).RunWithContext(0xc000763f90?, 0xc0003aa120)
        C:/Users/Sven/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/window.go:903 +0x4f
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread.func1()
        C:/Users/Sven/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/loop.go:234 +0x13b
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread
        C:/Users/Sven/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/loop.go:226 +0xea
```

### How to reproduce

1. Run the provided code
2. Minimize the app
3. App panics

### Example code

```go
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello World")

	w.SetContent(widget.NewEntry())
	w.ShowAndRun()
}
```

### Fyne version

2.3.0

### Go compiler version

1.19.5

### Operating system

Windows

### Operating system version

Windows 11 22H2

**Comment by SKBotNL** [comment]
Never mind, found the related issue #3552
Closing
