### ISSUE TITLE
If the screen is locked for a long time, panic occurs in fyne program

### ISSUE THREAD

**Issue by 93Alliance** [fyne-io/fyne#3728]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

On linux mint platform, if the screen is locked for a long time and the software is opened and closed again in the system tray, the software will flash quit.

### How to reproduce

NA

### Example code

NA

### Fyne version

2.3.1

### Go compiler version

1.18

### Operating system and version

linux mint 20.3

### Additional Information

fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x271 pc=0x271]

runtime stack:
runtime.throw({0xcb2998?, 0x9000026?})
    /usr/local/go/src/runtime/panic.go:992 +0x71
runtime.sigpanic()
    /usr/local/go/src/runtime/signal_unix.go:802 +0x3a9

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0xb32460, 0xc0005ddd88)
    /usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc0005ddd60 sp=0xc0005ddd28 pc=0x42e97c
github.com/go-gl/glfw/v3.3/glfw._Cfunc_glfwPollEvents()
    _cgo_gotypes.go:1577 +0x45 fp=0xc0005ddd88 sp=0xc0005ddd60 pc=0xab4b25
github.com/go-gl/glfw/v3.3/glfw.PollEvents()
    /home/vincent/opt/go-env/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20221017161538-93cebf72946b/window.go:964 +0x17 fp=0xc0005ddd98 sp=0xc0005ddd88 pc=0xac0d17
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).tryPollEvents(0xc0005ddec0?)
    /home/vincent/opt/go-env/pkg/mod/fyne.io/fyne/v2@v2.3.1/internal/driver/glfw/loop_desktop.go:39 +0x3b fp=0xc0005dddb8 sp=0xc0005ddd98 pc=0xafc09b
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).runGL(0xc000415dc0)
    /home/vincent/opt/go-env/pkg/mod/fyne.io/fyne/v2@v2.3.1/internal/driver/glfw/loop.go:134 +0x1f9 fp=0xc0005ddf00 sp=0xc0005dddb8 pc=0xafb2d9
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).Run(0xc000415dc0)
    /home/vincent/opt/go-env/pkg/mod/fyne.io/fyne/v2@v2.3.1/internal/driver/glfw/driver.go:168 +0x75 fp=0xc0005ddf20 sp=0xc0005ddf00 pc=0xaf9b35
fyne.io/fyne/v2/app.(*fyneApp).Run(0x21f5b30?)
    /home/vincent/opt/go-env/pkg/mod/fyne.io/fyne/v2@v2.3.1/app/app.go:74 +0x37 fp=0xc0005ddf38 sp=0xc0005ddf20 pc=0xb0b7d7
main.main()
    /media/vincent/common/project/tools/naivecat/naivecat.go:99 +0x215 fp=0xc0005ddf80 sp=0xc0005ddf38 pc=0xb1bc35
runtime.main()
    /usr/local/go/src/runtime/proc.go:250 +0x212 fp=0xc0005ddfe0 sp=0xc0005ddf80 pc=0x4618d2
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0005ddfe8 sp=0xc0005ddfe0 pc=0x48edc1

goroutine 7 [syscall, 1533 minutes]:
syscall.Syscall6(0xe8, 0xc, 0xc00048fc14, 0x7, 0xffffffffffffffff, 0x0, 0x0)
    /usr/local/go/src/syscall/asm_linux_amd64.s:43 +0x5
golang.org/x/sys/unix.EpollWait(0x0?, {0xc00048fc14?, 0x0?, 0x0?}, 0x0?)
    /home/vincent/opt/go-env/pkg/mod/golang.org/x/sys@v0.0.0-20220615213510-4f61da869c0c/unix/zsyscall_linux_amd64.go:56 +0x58
github.com/fsnotify/fsnotify.(*fdPoller).wait(0xc000043b60)
    /home/vincent/opt/go-env/pkg/mod/github.com/fsnotify/fsnotify@v1.5.4/inotify_poller.go:86 +0x7d
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc0000b4cd0)
    /home/vincent/opt/go-env/pkg/mod/github.com/fsnotify/fsnotify@v1.5.4/inotify.go:206 +0x26e
created by github.com/fsnotify/fsnotify.NewWatcher
    /home/vincent/opt/go-env/pkg/mod/github.com/fsnotify/fsnotify@v1.5.4/inotify.go:60 +0x1c5

goroutine 8 [chan receive, 1533 minutes]:
fyne.io/fyne/v2/app.watchFile.func1()
    /home/vincent/opt/go-env/pkg/mod/fyne.io/fyne/v2@v2.3.1/app/settings_desktop.go:43 +0x6c
created by fyne.io/fyne/v2/app.watchFile
    /home/vincent/opt/go-env/pkg/mod/fyne.io/fyne/v2@v2.3.1/app/settings_desktop.go:42 +0x10a

goroutine 9 [chan receive, 1533 minutes]:
github.com/godbus/dbus/v5.newConn.func1()
    /home/vincent/opt/go-env/pkg/mod/github.com/godbus/dbus/v5@v5.1.0/conn.go:303 +0x32
created by github.com/godbus/dbus/v5.newConn
    /home/vincent/opt/go-env/pkg/mod/github.com/godbus/dbus/v5@v5.1.0/conn.go:302 +0x4c5

goroutine 18 [IO wait, 1533 minutes]:
internal/poll.runtime_pollWait(0x7f4f891745d8, 0x72)
    /usr/local/go/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc000050c00?, 0xc00058c840?, 0x0)
    /usr/local/go/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
    /usr/local/go/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).ReadMsg(0xc000050c00, {0xc00058c840, 0x10, 0x10}, {0xc000114020, 0x1000, 0x1000}, 0x7f4f8bce5fff?)
    /usr/local/go/src/internal/poll/fd_unix.go:304 +0x31c
net.(*netFD).readMsg(0xc000050c00, {0xc00058c840?, 0xc00059a2d0?, 0x224a800?}, {0xc000114020?, 0xc0004a648e?, 0xc0004a6488?}, 0xc0004a6484?)
    /usr/local/go/src/net/fd_posix.go:78 +0x37
net.(*UnixConn).readMsg(0xc000010298, {0xc00058c840?, 0xc000596670?, 0xdc4120?}, {0xc000114020?, 0xdcb890?, 0x224a800?})
    /usr/local/go/src/net/unixsock_posix.go:115 +0x4f
net.(*UnixConn).ReadMsgUnix(0xc000010298, {0xc00058c840?, 0xc0005dfdb8?, 0x4383f4?}, {0xc000114020?, 0x53242b?, 0xc0004a83f0?})
    /usr/local/go/src/net/unixsock.go:143 +0x3c
github.com/godbus/dbus/v5.(*oobReader).Read(0xc000114000, {0xc00058c840?, 0xc0005dfde0?, 0x438727?})
    /home/vincent/opt/go-env/pkg/mod/github.com/godbus/dbus/v5@v5.1.0/transport_unix.go:21 +0x45
io.ReadAtLeast({0xdc3d60, 0xc000114000}, {0xc00058c840, 0x10, 0x10}, 0x10)
    /usr/local/go/src/io/io.go:331 +0x9a
io.ReadFull(...)
    /usr/local/go/src/io/io.go:350
github.com/godbus/dbus/v5.(*unixTransport).ReadMessage(0xc00000f380)
    /home/vincent/opt/go-env/pkg/mod/github.com/godbus/dbus/v5@v5.1.0/transport_unix.go:91 +0x11e
github.com/godbus/dbus/v5.(*Conn).inWorker(0xc0003d2c30)
    /home/vincent/opt/go-env/pkg/mod/github.com/godbus/dbus/v5@v5.1.0/conn.go:390 +0x48
created by github.com/godbus/dbus/v5.(*Conn).Auth
    /home/vincent/opt/go-env/pkg/mod/github.com/godbus/dbus/v5@v5.1.0/auth.go:118 +0x98d

goroutine 39 [syscall, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw._Cfunc_glfwMakeContextCurrent(0x2ef1c00)
    _cgo_gotypes.go:1551 +0x45
github.com/go-gl/glfw/v3.3/glfw.(*Window).MakeContextCurrent.func1(0xb07400?)
    /home/vincent/opt/go-env/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20221017161538-93cebf72946b/context.go:17 +0x46
github.com/go-gl/glfw/v3.3/glfw.(*Window).MakeContextCurrent(0x0?)
    /home/vincent/opt/go-env/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20221017161538-93cebf72946b/context.go:17 +0x19
fyne.io/fyne/v2/internal/driver/glfw.(*window).RunWithContext(0xc000415dc0?, 0xc000639e30)
    /home/vincent/opt/go-env/pkg/mod/fyne.io/fyne/v2@v2.3.1/internal/driver/glfw/window.go:905 +0x45
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow(0xc000639e98?, 0xc00ada4be0?)
    /home/vincent/opt/go-env/pkg/mod/fyne.io/fyne/v2@v2.3.1/internal/driver/glfw/loop.go:194 +0x4a
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).drawSingleFrame(0xc000639f90?)
    /home/vincent/opt/go-env/pkg/mod/fyne.io/fyne/v2@v2.3.1/internal/driver/glfw/loop.go:102 +0x1cb
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread.func1()
    /home/vincent/opt/go-env/pkg/mod/fyne.io/fyne/v2@v2.3.1/internal/driver/glfw/loop.go:250 +0x1a6
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread
    /home/vincent/opt/go-env/pkg/mod/fyne.io/fyne/v2@v2.3.1/internal/driver/glfw/loop.go:226 +0xea

goroutine 20 [syscall, 1533 minutes]:
syscall.Syscall6(0xe8, 0x11, 0xc00060fc14, 0x7, 0xffffffffffffffff, 0x0, 0x0)
    /usr/local/go/src/syscall/asm_linux_amd64.s:43 +0x5
golang.org/x/sys/unix.EpollWait(0x0?, {0xc00060fc14?, 0x0?, 0x0?}, 0x0?)
    /home/vincent/opt/go-env/pkg/mod/golang.org/x/sys@v0.0.0-20220615213510-4f61da869c0c/unix/zsyscall_linux_amd64.go:56 +0x58
github.com/fsnotify/fsnotify.(*fdPoller).wait(0xc0004ac120)
    /home/vincent/opt/go-env/pkg/mod/github.com/fsnotify/fsnotify@v1.5.4/inotify_poller.go:86 +0x7d
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc0004ce0f0)
    /home/vincent/opt/go-env/pkg/mod/github.com/fsnotify/fsnotify@v1.5.4/inotify.go:206 +0x26e
created by github.com/fsnotify/fsnotify.NewWatcher
    /home/vincent/opt/go-env/pkg/mod/github.com/fsnotify/fsnotify@v1.5.4/inotify.go:60 +0x1c5

goroutine 21 [chan receive, 1533 minutes]:
fyne.io/fyne/v2/app.watchFile.func1()
    /home/vincent/opt/go-env/pkg/mod/fyne.io/fyne/v2@v2.3.1/app/settings_desktop.go:43 +0x6c
created by fyne.io/fyne/v2/app.watchFile
    /home/vincent/opt/go-env/pkg/mod/fyne.io/fyne/v2@v2.3.1/app/settings_desktop.go:42 +0x10a

goroutine 22 [chan receive, 1533 minutes]:
fyne.io/fyne/v2/app.watchFreedekstopThemeChange()
    /home/vincent/opt/go-env/pkg/mod/fyne.io/fyne/v2@v2.3.1/app/app_xdg.go:187 +0x212
created by fyne.io/fyne/v2/app.watchTheme
    /home/vincent/opt/go-env/pkg/mod/fyne.io/fyne/v2@v2.3.1/app/app_xdg.go:159 +0x25

goroutine 40 [select, 1165 minutes]:
fyne.io/fyne/v2/internal/async.(*UnboundedFuncChan).processing(0xc00058a060)
    /home/vincent/opt/go-env/pkg/mod/fyne.io/fyne/v2@v2.3.1/internal/async/chan_func.go:45 +0xda
created by fyne.io/fyne/v2/internal/async.NewUnboundedFuncChan
    /home/vincent/opt/go-env/pkg/mod/fyne.io/fyne/v2@v2.3.1/internal/async/chan_func.go:22 +0xf8

goroutine 41 [chan receive, 1165 minutes]:
fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue(0x0?)
    /home/vincent/opt/go-env/pkg/mod/fyne.io/fyne/v2@v2.3.1/internal/driver/common/window.go:34 +0x4d
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1
    /home/vincent/opt/go-env/pkg/mod/fyne.io/fyne/v2@v2.3.1/internal/driver/glfw/window.go:946 +0x136

goroutine 43 [select, 1533 minutes]:
fyne.io/fyne/v2/internal/async.(*UnboundedFuncChan).processing(0xc00058a120)
    /home/vincent/opt/go-env/pkg/mod/fyne.io/fyne/v2@v2.3.1/internal/async/chan_func.go:45 +0xda
created by fyne.io/fyne/v2/internal/async.NewUnboundedFuncChan
    /home/vincent/opt/go-env/pkg/mod/fyne.io/fyne/v2@v2.3.1/internal/async/chan_func.go:22 +0xf8

goroutine 44 [chan receive, 1533 minutes]:
fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue(0x0?)
    /home/vincent/opt/go-env/pkg/mod/fyne.io/fyne/v2@v2.3.1/internal/driver/common/window.go:34 +0x4d
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1
    /home/vincent/opt/go-env/pkg/mod/fyne.io/fyne/v2@v2.3.1/internal/driver/glfw/window.go:946 +0x136

goroutine 67 [chan receive, 1533 minutes]:
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).refreshSystrayMenu.func1()
    /home/vincent/opt/go-env/pkg/mod/fyne.io/fyne/v2@v2.3.1/internal/driver/glfw/driver_desktop.go:130 +0x3a
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).refreshSystrayMenu
    /home/vincent/opt/go-env/pkg/mod/fyne.io/fyne/v2@v2.3.1/internal/driver/glfw/driver_desktop.go:129 +0xfa

goroutine 68 [chan receive, 1533 minutes]:
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).refreshSystray.func1()
    /home/vincent/opt/go-env/pkg/mod/fyne.io/fyne/v2@v2.3.1/internal/driver/glfw/driver_desktop.go:113 +0x2b
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).refreshSystray
    /home/vincent/opt/go-env/pkg/mod/fyne.io/fyne/v2@v2.3.1/internal/driver/glfw/driver_desktop.go:112 +0xe5

goroutine 83 [chan receive, 1533 minutes]:
github.com/godbus/dbus/v5.newConn.func1()
    /home/vincent/opt/go-env/pkg/mod/github.com/godbus/dbus/v5@v5.1.0/conn.go:303 +0x32
created by github.com/godbus/dbus/v5.newConn
    /home/vincent/opt/go-env/pkg/mod/github.com/godbus/dbus/v5@v5.1.0/conn.go:302 +0x4c5

goroutine 82 [chan receive, 1533 minutes]:
fyne.io/fyne/v2/internal/driver/glfw.catchTerm(0x0?)
    /home/vincent/opt/go-env/pkg/mod/fyne.io/fyne/v2@v2.3.1/internal/driver/glfw/driver.go:187 +0x8f
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).Run
    /home/vincent/opt/go-env/pkg/mod/fyne.io/fyne/v2@v2.3.1/internal/driver/glfw/driver.go:167 +0x6b

goroutine 45 [syscall, 1533 minutes]:
os/signal.signal_recv()
    /usr/local/go/src/runtime/sigqueue.go:151 +0x2f
os/signal.loop()
    /usr/local/go/src/os/signal/signal_unix.go:23 +0x19
created by os/signal.Notify.func1.1
    /usr/local/go/src/os/signal/signal.go:151 +0x2a

goroutine 69 [chan receive]:
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).refreshSystrayMenu.func1()
    /home/vincent/opt/go-env/pkg/mod/fyne.io/fyne/v2@v2.3.1/internal/driver/glfw/driver_desktop.go:130 +0x3a
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).refreshSystrayMenu
    /home/vincent/opt/go-env/pkg/mod/fyne.io/fyne/v2@v2.3.1/internal/driver/glfw/driver_desktop.go:129 +0xfa

goroutine 70 [chan receive, 1533 minutes]:
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).refreshSystray.func1()
    /home/vincent/opt/go-env/pkg/mod/fyne.io/fyne/v2@v2.3.1/internal/driver/glfw/driver_desktop.go:113 +0x2b
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).refreshSystray
    /home/vincent/opt/go-env/pkg/mod/fyne.io/fyne/v2@v2.3.1/internal/driver/glfw/driver_desktop.go:112 +0xe5

**Comment by andydotxyz** [comment]
I wonder if it could relate to https://github.com/fyne-io/fyne/issues/1603
