### ISSUE TITLE
table

### ISSUE THREAD

**Issue by yishuguo** [fyne-io/fyne#3904]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

			go func() {
				for {
					select {
					case tmp := <-dataUIBridgeChan:
						if stopFlag {
							return
						}
						responseData = append(responseData, tmp)  
						responseTable.SetRowHeight(len(responseData)-1, 60)         【flag here_A】
					}
				}
			}()

Only one goroutine .
When dataUIBridgeChan is very busy ,and the line code of  flag【hereA】turn on，will cause fatal error。 Maybe a bug?

fatal error: concurrent map read and map write

goroutine 20 [running]:
fyne.io/fyne/v2/widget.(*Table).visibleRowHeights(0xc00733d290, 0x42076000, 0x1d6)
        C:/Gopath/pkg/mod/fyne.io/fyne/v2@v2.3.4/widget/table.go:373 +0xe5
fyne.io/fyne/v2/widget.(*tableRenderer).moveIndicators(0xc00d5b8120)
        C:/Gopath/pkg/mod/fyne.io/fyne/v2@v2.3.4/widget/table.go:440 +0xa9
fyne.io/fyne/v2/widget.(*tableCells).hoverAt(0xc00d5aa230, {0x21175f88?, 0xc0?})
        C:/Gopath/pkg/mod/fyne.io/fyne/v2@v2.3.4/widget/table.go:637 +0x1de
fyne.io/fyne/v2/widget.(*tableCells).MouseMoved(0xc021175fb0?, 0xc0000d4001?)
        C:/Gopath/pkg/mod/fyne.io/fyne/v2@v2.3.4/widget/table.go:569 +0x25
fyne.io/fyne/v2/internal/driver/glfw.(*window).processMouseMoved.func3()
        C:/Gopath/pkg/mod/fyne.io/fyne/v2@v2.3.4/internal/driver/glfw/window.go:420 +0x26
fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue(0x0?)
        C:/Gopath/pkg/mod/fyne.io/fyne/v2@v2.3.4/internal/driver/common/window.go:35 +0x3e
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1
        C:/Gopath/pkg/mod/fyne.io/fyne/v2@v2.3.4/internal/driver/glfw/window.go:946 +0x136

### How to reproduce

			go func() {
				for {
					select {
					case tmp := <-dataUIBridgeChan:
						if stopFlag {
							return
						}
						responseData = append(responseData, tmp)  
						responseTable.SetRowHeight(len(responseData)-1, 60)         【flag here_A】
					}
				}
			}()

Only one goroutine .
When dataUIBridgeChan is very busy ,and the line code of  flag【hereA】turn on，will cause fatal error。 Maybe a bug?

fatal error: concurrent map read and map write

goroutine 20 [running]:
fyne.io/fyne/v2/widget.(*Table).visibleRowHeights(0xc00733d290, 0x42076000, 0x1d6)
        C:/Gopath/pkg/mod/fyne.io/fyne/v2@v2.3.4/widget/table.go:373 +0xe5
fyne.io/fyne/v2/widget.(*tableRenderer).moveIndicators(0xc00d5b8120)
        C:/Gopath/pkg/mod/fyne.io/fyne/v2@v2.3.4/widget/table.go:440 +0xa9
fyne.io/fyne/v2/widget.(*tableCells).hoverAt(0xc00d5aa230, {0x21175f88?, 0xc0?})
        C:/Gopath/pkg/mod/fyne.io/fyne/v2@v2.3.4/widget/table.go:637 +0x1de
fyne.io/fyne/v2/widget.(*tableCells).MouseMoved(0xc021175fb0?, 0xc0000d4001?)
        C:/Gopath/pkg/mod/fyne.io/fyne/v2@v2.3.4/widget/table.go:569 +0x25
fyne.io/fyne/v2/internal/driver/glfw.(*window).processMouseMoved.func3()
        C:/Gopath/pkg/mod/fyne.io/fyne/v2@v2.3.4/internal/driver/glfw/window.go:420 +0x26
fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue(0x0?)
        C:/Gopath/pkg/mod/fyne.io/fyne/v2@v2.3.4/internal/driver/common/window.go:35 +0x3e
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1
        C:/Gopath/pkg/mod/fyne.io/fyne/v2@v2.3.4/internal/driver/glfw/window.go:946 +0x136

### Example code

responseData = [][]string{
	{"subName", "Address", "Open Port", "WebStatus", "Web Title", "Server", "CNAME"},
}

// step one
responseTable := widget.NewTable(nil, nil, nil)

// step two
responseTable.Length = func() (int, int) {
	return len(responseData), len(responseData[0])
}

// step three
responseTable.CreateCell = func() fyne.CanvasObject {
	lbl := widget.NewLabel("newTable")
	lbl.Alignment = fyne.TextAlignLeading
	lbl.Wrapping = fyne.TextWrapWord
	return lbl
}

// Only one goroutine
go func() {
	for {
		select {
		case tmp := <-dataUIBridgeChan:
			if stopFlag {
				return
			}
			responseData = append(responseData, tmp)  
			responseTable.SetRowHeight(len(responseData)-1, 60)         【cause panic here_A】
		}
	}
}()

//other goroutine

for n := 0; n < 20000; n++ {
    go func() {
        for{
            ..................
          dataUIBridgeChan   <- dataUIBridgeChan <- []string{{"subName", "Address", "Open Port", "WebStatus", "Web Title", "Server", "CNAME"}}
        }
           ...............
}
 }

When dataUIBridgeChan is very busy ,and the line code of  flag【hereA】turn on，will cause fatal error。 Maybe a bug?

fatal error: concurrent map read and map write

goroutine 20 [running]:
fyne.io/fyne/v2/widget.(*Table).visibleRowHeights(0xc00733d290, 0x42076000, 0x1d6)
        C:/Gopath/pkg/mod/fyne.io/fyne/v2@v2.3.4/widget/table.go:373 +0xe5
fyne.io/fyne/v2/widget.(*tableRenderer).moveIndicators(0xc00d5b8120)
        C:/Gopath/pkg/mod/fyne.io/fyne/v2@v2.3.4/widget/table.go:440 +0xa9
fyne.io/fyne/v2/widget.(*tableCells).hoverAt(0xc00d5aa230, {0x21175f88?, 0xc0?})
        C:/Gopath/pkg/mod/fyne.io/fyne/v2@v2.3.4/widget/table.go:637 +0x1de
fyne.io/fyne/v2/widget.(*tableCells).MouseMoved(0xc021175fb0?, 0xc0000d4001?)
        C:/Gopath/pkg/mod/fyne.io/fyne/v2@v2.3.4/widget/table.go:569 +0x25
fyne.io/fyne/v2/internal/driver/glfw.(*window).processMouseMoved.func3()
        C:/Gopath/pkg/mod/fyne.io/fyne/v2@v2.3.4/internal/driver/glfw/window.go:420 +0x26
fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue(0x0?)
        C:/Gopath/pkg/mod/fyne.io/fyne/v2@v2.3.4/internal/driver/common/window.go:35 +0x3e
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1
        C:/Gopath/pkg/mod/fyne.io/fyne/v2@v2.3.4/internal/driver/glfw/window.go:946 +0x136

### Fyne version

v2.3.1

### Go compiler version

go version go1.20.2 windows/amd64

### Operating system and version

Microsoft Windows 10

**Comment by Jacalz** [comment]
There is also not a runnable code example that we can use to replicate this with. Please test with the latest stable Fyne release and if it still doesn't work, please update the code example.

**Comment by andydotxyz** [comment]
Closed due to lack of info or activity
