### ISSUE TITLE
Crash in tabs since 2.3.5

### ISSUE THREAD

**Issue by squidkeeper** [fyne-io/fyne#4009]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I am getting occasional panics associated with tabs in a non-trivial application, maybe 4-5 times per day.  It is hard to reproduce, but the attached code will occasionally crash in the same way. The relevant part of tabs.go was changed in 2.3.5, and I have not seen this crash in 2.3.4, which runs along nicely.

Stack trace:

```
$ go run knowncrasher/main.go 
panic: runtime error: index out of range [1] with length 1

goroutine 40 [running, locked to thread]:
fyne.io/fyne/v2/container.(*baseTabsRenderer).minSize(0xc000422070, {0xcb2940, 0xc000444120})
        /home/markc/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/container/tabs.go:372 +0x3bc
fyne.io/fyne/v2/container.(*appTabsRenderer).MinSize(0xcb3688?)
        /home/markc/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/container/apptabs.go:304 +0x25
fyne.io/fyne/v2/widget.(*BaseWidget).MinSize(0xc000444120?)
        /home/markc/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/widget/widget.go:91 +0x2e
fyne.io/fyne/v2/container.(*AppTabs).MinSize(0xc000444120)
        /home/markc/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/container/apptabs.go:142 +0x34
fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).MinSize(0xc00041c360)
        /home/markc/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/glfw/canvas.go:72 +0x9f
fyne.io/fyne/v2/internal/driver/common.(*Canvas).EnsureMinSize(0xc00041c360)
        /home/markc/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/common/canvas.go:70 +0x77
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow.func1()
        /home/markc/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/glfw/loop.go:199 +0x35
fyne.io/fyne/v2/internal/driver/glfw.(*window).RunWithContext(0xc0003c93b0?, 0xc00cef7e30)
        /home/markc/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/glfw/window.go:907 +0x4f
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow(0xc00e4c20a0?, 0xc0168089a0?)
        /home/markc/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/glfw/loop.go:198 +0x4a
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).drawSingleFrame(0xc00cef7f90?)
        /home/markc/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/glfw/loop.go:106 +0x1ac
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread.func1()
        /home/markc/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/glfw/loop.go:254 +0x1a6
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread
        /home/markc/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/glfw/loop.go:230 +0xea
exit status 2
```

### How to reproduce

1. Run app (maybe one that gets busy with memory)
2. Interact with it gently for a minute or two or ten. Maybe move the window.
3. Observe panic (or not; luck is involved)

### Example code

```go
package main

import (
	"strconv"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/data/binding"
	"fyne.io/fyne/v2/widget"
)

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("Crashme")
	myWindow.Resize(fyne.NewSize(300, 200))

	lastPrime := binding.NewString()
	form1 := widget.NewForm(
		widget.NewFormItem("One", widget.NewEntryWithData(lastPrime)),
		widget.NewFormItem("Two", widget.NewEntry()),
	)
	form2 := widget.NewForm(
		widget.NewFormItem("Three", widget.NewEntry()),
		widget.NewFormItem("Four", widget.NewEntry()),
	)
	tabs := container.NewAppTabs(
		container.NewTabItem("Controls", form1),
		container.NewTabItem("Settings", form2),
	)

	go eratosthenes(100_000_000, lastPrime)

	myWindow.SetContent(tabs)
	myWindow.ShowAndRun()
}

// stir up some action
func eratosthenes(top int, out binding.String) {
	for {
		notprime := make([]bool, top+1)
		notprime[0], notprime[1] = true, true
		for i := range notprime {
			if !notprime[i] {
				out.Set(strconv.Itoa(i))
				for j := 2 * i; j < len(notprime); j += i {
					notprime[j] = true
				}
			}
		}
	}
}
```

### Fyne version

2.3.5

### Go compiler version

1.20.4

### Operating system and version

Ubuntu 22.04

**Comment by squidkeeper** [comment]
I found this easy to reproduce on Ubuntu 18.04, and 22.04 that had been arrived at through upgrades from 18. However, I cannot reproduce it on fresh Ubuntu 22.04. Since 18.04 is now past the end of support, maybe close as ships that pass in the night?

**Comment by pseidemann** [comment]
I have the same problem. it's hard to reproduce but one just needs to keep switching tabs. eventually the panic will happen. the crash seems to be entirely internal to fyne.

```
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running, locked to thread]:
fyne.io/fyne/v2/container.(*baseTabsRenderer).minSize(0x140003a51f0, {0x100f62360, 0x140001fd9e0})
	/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/container/tabs.go:372 +0x354
fyne.io/fyne/v2/container.(*appTabsRenderer).MinSize(0x100f63408?)
	/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/container/apptabs.go:304 +0x28
fyne.io/fyne/v2/widget.(*BaseWidget).MinSize(0x140001fd9e0?)
	/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/widget/widget.go:91 +0x30
fyne.io/fyne/v2/container.(*AppTabs).MinSize(0x140001fd9e0)
	/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/container/apptabs.go:142 +0x38
fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).MinSize(0x14000498000)
	/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/glfw/canvas.go:72 +0xc0
fyne.io/fyne/v2/internal/driver/common.(*Canvas).EnsureMinSize(0x14000498000)
	/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/common/canvas.go:70 +0x6c
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow.func1()
	/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/glfw/loop.go:199 +0x34
fyne.io/fyne/v2/internal/driver/glfw.(*window).RunWithContext(0x100ce4f20?, 0x14000aabc60)
	/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/glfw/window.go:907 +0x4c
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow(0x14000aabcb8?, 0x96f0?)
	/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/glfw/loop.go:198 +0x44
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).drawSingleFrame(0x101591f10?)
	/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/glfw/loop.go:106 +0x204
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).runGL(0x140003a53b0)
	/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/glfw/loop.go:180 +0x550
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).Run(0x140003a53b0)
	/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/glfw/driver.go:169 +0x80
fyne.io/fyne/v2/internal/driver/glfw.(*window).ShowAndRun(0x140003e4000)
	/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/glfw/window.go:230 +0x2c
project/gui.(*gui).Run(0x140004a2080)
	project/gui/gui.go:51 +0x80
project/controller.(*Controller).Start(0x140004a0020)
	project/controller/controller.go:56 +0x80
main.main()
	project/project.go:13 +0x1e4
exit status 2
```

### Fyne version

2.3.5

### Go compiler version

1.20.6

### Operating system and version

macOS 13.5

**Comment by matwachich** [comment]
Similar crash here:

```
"runtime error: index out of range [1] with length 1"
Stack:
	 3  0x00007ff7764c59f4 in fyne.io/fyne/v2/container.(*docTabsRenderer).scrollToSelected
	     at C:/Users/Matwachich/go/pkg/mod/fyne.io/fyne/v2@v2.3.6-0.20230812072749-e63d4e8030ef/container/doctabs.go:366
	 4  0x00007ff7764c4891 in fyne.io/fyne/v2/container.(*docTabsRenderer).Refresh
	     at C:/Users/Matwachich/go/pkg/mod/fyne.io/fyne/v2@v2.3.6-0.20230812072749-e63d4e8030ef/container/doctabs.go:271
	 5  0x00007ff7764a08e9 in fyne.io/fyne/v2/widget.(*BaseWidget).Refresh
	     at C:/Users/Matwachich/go/pkg/mod/fyne.io/fyne/v2@v2.3.6-0.20230812072749-e63d4e8030ef/widget/widget.go:139
	 6  0x00007ff7767ed0c5 in main.NewMainWindow.func17
	     at c:/Users/Matwachich/Documents/Programmation/EMR Made Simple/emr-made-simple/src/main_window.go:103
	 7  0x00007ff7764ca251 in fyne.io/fyne/v2/container.selectIndex
	     at C:/Users/Matwachich/go/pkg/mod/fyne.io/fyne/v2@v2.3.6-0.20230812072749-e63d4e8030ef/container/tabs.go:198
	 8  0x00007ff7764ca365 in fyne.io/fyne/v2/container.selectItem
	     at C:/Users/Matwachich/go/pkg/mod/fyne.io/fyne/v2@v2.3.6-0.20230812072749-e63d4e8030ef/container/tabs.go:205
	 9  0x00007ff7764c3e70 in fyne.io/fyne/v2/container.(*DocTabs).Select
	     at C:/Users/Matwachich/go/pkg/mod/fyne.io/fyne/v2@v2.3.6-0.20230812072749-e63d4e8030ef/container/doctabs.go:143
	10  0x00007ff7767edc87 in main.(*MainWindow).TabSet
	     at c:/Users/Matwachich/Documents/Programmation/EMR Made Simple/emr-made-simple/src/main_window.go:171
	11  0x00007ff77686c69c in main.NewWTabHomeSearch.func7
	     at c:/Users/Matwachich/Documents/Programmation/EMR Made Simple/emr-made-simple/src/tab_w_home.go:117
	12  0x00007ff776452357 in fyne.io/fyne/v2/widget.(*Button).Tapped
	     at C:/Users/Matwachich/go/pkg/mod/fyne.io/fyne/v2@v2.3.6-0.20230812072749-e63d4e8030ef/widget/button.go:187
	13  0x00007ff7766065dd in github.com/matwachich/fynex-widgets.(*Button).Tapped
	     at c:/Users/Matwachich/Documents/Programmation/EMR Made Simple/fynex-widgets/button.go:70
	14  0x00007ff7766e06e2 in fyne.io/fyne/v2/internal/driver/glfw.(*window).mouseClickedHandleTapDoubleTap.func1
	     at C:/Users/Matwachich/go/pkg/mod/fyne.io/fyne/v2@v2.3.6-0.20230812072749-e63d4e8030ef/internal/driver/glfw/window.go:644
	15  0x00007ff7766a7133 in fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue
	     at C:/Users/Matwachich/go/pkg/mod/fyne.io/fyne/v2@v2.3.6-0.20230812072749-e63d4e8030ef/internal/driver/common/window.go:35
	16  0x00007ff7766e424b in fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1.1
	     at C:/Users/Matwachich/go/pkg/mod/fyne.io/fyne/v2@v2.3.6-0.20230812072749-e63d4e8030ef/internal/driver/glfw/window.go:956
```

**Comment by andydotxyz** [comment]
I have looked at the code on develop and cannot see how it would be possible any more, please do let us know how your tests get on!

**Comment by squidkeeper** [comment]
I cannot make it fail like this (crash in tabs.go:372) on develop v2.3.6-0.20230822134109-060343c8c5b1

**Comment by matwachich** [comment]
Sorry to say that I just encountered this crash on develop (v2.3.6-0.20230822100900-364b96764a96)

```
"runtime error: index out of range [1] with length 1"
Stack:
	 3  0x00007ff6af892265 in fyne.io/fyne/v2/container.(*docTabsRenderer).scrollToSelected
	     at C:/Users/Matwachich/go/pkg/mod/fyne.io/fyne/v2@v2.3.6-0.20230822100900-364b96764a96/container/doctabs.go:366
	 4  0x00007ff6af89110e in fyne.io/fyne/v2/container.(*docTabsRenderer).Refresh
	     at C:/Users/Matwachich/go/pkg/mod/fyne.io/fyne/v2@v2.3.6-0.20230822100900-364b96764a96/container/doctabs.go:271
	 5  0x00007ff6af86ef83 in fyne.io/fyne/v2/widget.(*BaseWidget).Refresh
	     at C:/Users/Matwachich/go/pkg/mod/fyne.io/fyne/v2@v2.3.6-0.20230822100900-364b96764a96/widget/widget.go:139
	 6  0x00007ff6af89077b in fyne.io/fyne/v2/container.(*DocTabs).Select
	     at C:/Users/Matwachich/go/pkg/mod/fyne.io/fyne/v2@v2.3.6-0.20230822100900-364b96764a96/container/doctabs.go:144
	 7  0x00007ff6afbdbd15 in main.(*MainWindow).TabSet
	     at c:/Users/Matwachich/Documents/Programmation/EMR Made Simple/emr-made-simple/src/main_window.go:182
	 8  0x00007ff6afc59416 in main.NewWTabHomeSearch.func7
	     at c:/Users/Matwachich/Documents/Programmation/EMR Made Simple/emr-made-simple/src/tab_w_home.go:117
	 9  0x00007ff6af820cab in fyne.io/fyne/v2/widget.(*Button).Tapped
	     at C:/Users/Matwachich/go/pkg/mod/fyne.io/fyne/v2@v2.3.6-0.20230822100900-364b96764a96/widget/button.go:187
	10  0x00007ff6afa2d357 in github.com/matwachich/fynex-widgets.(*Button).Tapped
	     at c:/Users/Matwachich/Documents/Programmation/EMR Made Simple/fynex-widgets/button.go:70
	11  0x00007ff6afad40bb in fyne.io/fyne/v2/internal/driver/glfw.(*window).mouseClickedHandleTapDoubleTap.func1
	     at C:/Users/Matwachich/go/pkg/mod/fyne.io/fyne/v2@v2.3.6-0.20230822100900-364b96764a96/internal/driver/glfw/window.go:645
	12  0x00007ff6afa9c310 in fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue
	     at C:/Users/Matwachich/go/pkg/mod/fyne.io/fyne/v2@v2.3.6-0.20230822100900-364b96764a96/internal/driver/common/window.go:35
	13  0x00007ff6afad7d25 in fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1.1
	     at C:/Users/Matwachich/go/pkg/mod/fyne.io/fyne/v2@v2.3.6-0.20230822100900-364b96764a96/internal/driver/glfw/window.go:957
```
It happend after adding a Tab (docTab.Append) followed by a select (docTab.Select).
It is like the tabRenderer.Scroller is not updated immediatly after docTab.Append

**Comment by matwachich** [comment]
Crash also happened on 2.4.0-rc1
When adding a Tab, after removing them all...

```
"runtime error: index out of range [1] with length 1"
Stack:
	 3  0x00007ff7965a24a5 in fyne.io/fyne/v2/container.(*docTabsRenderer).scrollToSelected
	     at C:/Users/Matwachich/go/pkg/mod/fyne.io/fyne/v2@v2.4.0-rc1/container/doctabs.go:366
	 4  0x00007ff7965a134e in fyne.io/fyne/v2/container.(*docTabsRenderer).Refresh
	     at C:/Users/Matwachich/go/pkg/mod/fyne.io/fyne/v2@v2.4.0-rc1/container/doctabs.go:271
	 5  0x00007ff79657f183 in fyne.io/fyne/v2/widget.(*BaseWidget).Refresh
	     at C:/Users/Matwachich/go/pkg/mod/fyne.io/fyne/v2@v2.4.0-rc1/widget/widget.go:139
	 6  0x00007ff7965a09bb in fyne.io/fyne/v2/container.(*DocTabs).Select
	     at C:/Users/Matwachich/go/pkg/mod/fyne.io/fyne/v2@v2.4.0-rc1/container/doctabs.go:144
	 7  0x00007ff7968ecd95 in main.(*MainWindow).TabSet
	     at c:/Users/Matwachich/Documents/Programmation/EMR Made Simple/emr-made-simple/src/main_window.go:182
	 8  0x00007ff79690d389 in main.NewWTabHomeSearch.func5
	     at c:/Users/Matwachich/Documents/Programmation/EMR Made Simple/emr-made-simple/src/tab_w_home.go:104
	 9  0x00007ff79673aead in github.com/matwachich/fynex-widgets.(*AutoComplete).data_complete
	     at c:/Users/Matwachich/Documents/Programmation/EMR Made Simple/fynex-widgets/autocomplete.go:172
	10  0x00007ff79673b52c in github.com/matwachich/fynex-widgets.(*AutoComplete).setTextFromList
	     at c:/Users/Matwachich/Documents/Programmation/EMR Made Simple/fynex-widgets/autocomplete.go:243
	11  0x00007ff79673cc93 in github.com/matwachich/fynex-widgets.(*autoCompleteListItem).Tapped
	     at c:/Users/Matwachich/Documents/Programmation/EMR Made Simple/fynex-widgets/autocomplete.go:394
	12  0x00007ff7967e427b in fyne.io/fyne/v2/internal/driver/glfw.(*window).mouseClickedHandleTapDoubleTap.func1
	     at C:/Users/Matwachich/go/pkg/mod/fyne.io/fyne/v2@v2.4.0-rc1/internal/driver/glfw/window.go:649
	13  0x00007ff7967ac5b0 in fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue
	     at C:/Users/Matwachich/go/pkg/mod/fyne.io/fyne/v2@v2.4.0-rc1/internal/driver/common/window.go:35
	14  0x00007ff7967e7ea5 in fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1.1
	     at C:/Users/Matwachich/go/pkg/mod/fyne.io/fyne/v2@v2.4.0-rc1/internal/driver/glfw/window.go:959
```

**Comment by andydotxyz** [comment]
> Sorry to say that I just encountered this crash on develop (v2.3.6-0.20230822100900-364b96764a96)
> 
> ```
> "runtime error: index out of range [1] with length 1"
> Stack:
> 	 3  0x00007ff6af892265 in fyne.io/fyne/v2/container.(*docTabsRenderer).scrollToSelected
> 	     at C:/Users/Matwachich/go/pkg/mod/fyne.io/fyne/v2@v2.3.6-0.20230822100900-364b96764a96/container/doctabs.go:366
> 	 4  0x00007ff6af89110e in fyne.io/fyne/v2/container.(*docTabsRenderer).Refresh
> 	     at C:/Users/Matwachich/go/pkg/mod/fyne.io/fyne/v2@v2.3.6-0.20230822100900-364b96764a96/container/doctabs.go:271
> 	 5  0x00007ff6af86ef83 in fyne.io/fyne/v2/widget.(*BaseWidget).Refresh
> 	     at C:/Users/Matwachich/go/pkg/mod/fyne.io/fyne/v2@v2.3.6-0.20230822100900-364b96764a96/widget/widget.go:139
> 	 6  0x00007ff6af89077b in fyne.io/fyne/v2/container.(*DocTabs).Select
> 	     at C:/Users/Matwachich/go/pkg/mod/fyne.io/fyne/v2@v2.3.6-0.20230822100900-364b96764a96/container/doctabs.go:144
> 	 7  0x00007ff6afbdbd15 in main.(*MainWindow).TabSet
> 	     at c:/Users/Matwachich/Documents/Programmation/EMR Made Simple/emr-made-simple/src/main_window.go:182
> 	 8  0x00007ff6afc59416 in main.NewWTabHomeSearch.func7
> 	     at c:/Users/Matwachich/Documents/Programmation/EMR Made Simple/emr-made-simple/src/tab_w_home.go:117
> 	 9  0x00007ff6af820cab in fyne.io/fyne/v2/widget.(*Button).Tapped
> 	     at C:/Users/Matwachich/go/pkg/mod/fyne.io/fyne/v2@v2.3.6-0.20230822100900-364b96764a96/widget/button.go:187
> 	10  0x00007ff6afa2d357 in github.com/matwachich/fynex-widgets.(*Button).Tapped
> 	     at c:/Users/Matwachich/Documents/Programmation/EMR Made Simple/fynex-widgets/button.go:70
> 	11  0x00007ff6afad40bb in fyne.io/fyne/v2/internal/driver/glfw.(*window).mouseClickedHandleTapDoubleTap.func1
> 	     at C:/Users/Matwachich/go/pkg/mod/fyne.io/fyne/v2@v2.3.6-0.20230822100900-364b96764a96/internal/driver/glfw/window.go:645
> 	12  0x00007ff6afa9c310 in fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue
> 	     at C:/Users/Matwachich/go/pkg/mod/fyne.io/fyne/v2@v2.3.6-0.20230822100900-364b96764a96/internal/driver/common/window.go:35
> 	13  0x00007ff6afad7d25 in fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1.1
> 	     at C:/Users/Matwachich/go/pkg/mod/fyne.io/fyne/v2@v2.3.6-0.20230822100900-364b96764a96/internal/driver/glfw/window.go:957
> ```
> 
> It happend after adding a Tab (docTab.Append) followed by a select (docTab.Select). It is like the tabRenderer.Scroller is not updated immediatly after docTab.Append

This is a different crash to the headline of this ticket, which does seem to remain resolved. #3909 is tracking this trace.
