### ISSUE TITLE
Investigate panic loading solitaire (GL build) over ssh connection

### ISSUE THREAD

**Issue by steveoc64** [fyne-io/fyne#45]
On GL build of examples - click on solitaire - boom, instant panic.

could be related to the color issue you mentioned before.

Im getting these when building & running these over an ssh connection to a fresh linux box (Ubuntu 18.10), so that can play havoc with the available palette IIRC.

Will try and sort it out - but its deep inside srwiley's code by the time it dies.

```
~/go/src/github.com/fyne-io/examples$ go run --tags=gl .
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x789ae7]

goroutine 1 [running, locked to thread]:
github.com/srwiley/rasterx.(*Gradient).blendStops(0xc0001580a0, 0x3f6555c71ed0a459, 0x3ff0000000000000, 0x0, 0x0, 0x0, 0x3ff0000000000000, 0x0, 0x0, 0x3ff0000000000000, ...)
        /home/steve/go/src/github.com/srwiley/rasterx/gradient.go:147 +0x87
github.com/srwiley/rasterx.(*Gradient).tColor(0xc0001580a0, 0x3f6555c71ed0a459, 0x3ff0000000000000, 0x11039e0, 0xc0000e1190)
        /home/steve/go/src/github.com/srwiley/rasterx/gradient.go:127 +0x843
github.com/srwiley/rasterx.(*Gradient).GetColorFunctionUS.func6(0x0, 0x0, 0x1, 0xc0004607b0)
        /home/steve/go/src/github.com/srwiley/rasterx/gradient.go:287 +0xf7
github.com/srwiley/rasterx.(*ColorFuncImage).At(0xc00027ae40, 0x0, 0x0, 0x0, 0x1)
        /home/steve/go/src/github.com/srwiley/rasterx/scan.go:23 +0x3e
golang.org/x/image/vector.(*Rasterizer).rasterizeOpOver(0xc000510600, 0x958920, 0xc00027ae00, 0x0, 0x0, 0x80, 0xc0, 0x957da0, 0xc00027ae40, 0x0, ...)
        /home/steve/go/src/golang.org/x/image/vector/vector.go:436 +0x283
golang.org/x/image/vector.(*Rasterizer).Draw(0xc000510600, 0x958920, 0xc00027ae00, 0x0, 0x0, 0x80, 0xc0, 0x957da0, 0xc00027ae40, 0x0, ...)
        /home/steve/go/src/golang.org/x/image/vector/vector.go:296 +0xd4
github.com/srwiley/rasterx.(*ScannerGV).Draw(0xc000510600)
        /home/steve/go/src/github.com/srwiley/rasterx/scan.go:140 +0x98
github.com/srwiley/oksvg.(*SvgPath).DrawTransformed(0xc0001880e0, 0xc0000b87e0, 0x3ff0000000000000, 0x3ff5805601580560, 0x0, 0x0, 0x3ff5805601580560, 0x0, 0x0)
        /home/steve/go/src/github.com/srwiley/oksvg/svgd.go:125 +0x66b
github.com/srwiley/oksvg.(*SvgIcon).Draw(0xc000158000, 0xc0000b87e0, 0x3ff0000000000000)
        /home/steve/go/src/github.com/srwiley/oksvg/svgd.go:83 +0x122
github.com/fyne-io/fyne/driver/gl.(*glCanvas).newGlImageTexture(0xc00027a080, 0x959fe0, 0xc0001961e0, 0xc00056a730)
        /home/steve/go/src/github.com/fyne-io/fyne/driver/gl/gl.go:134 +0x9c5
github.com/fyne-io/fyne/driver/gl.(*glCanvas).newGlImageTexture-fm(0x959fe0, 0xc0001961e0, 0xc0000e17d8)
        /home/steve/go/src/github.com/fyne-io/fyne/driver/gl/draw.go:116 +0x3e
github.com/fyne-io/fyne/driver/gl.getTexture(0x959fe0, 0xc0001961e0, 0xc0000e1860, 0x8)
        /home/steve/go/src/github.com/fyne-io/fyne/driver/gl/gl.go:34 +0x91
github.com/fyne-io/fyne/driver/gl.(*glCanvas).drawImage(0xc00027a080, 0xc0001961e0, 0x8, 0x8, 0x4a, 0x4a)
        /home/steve/go/src/github.com/fyne-io/fyne/driver/gl/draw.go:116 +0xf7
github.com/fyne-io/fyne/driver/gl.(*glCanvas).drawObject(0xc00027a080, 0x959fe0, 0xc0001961e0, 0x4, 0x4, 0x4a, 0x4a)
        /home/steve/go/src/github.com/fyne-io/fyne/driver/gl/draw.go:157 +0x2b5
github.com/fyne-io/fyne/driver/gl.(*glCanvas).paint.func1(0x959fe0, 0xc0001961e0, 0x4, 0x4)
        /home/steve/go/src/github.com/fyne-io/fyne/driver/gl/canvas.go:123 +0x64
github.com/fyne-io/fyne/driver/gl.walkObjects(0x959fe0, 0xc0001961e0, 0x4, 0x4, 0xc0000e1a58)
        /home/steve/go/src/github.com/fyne-io/fyne/driver/gl/draw.go:33 +0x1f6
github.com/fyne-io/fyne/driver/gl.walkObjects(0x959f20, 0xc00009b9e0, 0x0, 0x0, 0xc0000e1a58)
        /home/steve/go/src/github.com/fyne-io/fyne/driver/gl/draw.go:30 +0x197
github.com/fyne-io/fyne/driver/gl.(*glCanvas).paint(0xc00027a080, 0x4a, 0x4a)
        /home/steve/go/src/github.com/fyne-io/fyne/driver/gl/canvas.go:125 +0x124
github.com/fyne-io/fyne/driver/gl.(*gLDriver).runGL(0xc00000c800)
        /home/steve/go/src/github.com/fyne-io/fyne/driver/gl/loop.go:109 +0x617
github.com/fyne-io/fyne/driver/gl.(*gLDriver).Run(0xc00000c800)
        /home/steve/go/src/github.com/fyne-io/fyne/driver/gl/driver.go:82 +0x2b
github.com/fyne-io/fyne/driver/gl.(*window).ShowAndRun(0xc0000a81e0)
        /home/steve/go/src/github.com/fyne-io/fyne/driver/gl/window.go:161 +0x57
main.welcome(0x959a40, 0xc00000c820)
        /home/steve/go/src/github.com/fyne-io/examples/main.go:33 +0x270
main.main()
        /home/steve/go/src/github.com/fyne-io/examples/main.go:60 +0x4c9
exit status 2
```

**Comment by steveoc64** [comment]
can confirm that running the same code, over the same ssh connection, with the EFL driver ... works very very well, and is super quick.

Solitaire renders beautifully with the EFL build.

So its a GL rendering issue.

**Comment by andydotxyz** [comment]
Is your checkout of his code up to date?
I have no idea what the ssh connection might be doing to available colours etc

**Comment by steveoc64** [comment]
yes, its up to date.

Its not everyday that I develop over ssh though ... so its probably much of an edge case.  Suspect the actual issue is in the 3rd party code.  

Consider it low-priority at best.  Will fix it eventually anyway.

**Comment by jadr2ddude** [comment]
SSH forces everything through X/GLX. I suspect that this will still show up under certain configurations of non-SSH systems. Will try later with "weird" X modes.

**Comment by andydotxyz** [comment]
I just saw this issue on a macOS Mojave laptop, so perhaps it's not as limited as we thought?

**Comment by andydotxyz** [comment]
It looks like the StopColor field of the first stop in a gradient is not set (so nil).
Can you confirm the commit that your examples repo is on so I can eliminate any possible file issues (as the card back contained some information that oksvg does not yet support).

**Comment by andydotxyz** [comment]
Ouch the same thing happens on Windows...

**Comment by andydotxyz** [comment]
OK, it seems that there was an incompatibility with oksvg that got lost in a random git stash at my end... Apologies.

Pull an update and remove ~/.fyne to clear the icon cache - should be fixed
