### ISSUE TITLE
efl 1.20.7, random SEGV/ABRT ("double free or corruption"|"malloc_consolidate(): invalid chunk size")

### ISSUE THREAD

**Issue by ProhtMeyhet** [fyne-io/fyne#46]
i am on openSuse, which is the distribution the current Enlightenment Release Manager @simotek personally provides builds for e and efl, and tried running cmd/fyne_demo.

sadly, immediately after start i get random memory corruptions like the 2 below.

```
Information for package efl:
----------------------------
Repository     : EnlightenmentFactory
Name           : efl
Version        : 1.20.7-259.92
Arch           : x86_64
Vendor         : obs://build.opensuse.org/X11:Enlightenment
Installed Size : 3.3 MiB
Installed      : Yes
Status         : out-of-date (version 1.20.7-259.91 installed)
Source package : efl-1.20.7-259.92.src
```
```
double free or corruption (fasttop)
SIGABRT: abort
PC=0x7f972337508b m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x66cce0, 0xc0000f9630, 0xc000000000)
        /usr/lib64/go/current/src/runtime/cgocall.go:128 +0x5e fp=0xc0000f9600 sp=0xc0000f95c8 pc=0x4085ae
github.com/fyne-io/fyne/driver/efl._Cfunc_evas_object_del(0x4000001269bb)
        _cgo_gotypes.go:637 +0x41 fp=0xc0000f9630 sp=0xc0000f9600 pc=0x655ad1
github.com/fyne-io/fyne/driver/efl.(*eFLDriver).RenderedTextSize.func1.4(0x4000001269bb)
        /home/neo/go/src/github.com/fyne-io/fyne/driver/efl/text.go:83 +0x56 fp=0xc0000f9668 sp=0xc0000f9630 pc=0x6606a6
github.com/fyne-io/fyne/driver/efl.(*eFLDriver).RenderedTextSize.func1()
        /home/neo/go/src/github.com/fyne-io/fyne/driver/efl/text.go:83 +0x133 fp=0xc0000f96d8 sp=0xc0000f9668 pc=0x6607f3
github.com/fyne-io/fyne/driver/efl.runOnMain(0xc0001d1dc0)
        /home/neo/go/src/github.com/fyne-io/fyne/driver/efl/loop.go:150 +0x36 fp=0xc0000f9718 sp=0xc0000f96d8 pc=0x65c1a6
github.com/fyne-io/fyne/driver/efl.(*eFLDriver).RenderedTextSize(0xbab570, 0x714520, 0x1, 0xe, 0xc000000000, 0xc0000c06a8, 0xc0000f97c0)
        /home/neo/go/src/github.com/fyne-io/fyne/driver/efl/text.go:74 +0x138 fp=0xc0000f9760 sp=0xc0000f9718 pc=0x65c708
github.com/fyne-io/fyne/canvas.(*Text).MinSize(0xc0000f36c0, 0x76aa40, 0xc00008a780)
        /home/neo/go/src/github.com/fyne-io/fyne/canvas/text.go:24 +0x7e fp=0xc0000f97a8 sp=0xc0000f9760 pc=0x4d71fe
github.com/fyne-io/fyne/widget.(*buttonRenderer).MinSize(0xc00007d6e0, 0xc00008a780, 0x769900)
        /home/neo/go/src/github.com/fyne-io/fyne/widget/button.go:26 +0x60 fp=0xc0000f97d0 sp=0xc0000f97a8 pc=0x4da610
github.com/fyne-io/fyne/widget.(*baseWidget).minSize(0xc00008a780, 0x76aa40, 0xc00008a780, 0xc00008a780, 0xc000096400)
        /home/neo/go/src/github.com/fyne-io/fyne/widget/widget.go:46 +0x6d fp=0xc0000f9800 sp=0xc0000f97d0 pc=0x4e1e5d
github.com/fyne-io/fyne/widget.(*Button).MinSize(0xc00008a780, 0x76a3e0, 0xc00008a780)
        /home/neo/go/src/github.com/fyne-io/fyne/widget/button.go:134 +0x3e fp=0xc0000f9838 sp=0xc0000f9800 pc=0x4dac0e
github.com/fyne-io/fyne/layout.(*boxLayout).MinSize(0xc000084a44, 0xc0000d0180, 0x6, 0x8, 0x76ad40, 0xc000096460)
        /home/neo/go/src/github.com/fyne-io/fyne/layout/boxlayout.go:108 +0x145 fp=0xc0000f98a8 sp=0xc0000f9838 pc=0x4d9055
github.com/fyne-io/fyne/widget.(*boxRenderer).MinSize(0xc00007d6b0, 0xc000096460, 0x7698a0)
        /home/neo/go/src/github.com/fyne-io/fyne/widget/box.go:108 +0x4e fp=0xc0000f98e8 sp=0xc0000f98a8 pc=0x4da3ee
github.com/fyne-io/fyne/widget.(*baseWidget).minSize(0xc000096460, 0x76ad40, 0xc000096460, 0xc000096460, 0xc0000f9900)
        /home/neo/go/src/github.com/fyne-io/fyne/widget/widget.go:46 +0x6d fp=0xc0000f9918 sp=0xc0000f98e8 pc=0x4e1e5d
github.com/fyne-io/fyne/widget.(*Toolbar).MinSize(0xc000096460, 0x76a6e0, 0xc000096460)
        /home/neo/go/src/github.com/fyne-io/fyne/widget/toolbar.go:85 +0x3e fp=0xc0000f9950 sp=0xc0000f9918 pc=0x4e173e
github.com/fyne-io/fyne/layout.(*boxLayout).Layout(0xc00016a6fc, 0xc0000d0200, 0x8, 0x8, 0xa9, 0x23b)
        /home/neo/go/src/github.com/fyne-io/fyne/layout/boxlayout.go:55 +0x4b5 fp=0xc0000f9a20 sp=0xc0000f9950 pc=0x4d8ed5
github.com/fyne-io/fyne/widget.(*boxRenderer).Layout(0xc00007dad0, 0xa9, 0x23b)
        /home/neo/go/src/github.com/fyne-io/fyne/widget/box.go:112 +0x62 fp=0xc0000f9a60 sp=0xc0000f9a20 pc=0x4da482
github.com/fyne-io/fyne/widget.(*baseWidget).resize(0xc00008b2c0, 0xa9, 0x23b, 0x76a9e0, 0xc00008b2c0)
        /home/neo/go/src/github.com/fyne-io/fyne/widget/widget.go:26 +0x73 fp=0xc0000f9a90 sp=0xc0000f9a60 pc=0x4e1d23
github.com/fyne-io/fyne/widget.(*Box).Resize(0xc00008b2c0, 0xa9, 0x23b)
        /home/neo/go/src/github.com/fyne-io/fyne/widget/box.go:25 +0x52 fp=0xc0000f9ac8 sp=0xc0000f9a90 pc=0x4d9ce2
github.com/fyne-io/fyne/driver/efl.(*eflCanvas).resizeContent(0xc0000d0100)
        /home/neo/go/src/github.com/fyne-io/fyne/driver/efl/canvas.go:473 +0x144 fp=0xc0000f9b28 sp=0xc0000f9ac8 pc=0x65af84
github.com/fyne-io/fyne/driver/efl.onWindowResize(0x101b5c0)
        /home/neo/go/src/github.com/fyne-io/fyne/driver/efl/window.go:198 +0x113 fp=0xc0000f9b78 sp=0xc0000f9b28 pc=0x65d313
github.com/fyne-io/fyne/driver/efl._cgoexpwrap_3f20d64e3c1e_onWindowResize(0x101b5c0)
        _cgo_gotypes.go:1065 +0x2b fp=0xc0000f9b90 sp=0xc0000f9b78 pc=0x65707b
runtime.call32(0x0, 0x7fffc0f2ed90, 0x7fffc0f2ee28, 0x8)
        /usr/lib64/go/current/src/runtime/asm_amd64.s:522 +0x3b fp=0xc0000f9bc0 sp=0xc0000f9b90 pc=0x45a02b
runtime.cgocallbackg1(0x0)
        /usr/lib64/go/current/src/runtime/cgocall.go:316 +0x19b fp=0xc0000f9c38 sp=0xc0000f9bc0 pc=0x40894b
runtime.cgocallbackg(0x0)
        /usr/lib64/go/current/src/runtime/cgocall.go:194 +0xd6 fp=0xc0000f9ca0 sp=0xc0000f9c38 pc=0x408716
runtime.cgocallback_gofunc(0x4085d2, 0x66cc90, 0xc0000f9d30, 0xc00007d4a0)
        /usr/lib64/go/current/src/runtime/asm_amd64.s:775 +0x9b fp=0xc0000f9cc0 sp=0xc0000f9ca0 pc=0x45b5fb
runtime.asmcgocall(0x66cc90, 0xc0000f9d30)
        /usr/lib64/go/current/src/runtime/asm_amd64.s:622 +0x42 fp=0xc0000f9cc8 sp=0xc0000f9cc0 pc=0x45b492
runtime.cgocall(0x66cc90, 0xc0000f9d30, 0x0)
        /usr/lib64/go/current/src/runtime/cgocall.go:131 +0x82 fp=0xc0000f9d00 sp=0xc0000f9cc8 pc=0x4085d2
github.com/fyne-io/fyne/driver/efl._Cfunc_ecore_main_loop_iterate()
        _cgo_gotypes.go:584 +0x41 fp=0xc0000f9d30 sp=0xc0000f9d00 pc=0x655861
github.com/fyne-io/fyne/driver/efl.runEFL()
        /home/neo/go/src/github.com/fyne-io/fyne/driver/efl/loop.go:84 +0x1b2 fp=0xc0000f9e68 sp=0xc0000f9d30 pc=0x65b9e2
github.com/fyne-io/fyne/driver/efl.(*window).ShowAndRun(0xc00008c300)
        /home/neo/go/src/github.com/fyne-io/fyne/driver/efl/window.go:151 +0x35 fp=0xc0000f9e88 sp=0xc0000f9e68 pc=0x65cfc5
main.main()
        /home/neo/go/src/github.com/fyne-io/fyne/cmd/fyne_demo/main.go:114 +0xd50 fp=0xc0000f9f98 sp=0xc0000f9e88 pc=0x669d30
runtime.main()
        /usr/lib64/go/current/src/runtime/proc.go:201 +0x207 fp=0xc0000f9fe0 sp=0xc0000f9f98 pc=0x431467
runtime.goexit()
        /usr/lib64/go/current/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0000f9fe8 sp=0xc0000f9fe0 pc=0x45bd41

goroutine 19 [chan receive]:
github.com/fyne-io/fyne/app.NewAppWithDriver.func1(0xc000068180, 0xc0000947c0)
        /home/neo/go/src/github.com/fyne-io/fyne/app/app.go:79 +0x3d
created by github.com/fyne-io/fyne/app.NewAppWithDriver
        /home/neo/go/src/github.com/fyne-io/fyne/app/app.go:77 +0x119

rax    0x0
rbx    0x6
rcx    0x7f972337508b
rdx    0x0
rdi    0x2
rsi    0x7fffc0f2e7f0
rbp    0x7fffc0f2eb40
rsp    0x7fffc0f2e7f0
r8     0x0
r9     0x7fffc0f2e7f0
r10    0x8
r11    0x246
r12    0x1000
r13    0x7fffc0f2ea60
r14    0x10
r15    0x7f970c719000
rip    0x7f972337508b
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```
```
malloc_consolidate(): invalid chunk size
SIGABRT: abort
PC=0x7f530aafe08b m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x66cd30, 0xc0000f95f8, 0x29)
        /usr/lib64/go/current/src/runtime/cgocall.go:128 +0x5e fp=0xc0000f95c0 sp=0xc0000f9588 pc=0x4085ae
github.com/fyne-io/fyne/driver/efl._Cfunc_evas_object_text_font_set(0x400000104d3e, 0x2212070, 0xe)
        _cgo_gotypes.go:930 +0x45 fp=0xc0000f95f8 sp=0xc0000f95c0 pc=0x656ac5
github.com/fyne-io/fyne/driver/efl.updateFont.func1(0x400000104d3e, 0x2212070, 0xe)
        /home/neo/go/src/github.com/fyne-io/fyne/driver/efl/text.go:35 +0x68 fp=0xc0000f9630 sp=0xc0000f95f8 pc=0x660328
github.com/fyne-io/fyne/driver/efl.updateFont(0x400000104d3e, 0xc00015e000, 0xe, 0x0)
        /home/neo/go/src/github.com/fyne-io/fyne/driver/efl/text.go:35 +0xb9 fp=0xc0000f9668 sp=0xc0000f9630 pc=0x65c2e9
github.com/fyne-io/fyne/driver/efl.(*eFLDriver).RenderedTextSize.func1()
        /home/neo/go/src/github.com/fyne-io/fyne/driver/efl/text.go:79 +0xf3 fp=0xc0000f96d8 sp=0xc0000f9668 pc=0x6607b3
github.com/fyne-io/fyne/driver/efl.runOnMain(0xc0001e94c0)
        /home/neo/go/src/github.com/fyne-io/fyne/driver/efl/loop.go:150 +0x36 fp=0xc0000f9718 sp=0xc0000f96d8 pc=0x65c1a6
github.com/fyne-io/fyne/driver/efl.(*eFLDriver).RenderedTextSize(0xbab570, 0x714520, 0x1, 0xe, 0xc000000000, 0xc00017c5d8, 0x15)
        /home/neo/go/src/github.com/fyne-io/fyne/driver/efl/text.go:74 +0x138 fp=0xc0000f9760 sp=0xc0000f9718 pc=0x65c708
github.com/fyne-io/fyne/canvas.(*Text).MinSize(0xc000166070, 0x76aa40, 0xc00005e2a0)
        /home/neo/go/src/github.com/fyne-io/fyne/canvas/text.go:24 +0x7e fp=0xc0000f97a8 sp=0xc0000f9760 pc=0x4d71fe
github.com/fyne-io/fyne/widget.(*buttonRenderer).MinSize(0xc00015a1e0, 0xc00005e2a0, 0x769900)
        /home/neo/go/src/github.com/fyne-io/fyne/widget/button.go:26 +0x60 fp=0xc0000f97d0 sp=0xc0000f97a8 pc=0x4da610
github.com/fyne-io/fyne/widget.(*baseWidget).minSize(0xc00005e2a0, 0x76aa40, 0xc00005e2a0, 0x26, 0x1d)
        /home/neo/go/src/github.com/fyne-io/fyne/widget/widget.go:46 +0x6d fp=0xc0000f9800 sp=0xc0000f97d0 pc=0x4e1e5d
github.com/fyne-io/fyne/widget.(*Button).MinSize(0xc00005e2a0, 0x26, 0x1d)
        /home/neo/go/src/github.com/fyne-io/fyne/widget/button.go:134 +0x3e fp=0xc0000f9838 sp=0xc0000f9800 pc=0x4dac0e
github.com/fyne-io/fyne/layout.(*boxLayout).MinSize(0xc000018414, 0xc00015e080, 0x6, 0x8, 0x76ad40, 0xc000160140)
        /home/neo/go/src/github.com/fyne-io/fyne/layout/boxlayout.go:109 +0x163 fp=0xc0000f98a8 sp=0xc0000f9838 pc=0x4d9073
github.com/fyne-io/fyne/widget.(*boxRenderer).MinSize(0xc00015a1b0, 0xc000160140, 0x7698a0)
        /home/neo/go/src/github.com/fyne-io/fyne/widget/box.go:108 +0x4e fp=0xc0000f98e8 sp=0xc0000f98a8 pc=0x4da3ee
github.com/fyne-io/fyne/widget.(*baseWidget).minSize(0xc000160140, 0x76ad40, 0xc000160140, 0xc000160140, 0xc0000f9900)
        /home/neo/go/src/github.com/fyne-io/fyne/widget/widget.go:46 +0x6d fp=0xc0000f9918 sp=0xc0000f98e8 pc=0x4e1e5d
github.com/fyne-io/fyne/widget.(*Toolbar).MinSize(0xc000160140, 0x76a6e0, 0xc000160140)
        /home/neo/go/src/github.com/fyne-io/fyne/widget/toolbar.go:85 +0x3e fp=0xc0000f9950 sp=0xc0000f9918 pc=0x4e173e
github.com/fyne-io/fyne/layout.(*boxLayout).Layout(0xc0001800cc, 0xc00015e100, 0x8, 0x8, 0xa9, 0x23b)
        /home/neo/go/src/github.com/fyne-io/fyne/layout/boxlayout.go:55 +0x4b5 fp=0xc0000f9a20 sp=0xc0000f9950 pc=0x4d8ed5
github.com/fyne-io/fyne/widget.(*boxRenderer).Layout(0xc00015a5d0, 0xa9, 0x23b)
        /home/neo/go/src/github.com/fyne-io/fyne/widget/box.go:112 +0x62 fp=0xc0000f9a60 sp=0xc0000f9a20 pc=0x4da482
github.com/fyne-io/fyne/widget.(*baseWidget).resize(0xc00005ede0, 0xa9, 0x23b, 0x76a9e0, 0xc00005ede0)
        /home/neo/go/src/github.com/fyne-io/fyne/widget/widget.go:26 +0x73 fp=0xc0000f9a90 sp=0xc0000f9a60 pc=0x4e1d23
github.com/fyne-io/fyne/widget.(*Box).Resize(0xc00005ede0, 0xa9, 0x23b)
        /home/neo/go/src/github.com/fyne-io/fyne/widget/box.go:25 +0x52 fp=0xc0000f9ac8 sp=0xc0000f9a90 pc=0x4d9ce2
github.com/fyne-io/fyne/driver/efl.(*eflCanvas).resizeContent(0xc00015e000)
        /home/neo/go/src/github.com/fyne-io/fyne/driver/efl/canvas.go:473 +0x144 fp=0xc0000f9b28 sp=0xc0000f9ac8 pc=0x65af84
github.com/fyne-io/fyne/driver/efl.onWindowResize(0x201dc40)
        /home/neo/go/src/github.com/fyne-io/fyne/driver/efl/window.go:198 +0x113 fp=0xc0000f9b78 sp=0xc0000f9b28 pc=0x65d313
github.com/fyne-io/fyne/driver/efl._cgoexpwrap_3f20d64e3c1e_onWindowResize(0x201dc40)
        _cgo_gotypes.go:1065 +0x2b fp=0xc0000f9b90 sp=0xc0000f9b78 pc=0x65707b
runtime.call32(0x0, 0x7ffcb9668360, 0x7ffcb96683f8, 0x8)
        /usr/lib64/go/current/src/runtime/asm_amd64.s:522 +0x3b fp=0xc0000f9bc0 sp=0xc0000f9b90 pc=0x45a02b
runtime.cgocallbackg1(0x0)
        /usr/lib64/go/current/src/runtime/cgocall.go:316 +0x19b fp=0xc0000f9c38 sp=0xc0000f9bc0 pc=0x40894b
runtime.cgocallbackg(0x0)
        /usr/lib64/go/current/src/runtime/cgocall.go:194 +0xd6 fp=0xc0000f9ca0 sp=0xc0000f9c38 pc=0x408716
runtime.cgocallback_gofunc(0x4085d2, 0x66cc90, 0xc0000f9d30, 0xc00007d4a0)
        /usr/lib64/go/current/src/runtime/asm_amd64.s:775 +0x9b fp=0xc0000f9cc0 sp=0xc0000f9ca0 pc=0x45b5fb
runtime.asmcgocall(0x66cc90, 0xc0000f9d30)
        /usr/lib64/go/current/src/runtime/asm_amd64.s:622 +0x42 fp=0xc0000f9cc8 sp=0xc0000f9cc0 pc=0x45b492
runtime.cgocall(0x66cc90, 0xc0000f9d30, 0x0)
        /usr/lib64/go/current/src/runtime/cgocall.go:131 +0x82 fp=0xc0000f9d00 sp=0xc0000f9cc8 pc=0x4085d2
github.com/fyne-io/fyne/driver/efl._Cfunc_ecore_main_loop_iterate()
        _cgo_gotypes.go:584 +0x41 fp=0xc0000f9d30 sp=0xc0000f9d00 pc=0x655861
github.com/fyne-io/fyne/driver/efl.runEFL()
        /home/neo/go/src/github.com/fyne-io/fyne/driver/efl/loop.go:84 +0x1b2 fp=0xc0000f9e68 sp=0xc0000f9d30 pc=0x65b9e2
github.com/fyne-io/fyne/driver/efl.(*window).ShowAndRun(0xc00005a080)
        /home/neo/go/src/github.com/fyne-io/fyne/driver/efl/window.go:151 +0x35 fp=0xc0000f9e88 sp=0xc0000f9e68 pc=0x65cfc5
main.main()
        /home/neo/go/src/github.com/fyne-io/fyne/cmd/fyne_demo/main.go:114 +0xd50 fp=0xc0000f9f98 sp=0xc0000f9e88 pc=0x669d30
runtime.main()
        /usr/lib64/go/current/src/runtime/proc.go:201 +0x207 fp=0xc0000f9fe0 sp=0xc0000f9f98 pc=0x431467
runtime.goexit()
        /usr/lib64/go/current/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0000f9fe8 sp=0xc0000f9fe0 pc=0x45bd41

goroutine 4 [chan receive]:
github.com/fyne-io/fyne/app.NewAppWithDriver.func1(0xc000158000, 0xc00000c040)
        /home/neo/go/src/github.com/fyne-io/fyne/app/app.go:79 +0x3d
created by github.com/fyne-io/fyne/app.NewAppWithDriver
        /home/neo/go/src/github.com/fyne-io/fyne/app/app.go:77 +0x119

rax    0x0
rbx    0x6
rcx    0x7f530aafe08b
rdx    0x0
rdi    0x2
rsi    0x7ffcb9667bc0
rbp    0x7ffcb9667f10
rsp    0x7ffcb9667bc0
r8     0x0
r9     0x7ffcb9667bc0
r10    0x8
r11    0x246
r12    0x1000
r13    0x7ffcb9667e30
r14    0x10
r15    0x7f52f1c32000
rip    0x7f530aafe08b
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```

**Comment by ProhtMeyhet** [comment]
oh, and i've just successfully compiled and ran ephoto against this install of efl, so this efl works.

**Comment by andydotxyz** [comment]
Out of curiosity does it work correctly if you run "go run -tags gl ."?
I ask merely because the EFL driver has caused many problems and there is an alternative OpenGL one nearly ready...

**Comment by ProhtMeyhet** [comment]
ah and the tag building for whatever reason doesn't pull all requirements. have to fix manually so leaving it here...

```
go get github.com/go-gl/gl/v3.2-core/gl
go get github.com/go-gl/glfw/v3.2/glfw
go get github.com/golang/freetype
go get github.com/srwiley/oksvg
go get github.com/srwiley/rasterx

```

**Comment by andydotxyz** [comment]
The OpenGL driver is now the default, so if you update your fyne library the application should work as expected.

I'd be grateful if you could report if the flicker is better or worse, there has been much development of the window sizing code.
