### ISSUE TITLE
App panics when window is minimized

### ISSUE THREAD

**Issue by spatocode** [fyne-io/fyne#484]
**Describe the bug**
Fyne app crashes with panics with  when window is minimized. This only happens when the form widget is on display. I tried to find the cause but couldn't.

**To Reproduce**
1. Go to widget
2. Click on form
3. Minimize the window

**Device (please complete the following information):**
 - OS: [Windows]
 - Version [10]
 - Go version [1.12]
 - Fyne version [1.1.1]

**Comment by andydotxyz** [comment]
Can you please provide the stack trace or command output?

**Comment by spatocode** [comment]
This is the stack trace from the develop version. But, this bug is also replicated in version 1.1.1. 

panic: runtime error: slice bounds out of range

goroutine 1 [running, locked to thread]:
image/draw.drawGlyphOver(0x12c02f00, 0xfffffffe, 0xfffffff1, 0x0, 0xfffffffe, 0x12906cb0, 0x12c02f20, 0x0, 0xec4)
        c:/go/src/image/draw/draw.go:484 +0x251
image/draw.DrawMask(0xaec4e0, 0x12c02f00, 0xfffffffe, 0xfffffff1, 0x0, 0xfffffffe, 0xaebe10, 0x12906cb0, 0x0, 0x0, ...)
        c:/go/src/image/draw/draw.go:150 +0x8d9
fyne.io/fyne/vendor/golang.org/x/image/font.(*Drawer).DrawString(0x12833924, 0x12854530, 0xa)
        C:/Users/HP/Documents/REPO/GO/src/fyne.io/fyne/vendor/golang.org/x/image/font/font.go:178 +0x140
fyne.io/fyne/internal/painter/gl.(*glPainter).newGlTextTexture(0x128b85e0, 0xaee4e0, 0x12be8140, 0x128838dc)
        C:/Users/HP/Documents/REPO/GO/src/fyne.io/fyne/internal/painter/gl/gl_common.go:121 +0x33b
fyne.io/fyne/internal/painter/gl.getTexture(0xaee4e0, 0x12be8140, 0x128339bc, 0xb3)
        C:/Users/HP/Documents/REPO/GO/src/fyne.io/fyne/internal/painter/gl/gl_common.go:28 +0x77
fyne.io/fyne/internal/painter/gl.(*glPainter).drawText(0x128b85e0, 0x12be8140, 0xb3, 0x6b, 0x0, 0x0)
        C:/Users/HP/Documents/REPO/GO/src/fyne.io/fyne/internal/painter/gl/draw.go:153 +0x124
fyne.io/fyne/internal/painter/gl.(*glPainter).drawObject(0x128b85e0, 0xaee4e0, 0x12be8140, 0xb3, 0x6b, 0x0, 0x0)
        C:/Users/HP/Documents/REPO/GO/src/fyne.io/fyne/internal/painter/gl/draw.go:175 +0x41f
fyne.io/fyne/internal/painter/gl.(*glPainter).Paint(0x128b85e0, 0xaee4e0, 0x12be8140, 0xb3, 0x6b, 0x0, 0x0)
        C:/Users/HP/Documents/REPO/GO/src/fyne.io/fyne/internal/painter/gl/painter.go:67 +0x6e
fyne.io/fyne/internal/driver/glfw.(*glCanvas).paint.func1(0x12ffe930, 0xb3, 0x6b)
        C:/Users/HP/Documents/REPO/GO/src/fyne.io/fyne/internal/driver/glfw/canvas.go:301 +0xf1
fyne.io/fyne/internal/driver/glfw.(*glCanvas).walkTree.func1(0xaee4e0, 0x12be8140, 0xb3, 0x6b, 0x0, 0x0, 0x7fffffff, 0x7fffffff, 0x408b01)
        C:/Users/HP/Documents/REPO/GO/src/fyne.io/fyne/internal/driver/glfw/canvas.go:355 +0x116
fyne.io/fyne/internal/driver.walkObjectTree(0xaee4e0, 0x12be8140, 0xaeeb60, 0x12be8100, 0xaf, 0x67, 0x0, 0x0, 0x7fffffff, 0x7fffffff, ...)
        C:/Users/HP/Documents/REPO/GO/src/fyne.io/fyne/internal/driver/util.go:74 +0x1fc
fyne.io/fyne/internal/driver.walkObjectTree(0xaeeb60, 0x12be8100, 0xaee660, 0x1288a380, 0xab, 0x63, 0x0, 0x0, 0x7fffffff, 0x7fffffff, ...)
        C:/Users/HP/Documents/REPO/GO/src/fyne.io/fyne/internal/driver/util.go:81 +0x16a
fyne.io/fyne/internal/driver.walkObjectTree(0xaee660, 0x1288a380, 0xaee2e0, 0x12874ba0, 0x56, 0x63, 0x0, 0x0, 0x7fffffff, 0x7fffffff, ...)
        C:/Users/HP/Documents/REPO/GO/src/fyne.io/fyne/internal/driver/util.go:81 +0x16a
fyne.io/fyne/internal/driver.walkObjectTree(0xaee2e0, 0x12874ba0, 0xaee6a0, 0x12874b70, 0x56, 0x63, 0x0, 0x0, 0x7fffffff, 0x7fffffff, ...)
        C:/Users/HP/Documents/REPO/GO/src/fyne.io/fyne/internal/driver/util.go:81 +0x16a
fyne.io/fyne/internal/driver.walkObjectTree(0xaee6a0, 0x12874b70, 0xaee9a0, 0x12874cf0, 0x56, 0x42, 0x0, 0x0, 0x7fffffff, 0x7fffffff, ...)
        C:/Users/HP/Documents/REPO/GO/src/fyne.io/fyne/internal/driver/util.go:81 +0x16a
fyne.io/fyne/internal/driver.walkObjectTree(0xaee9a0, 0x12874cf0, 0xaee2e0, 0x12874d80, 0x56, 0x21, 0x0, 0x0, 0x7fffffff, 0x7fffffff, ...)
        C:/Users/HP/Documents/REPO/GO/src/fyne.io/fyne/internal/driver/util.go:81 +0x16a
fyne.io/fyne/internal/driver.walkObjectTree(0xaee2e0, 0x12874d80, 0xaee9a0, 0x128ecbd0, 0x4, 0x21, 0x0, 0x0, 0x7fffffff, 0x7fffffff, ...)
        C:/Users/HP/Documents/REPO/GO/src/fyne.io/fyne/internal/driver/util.go:81 +0x16a
fyne.io/fyne/internal/driver.walkObjectTree(0xaee9a0, 0x128ecbd0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fffffff, 0x7fffffff, ...)
        C:/Users/HP/Documents/REPO/GO/src/fyne.io/fyne/internal/driver/util.go:81 +0x16a
fyne.io/fyne/internal/driver.WalkVisibleObjectTree(0xaee9a0, 0x128ecbd0, 0x12833dc4, 0x12833db0, 0x387781e8)
        C:/Users/HP/Documents/REPO/GO/src/fyne.io/fyne/internal/driver/util.go:25 +0x81
fyne.io/fyne/internal/driver/glfw.(*glCanvas).walkTree(0x128a6140, 0x12c02440, 0x12833e04, 0x12833dfc)
        C:/Users/HP/Documents/REPO/GO/src/fyne.io/fyne/internal/driver/glfw/canvas.go:376 +0xf9
fyne.io/fyne/internal/driver/glfw.(*glCanvas).walkTrees(0x128a6140, 0x12833e04, 0x12833dfc)
        C:/Users/HP/Documents/REPO/GO/src/fyne.io/fyne/internal/driver/glfw/canvas.go:316 +0x3f
fyne.io/fyne/internal/driver/glfw.(*glCanvas).paint(0x128a6140, 0x0, 0x0)
        C:/Users/HP/Documents/REPO/GO/src/fyne.io/fyne/internal/driver/glfw/canvas.go:309 +0xcc
fyne.io/fyne/internal/driver/glfw.(*gLDriver).runGL.func1()
        C:/Users/HP/Documents/REPO/GO/src/fyne.io/fyne/internal/driver/glfw/loop.go:114 +0x6e
fyne.io/fyne/internal/driver/glfw.(*window).RunWithContext(0x128a60a0, 0x12833eac)
        C:/Users/HP/Documents/REPO/GO/src/fyne.io/fyne/internal/driver/glfw/window.go:988 +0x2b
fyne.io/fyne/internal/driver/glfw.(*gLDriver).runGL(0x128b84c0)
        C:/Users/HP/Documents/REPO/GO/src/fyne.io/fyne/internal/driver/glfw/loop.go:107 +0x207
fyne.io/fyne/internal/driver/glfw.(*gLDriver).Run(0x128b84c0)
        C:/Users/HP/Documents/REPO/GO/src/fyne.io/fyne/internal/driver/glfw/driver.go:66 +0x21
fyne.io/fyne/internal/driver/glfw.(*window).ShowAndRun(0x128a60a0)
        C:/Users/HP/Documents/REPO/GO/src/fyne.io/fyne/internal/driver/glfw/window.go:364 +0x46
main.main()
        C:/Users/HP/Documents/REPO/GO/src/fyne.io/fyne/cmd/fyne_demo/main.go:71 +0x767

**Comment by spatocode** [comment]
I couldn't replicate it anymore. Thanks!

Gonna close this issue now.
