### ISSUE TITLE
widgets.Entry outside the main function

### ISSUE THREAD

**Issue by zhangzitao** [fyne-io/fyne#490]
Found a problem: if you define ```var entry = widgets.Entry``` outside the main function, there is no problem in building progress. But when you run app, nil pointer problem appear, wrong with goroutine.

    panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xc0000005 code=0x0 addr=0x50 pc=0x4f90a3]

    goroutine 1 [running, locked to thread]:

**Comment by andydotxyz** [comment]
This should work fine. It sounds like you might not have initialised the variable. Can you share the code?

**Comment by zhangzitao** [comment]
```
package main

import (
	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
)

var tagText = widget.NewLabel("")
var checkText = widget.NewLabel("")
var entry *widget.Entry

// var entry = widget.NewEntry()

func main() {
	app := app.New()

	w := app.NewWindow("Title")
	w.CenterOnScreen()
	w.Resize(fyne.NewSize(900, 600))
	w.Canvas().SetScale(2)
	lHbox := widget.NewVBox()
	entry := widget.NewEntry()
	check := widget.NewButton("Check Item", func() {})
	submit := widget.NewButton("Submit Item", func() {})
	lHbox.Append(entry)
	lHbox.Append(widget.NewHBox(check, submit))
	lHbox.Append(checkText)
	lHbox.Append(tagText)

	rHbox := widget.NewVBox()
	itemEntry := widget.NewEntry()
	rHbox.Append(itemEntry)
	rHbox.Append(widget.NewLabel("All Tags:"))
	scroller := widget.NewScrollContainer(rHbox)

	w.SetContent(widget.NewHBox(
		scroller,
		lHbox,
	))

	w.ShowAndRun()
}
```

This code above running perfect. But this not:
```
var entry = widget.NewEntry()

func main() {
    ...
    lHbox.Append(entry)
}
```

Full error message:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x50 pc=0x4f90a3]

goroutine 1 [running, locked to thread]:
fyne.io/fyne/theme.current(0x0, 0x0)
        C:/Users/zt/go/pkg/mod/fyne.io/fyne@v1.1.2/theme/theme.go:227 +0x33
fyne.io/fyne/theme.ButtonColor(0xc00007be40, 0x0)
        C:/Users/zt/go/pkg/mod/fyne.io/fyne@v1.1.2/theme/theme.go:237 +0x29
fyne.io/fyne/widget.(*Entry).CreateRenderer(0xc000046410, 0x910560, 0xc000046410)
        C:/Users/zt/go/pkg/mod/fyne.io/fyne@v1.1.2/widget/entry.go:925 +0x32d
fyne.io/fyne/widget.Renderer(0x964500, 0xc000046410, 0xc000046450, 0xc00003e820)
        C:/Users/zt/go/pkg/mod/fyne.io/fyne@v1.1.2/widget/widget.go:98 +0xb6
fyne.io/fyne/widget.Refresh(0x964500, 0xc000046410)
        C:/Users/zt/go/pkg/mod/fyne.io/fyne@v1.1.2/widget/widget.go:115 +0x3c
fyne.io/fyne/widget.NewEntry(0x0)
        C:/Users/zt/go/pkg/mod/fyne.io/fyne@v1.1.2/widget/entry.go:985 +0x61
main.init.ializers()
        C:/Users/zt/go/src/zitao/repeat-fyne-bug/main.go:11 +0x6f
```

**Comment by andydotxyz** [comment]
I can’t tell for sure because you didn’t post the full code that does not work. My suspicion would be that you have to variables called “entry” and one is shadowing the other so it’s not setting the value you expect, this leaving one unexpectedly nil.

**Comment by zhangzitao** [comment]
The full code that does not work:
```
package main

import (
	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
)

var entry = widget.NewEntry()

func main() {
	app := app.New()

	w := app.NewWindow("Title")
	lHbox := widget.NewVBox()
	lHbox.Append(entry)

	w.SetContent(widget.NewHBox(
		lHbox,
	))

	w.ShowAndRun()
}
```
Thanks!

**Comment by andydotxyz** [comment]
Thanks, confirmed.
The application has not been set up which causes issues with theme handling.
This should not crash :)

**Comment by andydotxyz** [comment]
Until this is fixed you can work around it by moving the app creation above the entry widget like this:

`var a = app.New()`

**Comment by andydotxyz** [comment]
Ready for testing on develop branch
