### ISSUE TITLE
fyne_demo not runing  on FreeBSD

### ISSUE THREAD

**Issue by timsan7sk** [fyne-io/fyne#5178]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Can't run fyne_demo on FreeBSD 14

### How to reproduce

```sh
go run fyne.io/fyne/v2/cmd/fyne_demo@latest
```

### Screenshots

![Screenshot_2024-04-05_12-25-08](https://github.com/user-attachments/assets/1442a222-22dd-4694-b7cd-c2afe8c93560)

### Example code

```
timsan@nitec.kz:~$ go run fyne.io/fyne/v2/cmd/fyne_demo@latest
panic: failed to compile OpenGL shader:

>>> SHADER SOURCE
#version 110

attribute vec3 vert;
attribute vec2 vertTexCoord;
varying vec2 fragTexCoord;

void main() {
    fragTexCoord = vertTexCoord;

    gl_Position = vec4(vert, 1);
}
<<< SHADER SOURCE

goroutine 68 [running, locked to thread]:
fyne.io/fyne/v2/internal/painter/gl.(*painter).createProgram(0x8744c60a0, {0x37380d?, 0x0?})
	/home/timsan/go/pkg/mod/fyne.io/fyne/v2@v2.5.1/internal/painter/gl/painter.go:155 +0x5ac
fyne.io/fyne/v2/internal/painter/gl.(*painter).Init(0x8744c60a0)
	/home/timsan/go/pkg/mod/fyne.io/fyne/v2@v2.5.1/internal/painter/gl/gl_core.go:73 +0xda
fyne.io/fyne/v2/internal/driver/glfw.(*window).create.func2()
	/home/timsan/go/pkg/mod/fyne.io/fyne/v2@v2.5.1/internal/driver/glfw/window_desktop.go:764 +0x6a
fyne.io/fyne/v2/internal/driver/glfw.(*window).RunWithContext(0x87441c700, 0x87442a480)
	/home/timsan/go/pkg/mod/fyne.io/fyne/v2@v2.5.1/internal/driver/glfw/window.go:929 +0x43
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread.func1()
	/home/timsan/go/pkg/mod/fyne.io/fyne/v2@v2.5.1/internal/driver/glfw/loop.go:249 +0x12c
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread in goroutine 1
	/home/timsan/go/pkg/mod/fyne.io/fyne/v2@v2.5.1/internal/driver/glfw/loop.go:241 +0xbb
exit status 2
timsan@nitec.kz:~$ 
```

### Fyne version

2.5.1

### Go compiler version

1.22.2

### Operating system and version

FreeBSD

**Comment by andydotxyz** [comment]
Does your FreeBSD have the OpenGL driver / GLX installed?
We test it fairly regularly on FreeBSD and OpenBSD and know it works on our hardware.

**Comment by timsan7sk** [comment]
Hi there!
```sh
timsan@nitec.kz:~$ /usr/local/bin/glxinfo | grep glx
server glx vendor string: NVIDIA Corporation
server glx version string: 1.4
server glx extensions:
client glx vendor string: NVIDIA Corporation
client glx version string: 1.4
client glx extensions:
timsan@nitec.kz:~$ /usr/local/bin/glxinfo | grep OpenGL
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 660 Ti/PCIe/SSE2
OpenGL core profile version string: 4.5.0 NVIDIA 390.154
OpenGL core profile shading language version string: 4.50 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.5.0 NVIDIA 390.154
OpenGL shading language version string: 4.50 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 390.154
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

**Comment by andydotxyz** [comment]
Sorry I've not had any more thoughts.
if possible could you test v1.5.3 and develop versions to see if it's still the same?
