### ISSUE TITLE
Panic on demo Icons button

### ISSUE THREAD

**Issue by krostar** [fyne-io/fyne#60]
Hi,

I'm trying the demo and it's panicking on click on the Demos menu, in the Icons items, with the following stacktrace:

```
panic: runtime error: index out of range

goroutine 1 [running, locked to thread]:
fyne.io/fyne/vendor/golang.org/x/image/vector.(*Rasterizer).rasterizeDstRGBASrcUniformOpOver(0xc00011c0d0, 0xc000480500, 0x0, 0xffffffffffffffdb, 0x2, 0x0, 0xffff0000ffff, 0xffff0000ffff)
	/Users/alexis.destrez/Work/go/src/fyne.io/fyne/vendor/golang.org/x/image/vector/vector.go:398 +0x289
fyne.io/fyne/vendor/golang.org/x/image/vector.(*Rasterizer).Draw(0xc00011c0d0, 0x426e820, 0xc000480500, 0x0, 0xffffffffffffffdb, 0x2, 0x0, 0x426e4e0, 0xc000480540, 0x0, ...)
	/Users/alexis.destrez/Work/go/src/fyne.io/fyne/vendor/golang.org/x/image/vector/vector.go:287 +0x2e3
fyne.io/fyne/vendor/github.com/srwiley/rasterx.(*ScannerGV).Draw(0xc00011c0d0)
	/Users/alexis.destrez/Work/go/src/fyne.io/fyne/vendor/github.com/srwiley/rasterx/scan.go:141 +0xb0
fyne.io/fyne/vendor/github.com/srwiley/oksvg.(*SvgPath).DrawTransformed(0xc0004520e0, 0xc000124120, 0x3ff0000000000000, 0x3fb5555555555555, 0x0, 0x0, 0xbff8aaaaaaaaaaab, 0x0, 0x0)
	/Users/alexis.destrez/Work/go/src/fyne.io/fyne/vendor/github.com/srwiley/oksvg/svgd.go:125 +0x66b
fyne.io/fyne/vendor/github.com/srwiley/oksvg.(*SvgIcon).Draw(0xc000118000, 0xc000124120, 0x3ff0000000000000)
	/Users/alexis.destrez/Work/go/src/fyne.io/fyne/vendor/github.com/srwiley/oksvg/svgd.go:83 +0x122
fyne.io/fyne/driver/gl.(*glCanvas).newGlImageTexture(0xc0004801c0, 0x426f4a0, 0xc000482f50, 0xc0004ea420)
	/Users/alexis.destrez/Work/go/src/fyne.io/fyne/driver/gl/gl.go:170 +0xe89
fyne.io/fyne/driver/gl.(*glCanvas).newGlImageTexture-fm(0x426f4a0, 0xc000482f50, 0xc00009f968)
	/Users/alexis.destrez/Work/go/src/fyne.io/fyne/driver/gl/draw.go:135 +0x3e
fyne.io/fyne/driver/gl.getTexture(0x426f4a0, 0xc000482f50, 0xc00009fa10, 0xc00009f9d8)
	/Users/alexis.destrez/Work/go/src/fyne.io/fyne/driver/gl/gl.go:46 +0x127
fyne.io/fyne/driver/gl.(*glCanvas).drawImage(0xc0004801c0, 0xc000482f50, 0x4, 0x25, 0x8, 0x8)
	/Users/alexis.destrez/Work/go/src/fyne.io/fyne/driver/gl/draw.go:135 +0x7b
fyne.io/fyne/driver/gl.(*glCanvas).drawObject(0xc0004801c0, 0x426f4a0, 0xc000482f50, 0x4, 0x25, 0x8, 0x8)
	/Users/alexis.destrez/Work/go/src/fyne.io/fyne/driver/gl/draw.go:177 +0x2b5
fyne.io/fyne/driver/gl.(*glCanvas).paint.func1(0x426f4a0, 0xc000482f50, 0x4, 0x25)
	/Users/alexis.destrez/Work/go/src/fyne.io/fyne/driver/gl/canvas.go:131 +0x64
fyne.io/fyne/driver/gl.walkObjects(0x426f4a0, 0xc000482f50, 0x4, 0x25, 0xc00009fc90)
	/Users/alexis.destrez/Work/go/src/fyne.io/fyne/driver/gl/draw.go:29 +0x1f6
fyne.io/fyne/driver/gl.walkObjects(0x426f8c0, 0xc00005c240, 0x4, 0x4, 0xc00009fc90)
	/Users/alexis.destrez/Work/go/src/fyne.io/fyne/driver/gl/draw.go:26 +0x197
fyne.io/fyne/driver/gl.walkObjects(0x426f380, 0xc0004fa2d0, 0x0, 0x0, 0xc00009fc90)
	/Users/alexis.destrez/Work/go/src/fyne.io/fyne/driver/gl/draw.go:19 +0x2bb
fyne.io/fyne/driver/gl.(*glCanvas).paint(0xc0004801c0, 0x8, 0x8)
	/Users/alexis.destrez/Work/go/src/fyne.io/fyne/driver/gl/canvas.go:133 +0x124
fyne.io/fyne/driver/gl.(*gLDriver).runGL(0xc00000c460)
	/Users/alexis.destrez/Work/go/src/fyne.io/fyne/driver/gl/loop.go:101 +0x44d
fyne.io/fyne/driver/gl.(*gLDriver).Run(0xc00000c460)
	/Users/alexis.destrez/Work/go/src/fyne.io/fyne/driver/gl/driver.go:82 +0x2b
fyne.io/fyne/driver/gl.(*window).ShowAndRun(0xc00008e3c0)
	/Users/alexis.destrez/Work/go/src/fyne.io/fyne/driver/gl/window.go:179 +0x57
main.main()
	/Users/alexis.destrez/Work/go/src/fyne.io/fyne/cmd/fyne_demo/main.go:118 +0xdb4
exit status 2
```

Here is few more information:
```console
$> go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/alexis.destrez/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/alexis.destrez/Work/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0k/3xk6gf990yq1szxx_6fx0ltm28gp8s/T/go-build859804847=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

```console
$> go version
go version go1.11 darwin/amd64
```

I hope it helps,
krostar

**Comment by andydotxyz** [comment]
Thanks for the report.
Just looking for some other information/hints:
* Did you run fyne_demo with any parameters?
* Did the icons demo load correctly until you clicked the icons at the top - or did it crash when loading the icons window?

**Comment by philippgille** [comment]
The same happened to me, but only in a specific case. When starting the demo and clicking *only* the Icons demo it works fine. But when clicking the Canvas demo, *leaving the new Canvas window open* and then clicking on the Icons demo, the app crashes.

Stacktrace in my case:
```
panic: runtime error: index out of range

goroutine 1 [running, locked to thread]:
fyne.io/fyne/vendor/golang.org/x/image/vector.(*Rasterizer).rasterizeDstRGBASrcUniformOpOver(0xc042066410, 0xc04206a600, 0x0, 0xffffffffffffffe1, 0x70, 0x0, 0xffff0000ffff, 0xffff0000ffff)
        C:/path/to/go/src/fyne.io/fyne/vendor/golang.org/x/image/vector/vector.go:398 +0x276
fyne.io/fyne/vendor/golang.org/x/image/vector.(*Rasterizer).Draw(0xc042066410, 0x6607e0, 0xc04206a600, 0x0, 0xffffffffffffffe1, 0x70, 0x0, 0x6604e0, 0xc04206a640, 0x0, ...)
        C:/path/to/go/src/fyne.io/fyne/vendor/golang.org/x/image/vector/vector.go:287 +0x2f0
fyne.io/fyne/vendor/github.com/srwiley/rasterx.(*ScannerGV).Draw(0xc042066410)
        C:/path/to/go/src/fyne.io/fyne/vendor/github.com/srwiley/rasterx/scan.go:141 +0xb7
fyne.io/fyne/vendor/github.com/srwiley/oksvg.(*SvgPath).DrawTransformed(0xc0420820e0, 0xc0420d25a0, 0x3ff0000000000000, 0x4012aaaaaaaaaaab, 0x0, 0x0, 0xbff4aaaaaaaaaaab, 0x0, 0x0)
        C:/path/to/go/src/fyne.io/fyne/vendor/github.com/srwiley/oksvg/svgd.go:125 +0x654
fyne.io/fyne/vendor/github.com/srwiley/oksvg.(*SvgIcon).Draw(0xc042068000, 0xc0420d25a0, 0x3ff0000000000000)
        C:/path/to/go/src/fyne.io/fyne/vendor/github.com/srwiley/oksvg/svgd.go:83 +0xb5
fyne.io/fyne/driver/gl.(*glCanvas).newGlImageTexture(0xc04204c080, 0x6614a0, 0xc042482000, 0xc042486160)
        C:/path/to/go/src/fyne.io/fyne/driver/gl/gl.go:182 +0xa33
fyne.io/fyne/driver/gl.(*glCanvas).(fyne.io/fyne/driver/gl.newGlImageTexture)-fm(0x6614a0, 0xc042482000, 0xc042111688)
        C:/path/to/go/src/fyne.io/fyne/driver/gl/draw.go:135 +0x45
fyne.io/fyne/driver/gl.getTexture(0x6614a0, 0xc042482000, 0xc042111730, 0xda0000c0421116f8)
        C:/path/to/go/src/fyne.io/fyne/driver/gl/gl.go:48 +0x130
fyne.io/fyne/driver/gl.(*glCanvas).drawImage(0xc04204c080, 0xc042482000, 0x4, 0x25, 0x78, 0xa)
        C:/path/to/go/src/fyne.io/fyne/driver/gl/draw.go:135 +0x77
fyne.io/fyne/driver/gl.(*glCanvas).drawObject(0xc04204c080, 0x6614a0, 0xc042482000, 0x4, 0x25, 0x78, 0xa)
        C:/path/to/go/src/fyne.io/fyne/driver/gl/draw.go:177 +0x2c0
fyne.io/fyne/driver/gl.(*glCanvas).paint.func1(0x6614a0, 0xc042482000, 0x4, 0x25)
        C:/path/to/go/src/fyne.io/fyne/driver/gl/canvas.go:131 +0x6b
fyne.io/fyne/driver/gl.walkObjects(0x6614a0, 0xc042482000, 0x4, 0x25, 0xc0421119b0)
        C:/path/to/go/src/fyne.io/fyne/driver/gl/draw.go:29 +0x1f4
fyne.io/fyne/driver/gl.walkObjects(0x6618c0, 0xc04206a240, 0x4, 0x4, 0xc0421119b0)
        C:/path/to/go/src/fyne.io/fyne/driver/gl/draw.go:26 +0x18b
fyne.io/fyne/driver/gl.walkObjects(0x661380, 0xc0421540f0, 0x0, 0x0, 0xc0421119b0)
        C:/path/to/go/src/fyne.io/fyne/driver/gl/draw.go:19 +0x2a1
fyne.io/fyne/driver/gl.(*glCanvas).paint(0xc04204c080, 0x78, 0xa)
        C:/path/to/go/src/fyne.io/fyne/driver/gl/canvas.go:133 +0x120
fyne.io/fyne/driver/gl.updateWinSize(0xc0420aab40)
        C:/path/to/go/src/fyne.io/fyne/driver/gl/gl_windows.go:24 +0x67
fyne.io/fyne/driver/gl.(*window).refresh(0xc0420aab40, 0xc0420dc680)
        C:/path/to/go/src/fyne.io/fyne/driver/gl/window.go:233 +0x32
fyne.io/fyne/driver/gl.(*window).(fyne.io/fyne/driver/gl.refresh)-fm(0xc0420dc680)
        C:/path/to/go/src/fyne.io/fyne/driver/gl/window.go:486 +0x3b
fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw.goWindowRefreshCB(0x4fdf1d0)
        C:/path/to/go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/window.go:203 +0x50
fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw._cgoexpwrap_e04d887d9a45_goWindowRefreshCB(0x4fdf1d0)
        _cgo_gotypes.go:2205 +0x32
fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw._Cfunc_glfwPollEvents()
        _cgo_gotypes.go:1150 +0x48
fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw.PollEvents()
        C:/path/to/go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/window.go:777 +0x27
fyne.io/fyne/driver/gl.(*gLDriver).runGL(0xc0420647c0)
        C:/path/to/go/src/fyne.io/fyne/driver/gl/loop.go:72 +0x497
fyne.io/fyne/driver/gl.(*gLDriver).Run(0xc0420647c0)
        C:/path/to/go/src/fyne.io/fyne/driver/gl/driver.go:82 +0x32
fyne.io/fyne/driver/gl.(*window).ShowAndRun(0xc0420aa2a0)
        C:/path/to/go/src/fyne.io/fyne/driver/gl/window.go:179 +0x5e
main.main()
        C:/path/to/go/src/fyne.io/fyne/cmd/fyne_demo/main.go:118 +0xed8
```

Info:

- Windows 10 Pro
- `go version`: go version go1.10.1 windows/amd64
- Installed gcc via `scoop install gcc`

**Comment by krostar** [comment]
> Thanks for the report.
> Just looking for some other information/hints:
> 
>     * Did you run fyne_demo with any parameters?
> 
>     * Did the icons demo load correctly until you clicked the icons at the top - or did it crash when loading the icons window?

Hi,

I launched the program without any parameters:
```console
$> cd $GOPATH/src/fyne.io/fyne/cmd/fyne_demo/
$> go run .
```

When I `go run` the project, the main window loads. I can click on any clickable object on this window without any problems except for the `Icons` items. On click on this item, the program panic instantly.

I'm not sure I answered your second question, tell me if you need me to be more precise.

krostar

**Comment by andydotxyz** [comment]
Thanks, I finally tracked it down - there was a strange race condition where the image could be rendered before the canvas sized, creating a negative width. oops!
