### ISSUE TITLE
fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by vendelin8** [fyne-io/fyne#740]
### Describe the bug:
I did the Getting Started, and it broke.

### To Reproduce:
```
sudo pacman -S go xorg-server-devel
go get fyne.io/fyne
go get fyne.io/fyne/cmd/fyne_demo
fyne_demo
```
results in:
```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x89ba10, 0x16)
	/usr/lib/go/src/runtime/panic.go:1112 +0x72
runtime.sysMap(0xc004000000, 0x8ec000000, 0xeb2a98)
	/usr/lib/go/src/runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0xe9d680, 0x8eb400000, 0xe9d688, 0x475878)
	/usr/lib/go/src/runtime/malloc.go:715 +0x1cd
runtime.(*mheap).grow(0xe9d680, 0x475878, 0x0)
	/usr/lib/go/src/runtime/mheap.go:1286 +0x11c
runtime.(*mheap).allocSpan(0xe9d680, 0x475878, 0x7331ce7809220100, 0xeb2aa8, 0x0)
	/usr/lib/go/src/runtime/mheap.go:1124 +0x6a0
runtime.(*mheap).alloc.func1()
	/usr/lib/go/src/runtime/mheap.go:871 +0x64
runtime.(*mheap).alloc(0xe9d680, 0x475878, 0x101, 0x912820)
	/usr/lib/go/src/runtime/mheap.go:865 +0x81
runtime.largeAlloc(0x8eb0eecd0, 0xc000030101, 0xc000000180)
	/usr/lib/go/src/runtime/malloc.go:1152 +0x92
runtime.mallocgc.func1()
	/usr/lib/go/src/runtime/malloc.go:1047 +0x46
runtime.systemstack(0x483884)
	/usr/lib/go/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
	/usr/lib/go/src/runtime/proc.go:1041

goroutine 1 [running, locked to thread]:
runtime.systemstack_switch()
	/usr/lib/go/src/runtime/asm_amd64.s:330 fp=0xc000159248 sp=0xc000159240 pc=0x483980
runtime.mallocgc(0x8eb0eecd0, 0x7dee20, 0xc000220001, 0x449bf000)
	/usr/lib/go/src/runtime/malloc.go:1046 +0x895 fp=0xc0001592e8 sp=0xc000159248 pc=0x4301b5
runtime.makeslice(0x7dee20, 0x8eb0eecd0, 0x8eb0eecd0, 0xc00022e720)
	/usr/lib/go/src/runtime/slice.go:49 +0x6c fp=0xc000159318 sp=0xc0001592e8 pc=0x46cffc
image.NewRGBA(...)
	/usr/lib/go/src/image/image.go:157
fyne.io/fyne/internal/painter/gl.(*glPainter).newGlTextTexture(0xc00022e000, 0x929d80, 0xc000255ea0, 0xc000149010)
	/home/panda/og/src/fyne.io/fyne/internal/painter/gl/gl_common.go:105 +0x11f fp=0xc000159448 sp=0xc000159318 pc=0x73fbcf
fyne.io/fyne/internal/painter/gl.(*glPainter).newGlTextTexture-fm(0x929d80, 0xc000255ea0, 0xc0001594a8)
	/home/panda/og/src/fyne.io/fyne/internal/painter/gl/gl_common.go:99 +0x3e fp=0xc000159478 sp=0xc000159448 pc=0x74210e
fyne.io/fyne/internal/painter/gl.getTexture(0x929d80, 0xc000255ea0, 0xc0001595c8, 0x125)
	/home/panda/og/src/fyne.io/fyne/internal/painter/gl/gl_common.go:26 +0x94 fp=0xc0001594c8 sp=0xc000159478 pc=0x73ec64
fyne.io/fyne/internal/painter/gl.(*glPainter).drawTextureWithDetails(0xc00022e000, 0x929d80, 0xc000255ea0, 0xc0001595c8, 0xe5, 0x25, 0x125, 0x15, 0x29e, 0x1a2, ...)
	/home/panda/og/src/fyne.io/fyne/internal/painter/gl/draw.go:61 +0x4c fp=0xc000159548 sp=0xc0001594c8 pc=0x73da8c
fyne.io/fyne/internal/painter/gl.(*glPainter).drawText(0xc00022e000, 0xc000255ea0, 0xe5, 0x25, 0x29e, 0x1a2)
	/home/panda/og/src/fyne.io/fyne/internal/painter/gl/draw.go:127 +0x188 fp=0xc0001595e8 sp=0xc000159548 pc=0x73e638
fyne.io/fyne/internal/painter/gl.(*glPainter).drawObject(0xc00022e000, 0x929d80, 0xc000255ea0, 0x5a, 0x25, 0x29e, 0x1a2)
	/home/panda/og/src/fyne.io/fyne/internal/painter/gl/draw.go:146 +0x45e fp=0xc000159648 sp=0xc0001595e8 pc=0x73eb2e
fyne.io/fyne/internal/painter/gl.(*glPainter).Paint(0xc00022e000, 0x929d80, 0xc000255ea0, 0x5a, 0x25, 0x29e, 0x1a2)
	/home/panda/og/src/fyne.io/fyne/internal/painter/gl/painter.go:67 +0x8c fp=0xc000159690 sp=0xc000159648 pc=0x741a4c
fyne.io/fyne/internal/driver/glfw.(*glCanvas).paint.func1(0xc000094230, 0x5a, 0x25)
	/home/panda/og/src/fyne.io/fyne/internal/driver/glfw/canvas.go:312 +0x14e fp=0xc000159710 sp=0xc000159690 pc=0x752c4e
fyne.io/fyne/internal/driver/glfw.(*glCanvas).walkTree.func1(0x929d80, 0xc000255ea0, 0x5a, 0x25, 0x0, 0x0, 0x7fffffff, 0x7fffffff, 0x1a2)
	/home/panda/og/src/fyne.io/fyne/internal/driver/glfw/canvas.go:366 +0x137 fp=0xc000159760 sp=0xc000159710 pc=0x752e07
fyne.io/fyne/internal/driver.walkObjectTree(0x929d80, 0xc000255ea0, 0x92a200, 0xc00032a000, 0x56, 0x21, 0x0, 0x0, 0x7fffffff, 0x7fffffff, ...)
	/home/panda/og/src/fyne.io/fyne/internal/driver/util.go:75 +0x2d0 fp=0xc000159818 sp=0xc000159760 pc=0x6be450
fyne.io/fyne/internal/driver.walkObjectTree(0x92a200, 0xc00032a000, 0x929f00, 0xc000326850, 0x56, 0x21, 0x0, 0x0, 0x7fffffff, 0x7fffffff, ...)
	/home/panda/og/src/fyne.io/fyne/internal/driver/util.go:82 +0x1f6 fp=0xc0001598d0 sp=0xc000159818 pc=0x6be376
fyne.io/fyne/internal/driver.walkObjectTree(0x929f00, 0xc000326850, 0x92a500, 0xc000256480, 0x4, 0x21, 0x0, 0x0, 0x7fffffff, 0x7fffffff, ...)
	/home/panda/og/src/fyne.io/fyne/internal/driver/util.go:82 +0x1f6 fp=0xc000159988 sp=0xc0001598d0 pc=0x6be376
fyne.io/fyne/internal/driver.walkObjectTree(0x92a500, 0xc000256480, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fffffff, 0x7fffffff, ...)
	/home/panda/og/src/fyne.io/fyne/internal/driver/util.go:82 +0x1f6 fp=0xc000159a40 sp=0xc000159988 pc=0x6be376
fyne.io/fyne/internal/driver.WalkVisibleObjectTree(0x92a500, 0xc000256480, 0xc000159b30, 0xc000159b08, 0xc000000180)
	/home/panda/og/src/fyne.io/fyne/internal/driver/util.go:26 +0x82 fp=0xc000159ac0 sp=0xc000159a40 pc=0x6be0a2
fyne.io/fyne/internal/driver/glfw.(*glCanvas).walkTree(0xc000220000, 0xc0002235e0, 0xc000159bd0, 0xc000159bc0)
	/home/panda/og/src/fyne.io/fyne/internal/driver/glfw/canvas.go:387 +0x15c fp=0xc000159b78 sp=0xc000159ac0 pc=0x74bcec
fyne.io/fyne/internal/driver/glfw.(*glCanvas).walkTrees(0xc000220000, 0xc000159bd0, 0xc000159bc0)
	/home/panda/og/src/fyne.io/fyne/internal/driver/glfw/canvas.go:327 +0x4f fp=0xc000159ba8 sp=0xc000159b78 pc=0x74baff
fyne.io/fyne/internal/driver/glfw.(*glCanvas).paint(0xc000220000, 0x29e, 0x1a2)
	/home/panda/og/src/fyne.io/fyne/internal/driver/glfw/canvas.go:320 +0xd5 fp=0xc000159c00 sp=0xc000159ba8 pc=0x74ba85
fyne.io/fyne/internal/driver/glfw.(*gLDriver).repaintWindow.func1()
	/home/panda/og/src/fyne.io/fyne/internal/driver/glfw/loop.go:125 +0x88 fp=0xc000159c38 sp=0xc000159c00 pc=0x7532e8
fyne.io/fyne/internal/driver/glfw.(*window).RunWithContext(0xc0001a6000, 0xc000159c60)
	/home/panda/og/src/fyne.io/fyne/internal/driver/glfw/window.go:986 +0x38 fp=0xc000159c50 sp=0xc000159c38 pc=0x752228
fyne.io/fyne/internal/driver/glfw.(*gLDriver).repaintWindow(0xc0000a3170, 0xc0001a6000)
	/home/panda/og/src/fyne.io/fyne/internal/driver/glfw/loop.go:118 +0x66 fp=0xc000159c90 sp=0xc000159c50 pc=0x74d596
fyne.io/fyne/internal/driver/glfw.(*gLDriver).runGL(0xc0000a3170)
	/home/panda/og/src/fyne.io/fyne/internal/driver/glfw/loop.go:107 +0x3c8 fp=0xc000159e10 sp=0xc000159c90 pc=0x74d378
fyne.io/fyne/internal/driver/glfw.(*gLDriver).Run(0xc0000a3170)
	/home/panda/og/src/fyne.io/fyne/internal/driver/glfw/driver.go:66 +0x2b fp=0xc000159e28 sp=0xc000159e10 pc=0x74cc1b
fyne.io/fyne/internal/driver/glfw.(*window).ShowAndRun(0xc0001a6000)
	/home/panda/og/src/fyne.io/fyne/internal/driver/glfw/window.go:384 +0x57 fp=0xc000159e50 sp=0xc000159e28 pc=0x74f207
main.main()
	/home/panda/og/src/fyne.io/fyne/cmd/fyne_demo/main.go:74 +0x88e fp=0xc000159f88 sp=0xc000159e50 pc=0x78127e
runtime.main()
	/usr/lib/go/src/runtime/proc.go:203 +0x212 fp=0xc000159fe0 sp=0xc000159f88 pc=0x458c42
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000159fe8 sp=0xc000159fe0 pc=0x485a91

goroutine 21 [sleep]:
time.Sleep(0x22ecb25c00)
	/usr/lib/go/src/runtime/time.go:198 +0xba
fyne.io/fyne/internal/painter.svgCacheJanitor.func1()
	/home/panda/og/src/fyne.io/fyne/internal/painter/svg_cache.go:51 +0x116
sync.(*Once).doSlow(0xeb0ef8, 0xc0000b82e0)
	/usr/lib/go/src/sync/once.go:66 +0xec
sync.(*Once).Do(0xeb0ef8, 0xc0000b82e0)
	/usr/lib/go/src/sync/once.go:57 +0x45
created by fyne.io/fyne/internal/painter.svgCacheJanitor
	/home/panda/og/src/fyne.io/fyne/internal/painter/svg_cache.go:49 +0x9b

goroutine 22 [chan receive]:
fyne.io/fyne/app.NewAppWithDriver.func1(0xc000096180, 0xc000092420)
	/home/panda/og/src/fyne.io/fyne/app/app.go:107 +0x3d
created by fyne.io/fyne/app.NewAppWithDriver
	/home/panda/og/src/fyne.io/fyne/app/app.go:105 +0x17e

goroutine 23 [syscall]:
syscall.Syscall6(0xe8, 0x9, 0xc00020fb74, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/syscall/asm_linux_amd64.s:41 +0x5
fyne.io/fyne/vendor/golang.org/x/sys/unix.EpollWait(0x9, 0xc00020fb74, 0x7, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x0)
	/home/panda/og/src/fyne.io/fyne/vendor/golang.org/x/sys/unix/zsyscall_linux_amd64.go:1760 +0x72
fyne.io/fyne/vendor/github.com/fsnotify/fsnotify.(*fdPoller).wait(0xc0000ba1a0, 0x0, 0x0, 0x0)
	/home/panda/og/src/fyne.io/fyne/vendor/github.com/fsnotify/fsnotify/inotify_poller.go:86 +0x91
fyne.io/fyne/vendor/github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc000094140)
	/home/panda/og/src/fyne.io/fyne/vendor/github.com/fsnotify/fsnotify/inotify.go:192 +0x1f8
created by fyne.io/fyne/vendor/github.com/fsnotify/fsnotify.NewWatcher
	/home/panda/og/src/fyne.io/fyne/vendor/github.com/fsnotify/fsnotify/inotify.go:59 +0x1a5

goroutine 24 [chan receive]:
fyne.io/fyne/app.watchFile.func1(0xc000094140, 0xc0000b4120, 0x26, 0xc0000a12a0, 0xc0000a12b0)
	/home/panda/og/src/fyne.io/fyne/app/settings_desktop.go:42 +0x58
created by fyne.io/fyne/app.watchFile
	/home/panda/og/src/fyne.io/fyne/app/settings_desktop.go:41 +0xe7

goroutine 34 [chan receive]:
fyne.io/fyne/internal/driver/glfw.(*window).runEventQueue(0xc0001a6000)
	/home/panda/og/src/fyne.io/fyne/internal/driver/glfw/window.go:1029 +0x86
created by fyne.io/fyne/internal/driver/glfw.(*gLDriver).CreateWindow.func1
	/home/panda/og/src/fyne.io/fyne/internal/driver/glfw/window.go:1062 +0x1a0

goroutine 35 [chan receive]:
fyne.io/fyne/internal/driver/glfw.(*glCanvas).setupThemeListener.func1(0xc00022c000, 0xc000220000)
	/home/panda/og/src/fyne.io/fyne/internal/driver/glfw/canvas.go:409 +0x47
created by fyne.io/fyne/internal/driver/glfw.(*glCanvas).setupThemeListener
	/home/panda/og/src/fyne.io/fyne/internal/driver/glfw/canvas.go:407 +0xa6

goroutine 25 [chan receive]:
fyne.io/fyne/internal/painter.SvgCacheMonitorTheme.func1(0xc000096360)
	/home/panda/og/src/fyne.io/fyne/internal/painter/svg_cache.go:104 +0x34
created by fyne.io/fyne/internal/painter.SvgCacheMonitorTheme
	/home/panda/og/src/fyne.io/fyne/internal/painter/svg_cache.go:102 +0x9c

goroutine 37 [chan receive]:
fyne.io/fyne/widget.(*infProgressRenderer).infiniteProgressLoop(0xc000260540)
	/home/panda/og/src/fyne.io/fyne/widget/progressbarinfinite.go:119 +0x3a
created by fyne.io/fyne/widget.(*infProgressRenderer).start
	/home/panda/og/src/fyne.io/fyne/widget/progressbarinfinite.go:105 +0xe9

goroutine 38 [sleep]:
time.Sleep(0x5f5e100)
	/usr/lib/go/src/runtime/time.go:198 +0xba
fyne.io/fyne/cmd/fyne_demo/screens.makeProgressTab.func1(0xc0002243c0)
	/home/panda/og/src/fyne.io/fyne/cmd/fyne_demo/screens/widget.go:59 +0x39
created by fyne.io/fyne/cmd/fyne_demo/screens.makeProgressTab
	/home/panda/og/src/fyne.io/fyne/cmd/fyne_demo/screens/widget.go:56 +0x5f

goroutine 3 [sleep]:
time.Sleep(0x3b9aca00)
	/usr/lib/go/src/runtime/time.go:198 +0xba
fyne.io/fyne/cmd/fyne_demo/screens.GraphicsScreen.func1(0xc0001b7ec0)
	/home/panda/og/src/fyne.io/fyne/cmd/fyne_demo/screens/graphics.go:25 +0x41
created by fyne.io/fyne/cmd/fyne_demo/screens.GraphicsScreen
	/home/panda/og/src/fyne.io/fyne/cmd/fyne_demo/screens/graphics.go:23 +0x13f
```

I tried the minimal working example. This creates a full screen window, totally empty (without SetContent):
```
package main

import (
	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
)

func main() {
	app := app.New()

	w := app.NewWindow("Hello")
	widget.NewLabel("Hello Fyne!")

	w.ShowAndRun()
}
```

But this fails the same as above:
```
package main

import (
	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
)

func main() {
	app := app.New()

	w := app.NewWindow("Hello")
	l := widget.NewLabel("Hello Fyne!")
	w.SetContent(l)

	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - OS: Arch Linux
 - Version: n/a
 - Go version: 1.14-1
 - Fyne version: 25a9bce2a04b2b63e3494318e161338dc62eed9a

**Comment by andydotxyz** [comment]
None of these should be appearing full-screen.
Can yo confirm what desktop environment or window manager you are using?

**Comment by andydotxyz** [comment]
I wonder if there is some error in the scaling calculations, would it be possible to print out the value of `bounds`, `width` and `height` inside `newGlTextTexture()` inside internal/painter/gl/gl_common.go (around line 105)? Thanks!

**Comment by vendelin8** [comment]
It's on Mate 1.24.0-1
```bounds: {79 21}
width: 98553
height: 26198
```

**Comment by andydotxyz** [comment]
OUCH! yes we have a problem here...
Can you try running with FYNE_SCALE=1 env to see if that helps.
Scaling is now quite complex unfortunately, so it can be impacted by your display hardware - anything special about your monitor?

**Comment by vendelin8** [comment]
That helped, thanks!
I don't know about anything special. It's an Acer laptop with, 1366x768 resolution.

**Comment by andydotxyz** [comment]
Can you please provide 2 more things for me?
* Please share the output of the command `xrandr`
* What is the scale value in the "Advanced" tab of fyne_demo

**Comment by vendelin8** [comment]
```
$ xrandr 
Screen 0: minimum 8 x 8, current 1366 x 768, maximum 32767 x 32767
eDP1 connected primary 1366x768+0+0 (normal left inverted right x axis y axis) 290mm x 160mm
   1366x768      60.01*+
   1280x720      59.74  
   1024x768      60.00  
   1024x576      60.00    59.90    59.82  
   960x540       60.00    59.63    59.82  
   800x600       60.32    56.25  
   864x486       60.00    59.92    59.57  
   640x480       59.94  
   720x405       59.51    60.00    58.99  
   680x384       60.00  
   640x360       59.84    59.32    60.00  
HDMI1 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)
```

Scale: 1.20

**Comment by andydotxyz** [comment]
It's a bit of a long shot but what happens if you remove ~/.config/fyne/* (and don't use the env var)?

**Comment by vendelin8** [comment]
It works fine. Probably you know why. My guess is that `xorg-server-devel` wasn't installed at first. Then I tried to remove sources and binaries, then restart again, but I didn't think about such a config. What do you think?

**Comment by andydotxyz** [comment]
Without the libraries installed it should not have compiled so it would be strange that the config would have been written. But it does seem like somehow a bad scale value was written into the config file..?

**Comment by vendelin8** [comment]
I tried the library a couple of months ago. All I can remember is that I wrote an infinite loop, so I had to restart my computer. Maybe something broke meanwhile with the config. I can't remember if it showed a GUI at all, but I think it did.

**Comment by andydotxyz** [comment]
OK, that could be related. I wonder if we could close this issue and re-open for a proper investigation if it ever happens again?

**Comment by vendelin8** [comment]
Sure, thanks for all your help, and this wonderful lib! :)
