### ISSUE TITLE
Panic when trying to paste empty clipboard into entry

### ISSUE THREAD

**Issue by terminationshock** [fyne-io/fyne#743]
### Describe the bug:
An app crashes if one tries to paste text into an entry when the clipboard is empty.

### To Reproduce:

1. Clean the clipboard first: `xsel -bc`
2. Build and run the application below.
3. Put the cursor into the entry and hit "Ctrl + v"
4. Observe the crash

### Stack trace:

```
GLFW: An invalid error was not accepted by the caller: FormatUnavailable: X11: Failed to convert selection to string
GLFW: Please report this bug in the Go package immediately.
panic: FormatUnavailable: X11: Failed to convert selection to string

goroutine 1 [running, locked to thread]:
fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/glfw.acceptError(0x0, 0x0, 0x0, 0x745cb5, 0xc000172501)
	/home/tobi/Code/Go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/glfw/error.go:178 +0x201
fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/glfw.panicError(...)
	/home/tobi/Code/Go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/glfw/error.go:185
fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/glfw.PollEvents()
	/home/tobi/Code/Go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/glfw/window.go:949 +0x38
fyne.io/fyne/internal/driver/glfw.(*gLDriver).runGL(0xc00009d170)
	/home/tobi/Code/Go/src/fyne.io/fyne/internal/driver/glfw/loop.go:84 +0x1ff
fyne.io/fyne/internal/driver/glfw.(*gLDriver).Run(0xc00009d170)
	/home/tobi/Code/Go/src/fyne.io/fyne/internal/driver/glfw/driver.go:61 +0x2b
fyne.io/fyne/internal/driver/glfw.(*window).ShowAndRun(0xc0000cc280)
	/home/tobi/Code/Go/src/fyne.io/fyne/internal/driver/glfw/window.go:386 +0x57
main.main()
```

### Example code:

```
package main

import (
    "fyne.io/fyne/app"
    "fyne.io/fyne/widget"
)

func main() {
    application := app.New()
    win := application.NewWindow("")

    entry := widget.NewEntry()

    win.SetContent(entry)
    win.ShowAndRun()
}
```

### Device (please complete the following information):
 - OS: Ubuntu 18.04.4 LTS
 - Go version: go1.13.6 linux/amd64
 - fyne commit 07a56470

**Comment by spatocode** [comment]
This is a GLFW error and i think its specific to Linux.

**Comment by andydotxyz** [comment]
Yes it looks like a GLFW (or the go bindings) issue, but we need to either fix it or catch it so that Fyne apps don't crash when it occurs.

**Comment by andydotxyz** [comment]
Thankfully this is only on develop, not master :)

**Comment by andydotxyz** [comment]
Fixed for testing on develop. Removed from 1.2.x as this only affects the 1.3 release

**Comment by terminationshock** [comment]
Thanks a lot for fixing!
