### ISSUE TITLE
Terminating app due to uncaughtexception 'NSInternalInconsistencyException', reason: 'nextEventMatchingMask should only be called from the Main Thread!'

### ISSUE THREAD

**Issue by sunfmin** [fyne-io/fyne#77]
Program:

```go
package main

import (
	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
)

func main() {
	app := app.New()

	w2 := app.NewWindow("Select country")

	w2.SetContent(widget.NewLabel("This is select country"))

	w := app.NewWindow("Hello")
	w.SetContent(widget.NewVBox(
		widget.NewLabel("Hello Fyne!"),
		widget.NewButton("Select Country", func() {
			w2.ShowAndRun()
		}),
	))

	w.ShowAndRun()
}


```

Error:

```
$ go run main.go
2019-01-12 14:41:02.239 main[57613:393268] *** Terminating app due to uncaughtexception 'NSInternalInconsistencyException', reason: 'nextEventMatchingMask should only be called from the Main Thread!'
*** First throw call stack:
(
        0   CoreFoundation                      0x00007fff3321c66b __exceptionPreprocess + 171
        1   libobjc.A.dylib                     0x00007fff5a460942 objc_exception_throw + 48
        2   AppKit                              0x00007fff30ebf297 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 4167
        3   main                                0x000000000418ac03 _glfwPlatformPollEvents + 147
        4   main                                0x0000000004056c90 runtime.asmcgocall + 112
)
libc++abi.dylib: terminating with uncaught exception of type NSException
SIGABRT: abort
PC=0x7fff5b1c7b66 m=8 sigcode=0

goroutine 0 [idle]:
runtime: unknown pc 0x7fff5b1c7b66
stack: frame={sp:0x7000077be548, fp:0x0} stack=[0x700007740290,0x7000077bfe90)
00007000077be448:  0000006833588b78  00007000ffff4208
00007000077be458:  0000000004c46140  000000000000007f
00007000077be468:  0000007a3311c279  00000000ffff4208
00007000077be478:  00007000077be4b0  000070000000007f
00007000077be488:  00007fff8d112af0  0000000000000000
00007000077be498:  0000000032aaaba2  0000000000000000
00007000077be4a8:  00007000077be5e0  0000000000000000
00007000077be4b8:  0000000032aaaba2  0000000000000000
00007000077be4c8:  0000000000000000  0000000000000000
00007000077be4d8:  0000000000000000  0000000000000000
00007000077be4e8:  0000000000000000  0000000000000000
00007000077be4f8:  0000000000000003  0000000000000000
00007000077be508:  0000000000000000  0000000000000000
00007000077be518:  0000000000000000  00007fff9383c240
00007000077be528:  00007fff9383bca0  00007fff5b102366
00007000077be538:  0000000000000000  00007000077be580
00007000077be548: <00007fff5b392080  00007000077c0000
00007000077be558:  00007000077be598  0000000000000008
00007000077be568:  0000000000000030  00007fff59041501
00007000077be578:  00007fff9383c9a0  00007000077be5b0
00007000077be588:  00007fff5b1231ae  0000000000000008
00007000077be598:  00000000ffffffdf  ffffffff59041501
00007000077be5a8:  00007000077be6b0  00007000077be6e0
00007000077be5b8:  00007fff59020f8f  0000003000000018
00007000077be5c8:  00007000077be6f0  00007000077be600
00007000077be5d8:  00007000077be7f0  0000003000000018
00007000077be5e8:  00007000077be6f0  00007000077be600
00007000077be5f8:  00007000077be7f8  00000000000007e3
00007000077be608:  00007fff5904155c  00007fff3359b6ed
00007000077be618:  00007fff5a46e46f  0000000000000000
00007000077be628:  02aaaaaaaaaaaaaa  00007000077be430
00007000077be638:  0000000000000000  00007000077be6d0
runtime: unknown pc 0x7fff5b1c7b66
stack: frame={sp:0x7000077be548, fp:0x0} stack=[0x700007740290,0x7000077bfe90)
00007000077be448:  0000006833588b78  00007000ffff4208
00007000077be458:  0000000004c46140  000000000000007f
00007000077be468:  0000007a3311c279  00000000ffff4208
00007000077be478:  00007000077be4b0  000070000000007f
00007000077be488:  00007fff8d112af0  0000000000000000
00007000077be498:  0000000032aaaba2  0000000000000000
00007000077be4a8:  00007000077be5e0  0000000000000000
00007000077be4b8:  0000000032aaaba2  0000000000000000
00007000077be4c8:  0000000000000000  0000000000000000
00007000077be4d8:  0000000000000000  0000000000000000
00007000077be4e8:  0000000000000000  0000000000000000
00007000077be4f8:  0000000000000003  0000000000000000
00007000077be508:  0000000000000000  0000000000000000
00007000077be518:  0000000000000000  00007fff9383c240
00007000077be528:  00007fff9383bca0  00007fff5b102366
00007000077be538:  0000000000000000  00007000077be580
00007000077be548: <00007fff5b392080  00007000077c0000
00007000077be558:  00007000077be598  0000000000000008
00007000077be568:  0000000000000030  00007fff59041501
00007000077be578:  00007fff9383c9a0  00007000077be5b0
00007000077be588:  00007fff5b1231ae  0000000000000008
00007000077be598:  00000000ffffffdf  ffffffff59041501
00007000077be5a8:  00007000077be6b0  00007000077be6e0
00007000077be5b8:  00007fff59020f8f  0000003000000018
00007000077be5c8:  00007000077be6f0  00007000077be600
00007000077be5d8:  00007000077be7f0  0000003000000018
00007000077be5e8:  00007000077be6f0  00007000077be600
00007000077be5f8:  00007000077be7f8  00000000000007e3
00007000077be608:  00007fff5904155c  00007fff3359b6ed
00007000077be618:  00007fff5a46e46f  0000000000000000
00007000077be628:  02aaaaaaaaaaaaaa  00007000077be430
00007000077be638:  0000000000000000  00007000077be6d0

goroutine 21 [syscall]:
runtime.cgocall(0x418ca20, 0xc000045dd0, 0x4f16790)
        /usr/local/Cellar/go/1.11.4/libexec/src/runtime/cgocall.go:128 +0x5e fp=0xc000045da0 sp=0xc000045d68 pc=0x400511e
fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw._Cfunc_glfwPollEvents()
        _cgo_gotypes.go:1117 +0x41 fp=0xc000045dd0 sp=0xc000045da0 pc=0x41649c1
fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw.PollEvents()
        /Users/sunfmin/go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/window.go:777 +0x20 fp=0xc000045de0 sp=0xc000045dd0 pc=0x4169400
fyne.io/fyne/driver/gl.(*gLDriver).runGL(0xc00000c420)
        /Users/sunfmin/go/src/fyne.io/fyne/driver/gl/loop.go:72 +0x16e fp=0xc000045f68 sp=0xc000045de0 pc=0x416f10e
fyne.io/fyne/driver/gl.(*gLDriver).Run(0xc00000c420)
        /Users/sunfmin/go/src/fyne.io/fyne/driver/gl/driver.go:82 +0x2b fp=0xc000045f80 sp=0xc000045f68 pc=0x416cc0b
fyne.io/fyne/driver/gl.(*window).ShowAndRun(0xc00008a3c0)
        /Users/sunfmin/go/src/fyne.io/fyne/driver/gl/window.go:179 +0x57 fp=0xc000045fa8 sp=0xc000045f80 pc=0x416fd67
main.main.func1()
        /Users/sunfmin/go/src/github.com/sunfmin/fynedemo/main.go:19 +0x32 fp=0xc000045fc0 sp=0xc000045fa8 pc=0x4173a42
fyne.io/fyne/widget.(*Button).OnMouseDown(0xc0000fa0c0, 0xc000072000)
        /Users/sunfmin/go/src/fyne.io/fyne/widget/button.go:150 +0x37 fp=0xc000045fd0 sp=0xc000045fc0 pc=0x40c6407
runtime.goexit()
        /usr/local/Cellar/go/1.11.4/libexec/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000045fd8 sp=0xc000045fd0 pc=0x40574f1
created by fyne.io/fyne/driver/gl.(*window).mouseClicked
        /Users/sunfmin/go/src/fyne.io/fyne/driver/gl/window.go:292 +0x1d0

goroutine 1 [runnable, locked to thread]:
fyne.io/fyne/vendor/github.com/go-gl/gl/v3.2-core/gl._Cfunc_glowUseProgram(0x7fff3cb507cb, 0x3)
        _cgo_gotypes.go:21380 +0x45
fyne.io/fyne/vendor/github.com/go-gl/gl/v3.2-core/gl.UseProgram(0xc000000003)
        /Users/sunfmin/go/src/fyne.io/fyne/vendor/github.com/go-gl/gl/v3.2-core/gl/package.go:12647 +0x35
fyne.io/fyne/driver/gl.(*gLDriver).runGL(0xc00000c420)
        /Users/sunfmin/go/src/fyne.io/fyne/driver/gl/loop.go:78 +0x208
fyne.io/fyne/driver/gl.(*gLDriver).Run(0xc00000c420)
        /Users/sunfmin/go/src/fyne.io/fyne/driver/gl/driver.go:82 +0x2b
fyne.io/fyne/driver/gl.(*window).ShowAndRun(0xc00008a4e0)
        /Users/sunfmin/go/src/fyne.io/fyne/driver/gl/window.go:179 +0x57
main.main()
        /Users/sunfmin/go/src/github.com/sunfmin/fynedemo/main.go:23 +0x219

goroutine 4 [chan receive]:
fyne.io/fyne/app.NewAppWithDriver.func1(0xc0000201e0, 0xc00007e6c0)
        /Users/sunfmin/go/src/fyne.io/fyne/app/app.go:98 +0x3d
created by fyne.io/fyne/app.NewAppWithDriver
        /Users/sunfmin/go/src/fyne.io/fyne/app/app.go:96 +0x157

rax    0x0
rbx    0x7000077c0000
rcx    0x7000077be548
rdx    0x0
rdi    0x15207
rsi    0x6
rbp    0x7000077be580
rsp    0x7000077be548
r8     0x7000077be410
r9     0x7000077be5e0
r10    0x0
r11    0x206
r12    0x15207
r13    0x30
r14    0x6
r15    0x2d
rip    0x7fff5b1c7b66
rflags 0x206
cs     0x7
fs     0x0
gs     0x0
exit status 2
```

**Comment by andydotxyz** [comment]
This is a confusing error sorry! You should use w2.Show() rather than w2.ShowAndRun().
ShowAndRun() is a shortcut for win.Show(); app.Run().

I will try to update the function so it does not try to call Run a second time

**Comment by andydotxyz** [comment]
I updated the run method so this should never happen even if you accidentally call Run() or ShowAndRun() a second time
