### ISSUE TITLE
Test App mutex not initialized

### ISSUE THREAD

**Issue by stuartmscott** [fyne-io/fyne#854]
test.NewApp() creates a test driver with;
```
test.driver = NewDriver().(*testDriver)
```
which, unlike NewDriverWithPainter, does not initialize windowsMutex.

This can cause a segfault:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x12d25a3]

goroutine 12 [running]:
sync.(*RWMutex).RLock(...)
	/usr/local/go/src/sync/rwmutex.go:48
fyne.io/fyne/test.(*testDriver).CanvasForObject(0x0, 0x14cf980, 0xc000098820, 0x0, 0x0)
	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/test/testdriver.go:30 +0x33
fyne.io/fyne/canvas.Refresh(0x14cf980, 0xc000098820)
	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/canvas/base.go:69 +0x81
fyne.io/fyne/widget.(*buttonRenderer).Refresh(0xc0004b6120)
	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/widget/button.go:123 +0xff
fyne.io/fyne/widget.(*BaseWidget).Refresh(0xc000098820)
	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/widget/widget.go:107 +0x51
fyne.io/fyne/widget.(*Button).SetText(...)
	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/widget/button.go:212
```

**Comment by andydotxyz** [comment]
Fixed on develop
