### ISSUE TITLE
Cannot call window.SetContent from non-main thread before app runs

### ISSUE THREAD

**Issue by stuartmscott** [fyne-io/fyne#926]
Calling window.SetContent from non-main thread before ShowAndRun() crashes app on macOS:

```
2020-05-02 13:26:12.299 cmd[49661:5792039] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff2fd29d07 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff68a4d5bf objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2fd5250c -[NSException raise] + 9
	3   AppKit                              0x00007fff2cf5924c -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 310
	4   AppKit                              0x00007fff2cf6851e -[NSThemeFrame _tileTitlebarAndRedisplay:] + 98
	5   AppKit                              0x00007fff2cf86b25 -[NSThemeFrame setFrameSize:] + 631
	6   AppKit                              0x00007fff2cf86314 -[NSWindow _oldPlaceWindow:fromServer:] + 793
	7   AppKit                              0x00007fff2cf845d5 -[NSWindow _setFrameCommon:display:fromServer:] + 1352
	8   cmd                                 0x00000000044d2df3 _glfwPlatformSetWindowSize + 563
	9   cmd                                 0x0000000004063cf0 runtime.asmcgocall + 112
)
libc++abi.dylib: terminating with uncaught exception of type NSException
SIGABRT: abort
PC=0x7fff69d3c33a m=8 sigcode=0
```

**Comment by stuartmscott** [comment]
```
goroutine 14 [syscall]:
runtime.cgocall(0x44d6fb0, 0xc00004ecf8, 0xc0001d0000)
	/usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc00004ecc8 sp=0xc00004ec90 pc=0x40058db
fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/glfw._Cfunc_glfwSetWindowSize(0x524c060, 0x10a00000280)
	_cgo_gotypes.go:2194 +0x45 fp=0xc00004ecf8 sp=0xc00004ecc8 pc=0x43ba7f5
fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/glfw.(*Window).SetSize.func1(0xc000118480, 0x280, 0x10a)
	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/glfw/window.go:496 +0x67 fp=0xc00004ed30 sp=0xc00004ecf8 pc=0x43c3b87
fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/glfw.(*Window).SetSize(0xc000118480, 0x280, 0x10a)
	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/glfw/window.go:496 +0x3f fp=0xc00004ed68 sp=0xc00004ed30 pc=0x43c096f
fyne.io/fyne/internal/driver/glfw.(*window).fitContent(0xc00012e280)
	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/internal/driver/glfw/window.go:253 +0xdf fp=0xc00004edb8 sp=0xc00004ed68 pc=0x43cb64f
fyne.io/fyne/internal/driver/glfw.(*window).rescaleOnMain(0xc00012e280)
	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/internal/driver/glfw/window.go:1004 +0x2f fp=0xc00004ee08 sp=0xc00004edb8 pc=0x43cf2df
fyne.io/fyne/internal/driver/glfw.(*window).RescaleContext.func1()
	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/internal/driver/glfw/window.go:999 +0x2a fp=0xc00004ee20 sp=0xc00004ee08 pc=0x43d19ca
fyne.io/fyne/internal/driver/glfw.runOnMain(0xc000098850)
	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/internal/driver/glfw/loop.go:43 +0xab fp=0xc00004ee60 sp=0xc00004ee20 pc=0x43c8d2b
fyne.io/fyne/internal/driver/glfw.(*window).RescaleContext(0xc00012e280)
	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/internal/driver/glfw/window.go:998 +0x57 fp=0xc00004ee80 sp=0xc00004ee60 pc=0x43cf287
fyne.io/fyne/internal/driver/glfw.(*window).SetContent(0xc00012e280, 0x46efd00, 0xc00008e370)
	/Users/stuartscott/Documents/Projects/Go/src/fyne.io/fyne/internal/driver/glfw/window.go:381 +0x61 fp=0xc00004eea8 sp=0xc00004ee80 pc=0x43cbfd1
github.com/AletheiaWareLLC/labclientgo.(*Client).ShowNodeDialog(0xc000174380, 0xc000098000)
	/Users/stuartscott/Documents/Projects/Go/src/github.com/AletheiaWareLLC/labclientgo/client.go:204 +0x439 fp=0xc00004ef58 sp=0xc00004eea8 pc=0x44c0899
github.com/AletheiaWareLLC/labclientgo.(*Client).GetNode(0xc000174380, 0x0)
	/Users/stuartscott/Documents/Projects/Go/src/github.com/AletheiaWareLLC/labclientgo/client.go:62 +0x9a fp=0xc00004ef90 sp=0xc00004ef58 pc=0x44c031a
main.main.func1(0xc000174380)
	/Users/stuartscott/Documents/Projects/Go/src/github.com/AletheiaWareLLC/labclientgo/cmd/main.go:77 +0x2f fp=0xc00004efd8 sp=0xc00004ef90 pc=0x44c230f
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00004efe0 sp=0xc00004efd8 pc=0x4064591
created by main.main
	/Users/stuartscott/Documents/Projects/Go/src/github.com/AletheiaWareLLC/labclientgo/cmd/main.go:76 +0x405
```

**Comment by andydotxyz** [comment]
I think I have a fix in the works, but if you could please post the code for replicating then I could verify locally.

**Comment by stuartmscott** [comment]
Sure, thanks for working on this

```go
package main

import (
	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
	"time"
)

func main() {
	a := app.New()
	w := a.NewWindow("")

	go func() {
		//time.Sleep(time.Second) // Uncomment to avoid error
		w.SetContent(widget.NewLabel("Test"))
	}()

	w.ShowAndRun()
}
```

**Comment by andydotxyz** [comment]
fixed on develop
