### ISSUE TITLE
running demo has many errors

### ISSUE THREAD

**Issue by yms2772** [fyne-io/fyne#934]
Run ``go get fyne.io/fyne/cmd/fyne_demo@develop`` and ``fyne_demo.exe``.
Then It shows the following error.

```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x733189]

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.(*Window).GetContentScale.func1(0x0, 0xc000280028, 0xc00028002c)
        C:/Users/yms27/Documents/Workspace/Go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200420212212-258d9bec320e/window.go:554 +0x29
github.com/go-gl/glfw/v3.3/glfw.(*Window).GetContentScale(0x0, 0xc46200)
        C:/Users/yms27/Documents/Workspace/Go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200420212212-258d9bec320e/window.go:554 +0x79
fyne.io/fyne/internal/driver/glfw.(*glDevice).SystemScaleForWindow(0xf1f5d0, 0xc4c5e0, 0xc000188180, 0x158)
        C:/Users/yms27/Documents/Workspace/Go/pkg/mod/fyne.io/fyne@v1.2.5-0.20200504194144-803586a17607/internal/driver/glfw/device.go:41 +0x46
fyne.io/fyne/internal/driver/glfw.(*window).calculatedScale(0xc000188180, 0x3f9737f6)
        C:/Users/yms27/Documents/Workspace/Go/pkg/mod/fyne.io/fyne@v1.2.5-0.20200504194144-803586a17607/internal/driver/glfw/window.go:300 +0x66
fyne.io/fyne/internal/driver/glfw.(*gLDriver).createWindow.func1()
        C:/Users/yms27/Documents/Workspace/Go/pkg/mod/fyne.io/fyne@v1.2.5-0.20200504194144-803586a17607/internal/driver/glfw/window.go:1089 +0x189
fyne.io/fyne/internal/driver/glfw.runOnMain(0xc00020a000)
        C:/Users/yms27/Documents/Workspace/Go/pkg/mod/fyne.io/fyne@v1.2.5-0.20200504194144-803586a17607/internal/driver/glfw/loop.go:43 +0xb2
fyne.io/fyne/internal/driver/glfw.(*gLDriver).createWindow(0xc00006f110, 0xbab7e3, 0x9, 0xc00008fd01, 0x75d8e8, 0xc0000f4100)
        C:/Users/yms27/Documents/Workspace/Go/pkg/mod/fyne.io/fyne@v1.2.5-0.20200504194144-803586a17607/internal/driver/glfw/window.go:1078 +0xdb
fyne.io/fyne/internal/driver/glfw.(*gLDriver).CreateWindow(0xc00006f110, 0xbab7e3, 0x9, 0xc000058180, 0xc000054300)
        C:/Users/yms27/Documents/Workspace/Go/pkg/mod/fyne.io/fyne@v1.2.5-0.20200504194144-803586a17607/internal/driver/glfw/window.go:1070 +0x4b
fyne.io/fyne/app.(*fyneApp).NewWindow(0xc000054300, 0xbab7e3, 0x9, 0xc, 0xc49f60)
        C:/Users/yms27/Documents/Workspace/Go/pkg/mod/fyne.io/fyne@v1.2.5-0.20200504194144-803586a17607/app/app.go:43 +0x4e
main.main()
        C:/Users/yms27/Documents/Workspace/Go/pkg/mod/fyne.io/fyne@v1.2.5-0.20200504194144-803586a17607/cmd/fyne_demo/main.go:71 +0x11c
```

### Device (please complete the following information):
 - OS: Windows 10 1909 18363.778
 - Go version: 1.14
 - Fyne version: develop fyne.io/fyne v1.2.5-0.20200504194144-803586a17607

**Comment by andydotxyz** [comment]
Thanks, the window initialisation code is being fixed for a few issues and we may have missed a Windows corner case. Can you please confirm if the same thing happens on the master branch?

**Comment by yms2772** [comment]
> Thanks, the window initialisation code is being fixed for a few issues and we may have missed a Windows corner case. Can you please confirm if the same thing happens on the master branch?

Thanks for your reply. Fortunately there is no error on the master branch.
Speaking of this error, according to roadmap, It says 1.3 version will be released on May 4th.
When will it be released?

**Comment by andydotxyz** [comment]
Quite right, it is delayed - sorry the roadmap is not updated. We had hoped 11th but that looks unlikely. We are having a call later this week and will update expected release date at that point.
